Repository openthread/openthread, pull requests merged in 2018-10, with the labels that each got.

#3110 [docs] minor Doxygen fixes
  include/openthread/error.h
  include/openthread/instance.h
Labels: docs

#3106 [thci] wpanctl firmware validation and modify getGUA according to GRL change
  tools/harness-thci/OpenThread.py
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P2, certification, enhancement

#3112 [thci] fix preferred flag when config border router for ncp device
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P1, bug, certification

#3116 [thci] fix IPv6 prefix format
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P1, bug, certification

#3119 [posix-app] update the logging implementation
  src/posix/platform/logging.c
  src/posix/platform/platform-posix.h
  src/posix/platform/system.c
Labels: P4, posix-app

#3120 [docs] fixing typos in comments/docs
  examples/platforms/openthread-system.h
  examples/platforms/utils/flash.h
  include/openthread/platform/radio.h
  src/core/api/instance_api.cpp
  src/core/openthread-core-default-config.h
  src/ncp/spinel.h
  src/posix/platform/flash.h
  src/posix/platform/openthread-system.h
  src/posix/platform/radio_spinel.hpp
Labels: P4, enhancement

#3123 [meshcop] add commissioner aloc
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
Labels: P3

#3124 [spinel] add and use new capability NET_THREAD_1_1
  src/ncp/ncp_base.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3127 [dtls] remove unnecessary member variable mClient
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
Labels: P4, enhancement

#3111 [toranj] adding test-026 for addition/removal of SLAAC IPv6 address
  tests/toranj/start.sh
  tests/toranj/test-026-slaac-address.py
Labels: P4, continuous-integration, enhancement

#3128 [dhcp6] add dhcp6 server support to NCP
  src/ncp/ncp_base_mtd.cpp
  tests/scripts/thread-cert/Makefile.am
Labels: P4, enhancement

#3084 [core] update first parent request with only R flag during downgrade
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
Labels: P4, enhancement

#3108 [posix-app] simplify saving settings
  Android.mk
  src/posix/platform/Makefile.am
  src/posix/platform/flash.c
  src/posix/platform/flash.h
  src/posix/platform/frame_queue.cpp
  src/posix/platform/settings.cpp
  src/posix/platform/sim.c
  tests/toranj/start.sh
  third_party/openthread-test-driver/test-driver
Labels: P4, enhancement

#3131 [meshcop] do not set joiner port in constructor
  src/core/meshcop/joiner_router.cpp
Labels: P4, enhancement

#3133 [posix-app] map log level with syslog
  src/posix/platform/logging.c
Labels: P4, enhancement

#3136 [nrf52840] fix typo in log parameter
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
Labels: P4, bug, platform: nrf52840

#3132 [qos] reverse message priority level values
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mesh_forwarder_mtd.cpp
  tests/unit/test_priority_queue.cpp
Labels: P4, enhancement

#3130 [core] remove dependency on libstdc++
  configure.ac
  examples/platforms/posix/Makefile.platform.am
  src/cli/cli_server.hpp
  src/core/net/netif.hpp
  src/posix/Makefile.am
Labels: P4, enhancement

#3134 [travis] update to gcc-arm-none-eabi-7-2018-q2-update
  .travis/before_install.sh
  .travis/script.sh
Labels: P4, continuous-integration, enhancement

#3135 [mesh-forwarder] update indirect message logs
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#3138 [posix-app] remove dependency on stty
  .travis/script.sh
  src/posix/README.md
  src/posix/platform/radio_spinel.cpp
Labels: P3, enhancement, posix-app

#3140 [posix-app] get RCP (NCP in radio mode) version
  include/openthread/instance.h
  include/openthread/platform/radio.h
  src/core/api/instance_api.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
  tests/toranj/openthread-core-toranj-config.h
Labels: NCP, P4, enhancement, posix-app

#3141 [posix-app] check spinel version of RCP from RaioSpinel::Init()
  src/posix/platform/radio_spinel.cpp
Labels: P4, enhancement, posix-app

#3150 [thci] fix channel mask format issue in wpanctl commissioner command for ncp device
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P1, bug, certification

#3149 [posix-app] always reset radio when init
  src/posix/platform/radio_spinel.cpp
Labels: P2, posix-app

#3139 [dtls] include server only with commissioner or coaps
  src/core/coap/coap_secure.cpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
  third_party/mbedtls/mbedtls-config.h
Labels: P4, enhancement

#3142 [doc] add note for 'parent' command
  src/cli/README.md
Labels: P4, docs

#3145 [docs] specify seconds as the unit for child timeout value
  include/openthread/thread.h
  src/core/thread/mle.hpp
  src/ncp/spinel.h
Labels: P4, docs, enhancement

#3148 [posix-app] verify radio capabilities
  src/posix/platform/radio_spinel.cpp
Labels: enhancement, posix-app

#3151 [mesh-forwarder] add log for retry attempts of indirect tx to sleepy nodes
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#3153 [spinel] do not use glibc-internal header sys/cdefs.h
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3154 [posix-app] exit on untimely RCP crash/reset
  src/posix/platform/radio_spinel.cpp
Labels: P3, enhancement, posix-app

#3157 [posix-app] fix set radio spinel speed
  src/posix/platform/radio_spinel.cpp
Labels: P2, bug, posix-app

#3070 [posix-app] platform UDP
  .travis/before_install.sh
  .travis/check-posix-app-pty
  .travis/script.sh
  configure.ac
  include/openthread/platform/Makefile.am
  include/openthread/platform/udp.h
  include/openthread/udp.h
  src/core/api/udp_api.cpp
  src/core/net/ip6.cpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
  src/posix/Makefile-posix
  src/posix/platform/Makefile.am
  src/posix/platform/platform-posix.h
  src/posix/platform/system.c
  src/posix/platform/udp.cpp
Labels: P4, api: platform, enhancement, posix-app

#3155 [travis] fix scan-build check
  .travis/script.sh
Labels: P3, bug, continuous-integration

#3158 [posix-app] fix warnings on macOS
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/settings.cpp
Labels: P4, enhancement, posix-app

#3163 [macos] fix platform UDP on macOS
  src/posix/platform/udp.cpp
Labels: P4, enhancement, posix-app

#3165 [thci] conditionally import paramiko and change getting joiner state method
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P1, bug, certification

#3166 [fuzz] exclude -fno-rtti when fuzzer is enabled
  configure.ac
Labels: P3, bug, continuous-integration

#3160 [settings] remove unused APIs
  include/openthread/platform/settings.h
Labels: P4, api: platform, enhancement

#3167 [time-sync] fix build issue with time sync enabled
  .travis/script.sh
  examples/platforms/posix/radio.c
  include/openthread/network_time.h
  src/core/mac/mac.cpp
  src/core/mac/mac_frame.cpp
  src/core/thread/time_sync_service.cpp
  src/core/thread/time_sync_service.hpp
Labels: P4, bug

#3171 [ip6] rename aEui64 to aExtAddress
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
Labels: P4, enhancement

#3172 [link-raw] retransmit frames on any error
  src/core/mac/link_raw.cpp
Labels: P4, bug

#3156 [posix-app] define posix app exit code
  src/posix/platform/platform-posix.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/settings.cpp
  src/posix/platform/sim.c
  src/posix/platform/spi-stubs.c
  src/posix/platform/system.c
  src/posix/platform/uart.c
Labels: P2, enhancement, posix-app

#3175 [posix-app] clean headers in platform-posix.h
  src/posix/platform/alarm.c
  src/posix/platform/frame_queue.cpp
  src/posix/platform/logging.c
  src/posix/platform/misc.c
  src/posix/platform/platform-posix.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/settings.cpp
  src/posix/platform/sim.c
  src/posix/platform/system.c
  src/posix/platform/udp.cpp
Labels: P4, enhancement, posix-app

#3176 [posix-app] support dry run
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/system.c
Labels: P3, enhancement, posix-app

#3177 [coap] remove get port
  src/core/coap/coap.hpp
  src/core/meshcop/joiner.cpp
Labels: P4, coap

#3178 [coaps] refine definition of CoapSecure::Connect
  include/openthread/coap_secure.h
  src/cli/cli_coap_secure.cpp
  src/core/api/coap_secure_api.cpp
  src/core/coap/coap_secure.cpp
  src/core/coap/coap_secure.hpp
  src/core/meshcop/joiner.cpp
  src/core/net/socket.hpp
Labels: P4, coap, enhancement

#3147 [ncp] send Parent Response info on NCP FTD configuration
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_ftd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3181 [nrf52840] fix the k802154Sync timer
  examples/platforms/nrf52840/alarm.c
Labels: P3, bug, platform: nrf52840

#3192 [thci] fix paramiko scope issue when connecting to ncp device via ssh
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P3, bug, certification

#3186 [border-agent] border agent state event
  include/openthread/Makefile.am
  include/openthread/border_agent.h
  include/openthread/instance.h
  src/core/api/border_agent_api.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/border_agent.hpp
Labels: P4, api: user, enhancement

#3197 [travis] ensure to exit with error on toranj build failure
  .travis/script.sh
Labels: P2, bug, continuous-integration

#3179 [coverage] remove empty functions
  src/core/Makefile.am
  src/core/meshcop/dataset_manager.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_mtd.cpp
  src/core/thread/network_data_leader.hpp
  src/core/thread/network_data_leader_mtd.hpp
Labels: P4, enhancement

#3159 [qos] rename message priority
  src/core/coap/coap.hpp
  src/core/common/message.hpp
  src/core/meshcop/meshcop.hpp
  src/core/net/ip6.hpp
  src/core/net/udp6.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle.hpp
  tests/unit/test_priority_queue.cpp
Labels: P4, enhancement

#3183 [core] add support for external OT vendor extension
  .travis/script.sh
  configure.ac
  src/core/Makefile.am
  src/core/common/extension.hpp
  src/core/common/extension_example.cpp
  src/core/common/instance.cpp
  src/core/common/instance.hpp
  src/ncp/ncp_base.cpp
Labels: P4, enhancement

#3191 [doc] add a method to download image to specified EFR32 dev board
  examples/platforms/efr32/README.md
Labels: P4, docs, enhancement, platform: efr32

#3196 [toranj] adding build script for different configs: ncp, rcp, posix-app
  tests/toranj/build.sh
  tests/toranj/start.sh
Labels: P4, continuous-integration, enhancement

#3200 [platform-udp] fix processing message received from other interface
  src/posix/platform/udp.cpp
Labels: P3, bug, posix-app

#3202 [nrf52840] fix possible permanent sleep in multiprotocol
  examples/platforms/nrf52840/alarm.c
  examples/platforms/nrf52840/system.c
Labels: P3, bug, platform: nrf52840

#3203 [nrf52840] update nRF52840 radio driver to version 1.2.2
  examples/platforms/nrf52840/Makefile.am
  examples/platforms/nrf52840/platform-fem.h
  third_party/NordicSemiconductor/drivers/radio/fem/nrf_fem_control_api.h
  third_party/NordicSemiconductor/drivers/radio/mac_features/nrf_802154_ack_timeout.h
  third_party/NordicSemiconductor/drivers/radio/mac_features/nrf_802154_csma_ca.c
  third_party/NordicSemiconductor/drivers/radio/mac_features/nrf_802154_filter.c
  third_party/NordicSemiconductor/drivers/radio/mac_features/nrf_802154_precise_ack_timeout.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_config.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_const.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_pib.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_procedures_duration.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_request_swi.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_types.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_utils.h
  third_party/NordicSemiconductor/drivers/radio/platform/lp_timer/nrf_802154_lp_timer_nodrv.c
Labels: P4, enhancement, platform: nrf52840

#3204 [posix-app] update default core config header file
  src/posix/platform/openthread-core-posix-config.h
Labels: P4, enhancement, posix-app

#3205 [posix-app] add option to print version of radio
  src/posix/main.c
  src/posix/platform/openthread-system.h
  src/posix/platform/system.c
Labels: P3, enhancement, posix-app

#3207 [coap] remove unneeded namespace binding
  src/core/coap/coap_header.cpp
  src/core/coap/coap_header.hpp
Labels: P4, coap, enhancement

#3208 [common-switches] add missing switches
  examples/common-switches.mk
Labels: P4, comp: build, enhancement

#3210 [coap] add support for CoAP header exceeding 255 bytes
  include/openthread/coap.h
  src/core/coap/coap_header.cpp
  src/core/coap/coap_header.hpp
Labels: P4, coap, enhancement

#3211 [coap] add support for Proxy-Uri option
  include/openthread/coap.h
  src/core/api/coap_api.cpp
  src/core/coap/coap_header.cpp
  src/core/coap/coap_header.hpp
Labels: P4, coap, enhancement

#3217 [mbedtls] disable debug by default
  .travis/script.sh
  src/core/meshcop/dtls.cpp
  third_party/mbedtls/mbedtls-config.h
Labels: P4, enhancement

#3216 [mac] simplify implementation of ENABLE_BEACON_RSP_WHEN_JOINABLE feature
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
Labels: P4, enhancement

#3221 [coaps] fix disconnect in CoAP secure
  src/core/coap/coap_secure.cpp
  src/posix/platform/udp.cpp
Labels: coap, enhancement, posix-app

#3224 [efr32] add missing instance header include
  examples/platforms/efr32/platform-efr32.h
Labels: P3, bug, platform: efr32

#3225 [posix-app] fix typo of app logging
  src/core/openthread-core-default-config.h
  src/posix/main.c
Labels: P4, bug

#3227 [cli] fix bug in printing coap peer address
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
Labels: P4, bug, comp: cli

#3214 [mac] use direct callbacks into mesh forwarder for send/recv
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#3215 [posix-app] check RCP capabilities and add support for stream log
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
  tests/toranj/openthread-core-toranj-config.h
Labels: P4, enhancement, posix-app

#3229 [examples] change sInstance to instance
  examples/apps/cli/main.c
  examples/apps/ncp/main.c
Labels: P4, enhancement

#3212 [efr32] implement otPlatTime* APIs
  examples/platforms/efr32/alarm.c
Labels: P4, enhancement, platform: efr32

#3218 [crypto] add support for ECDSA signing
  .travis/script.sh
  configure.ac
  examples/common-switches.mk
  include/openthread/crypto.h
  src/core/Makefile.am
  src/core/api/crypto_api.cpp
  src/core/crypto/ecdsa.cpp
  src/core/crypto/ecdsa.hpp
  third_party/mbedtls/mbedtls-config.h
Labels: P4, enhancement

#3228 [mac] add "Mac::ExtAddress::GenerateRandom()" to create random address
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  src/core/meshcop/joiner.cpp
Labels: P4, enhancement

#3231 [mac] allow same operation to start from done callback handler
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
Labels: P4, enhancement

#3242 [script] clang-format bootstrap on macOS
  script/bootstrap
Labels: P4, enhancement

#3194 [format] use cpp03 standard
  .clang-format
Labels: P4, continuous-integration, enhancement

#3232 [coaps] directly send DTLS message
  src/core/coap/coap_secure.cpp
  src/core/coap/coap_secure.hpp
Labels: P4, coap
