Repository openthread/openthread, pull requests merged in 2018-12, with the labels that each got.

#3312 [nrf52840] add support for the USB DFU software trigger
  examples/Makefile-nrf52840
  examples/platforms/nrf52840/Makefile.am
  examples/platforms/nrf52840/README.md
  examples/platforms/nrf52840/platform-config.h
  examples/platforms/nrf52840/usb-cdc-uart.c
  third_party/NordicSemiconductor/README.md
  third_party/NordicSemiconductor/dependencies/nrf_log_ctrl.h
  third_party/NordicSemiconductor/dependencies/nrf_log_ctrl_internal.h
  third_party/NordicSemiconductor/dependencies/sdk_config.h
  third_party/NordicSemiconductor/libraries/usb/app_usbd_nrf_dfu_trigger.c
  third_party/NordicSemiconductor/libraries/usb/app_usbd_nrf_dfu_trigger.h
  third_party/NordicSemiconductor/libraries/usb/app_usbd_nrf_dfu_trigger_internal.h
  third_party/NordicSemiconductor/libraries/usb/app_usbd_nrf_dfu_trigger_types.h
  third_party/NordicSemiconductor/libraries/usb/nrf_dfu_trigger_usb.c
  third_party/NordicSemiconductor/libraries/usb/nrf_dfu_trigger_usb.h
Labels: P4, enhancement, platform: nrf52840

#3337 [logging] add initial log level config option
  src/core/common/instance.cpp
  src/core/openthread-core-default-config.h
Labels: P4, enhancement

#3347 [docs] added new Dockerfiles
  etc/docker/README.md
  etc/docker/codelab_otsim/Dockerfile
  etc/docker/environment/Dockerfile
Labels: docs

#3343 [android] fix untracked pid
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/hdlc_interface.hpp
Labels: P3, enhancement

#3348 [link] move otLinkSetShortAddress() decl to link_raw.h
  include/openthread/link.h
  include/openthread/link_raw.h
  src/core/api/link_raw_api.cpp
  src/ncp/ncp_base_radio.cpp
Labels: P4, api: user, enhancement

#3342 [android] build spi-hdlc-adapter in OpenThread
  .travis/check-android-build
  Android.mk
Labels: P4, comp: build, enhancement

#3350 [posix-app] eliminate unnecessary transactions with radio
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
Labels: P4, enhancement, posix-app

#3353 [network-data] synchronize 6LoWPAN Contexts after Leader is reset
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
Labels: P2, bug

#3354 [network-data] retrieve network data when restoring as leader
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
Labels: P3, bug

#3341 [spi-hdlc-adapter] make pretty
  tools/Makefile.am
  tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Labels: P4, enhancement

#3355 [examples] always build examples/platforms/utils
  examples/Makefile.am
Labels: P4, comp: build, enhancement

#3357 [spinel] add capability definitions for FTD, MTD, RADIO configuration
  src/ncp/ncp_base.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3349 [mle] simplify the channel mask
  include/openthread/dataset.h
  src/core/mac/mac.hpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/thread/announce_sender.cpp
  src/core/thread/announce_sender.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
Labels: P4, enhancement

#3356 [bootstrap] add `-y` option to `apt-get install`
  script/bootstrap
Labels: P4, enhancement

#3365 [cli] add an API to write string to UART
  include/openthread/cli.h
  src/cli/cli_uart.cpp
Labels: P3, api: user, enhancement

#3366 [ecdsa] do not free mpi context before initializing it
  src/core/crypto/ecdsa.cpp
Labels: P3, bug

#3287 [dhcp6-client] remove dhcp6 client api
  examples/drivers/windows/otLwf/filter.h
  examples/drivers/windows/otLwf/precomp.h
  examples/drivers/windows/otLwf/thread.c
  include/openthread/Makefile.am
  include/openthread/dhcp6_client.h
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/dhcp6_api.cpp
  src/core/net/dhcp6.hpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dhcp6_client.hpp
  src/core/net/dhcp6_server.cpp
  src/core/thread/mle.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, api: user, enhancement

#3368 [mesh-forwarder] fix double logging msg tx to non-sleepy child
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, bug

#3370 [nrf52840] only enable ecdsa when OpenThread configures
  third_party/NordicSemiconductor/libraries/crypto/nrf52840-mbedtls-config.h
Labels: P3, enhancement, platform: nrf52840

#3374 [mac] remove unused method definitions
  src/core/mac/mac.hpp
Labels: P4, enhancement

#3375 [src-match-controller] update to use Mac::Address
  src/core/thread/src_match_controller.cpp
Labels: P4, enhancement

#3377 [link-raw] update to use Mac::Address to reverse extended address
  src/core/api/link_raw_api.cpp
Labels: P4, enhancement

#3376 [mle-router] stop mStateUpdateTimer on mode change
  src/core/thread/mle_router.cpp
Labels: P3, bug

#3318 [qos] handle NCP messages based on the priority of the message
  include/openthread/ip6.h
  src/core/api/ip6_api.cpp
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
  src/core/net/ip6_headers.cpp
  src/core/net/ip6_headers.hpp
  src/ncp/ncp_base_mtd.cpp
Labels: NCP, P4, enhancement

#3388 [nrf52840] fix build with ECDSA=1
  third_party/NordicSemiconductor/libraries/crypto/ecp_alt_cc310.c
Labels: P4, enhancement, platform: nrf52840

#3389 [mbedtls] build switch to disable mbedtls in makefile
  examples/Makefile-cc1352
  examples/Makefile-cc2652
  examples/Makefile-da15000
  examples/Makefile-efr32
  examples/Makefile-nrf52840
  examples/common-switches.mk
Labels: P4, comp: build, enhancement

#3384 [posix-app] simplify UART on POSIX app
  src/cli/cli_uart.cpp
  src/posix/Makefile-posix
  src/posix/main.c
  src/posix/platform/uart.c
  tests/scripts/thread-cert/node_api.py
  tests/scripts/thread-cert/node_cli.py
Labels: P4, enhancement, posix-app

#3394 [posix-app] discard received HDLC frame on error
  src/posix/platform/hdlc_interface.cpp
Labels: P3, bug, posix-app

#3379 [tests] enhance Cert_5_1_06_RemoveRouterId
  tests/scripts/thread-cert/Cert_5_1_06_RemoveRouterId.py
  tests/scripts/thread-cert/command.py
Labels: P4, continuous-integration, enhancement

#3391 [build] option to disable executable build
  configure.ac
  examples/apps/Makefile.am
  examples/common-switches.mk
  src/posix/Makefile.am
Labels: P4, comp: build, enhancement

#3395 [hdlc] report frames smaller than FCS size as error frame
  src/ncp/hdlc.cpp
  tests/unit/test_hdlc.cpp
Labels: NCP, P3, bug

#3361 [thci] update `pollperiod` command to accept ms resolution configuration
  src/cli/README.md
  src/cli/cli.cpp
  tools/harness-thci/OpenThread.py
Labels: P4, enhancement

#3392 [bootstrap] install arm gcc toolchain on Raspbian
  script/bootstrap
Labels: P4, enhancement

#3402 [nrf52840] allow change state handler config in command line
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
Labels: P4, enhancement, platform: nrf52840

#3403 [message] allocate message with corresponding component
  src/core/api/ip6_api.cpp
  src/core/api/udp_api.cpp
Labels: P4, api: user, enhancement

#3404 [posix-app] enhance build switches
  src/posix/Makefile-posix
Labels: P4, comp: build, enhancement, posix-app

#3407 [ncp-base] limit legacy related member variable definitions to FTD/MTD builds
  src/ncp/ncp_base.hpp
Labels: NCP, P4, enhancement

#3401 [data-poll-manager] check user-specified poll period
  examples/apps/windows/otAdapter.h
  examples/drivers/windows/otApi/otApi.cpp
  examples/drivers/windows/otLwf/iocontrol.c
  include/openthread/link.h
  src/cli/cli.cpp
  src/core/api/link_api.cpp
  src/core/thread/data_poll_manager.cpp
  src/core/thread/data_poll_manager.hpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, enhancement

#3398 [udp] call at most one handler
  src/core/net/udp6.cpp
Labels: P4, enhancement

#3412 [udp6] init member variable from constructor
  src/core/net/udp6.cpp
Labels: P4, enhancement

#3413 [socket] use "this" pointer in memset while initialization SockAddr
  src/core/net/socket.hpp
Labels: P4, enhancement

#3414 [border-agent] check read UdpEncapsulationTlv length
  src/core/meshcop/border_agent.cpp
Labels: P4, enhancement

#3387 [tests] enhance Cert_6_1_02_REEDAttach_MED/SED
  tests/scripts/thread-cert/Cert_5_1_06_RemoveRouterId.py
  tests/scripts/thread-cert/Cert_6_1_02_REEDAttach_MED.py
  tests/scripts/thread-cert/Cert_6_1_02_REEDAttach_SED.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/command.py
  tests/scripts/thread-cert/mac802154.py
  tests/scripts/thread-cert/message.py
Labels: P4, continuous-integration, enhancement

#3420 [meshcop] correct UDP_PROXY in script and doc
  .travis/script.sh
  doc/spinel-protocol-src/spinel-tech-thread.md
Labels: P4, enhancement
