Repository openthread/openthread, pull requests merged in 2018-03, with the labels that each got.

#2588 [tests] fix occasional failures in Cert_5_2_07_REEDSynchronization.py
  tests/scripts/thread-cert/Cert_5_2_07_REEDSynchronization.py
Labels: P4, enhancement

#2597 [meshcop] improve logging of adding/removing joiners
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
  src/core/meshcop/joiner.cpp
Labels: P4, bug

#2598 [address-resolver] fix bug in updating address cache by snooping
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, bug

#2591 [operational-dataset] fix bug in getting the channel mask
  src/cli/cli_dataset.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_local.cpp
Labels: P4, bug

#2593 [operational-dataset] remove redundant Get/Set methods
  src/core/meshcop/dataset_local.cpp
Labels: P4, enhancement

#2600 [child-table] detect child move by inspecting messages
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#2599 [operational-dataset] cache Active/Pending Timestamp value
  src/core/meshcop/dataset_local.cpp
  src/core/meshcop/dataset_local.hpp
  src/core/meshcop/dataset_manager.cpp
Labels: P4, enhancement

#2602 [nrf52840] Update alarm.c for nrf52840 platform
  examples/platforms/nrf52840/alarm.c
Labels: P4, enhancement, platform: nrf52840

#2586 [harness-automation] support Test Harness V1.1 R1.2.1 and testbeds with mixed-type devices
  tools/harness-automation/autothreadharness/harness_case.py
  tools/harness-automation/autothreadharness/settings_sample.py
Labels: P4, enhancement

#2596 [meshcop] update Border Agent Locator TLV on keep alives
  src/core/meshcop/leader.cpp
Labels: P4, enhancement

#2603 [ncp] config option for max log string size in otNcpPlatLogv()
  include/openthread/ncp.h
  src/core/openthread-core-default-config.h
  src/ncp/ncp_base.cpp
Labels: NCP, P4, enhancement

#2604 [mle] skip IPv6 address registration entries with no matching context
  src/core/thread/mle_router.cpp
Labels: P4, bug

#2559 [tests] adding `toranj` test framework
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
  tests/toranj/README.md
  tests/toranj/openthread-core-toranj-config.h
  tests/toranj/start.sh
  tests/toranj/test-001-get-set.py
  tests/toranj/test-002-form.py
  tests/toranj/test-003-join.py
  tests/toranj/test-004-scan.py
  tests/toranj/test-005-discover-scan.py
  tests/toranj/test-006-traffic-router-end-device.py
  tests/toranj/test-007-traffic-router-sleepy.py
  tests/toranj/test-008-permit-join.py
  tests/toranj/test-nnn-template.py
  tests/toranj/wpan.py
Labels: P4, enhancement

#2607 [nrf52840] Add timer API for new radio driver in alarm.c
  examples/platforms/nrf52840/Makefile.am
  examples/platforms/nrf52840/alarm.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154.c
Labels: P4, enhancement, platform: nrf52840

#2610 [meshcop] handle Keep Alive when no Commissioner is active
  src/core/meshcop/leader.cpp
Labels: P4, bug

#2611 [operational-dataset] optimize storing dataset to non-volatile
  src/core/meshcop/dataset_local.cpp
Labels: P4, enhancement

#2612 [network-data] optimize network data update via MLE
  src/core/thread/mle.cpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader.hpp
  tests/unit/test_lowpan.cpp
Labels: P4, enhancement

#2605 [logging] remove deprecated use of OPENTHREAD_ENABLE_CLI_LOGGING
  examples/platforms/efr32/logging.c
  examples/platforms/kw41z/logging.c
Labels: P4, enhancement, platform: efr32, platform: kw41z

#2609 [icmp6] allow config of echo handling for unicast/multicast separately
  doc/spinel-protocol-src/spinel-prop-ipv6.md
  examples/drivers/windows/otLwf/eventprocessing.c
  examples/drivers/windows/otLwf/radio.c
  include/openthread/icmp6.h
  src/core/api/icmp6_api.cpp
  src/core/net/icmp6.cpp
  src/core/net/icmp6.hpp
  src/core/net/ip6.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, P4, api: user, enhancement

#2613 [mac] refactor frame rx/tx logging logic into methods
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
Labels: P4, enhancement

#2614 [mesh-forwarder] refactor logging code into method
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
Labels: P4, enhancement

#2621 [examples] Introducing pseudo resets
  examples/apps/cli/main.c
  examples/apps/ncp/main.c
  examples/platforms/cc2538/platform.c
  examples/platforms/cc2650/platform.c
  examples/platforms/cc2652/platform.c
  examples/platforms/da15000/platform.c
  examples/platforms/efr32/platform.c
  examples/platforms/emsk/platform.c
  examples/platforms/gp712/platform.c
  examples/platforms/kw41z/platform.c
  examples/platforms/nrf52840/alarm.c
  examples/platforms/nrf52840/misc.c
  examples/platforms/nrf52840/platform-config.h
  examples/platforms/nrf52840/platform.c
  examples/platforms/platform.h
  examples/platforms/posix/misc.c
  examples/platforms/posix/platform.c
  examples/platforms/posix/sim/platform-sim.c
  examples/platforms/samr21/platform.c
Labels: NCP, P1, enhancement, platform: nrf52840, platform: posix

#2615 [tests] Update toranj test script to retry failed tests
  .travis/before_install.sh
  tests/toranj/start.sh
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2619 [cli] get external route list in the local Network Data
  examples/drivers/windows/include/otLwfIoctl.h
  examples/drivers/windows/otApi/otApi.cpp
  examples/drivers/windows/otLwf/iocontrol.c
  examples/drivers/windows/otLwf/iocontrol.h
  include/openthread/border_router.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
Labels: P4, enhancement

#2626 [travis] fix pip install issue
  .travis/before_install.sh
Labels: P4, comp: build, continuous-integration

#2606 [settings] adding Settings class
  etc/visual-studio/libopenthread.vcxproj
  etc/visual-studio/libopenthread.vcxproj.filters
  etc/visual-studio/libopenthread_k.vcxproj
  etc/visual-studio/libopenthread_k.vcxproj.filters
  src/core/Makefile.am
  src/core/api/thread_api.cpp
  src/core/common/instance.cpp
  src/core/common/instance.hpp
  src/core/common/settings.cpp
  src/core/common/settings.hpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dataset_local.cpp
  src/core/meshcop/dataset_local.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
Labels: P4, enhancement

#2623 [channel-monitor] add public OT API to start and stop channel monitoring
  include/openthread/channel_monitor.h
  src/core/api/channel_monitor_api.cpp
  src/core/utils/channel_monitor.cpp
  src/core/utils/channel_monitor.hpp
Labels: P4, api: user, enhancement

#2620 [cli] return error when the command's argument is not supported
  src/cli/cli.cpp
  src/cli/cli_coap.cpp
  src/cli/cli_dataset.cpp
  src/cli/cli_udp_example.cpp
Labels: P4, enhancement

#2625 [ncp] decode PROP_IPV6_ML_PREFIX property as [6C]
  src/ncp/ncp_base_mtd.cpp
Labels: NCP, P4, enhancement

#2627 [child-supervision] change how child supervision gets started/stopped
  src/core/common/notifier.hpp
  src/core/thread/thread_netif.cpp
  src/core/utils/child_supervision.cpp
  src/core/utils/child_supervision.hpp
Labels: P4, enhancement

#2629 [nrf52840] use mac features introduced in new radio driver
  examples/platforms/nrf52840/Makefile.am
  examples/platforms/nrf52840/platform-config.h
  examples/platforms/nrf52840/radio.c
Labels: P4, enhancement, platform: nrf52840

#2631 [nrf52840] custom EUI-64 get
  examples/platforms/nrf52840/radio.c
  src/core/openthread-core-default-config.h
Labels: P4, enhancement, platform: nrf52840

#2617 [efr32] pass up received ACK frame
  examples/platforms/efr32/radio.c
Labels: P4, enhancement, platform: efr32

#2636 [key-manager] set default key from KeyManager
  src/core/thread/key_manager.cpp
  src/core/thread/thread_netif.cpp
Labels: P4, enhancement

#2637 [nrf52840] remove startup delay after software reset in USB driver
  examples/platforms/nrf52840/platform-config.h
  examples/platforms/nrf52840/usb-cdc-uart.c
Labels: P4, bug, platform: nrf52840

#2638 [nrf52840] update radio driver to f36aa41 and provide temperature
  examples/platforms/nrf52840/Makefile.am
  examples/platforms/nrf52840/platform-config.h
  examples/platforms/nrf52840/platform-nrf5.h
  examples/platforms/nrf52840/platform.c
  examples/platforms/nrf52840/temp.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_config.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_debug.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_rssi.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_rssi.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_types.h
  third_party/NordicSemiconductor/drivers/radio/platform/temperature/nrf_802154_temperature.h
  third_party/NordicSemiconductor/drivers/radio/platform/temperature/nrf_802154_temperature_none.c
  third_party/NordicSemiconductor/drivers/radio/raal/softdevice/nrf_raal_softdevice.c
  third_party/NordicSemiconductor/drivers/radio/timer_scheduler/nrf_802154_timer_sched.c
Labels: P4, enhancement, platform: nrf52840

#2641 [nrf52840] fix IAR warning in radio.c
  examples/platforms/nrf52840/radio.c
Labels: P4, enhancement, platform: nrf52840

#2632 [nrf52840] add SPI Slave support
  examples/Makefile-nrf52840
  examples/platforms/nrf52840/Makefile.am
  examples/platforms/nrf52840/README.md
  examples/platforms/nrf52840/platform-config.h
  examples/platforms/nrf52840/platform-nrf5.h
  examples/platforms/nrf52840/platform.c
  examples/platforms/nrf52840/spi-slave.c
Labels: P4, enhancement, platform: nrf52840

#2644 [docs] add Project Zephyr logo to README
  README.md
  doc/images/ot-contrib-zephyr.png
Labels: docs

#2643 [nrf52840] use single config for mbedtls build
  examples/Makefile-nrf52840
  examples/platforms/nrf52840/Makefile.am
  third_party/NordicSemiconductor/libraries/crypto/aes_alt.h
  third_party/NordicSemiconductor/libraries/crypto/aes_alt_cc310.c
  third_party/NordicSemiconductor/libraries/crypto/cc310_mbedtls.c
  third_party/NordicSemiconductor/libraries/crypto/cc310_mbedtls.h
  third_party/NordicSemiconductor/libraries/crypto/ecp_alt.h
  third_party/NordicSemiconductor/libraries/crypto/ecp_alt_cc310.c
  third_party/NordicSemiconductor/libraries/crypto/ecp_curves_alt.c
  third_party/NordicSemiconductor/libraries/crypto/hw/nrf52840-mbedtls-config.h
  third_party/NordicSemiconductor/libraries/crypto/hw/sha256_alt.h
  third_party/NordicSemiconductor/libraries/crypto/nrf52840-mbedtls-config.h
  third_party/NordicSemiconductor/libraries/crypto/sha256_alt.h
  third_party/NordicSemiconductor/libraries/crypto/sha256_alt_cc310.c
  third_party/mbedtls/Makefile.am
Labels: P4, enhancement, platform: nrf52840
