Repository openthread/openthread, pull requests merged in 2018-04, with the labels that each got.

#2646 [nrf52840] update radio driver to version 1.1.0
  examples/platforms/nrf52840/radio.c
  third_party/NordicSemiconductor/drivers/radio/mac_features/nrf_802154_filter.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_critical_section.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_priority_drop.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_priority_drop_direct.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_priority_drop_swi.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_request_direct.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_request_swi.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_revision.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_swi.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_swi.h
  third_party/NordicSemiconductor/drivers/radio/raal/single_phy/single_phy.c
  third_party/NordicSemiconductor/drivers/radio/raal/softdevice/nrf_raal_softdevice.c
Labels: P4, enhancement, platform: nrf52840

#2647 [spi-hdlc-adapter] enhance the retry logic when slave is busy
  tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Labels: P4, enhancement

#2648 [nrf52840] fix radio deinitialization
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c
Labels: P4, enhancement, platform: nrf52840

#2649 [nrf52840] improve timeslot_request in timeslot_request_prepare
  third_party/NordicSemiconductor/drivers/radio/raal/softdevice/nrf_raal_softdevice.c
Labels: P4, enhancement, platform: nrf52840

#2650 [toranj] add cleanup code after every test-case
  tests/toranj/start.sh
Labels: P4, continuous-integration, enhancement

#2651 [logging] remove deprecated OPENTHREAD_CONFIG_ENABLE_DEFAULT_LOG_OUTPUT
  examples/platforms/samr21/logging.c
Labels: P4, enhancement, platform: samr21

#2653 [spinel] add string conversion support for MCU_POWER_STATE definitions
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#2656 [mac] process frame pending bit at the MAC layer
  src/core/mac/mac.cpp
  src/core/thread/mesh_forwarder.cpp
Labels: P4, enhancement

#2657 [build] sync with latest nlbuild-autotools repo
  configure.ac
  third_party/nlbuild-autotools/repo/.default-version
  third_party/nlbuild-autotools/repo/CHANGES
  third_party/nlbuild-autotools/repo/MANIFEST
  third_party/nlbuild-autotools/repo/README.md
  third_party/nlbuild-autotools/repo/autoconf/m4/nl_enable_coverage.m4
  third_party/nlbuild-autotools/repo/autoconf/m4/nl_werror.m4
  third_party/nlbuild-autotools/repo/examples/Makefile-tests.am
  third_party/nlbuild-autotools/repo/examples/Makefile-third_party.am
  third_party/nlbuild-autotools/repo/examples/Makefile-toplevel.am
  third_party/nlbuild-autotools/repo/examples/configure.ac
  third_party/nlbuild-autotools/repo/scripts/bootstrap
  third_party/nlbuild-autotools/repo/third_party/autoconf/ar-lib
  third_party/nlbuild-autotools/repo/third_party/autoconf/compile
  third_party/nlbuild-autotools/repo/third_party/autoconf/config.guess
  third_party/nlbuild-autotools/repo/third_party/autoconf/config.sub
  third_party/nlbuild-autotools/repo/third_party/autoconf/depcomp
  third_party/nlbuild-autotools/repo/third_party/autoconf/install-sh
  third_party/nlbuild-autotools/repo/third_party/autoconf/ltmain.sh
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ax_compare_version.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ax_cxx_compile_stdcxx.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ax_cxx_compile_stdcxx_0x.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ax_cxx_compile_stdcxx_11.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ax_cxx_compile_stdcxx_14.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ax_jni_include_dir.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ax_prog_doxygen.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ax_pthread.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/libtool.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ltoptions.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ltsugar.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ltversion.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/lt~obsolete.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/pkg.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/missing
  third_party/nlbuild-autotools/repo/third_party/autoconf/mkinstalldirs
  third_party/nlbuild-autotools/repo/third_party/autoconf/py-compile
  third_party/nlbuild-autotools/repo/third_party/autoconf/test-driver
  third_party/nlbuild-autotools/repo/tools/Makefile
  third_party/nlbuild-autotools/repo/tools/packages/build
Labels: P4, comp: build, enhancement

#2654 [coverage] enable coverage on toranj tests
  .travis/script.sh
  tests/toranj/start.sh
Labels: P4, continuous-integration, enhancement

#2663 [meshcop] fix dataset manager returning stack pointer
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/joiner_router.cpp
  src/core/thread/mle.cpp
Labels: P1, bug

#2085 [ncp] add radio only mode NCP app
  configure.ac
  examples/apps/ncp/Makefile.am
  examples/platforms/da15000/platform.c
  examples/platforms/posix/openthread-core-posix-config.h
  include/openthread/link.h
  include/openthread/link_raw.h
  src/core/Makefile.am
  src/core/api/instance_api.cpp
  src/core/api/link_raw.hpp
  src/core/api/link_raw_api.cpp
  src/core/api/message_api.cpp
  src/core/api/thread_api.cpp
  src/core/common/instance.cpp
  src/core/common/instance.hpp
  src/core/common/locator.cpp
  src/core/common/message.cpp
  src/core/openthread-core-default-config.h
  src/ncp/Makefile.am
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_ftd.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/ncp_base_radio.cpp
Labels: NCP, P4, bug, enhancement

#2624 [posix] enable time speed up feature
  examples/platforms/posix/alarm.c
  examples/platforms/posix/platform-posix.h
  examples/platforms/posix/platform.c
  examples/platforms/posix/sim/alarm-sim.c
  examples/platforms/posix/sim/platform-sim.c
  tests/toranj/wpan.py
Labels: P4, enhancement, platform: posix

#2662 [toranj] update verify() to print line-no and test-name
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2659 [toranj] add test case related to MCU power state control
  examples/platforms/posix/misc.c
  tests/toranj/openthread-core-toranj-config.h
  tests/toranj/start.sh
  tests/toranj/test-100-mcu-power-state.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2634 [channel-manager] channel selection
  doc/spinel-protocol-src/spinel-feature-channel-monitor.md
  examples/platforms/posix/radio.c
  include/openthread/channel_manager.h
  include/openthread/channel_monitor.h
  include/openthread/instance.h
  src/core/api/channel_manager_api.cpp
  src/core/api/channel_monitor_api.cpp
  src/core/common/notifier.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/openthread-core-default-config.h
  src/core/utils/channel_manager.cpp
  src/core/utils/channel_manager.hpp
  src/core/utils/channel_monitor.cpp
  src/core/utils/channel_monitor.hpp
  src/ncp/changed_props_set.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_ftd.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
  tests/toranj/openthread-core-toranj-config.h
  tests/toranj/start.sh
  tests/toranj/test-600-channel-manager-properties.py
  tests/toranj/test-601-channel-manager-channel-change.py
  tests/toranj/test-602-channel-manager-channel-select.py
  tests/toranj/wpan.py
Labels: NCP, P4, enhancement

#2666 [mac] on ack timeout switch the radio to receive mode
  src/core/mac/mac.cpp
Labels: P4, bug

#2667 [utils] make heap for general use
  src/core/Makefile.am
  src/core/common/instance.hpp
  src/core/crypto/mbedtls.cpp
  src/core/openthread-core-default-config.h
  src/core/utils/heap.cpp
  src/core/utils/heap.hpp
  tests/unit/Makefile.am
  tests/unit/test_heap.cpp
Labels: P4, enhancement

#2668 [radio] fix link raw caps calculation
  src/core/api/link_raw_api.cpp
Labels: P4, enhancement

#2670 [channel-manager] allow channel manager feature without channel-monitor
  src/core/utils/channel_manager.cpp
  src/core/utils/channel_manager.hpp
Labels: P4, bug

#2669 [mle] send a unicast MLE Announce in response to a received Announce
  src/core/openthread-core-default-config.h
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
Labels: P4, enhancement

#2672 [mle] adding SetRole() method to change device role
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
Labels: P4, enhancement

#2671 [dataset] add message length checks when processing MGMT_SET.req
  src/core/meshcop/dataset_manager_ftd.cpp
Labels: P4, bug

#2673 [travis] add build checks for gcc-arm 7
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
Labels: P4, continuous-integration, enhancement

#2655 [efr32] update to RAIL v2.2
  examples/Makefile-efr32
  examples/platforms/efr32/Makefile.am
  examples/platforms/efr32/Makefile.platform.am
Labels: P4, enhancement, platform: efr32

#2677 [build] update nlbuild-autotools to 1.5.1
  configure.ac
  third_party/nlbuild-autotools/repo/.default-version
  third_party/nlbuild-autotools/repo/CHANGES
  third_party/nlbuild-autotools/repo/README.md
  third_party/nlbuild-autotools/repo/examples/Makefile-bootstrap
  third_party/nlbuild-autotools/repo/examples/Makefile-third_party.am
  third_party/nlbuild-autotools/repo/examples/Makefile-toplevel.am
  third_party/nlbuild-autotools/repo/examples/configure.ac
  third_party/nlbuild-autotools/repo/examples/repos.conf
  third_party/nlbuild-autotools/repo/make/host/tools.mak
  third_party/nlbuild-autotools/repo/make/host/tools/bootstrap.mak
  third_party/nlbuild-autotools/repo/make/host/tools/tools.mak
  third_party/nlbuild-autotools/repo/make/post.mak
  third_party/nlbuild-autotools/repo/make/post/rules.mak
  third_party/nlbuild-autotools/repo/make/post/rules/bootstrap.mak
  third_party/nlbuild-autotools/repo/make/post/rules/help.mak
  third_party/nlbuild-autotools/repo/make/post/rules/repos.mak
  third_party/nlbuild-autotools/repo/make/pre.mak
  third_party/nlbuild-autotools/repo/make/pre/macros.mak
  third_party/nlbuild-autotools/repo/make/pre/macros/git.mak
  third_party/nlbuild-autotools/repo/make/pre/macros/repos.mak
  third_party/nlbuild-autotools/repo/make/pre/macros/verbosity.mak
  third_party/nlbuild-autotools/repo/make/pre/tools.mak
  third_party/nlbuild-autotools/repo/scripts/mkskeleton
  third_party/nlbuild-autotools/repo/tools/packages/build
Labels: P4, comp: build, enhancement

#2679 [efr32] update crypto to RAIL v2.2
  third_party/mbedtls/Makefile.am
Labels: P4, enhancement, platform: efr32

#2681 [posix] fix a warning on gcc7
  examples/platforms/posix/alarm.c
Labels: P4, comp: build, enhancement, platform: posix

#2684 [link-raw] fix a log error
  src/core/api/link_raw_api.cpp
Labels: P3, bug

#2685 [travis] add posix build check for gcc 7
  .travis.yml
  src/ncp/ncp_spi.cpp
Labels: P4, continuous-integration, enhancement

#2687 [posix] correct config.guess path
  examples/Makefile-posix
Labels: P4, bug, comp: build, platform: posix

#2691 [nrf52840] check return value of vsnprintf in otPlatLog
  examples/platforms/nrf52840/logging.c
Labels: P4, platform: nrf52840
