Repository openthread/openthread, pull requests merged in 2018-05, with the labels that each got.

#2680 [dataset] validate TLVs when applying configuration
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/meshcop/meshcop_tlvs.hpp
Labels: P4, enhancement

#2696 [toranj] add new test script for insecure traffic exchange (during join)
  tests/toranj/start.sh
  tests/toranj/test-009-insecure-traffic-join.py
Labels: P4, continuous-integration, enhancement

#2699 [docs] update OpenThread logos
  doc/images/Open-Thread-Logo-200x42.png
  doc/images/openthread_logo.png
Labels: docs

#2678 [router-table] reduce router allocation from 63 to 32
  etc/visual-studio/libopenthread.vcxproj
  etc/visual-studio/libopenthread.vcxproj.filters
  etc/visual-studio/libopenthread_k.vcxproj
  etc/visual-studio/libopenthread_k.vcxproj.filters
  include/openthread/thread_ftd.h
  src/core/Makefile.am
  src/core/api/thread_api.cpp
  src/core/api/thread_ftd_api.cpp
  src/core/common/instance.cpp
  src/core/openthread-core-default-config.h
  src/core/thread/child_table.hpp
  src/core/thread/key_manager.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_constants.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router_ftd.hpp
  src/core/thread/mle_router_mtd.hpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/router_table.cpp
  src/core/thread/router_table.hpp
  src/core/thread/topology.hpp
Labels: P4, enhancement

#2694 [mac] serialize access to the radio channel
  src/core/api/link_api.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/joiner.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mle.cpp
  src/core/utils/channel_manager.cpp
Labels: P3, enhancement

#2692 [mle] change the attach MLE Announcement transmissions
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_constants.hpp
  src/core/thread/mle_router.cpp
  tests/toranj/start.sh
  tests/toranj/test-603-channel-manager-announce-recovery.py
Labels: P4, enhancement

#2704 [router-table] avoid out-of-bound access
  src/core/thread/router_table.cpp
Labels: P4, enhancement

#2700 [nrf52840] fix race condition when reporting channel busy event
  examples/platforms/nrf52840/radio.c
Labels: P3, bug, platform: nrf52840

#2708 [nrf52840] fix mbedtls define names in openthread-core-nrf52840-config.h
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
Labels: P3, bug, platform: nrf52840

#2710 [router-table] validate router id before allocating router
  src/core/thread/router_table.cpp
Labels: P4, enhancement

#2706 [debug] allow build system to provide custom file name
  src/core/common/debug.hpp
Labels: P4, enhancement

#2658 [ble] initial platform API for BLE
  include/openthread/platform/Makefile.am
  include/openthread/platform/ble.h
Labels: P4, api: platform, enhancement

#2693 [announce-sender] feature to enable periodic tx of MLE Announce
  etc/visual-studio/libopenthread.vcxproj
  etc/visual-studio/libopenthread.vcxproj.filters
  etc/visual-studio/libopenthread_k.vcxproj
  etc/visual-studio/libopenthread_k.vcxproj.filters
  src/core/Makefile.am
  src/core/common/instance.cpp
  src/core/common/instance.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/openthread-core-default-config.h
  src/core/thread/announce_begin_server.cpp
  src/core/thread/announce_begin_server.hpp
  src/core/thread/announce_sender.cpp
  src/core/thread/announce_sender.hpp
  src/core/thread/mle_router_mtd.hpp
  tests/unit/test_mac_frame.cpp
Labels: P4, enhancement

#2705 [meshcop-tlvs] new methods for parsing Channel Mask Entry
  src/core/meshcop/dataset.cpp
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/thread/mle.cpp
Labels: P4, enhancement

#2712 [spi-hdlc-adapter] fix compilation on Alpine Linux with musl libc
  tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Labels: P2, enhancement

#2723 [router-table] check num active routers before allocating
  src/core/thread/router_table.cpp
Labels: P4, enhancement

#2714 [cc2538] fix IEEE EUI-64 address word ordering
  examples/platforms/cc2538/radio.c
Labels: P3, bug, platform: cc2538

#2722 [ncp] adding new log output through NCP spinel property
  examples/apps/ncp/main.c
  examples/platforms/cc2538/logging.c
  examples/platforms/cc2650/logging.c
  examples/platforms/cc2652/logging.c
  examples/platforms/da15000/logging.c
  examples/platforms/efr32/logging.c
  examples/platforms/emsk/logging.c
  examples/platforms/gp712/logging.c
  examples/platforms/kw41z/logging.c
  examples/platforms/nrf52840/logging.c
  examples/platforms/nrf52840/platform.c
  examples/platforms/posix/logging.c
  examples/platforms/samr21/logging.c
  src/core/openthread-core-default-config.h
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/spinel.c
  src/ncp/spinel.h
  tests/toranj/openthread-core-toranj-config.h
Labels: P4, enhancement

#2729 [configure.ac] fix typographical error
  configure.ac
Labels: P4, docs

#2718 [mle] add helper methods to check device mode flags
  src/core/mac/mac.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/thread/data_poll_manager.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_diagnostic.cpp
Labels: P4, enhancement

#2707 [mle] update processing of received MLE Announce messages
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_constants.hpp
Labels: P4, enhancement

#2721 [toranj] adding test-case for adding on-mesh prefix (config-gateway)
  tests/toranj/start.sh
  tests/toranj/test-010-on-mesh-prefix-config-gateway.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2725 [ncp] add vendor hook for property get/set handlers for vendor properties
  src/ncp/example_vendor_hook.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
Labels: NCP, P4, enhancement

#2736 [logging] fix logging in LinkRaw class
  src/core/api/link_raw_api.cpp
Labels: P4, bug

#2739 [mpl] update dynamic MPL interval according to new interface
  src/core/net/ip6_mpl.cpp
  src/core/thread/router_table.hpp
Labels: P4, bug

#2740 [mac] reset CCA success rate tracker on channel change
  src/core/mac/mac.cpp
Labels: P4, enhancement

#2745 [address-resolver] include age field as part of otEidCacheEntry
  include/openthread/types.h
  src/core/thread/address_resolver.cpp
  src/core/thread/address_resolver.hpp
Labels: P4, enhancement

#2746 [makefile] sort filename lists in alphabetical order
  src/cli/Makefile.am
  src/core/Makefile.am
  src/ncp/Makefile.am
  tests/unit/Makefile.am
Labels: P4, enhancement

#2744 [router-table] validate num routers when processing Route TLV
  src/core/thread/router_table.cpp
Labels: P4, enhancement

#2737 [logging] append log level and region prefix strings at compile-time
  src/core/common/logging.cpp
  src/core/common/logging.hpp
Labels: P4, enhancement

#2743 [code-utils] adding helper macro OT_ARRAY_LENGTH()
  src/cli/cli.cpp
  src/cli/cli_dataset.cpp
  src/cli/cli_udp_example.cpp
  src/core/common/code_utils.hpp
  src/core/meshcop/commissioner.cpp
  src/core/net/netif.cpp
  src/core/thread/mle.cpp
  src/ncp/changed_props_set.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_mtd.cpp
  tests/unit/test_child.cpp
  tests/unit/test_child_table.cpp
  tests/unit/test_link_quality.cpp
  tests/unit/test_mac_frame.cpp
  tests/unit/test_network_data.cpp
  tests/unit/test_timer.cpp
Labels: P4, enhancement

#2751 [ncp] enable missing properties in radio only mode
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
Labels: bug

#2747 [cli] fix router table command
  examples/drivers/windows/include/otLwfIoctl.h
  examples/drivers/windows/otApi/otApi.cpp
  examples/drivers/windows/otLwf/iocontrol.c
  examples/drivers/windows/otLwf/iocontrol.h
  include/openthread/thread_ftd.h
  src/cli/cli.cpp
Labels: P4, bug, comp: cli

#2754 [mle] read Link Margin TLV from Link Accept in detached state
  src/core/thread/mle_router.cpp
Labels: P3, enhancement

#2755 [cli] align autostart command
  src/cli/README.md
  src/cli/cli.cpp
Labels: P4, comp: cli, enhancement

#2753 [kw41z] radio driver bug fixes
  examples/platforms/kw41z/radio.c
Labels: P2, bug, platform: kw41z

#2742 [trickle-timer] improve/simplify the implementation
  src/core/common/trickle_timer.cpp
  src/core/common/trickle_timer.hpp
Labels: P4, enhancement

#2713 [mle] attach backoff feature
  src/core/openthread-core-default-config.h
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_constants.hpp
Labels: P4, enhancement

#2741 [docs] fix typos and update comment/doxygen style
  CONTRIBUTING.md
  include/openthread/coap.h
  include/openthread/dataset_ftd.h
  include/openthread/instance.h
  include/openthread/jam_detection.h
  include/openthread/link.h
  include/openthread/link_raw.h
  include/openthread/message.h
  include/openthread/netdata.h
  include/openthread/server.h
  include/openthread/tasklet.h
  include/openthread/thread.h
  include/openthread/thread_ftd.h
  include/openthread/types.h
  include/openthread/udp.h
  src/core/common/code_utils.hpp
  src/core/common/random.hpp
  src/core/mac/mac.hpp
  src/ncp/ncp_uart.cpp
  src/ncp/ncp_uart.hpp
Labels: P4, docs, enhancement
