Repository openthread/openthread, pull requests merged in 2018-06, with the labels that each got.

#2728 [diags] make diag output & cmd line buffer params configurable
  src/core/openthread-core-default-config.h
  src/diag/diag_process.hpp
  src/diag/openthread-diag.cpp
Labels: P4, enhancement

#2757 [kw41z] radio driver fix to allow channel change
  examples/platforms/kw41z/radio.c
Labels: P3, bug, platform: kw41z

#2759 [mle] properly handle cases where router table is not populated
  src/core/thread/mle_router.cpp
  src/core/thread/router_table.cpp
Labels: P2, bug

#2769 [network-diagnostic] fix Connectivity and Route TLV type issue when get
  src/core/thread/mle_router.cpp
Labels: P2, bug, certification

#2768 [nrf52840] handle mIsCcaEnabled flag
  examples/platforms/nrf52840/radio.c
Labels: P4, enhancement, platform: nrf52840

#2735 [logging] adding a new log level NOTE
  include/openthread/platform/logging.h
  src/core/common/logging.hpp
  src/ncp/ncp_base.cpp
Labels: P4, enhancement

#2765 [mesh-forwarder] do not treat CCA failures the same as no-ack
  src/core/thread/data_poll_manager.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#2766 [mle] implement MLE Data Request retransmissions
  src/core/thread/mle.cpp
Labels: P4, enhancement

#2770 [data-poll] only allow data polling when rx-off-when-idle
  src/core/thread/data_poll_manager.cpp
Labels: P4, enhancement

#2772 [network-diagnostic] REED should omit ChildTable TLV request
  src/core/thread/network_diagnostic.cpp
Labels: P2, bug, certification

#2734 [ncp-spi] improve callback implementation, change code style format
  src/ncp/ncp_spi.cpp
  src/ncp/ncp_spi.hpp
Labels: NCP, P4, enhancement

#2764 [string] adding ot::String<size> class
  etc/visual-studio/libopenthread.vcxproj
  etc/visual-studio/libopenthread.vcxproj.filters
  etc/visual-studio/libopenthread_k.vcxproj
  etc/visual-studio/libopenthread_k.vcxproj.filters
  src/core/Makefile.am
  src/core/common/settings.cpp
  src/core/common/string.cpp
  src/core/common/string.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/joiner.cpp
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  src/core/thread/address_resolver.cpp
  src/core/thread/announce_sender.cpp
  src/core/thread/link_quality.cpp
  src/core/thread/link_quality.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/utils/channel_manager.cpp
  tests/unit/Makefile.am
  tests/unit/test_link_quality.cpp
  tests/unit/test_mac_frame.cpp
  tests/unit/test_string.cpp
Labels: P4, enhancement

#2773 [mesh-forwarder] do not log dropping of received beacon frames
  src/core/thread/mesh_forwarder.cpp
Labels: P4, enhancement

#2776 [toranj] add test-case for child table and child recovery
  tests/toranj/start.sh
  tests/toranj/test-011-child-table.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2777 [docs] updating Doxygen tags for ble module
  include/openthread/openthread.h
  include/openthread/platform/ble.h
Labels: docs

#2774 [lowpan] use BigEndian::ReadUint16()
  src/core/thread/lowpan.cpp
Labels: P4, enhancement

#2760 [docker] dockerfiles for openthread sim and wpantund
  etc/docker/Makefile
  etc/docker/README.md
  etc/docker/arm32v7_ubuntu_wpantund/Dockerfile
  etc/docker/ot_sim/Dockerfile
  etc/docker/ot_sim/README.md
  etc/docker/ot_sim/add_node
  etc/docker/ot_sim/start_sim
  etc/docker/ot_sim/stop_sim
  etc/docker/x86_ubuntu_wpantund/Dockerfile
Labels: P4, enhancement

#2779 [posix] skip calling RadioReceiveDone with OT_ERROR_ABORT
  examples/platforms/posix/radio.c
Labels: P4, enhancement, platform: posix

#2763 [efr32] add BRD4304A (MGM12P) support and board-specific hal-config.h
  examples/Makefile-efr32
  examples/platforms/efr32/Makefile.am
  examples/platforms/efr32/brd4161a/hal-config.h
  examples/platforms/efr32/brd4166a/hal-config.h
  examples/platforms/efr32/brd4304a/hal-config.h
  examples/platforms/efr32/platform.c
Labels: P4, enhancement, platform: efr32

#2784 [toranj] update README.md (alternate way to install wpantund)
  tests/toranj/README.md
Labels: P4, docs, enhancement

#2782 [toranj] adding test-case for multi-hop traffic exchange
  tests/toranj/start.sh
  tests/toranj/test-012-multi-hop-traffic.py
Labels: P4, continuous-integration, enhancement

#2786 [radio] remove unused mSecurityValid from otRadioFrame structure
  include/openthread/link.h
  include/openthread/platform/radio.h
  src/core/mac/mac.cpp
  src/core/mac/mac_frame.hpp
Labels: P4, api: platform, enhancement

#2787 [mac] unify mac frame access using Get()/Set() methods
  include/openthread/platform/radio.h
  src/core/mac/mac.cpp
  src/core/mac/mac_frame.hpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_radio.cpp
Labels: P4, api: platform, enhancement

#2790 [cli] recover default behavior of ctrl-c
  src/cli/cli_uart.cpp
Labels: P4, comp: cli, enhancement

#2791 [dataset] fix dataset update issue
  src/core/meshcop/dataset_manager.cpp
Labels: P2, bug, certification

#2794 [nlbuild-autotools] ignore autoconf files modified by bootstrap
  .gitignore
  third_party/nlbuild-autotools/repo/third_party/autoconf/compile
  third_party/nlbuild-autotools/repo/third_party/autoconf/depcomp
  third_party/nlbuild-autotools/repo/third_party/autoconf/ltmain.sh
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/libtool.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ltoptions.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ltsugar.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/ltversion.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/m4/lt~obsolete.m4
  third_party/nlbuild-autotools/repo/third_party/autoconf/missing
Labels: P4, comp: build, enhancement

#2795 [mesh-forwarder] fix bug when stopping discover request
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
Labels: P2, bug

#2793 [commissioner-dataset] initialize mSessionId to a random value
  src/core/meshcop/leader.cpp
Labels: P3, bug, enhancement

#2796 [cert] THCI: apply GRL's update
  tools/harness-thci/OpenThread.py
Labels: P3, bug, certification

#2800 [link-raw] add switch for link raw to common-switches.mk
  examples/common-switches.mk
Labels: P4, comp: build, enhancement

#2797 [cert] THCI: enhance firmware validation
  tools/harness-thci/OpenThread.py
Labels: P3, certification, enhancement

#2808 [posix] remove duplicated definition in Makefile-posix
  examples/Makefile-posix
Labels: P4, comp: build, enhancement

#2807 [mle] minor TLV and route table cleanup
  src/core/thread/network_diagnostic_tlvs.hpp
  src/core/thread/router_table.cpp
Labels: P4, enhancement

#2783 [mesh-forwarder] add logs for forwarded MeshHeader messages
  src/core/thread/lowpan.cpp
  src/core/thread/lowpan.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#2811 [ncp] make NCP sources pretty
  src/Makefile.am
  src/ncp/changed_props_set.cpp
  src/ncp/changed_props_set.hpp
  src/ncp/hdlc.cpp
  src/ncp/hdlc.hpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_ftd.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/ncp_base_radio.cpp
  src/ncp/ncp_buffer.cpp
  src/ncp/ncp_buffer.hpp
  src/ncp/ncp_spi.hpp
  src/ncp/ncp_uart.cpp
  src/ncp/ncp_uart.hpp
  src/ncp/spinel.c
  src/ncp/spinel.h
  src/ncp/spinel_decoder.cpp
  src/ncp/spinel_decoder.hpp
  src/ncp/spinel_encoder.cpp
  src/ncp/spinel_encoder.hpp
  src/ncp/spinel_platform.h
Labels: NCP, P4, enhancement

#2809 [router-table] clear router table when changing partitions
  src/core/thread/mle_router.cpp
Labels: P2, bug

#2810 [mac] separate aes ccm process from ProcessTransmitSecurity() method
  include/openthread/platform/radio.h
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.hpp
Labels: P4, enhancement

#2819 [nrf52840] fix frame handling with disabled CCA
  examples/platforms/nrf52840/radio.c
Labels: P4, enhancement, platform: nrf52840

#2820 [nrf52840] fix building with link raw enabled
  examples/platforms/nrf52840/radio.c
Labels: P4, bug, platform: nrf52840

#2821 [link-raw] handle mIsCcaEnabled flag with software retransmit
  src/core/api/link_raw_api.cpp
Labels: P4, enhancement

#2818 [notifier] always signal changed state/config for the first time
  include/openthread/instance.h
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/common/notifier.cpp
  src/core/common/notifier.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/joiner_router.hpp
  src/core/net/netif.cpp
  src/core/thread/announce_sender.cpp
  src/core/thread/announce_sender.hpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/energy_scan_server.hpp
  src/core/thread/key_manager.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/utils/channel_manager.cpp
  src/core/utils/channel_manager.hpp
  src/core/utils/child_supervision.cpp
  src/core/utils/child_supervision.hpp
  src/core/utils/jam_detector.cpp
  src/core/utils/jam_detector.hpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, enhancement

#2824 [mle] reset the attach counter and restart backoff on "mode" change
  src/core/thread/mle.cpp
Labels: P4, enhancement

#2825 [mac] simplify Mac::SetNetworkName(string)
  src/core/mac/mac.cpp
Labels: P4, enhancement

#2827 [mesh-forwarder] limit mesh header message logging to FTD build
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#2828 [child/router-table] overload `++` operator to advance iterators
  src/core/common/settings.hpp
  src/core/thread/address_resolver.cpp
  src/core/thread/child_table.hpp
  src/core/thread/key_manager.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/router_table.hpp
  src/core/thread/src_match_controller.cpp
  src/core/utils/child_supervision.cpp
  tests/unit/test_child_table.cpp
Labels: P4, enhancement

#2826 [child-table] fix typo in constant name
  src/core/thread/child_table.cpp
  src/core/thread/child_table.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
  tests/unit/test_child_table.cpp
Labels: P4, enhancement

#2830 [efr32] fix building errors on boards without FEM
  examples/platforms/efr32/Makefile.am
  examples/platforms/efr32/fem-control.c
Labels: P2, bug, comp: build, platform: efr32

#2832 [docs] add missing Doxygen comments for radio
  include/openthread/platform/radio.h
Labels: P4, docs, enhancement

#2618 [time-sync] network-wide time synchronization service
  examples/platforms/nrf52840/alarm.c
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
  examples/platforms/nrf52840/platform-config.h
  examples/platforms/nrf52840/radio.c
  examples/platforms/posix/alarm.c
  examples/platforms/posix/radio.c
  include/openthread/Makefile.am
  include/openthread/network_time.h
  include/openthread/platform/Makefile.am
  include/openthread/platform/radio.h
  include/openthread/platform/time.h
  include/openthread/types.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/Makefile.am
  src/core/api/link_raw_api.cpp
  src/core/api/network_time_api.cpp
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  src/core/openthread-core-default-config.h
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router_ftd.hpp
  src/core/thread/mle_router_mtd.hpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
  src/core/thread/time_sync_service.cpp
  src/core/thread/time_sync_service.hpp
  src/core/thread/topology.hpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_ftd.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
  tests/unit/test_mac_frame.cpp
Labels: P4, enhancement

#2837 [posix] fix a bug when updating time info for time synchronization
  examples/platforms/posix/radio.c
Labels: P4, bug, platform: posix

#2835 [logging] change some log messages from INFO level to NOTE level
  include/openthread/platform/logging-windows.h
  src/core/net/ip6.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/router_table.cpp
Labels: P4, enhancement

#2841 [ncp] update/add comments and re-order handler lookup
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
Labels: NCP, P4, enhancement

#2836 [mesh-forwarder] update `LogMessage` to use NOTE level for failure/error cases
  include/openthread/platform/logging-windows.h
  src/core/common/instance.hpp
  src/core/common/logging.cpp
  src/core/common/logging.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement
