Repository openthread/openthread, pull requests merged in 2018-07, with the labels that each got.

#2838 [mac] tracking supported channel mask
  include/openthread/instance.h
  include/openthread/link.h
  src/core/api/link_api.cpp
  src/core/common/notifier.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/ncp/changed_props_set.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, enhancement

#2844 [radio] rename CcaEnabled to CsmaCaEnabled
  examples/platforms/nrf52840/radio.c
  include/openthread/platform/radio.h
  src/core/api/link_raw_api.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac_frame.hpp
  src/core/openthread-core-default-config.h
Labels: P4, api: platform, enhancement

#2845 [mac] ensure frame validation checks occur before reading FCF
  src/core/mac/mac_frame.cpp
Labels: P4, bug

#2846 [mesh-forwarder] retransmit on CCA errors
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#2848 [toranj] limit the logs during init of all nodes
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2849 [nrf52840] avoid endless "otPlatUartSendDone" log when using usb-cdc
  examples/platforms/nrf52840/usb-cdc-uart.c
Labels: P4, platform: nrf52840

#2847 [ip6] fix forwarding of off-mesh traffic on FED
  src/core/net/ip6.cpp
  tests/toranj/start.sh
  tests/toranj/test-013-off-mesh-route-traffic.py
  tests/toranj/wpan.py
Labels: P4, bug, continuous-integration

#2850 [nrf52840] set initialized state to false in nrf_drv_clock_uninit()
  third_party/NordicSemiconductor/drivers/clock/nrf_drv_clock.c
Labels: P4, bug, platform: nrf52840

#2839 [mle-router] update the route table log message
  src/core/thread/mle_router.cpp
Labels: P4, enhancement

#2852 [toranj] add support for `add-prefix` and `remove-prefix`
  tests/toranj/test-010-on-mesh-prefix-config-gateway.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2853 [toranj] test-case for adding IPv6 addresses
  tests/toranj/start.sh
  tests/toranj/test-014-ip6-address-add.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2854 [ncp] add new fields (age, rssi, etc) to PARENT spinel property
  doc/spinel-protocol-src/spinel-tech-thread.md
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#2855 [posix-app] add missing check for spinel radio
  src/posix/platform/radio_spinel.cpp
Labels: P2, bug, posix-app

#2859 [api] fix no reset event in radio only mode
  src/core/api/instance_api.cpp
  src/core/common/instance.cpp
  src/core/common/instance.hpp
Labels: P2, bug

#2865 [core] update tmf rules to allow link local multicast address as dest
  src/core/thread/thread_netif.cpp
Labels: P4, bug, enhancement

#2862 [nrf52840] avoid unexpected transmit done callback after pseudo reset
  examples/platforms/nrf52840/platform-nrf5.h
  examples/platforms/nrf52840/platform.c
  examples/platforms/nrf52840/radio.c
Labels: P4, bug, platform: nrf52840

#2864 [posix-app] add Makefile for building with android build system
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
  Android.mk
  include/openthread-config-android.h
  src/posix/platform/flash.c
  src/posix/platform/misc.c
  src/posix/platform/openthread-core-posix-config.h
  src/posix/platform/radio_spinel.cpp
Labels: P3, enhancement, posix-app

#2868 [build] fix errors and warnings when building on IAR and Keil
  src/core/common/string.cpp
  src/core/thread/lowpan.cpp
  third_party/NordicSemiconductor/libraries/crypto/nrf52840-mbedtls-config.h
Labels: P4, comp: build, enhancement

#2872 [android] fix removal of tmf_proxy.cpp in Android.mk
  Android.mk
  include/openthread-config-android.h
Labels: P0, bug, comp: build

#2871 [toranj] adding verify_within and updating `test-014-ip-address-add`.
  tests/toranj/test-014-ip6-address-add.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2870 [tlv] change GetSize() return type to uint16_t to avoid overflow
  src/core/common/tlvs.hpp
  src/core/meshcop/meshcop_tlvs.hpp
Labels: P4, bug

#2873 [travis] add cc1352 build checks
  .travis/script.sh
Labels: P4, continuous-integration, enhancement

#2875 [travis] add link raw to nrf52840 build checks
  .travis/script.sh
Labels: P4, continuous-integration, enhancement, platform: nrf52840

#2371 [cc2538] avoid possible deadlock in otPlatRadioTransmit
  examples/platforms/cc2538/cc2538-reg.h
  examples/platforms/cc2538/radio.c
Labels: P4, bug, platform: cc2538

#2878 [nrf52840] reinitialize all peripherals except uart for pseudo reset
  examples/platforms/nrf52840/platform-nrf5.h
  examples/platforms/nrf52840/platform.c
  examples/platforms/nrf52840/radio.c
  third_party/NordicSemiconductor/drivers/radio/platform/clock/nrf_802154_clock_sdk.c
Labels: P4, bug, platform: nrf52840

#2815 [mac] enable broadcast message retransmission in MAC layer
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/openthread-core-default-config.h
  src/core/thread/mle_router.cpp
Labels: P4, enhancement

#2879 [ncp] add `UDP_PROXY_STREAM` to dispatcher list and update documents
  doc/spinel-protocol-src/spinel-tech-thread.md
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#2880 [toranj] disable OT/NCP logs (by default) during initialization of nodes
  tests/toranj/test-007-traffic-router-sleepy.py
  tests/toranj/test-010-on-mesh-prefix-config-gateway.py
  tests/toranj/test-011-child-table.py
  tests/toranj/test-012-multi-hop-traffic.py
  tests/toranj/test-013-off-mesh-route-traffic.py
  tests/toranj/test-014-ip6-address-add.py
  tests/toranj/test-602-channel-manager-channel-select.py
  tests/toranj/test-603-channel-manager-announce-recovery.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2883 [ncp] increase ChangedPropsSet max supported entries to 64
  src/ncp/changed_props_set.cpp
  src/ncp/changed_props_set.hpp
Labels: NCP, P4, enhancement

#2874 [core] update Child Update Request aggregation feature
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_constants.hpp
Labels: P3, certification, enhancement

#2888 [posix-app] fix bugs of posix apps
  examples/platforms/posix/radio.c
  src/posix/platform/frame_queue.cpp
  src/posix/platform/frame_queue.hpp
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
Labels: P3, bug, enhancement, posix-app

#2876 [build] separate Header IE feature from time sync code
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
  examples/platforms/nrf52840/platform-config.h
  examples/platforms/nrf52840/radio.c
  examples/platforms/posix/radio.c
  src/core/api/link_raw_api.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  src/core/openthread-core-default-config.h
  src/core/thread/mesh_forwarder.cpp
Labels: P4, enhancement

#2886 [toranj] update wpan.init_all_nodes to allow wait time per node
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2887 [ncp] remove unused variable from ncp_base_mtd.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: NCP, P4, enhancement

#2889 [instance] inline getters
  src/core/common/instance.cpp
  src/core/common/instance.hpp
Labels: P4, enhancement

#2890 [travis] update UDP_PROXY flag
  .travis/script.sh
Labels: P3, bug, continuous-integration

#2892 [travis] fix Cert_6_3_02_NetworkDataUpdate of posix-ncp check
  tests/scripts/thread-cert/Cert_5_1_05_RouterAddressTimeout.py
  tests/scripts/thread-cert/Cert_5_6_01_NetworkDataRegisterBeforeAttachLeader.py
  tests/scripts/thread-cert/Cert_6_3_02_NetworkDataUpdate.py
Labels: P3, continuous-integration, enhancement

#2866 [dataset] update dataset `SendMgmtGet` APIs and add support in spinel/NCP
  doc/spinel-protocol-src/spinel-tech-thread.md
  examples/drivers/windows/otApi/otApi.cpp
  examples/drivers/windows/otLwf/iocontrol.c
  examples/drivers/windows/otNodeApi/otNodeApi.cpp
  include/openthread/dataset_ftd.h
  include/openthread/types.h
  src/cli/cli_dataset.cpp
  src/core/api/dataset_api.cpp
  src/core/api/dataset_ftd_api.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/utils/channel_manager.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_ftd.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#2897 [nrf52840] don't reinitialize cc310 during pseudo reset
  examples/platforms/nrf52840/platform.c
Labels: P3, bug, platform: nrf52840

#2899 [nrf52840] prevent linker from dicarding strong nrf5CryptoInit implementation
  third_party/NordicSemiconductor/libraries/crypto/cc310_mbedtls.c
  third_party/NordicSemiconductor/libraries/crypto/cc310_mbedtls.h
Labels: P3, bug, platform: nrf52840

#2891 [code-style] remove multiple return statements per free function or method
  src/cli/cli.cpp
  src/cli/cli_coap.cpp
  src/cli/cli_uart.cpp
  src/core/api/dataset_api.cpp
  src/core/common/message.cpp
  src/core/meshcop/border_agent.cpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dhcp6_server.cpp
  src/core/net/ip6_address.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/ncp/hdlc.cpp
Labels: P4, enhancement

#2900 [commissioner] update comments and method documentations
  include/openthread/commissioner.h
  src/core/meshcop/announce_begin_client.hpp
  src/core/meshcop/commissioner.hpp
Labels: P4, docs, enhancement

#2902 [docs] update API menu for new APIs
  include/openthread/openthread.h
Labels: docs

#2907 [meshcop] fix handling commissioner keep alive
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/border_agent.hpp
Labels: P2, bug

#2885 [spinel] add a section for MeshCop properties and update documentation
  doc/spinel-protocol-src/spinel-prop.md
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#2901 [toranj] perform a subprocess.poll() on wpantund instance during init
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#2895 [mle] fix mChildUpdateRequestTimer use for retranmission of Data Reqeust
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
Labels: P4, enhancement

#2905 [network-data] clean stale child's server info when its parent is removed
  src/core/thread/mle.hpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
  src/core/thread/router_table.cpp
Labels: P4, bug, enhancement

#2906 [meshcop] allow MBEDTLS_ERR_SSL_WANT_WRITE from mbedtls_ssl_write()
  src/core/meshcop/dtls.cpp
  src/core/openthread-core-default-config.h
Labels: P3, enhancement

#2910 [core-config-check] add `CONFIG_MAX_TX_ATTEMPTS_DIRECT` to list of replaced options
  src/core/openthread-core-config-check.h
Labels: P4, enhancement

#2893 [core] move border agent into thread_netif
  src/core/api/commissioner_api.cpp
  src/core/common/instance.cpp
  src/core/common/instance.hpp
  src/core/thread/mle.cpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
Labels: P4, enhancement

#2909 [efr32] update to Gecko SDK v2.3
  examples/Makefile-efr32
  examples/platforms/efr32/Makefile.am
  examples/platforms/efr32/Makefile.platform.am
  examples/platforms/efr32/fem-control.c
  third_party/mbedtls/Makefile.am
Labels: P4, enhancement, platform: efr32

#2884 [commissioner] add new API to get Provisioning URL
  include/openthread/commissioner.h
  src/core/api/commissioner_api.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
Labels: P4, enhancement

#2775 [mle] support for long routes
  include/openthread-windows-config.h
  src/core/openthread-core-default-config.h
  src/core/thread/mle_constants.hpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/topology.hpp
Labels: P4, enhancement

#2922 [mac] fix build failure with CONFIG_DISABLE_CSMA_CA_ON_LAST_ATTEMPT
  src/core/mac/mac.cpp
Labels: P3, bug

#2923 [efr32] do not use CCA/CSMA when it is disabled
  examples/platforms/efr32/radio.c
Labels: P4, enhancement, platform: efr32

#2924 [config] update comment to use new config name `FRAME_RETRIES_INDIRECT`
  src/core/openthread-core-default-config.h
Labels: P4, docs, enhancement

#2925 [config] add check for OPENTHREAD_CONFIG_DISABLE_CCA_ON_LAST_ATTEMPT
  src/core/openthread-core-config-check.h
Labels: P4, enhancement

#2882 [kw41z] load bytes into TX Packet Buffer in order
  examples/platforms/kw41z/radio.c
Labels: P3, bug, platform: kw41z

#2919 [flash] move example flash driver from c++ to c
  etc/visual-studio/libopenthread-windows.vcxproj
  etc/visual-studio/libopenthread-windows.vcxproj.filters
  examples/platforms/utils/Makefile.am
  examples/platforms/utils/settings_flash.c
Labels: P4, enhancement

#2920 [github] update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: P4, enhancement

#2928 [travis] remove lib32z1 from arm-gcc-6/7 build checks
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
Labels: P4, continuous-integration, enhancement

#2903 [message] update comment/documentation
  src/core/common/message.hpp
Labels: P4, docs, enhancement

#2933 [mle] fix logging at NOTE level
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
Labels: P3, bug

#2915 [toranj] test case for adding IPv6 addresses with same prefix on multiple nodes
  tests/toranj/start.sh
  tests/toranj/test-015-same-prefix-on-multiple-nodes.py
Labels: P4, continuous-integration, enhancement

#2936 [mle] remove unused LeaderDataTlv from HandleChildUpdateRequest
  src/core/thread/mle.cpp
Labels: P4, enhancement

#2937 [message-info] remove unnecessary memset initialization
  src/cli/cli.cpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dhcp6_server.cpp
Labels: P4, enhancement
