Repository openthread/openthread, pull requests merged in 2019-02, with the labels that each got.

#3542 [mle] remove unused attach state kAttachStateSynchronize
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
Labels: P4, enhancement

#3543 [style] return void where code always returns OT_ERROR_NONE
  src/core/api/crypto_api.cpp
  src/core/api/jam_detection_api.cpp
  src/core/api/joiner_api.cpp
  src/core/api/link_api.cpp
  src/core/api/thread_api.cpp
  src/core/api/thread_ftd_api.cpp
  src/core/coap/coap_secure.cpp
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/crypto/aes_ccm.cpp
  src/core/crypto/aes_ccm.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner.hpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/joiner_router.hpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dhcp6_client.hpp
  src/core/net/dhcp6_server.cpp
  src/core/net/dhcp6_server.hpp
  src/core/net/icmp6.cpp
  src/core/net/icmp6.hpp
  src/core/net/ip6.cpp
  src/core/net/ip6_routes.cpp
  src/core/net/ip6_routes.hpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
  src/core/thread/key_manager.cpp
  src/core/thread/key_manager.hpp
  src/core/thread/lowpan.cpp
  src/core/thread/lowpan.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router_ftd.hpp
  src/core/thread/mle_router_mtd.hpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data.hpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_data_local.hpp
  src/core/utils/jam_detector.cpp
  src/core/utils/jam_detector.hpp
  src/ncp/ncp_buffer.cpp
  src/ncp/ncp_buffer.hpp
  src/ncp/spinel_encoder.cpp
  tests/unit/test_ncp_buffer.cpp
Labels: P4, enhancement

#3546 [posix] fix build for SPI bus
  Android.mk
  src/ncp/hdlc.cpp
  src/posix/platform/Makefile.am
Labels: P2, bug, posix-app

#3514 [ci] test with time sync and header ie
  .travis.yml
  examples/common-switches.mk
  examples/platforms/posix/Makefile.am
  examples/platforms/posix/sim/alarm-sim.c
  examples/platforms/posix/sim/radio-sim.c
  include/openthread/platform/time.h
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/mac802154.py
  tests/scripts/thread-cert/mle.py
  tests/scripts/thread-cert/network_layer.py
  tests/unit/test_platform.cpp
Labels: P4, continuous-integration, enhancement

#3463 [posix-app] add daemon mode
  configure.ac
  src/posix/Makefile-posix
  src/posix/Makefile.am
  src/posix/README.md
  src/posix/client.c
  src/posix/platform/hdlc_interface.hpp
  src/posix/platform/platform-config.h
  src/posix/platform/platform-posix.h
  src/posix/platform/uart.c
Labels: P4, enhancement, posix-app

#3544 [toranj] allow specifying wpantund path
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#3525 [qpg6095] add Qorvo QPG6095 platform
  configure.ac
  examples/Makefile-qpg6095
  examples/platforms/Makefile.am
  examples/platforms/Makefile.platform.am
  examples/platforms/qpg6095/Makefile.am
  examples/platforms/qpg6095/Makefile.platform.am
  examples/platforms/qpg6095/alarm.c
  examples/platforms/qpg6095/alarm_qorvo.h
  examples/platforms/qpg6095/crypto/qpg6095-mbedtls-config.h
  examples/platforms/qpg6095/diag.c
  examples/platforms/qpg6095/logging.c
  examples/platforms/qpg6095/misc.c
  examples/platforms/qpg6095/misc_qorvo.h
  examples/platforms/qpg6095/openthread-core-qpg6095-config.h
  examples/platforms/qpg6095/platform.c
  examples/platforms/qpg6095/platform_qorvo.h
  examples/platforms/qpg6095/qpg6095.ld
  examples/platforms/qpg6095/radio.c
  examples/platforms/qpg6095/radio_qorvo.h
  examples/platforms/qpg6095/random.c
  examples/platforms/qpg6095/random_qorvo.h
  examples/platforms/qpg6095/settings.cpp
  examples/platforms/qpg6095/settings_qorvo.h
  examples/platforms/qpg6095/uart.c
  examples/platforms/qpg6095/uart_qorvo.h
  third_party/Qorvo/LICENSE.txt
  third_party/Qorvo/README.md
  third_party/Qorvo/qpg6095/libQorvoQPG6095.a
Labels: P4, enhancement

#3547 [ncp] disable assert and watchdog property when fuzz testing
  src/ncp/ncp_base.cpp
Labels: NCP, P4, continuous-integration, enhancement

#3548 [cli] validate ping interval is positive to avoid Timer::Start() assert
  src/cli/cli.cpp
Labels: P4, bug, comp: cli

#3549 [fuzz] return valid radio transmit buffer
  tests/fuzz/fuzzer_platform.c
Labels: P4, continuous-integration, enhancement

#3550 [topology] add static assertion to exclude counter overflow
  src/core/thread/topology.hpp
Labels: P4, enhancement

#3367 [efr32] random number generation fix
  examples/platforms/efr32/random.c
Labels: P3, bug, platform: efr32

#3416 [settings-flash] use #if to avoid unreachable code errors
  examples/platforms/utils/settings_flash.c
Labels: P4, enhancement

#3552 [settings] skip non-volatile save with same NetworkInfo/ParentInfo
  src/core/common/settings.cpp
Labels: P4, enhancement

#3553 [mle] skip saving network info on role change to detached
  src/core/thread/mle.cpp
Labels: P4, enhancement

#3554 [mle] use IsAttached() to start border agent
  src/core/thread/mle.cpp
Labels: P4, enhancement

#3555 [notifier] auto-register callback from its constructor
  src/core/common/notifier.cpp
  src/core/common/notifier.hpp
  src/core/meshcop/joiner_router.cpp
  src/core/thread/announce_sender.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/mle.cpp
  src/core/thread/time_sync_service.cpp
  src/core/utils/channel_manager.cpp
  src/core/utils/child_supervision.cpp
  src/core/utils/jam_detector.cpp
Labels: P4, enhancement

#3556 [travis] enhance samr21 build checks
  .travis/script.sh
Labels: P4, continuous-integration, enhancement, platform: samr21

#3558 [ncp] add support for getting MLE counters
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3559 [link-raw] handle get/set channel when LinkRaw is enabled
  src/core/api/link_api.cpp
Labels: P4, enhancement

#3560 [mac] always emit OT_CHANGED_THREAD_CHANNEL on channel change
  src/core/mac/mac.cpp
Labels: P4, bug

#3561 [nrf52840] do not compile spi-slave.c if NCP_SPI is not used
  examples/Makefile-nrf52840
  examples/platforms/nrf52840/spi-slave.c
  examples/platforms/nrf52840/system.c
  examples/platforms/nrf52840/uart.c
Labels: P4, comp: build, enhancement, platform: nrf52840

#3562 [travis] move platform builds to common functions
  .travis/script.sh
Labels: P4, continuous-integration, enhancement

#3567 [travis] add build checks for qpg6095 platform
  .travis/script.sh
  examples/Makefile-qpg6095
Labels: P4, continuous-integration, enhancement, platform: qpg6095

#3568 [mac] use ot::Instance reference in scan callback handlers
  src/core/api/link_api.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/energy_scan_server.hpp
  src/core/thread/panid_query_server.cpp
  src/core/thread/panid_query_server.hpp
  src/core/utils/channel_monitor.cpp
  src/core/utils/channel_monitor.hpp
Labels: P4, enhancement

#3569 [instance] update the documentation for `Get<Type>` definition
  src/core/common/instance.hpp
Labels: P4, docs, enhancement

#3571 [ncp] add static assert to check size of changed set entries array
  src/ncp/changed_props_set.cpp
Labels: NCP, P4, enhancement

#3572 [tests] fix class name for Cert_9_2_04
  tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
Labels: P4, continuous-integration, enhancement

#3573 [nrf528xx] test all transport variants in CI
  .travis/script.sh
Labels: P4, continuous-integration, enhancement, platform: nrf52811, platform: nrf52840

#3574 [posix-app] explictly set optind
  src/posix/platform/system.c
Labels: P4, enhancement, posix-app

#3576 [posix-app] fix write in daemon mode
  .travis.yml
  .travis/check-posix-app-pty
  .travis/script.sh
  src/posix/platform/misc.c
  src/posix/platform/platform-posix.h
  src/posix/platform/uart.c
Labels: P4, bug, enhancement, posix-app

#3579 [posix-app] fix aliasing issue
  src/posix/platform/udp.cpp
Labels: P4, enhancement, posix-app

#3581 [build] don't define UINT32_MAX for C
  include/openthread/platform/toolchain.h
Labels: P4, bug, comp: build

#3570 [toranj] add test-case for data poll transmission and poll interval
  tests/toranj/start.sh
  tests/toranj/test-029-data-poll-interval.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#3583 [notifier] enhance documentation
  src/core/common/notifier.hpp
Labels: P4, docs, enhancement

#3584 [ip6] update documentation for otIp6ReceiveCallback
  include/openthread/ip6.h
Labels: P4, docs, enhancement

#3557 [mpl] allow multiple entries from the same Seed ID
  src/core/net/ip6_mpl.cpp
Labels: P4, enhancement

#3563 [ble] BLE API improvements: add l2cap and gatt services registration.
  include/openthread/platform/ble.h
Labels: P4, api: platform, enhancement

#3575 [mbedtls] guard allocator with accurate macro
  configure.ac
  src/core/common/instance.hpp
  src/core/crypto/mbedtls.cpp
  src/core/meshcop/dtls.cpp
  src/core/openthread-core-default-config.h
Labels: P4, enhancement

#3585 [ip6] messages sent to Service Locator will not be filtered out
  src/core/net/ip6.cpp
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
Labels: NCP, P4, enhancement

#3512 [slaac] add config option to enable/disable SLAAC support
  .travis/script.sh
  examples/common-switches.mk
  examples/platforms/posix/openthread-core-posix-config.h
  src/core/openthread-core-default-config.h
  src/core/thread/mle.cpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
  src/posix/platform/openthread-core-posix-config.h
Labels: P4, enhancement

#3590 [platform-netif] disable icmp echo
  src/posix/platform/netif.cpp
Labels: P4, enhancement, posix-app

#3587 [mpl] fix inserting mechanism and timer handling
  src/core/net/ip6_mpl.cpp
Labels: P2, bug

#3588 [mpl] fix bug in comparing sequence numbers
  src/core/net/ip6_mpl.cpp
Labels: P2, bug

#3586 [style] remove snake case from style guide
  STYLE_GUIDE.md
Labels: P4, docs, enhancement

#3591 [posix-app] fix aliasing issues in platform UDP
  src/posix/platform/udp.cpp
Labels: P4, enhancement, posix-app

#3592 [mac] assert on failure of otPlatRadioEnable()
  src/core/mac/sub_mac.cpp
Labels: P4, enhancement

#3593 [nrf528xx] always enable diag module
  examples/Makefile-nrf52811
  examples/Makefile-nrf52840
Labels: P4, comp: build, enhancement, platform: nrf52811, platform: nrf52840

#3594 [doc] improve doxygen comments
  src/core/openthread-core-default-config.h
Labels: P4, docs, enhancement

#3595 [nrf528xx] improve platform specific configs
  examples/platforms/nrf52811/openthread-core-nrf52811-config.h
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
Labels: P4, docs, enhancement, platform: nrf52811, platform: nrf52840

#3598 [link-raw] remove the redundant logs in link-raw api
  src/core/api/link_raw_api.cpp
Labels: P4, enhancement

#3601 [nrf528xx] update app_error_weak.c
  third_party/NordicSemiconductor/libraries/app_error/app_error_weak.c
Labels: P4, enhancement, platform: nrf52811, platform: nrf52840

#3602 [nrf528xx] improve flash API
  examples/platforms/nrf52811/flash_nosd.c
  examples/platforms/nrf52811/platform-nrf5.h
  examples/platforms/nrf52840/flash_nosd.c
  examples/platforms/nrf52840/flash_sd.c
  examples/platforms/nrf52840/platform-nrf5.h
Labels: P4, enhancement, platform: nrf52811, platform: nrf52840

#3405 [tests] add traffic check in test case Cert_7_1_01
  tests/scripts/thread-cert/Cert_7_1_01_BorderRouterAsLeader.py
  tests/scripts/thread-cert/Cert_7_1_03_BorderRouterAsLeader.py
  tests/scripts/thread-cert/command.py
  tests/scripts/thread-cert/message.py
Labels: P4, continuous-integration, enhancement

#3606 [nrf52811] fix uart hwfc define in the platform config
  examples/platforms/nrf52811/platform-config.h
Labels: bug, platform: nrf52811

#3604 [cli] correct dataset examples in README
  src/cli/README.md
Labels: P4, comp: cli, docs, enhancement

#3605 [cli] add command to retrieve mle counters
  examples/drivers/windows/include/otLwfIoctl.h
  examples/drivers/windows/otApi/otApi.cpp
  examples/drivers/windows/otLwf/iocontrol.c
  examples/drivers/windows/otLwf/iocontrol.h
  include/openthread/thread.h
  src/cli/cli.cpp
Labels: comp: cli, enhancement

#3607 [cli] allow to define ping interval in milliseconds
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
Labels: comp: cli, enhancement

#3596 [efr32] update to Silicon Labs Flex SDK v2.5
  examples/Makefile-efr32
  examples/platforms/efr32/Makefile.am
  examples/platforms/efr32/Makefile.platform.am
  examples/platforms/efr32/README.md
  examples/platforms/efr32/fem-control.c
Labels: P4, enhancement, platform: efr32

#3478 [nrf52840] add nrfjprog target for flashing
  examples/Makefile-nrf52840
Labels: comp: build, enhancement, platform: nrf52840

#3608 [mbedtls] include debug.h
  src/core/crypto/mbedtls.cpp
Labels: P4, enhancement

#3613 [doc] fix incorrect SNTP comment
  include/openthread/sntp.h
Labels: P4, docs, enhancement

#3610 [mle] remove assert in `Mle::FillConnectivityTlv()` when detached
  src/core/thread/mle_router.cpp
Labels: P4, enhancement

#3614 [mesh-forwarder] avoid assert when processing direct transmissions
  src/core/thread/mesh_forwarder.cpp
Labels: P4, bug

#3612 [slaac] remove otIp6SlaacUpdate leftover from the ip6.h header
  include/openthread/ip6.h
Labels: P4, api: user, enhancement

#3609 [cc2538] add support for CC2538-CC2592-EM
  examples/Makefile-cc2538
  examples/platforms/cc2538/README.md
  examples/platforms/cc2538/cc2538-reg.h
  examples/platforms/cc2538/openthread-core-cc2538-config.h
  examples/platforms/cc2538/platform-cc2538.h
  examples/platforms/cc2538/radio.c
Labels: P4, enhancement, platform: cc2538

#3616 [tests] add conditionals around unit tests
  tests/Makefile.am
  tests/unit/Makefile.am
  tests/unit/test_lowpan.cpp
Labels: P4, continuous-integration, enhancement

#3617 [fuzz] process pending tasklets to increase coverage
  tests/fuzz/cli_uart_received.cpp
  tests/fuzz/ip6_send.cpp
  tests/fuzz/ncp_uart_received.cpp
  tests/fuzz/radio_receive_done.cpp
Labels: P4, continuous-integration, enhancement

#3618 [nrf528xx] update usbd
  third_party/NordicSemiconductor/Makefile.am
  third_party/NordicSemiconductor/dependencies/nrfx_glue.h
  third_party/NordicSemiconductor/dependencies/sdk_config.h
  third_party/NordicSemiconductor/drivers/usbd/nrf_drv_usbd.c
  third_party/NordicSemiconductor/drivers/usbd/nrf_drv_usbd.h
  third_party/NordicSemiconductor/drivers/usbd/nrf_drv_usbd_errata.h
Labels: P4, enhancement, platform: nrf52811, platform: nrf52840

#3622 [posix-app] fix daemon uart send done
  src/posix/platform/uart.c
Labels: P3, bug, posix-app

#3620 [efr32] unify flash config around SETTINGS_CONFIG_PAGE_NUM
  examples/platforms/efr32/flash.c
  examples/platforms/efr32/openthread-core-efr32-config.h
Labels: P4, enhancement, platform: efr32

#3625 [efr32] fix cannot compile with log output OPENTHREAD_CONFIG_LOG_OUTPUT_APP
  examples/platforms/efr32/system.c
Labels: P4, bug, platform: efr32

#3627 [docs] add STMicroelectronics to the list of supporters
  README.md
  doc/images/ot-contrib-stm.png
Labels: docs

#3626 [network-data] add check for prefix length
  src/core/common/encoding.hpp
  src/core/thread/network_data_tlvs.hpp
Labels: P4, enhancement

#3628 [dtls] do not free mbedtls context if one is already being used
  src/core/meshcop/dtls.cpp
Labels: P4, bug

#3629 [mesh-forwarder] do not allow eviction of message being processed
  src/core/common/message.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P3, bug

#3611 [posix-app] clean up posix app defines
  Android.mk
  configure.ac
  include/openthread-config-android.h
  src/Makefile.am
  src/posix/Makefile.am
  src/posix/main.c
  src/posix/platform/Makefile.am
  tests/toranj/openthread-core-toranj-config.h
  tests/unit/Makefile.am
Labels: P4, comp: build, enhancement, posix-app

#3623 [coaps] fix disconnected
  include/openthread/coap_secure.h
  src/cli/cli_coap_secure.cpp
  src/core/api/coap_secure_api.cpp
  src/core/coap/coap_secure.cpp
  src/core/coap/coap_secure.hpp
  src/core/meshcop/border_agent.cpp
Labels: P3, bug, coap

#3441 [tests] support testing commissioning
  .travis/script.sh
  Makefile.am
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/command.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/dtls.py
  tests/scripts/thread-cert/mesh_cop.py
  tests/scripts/thread-cert/message.py
  tests/scripts/thread-cert/mle.py
  tests/scripts/thread-cert/node_cli.py
  tests/scripts/thread-cert/pcap.py
  tests/scripts/thread-cert/simulator.py
  tests/scripts/thread-cert/sniffer.py
Labels: P4, continuous-integration, enhancement

#3630 [posix-app] cause compile failure for SPI bus
  Android.mk
  src/posix/platform/Makefile.am
  src/posix/platform/spi-stubs.c
Labels: api: platform, enhancement, posix-app

#3631 [efr32] implement otPlatRadioEnergyScan API
  examples/platforms/efr32/radio.c
Labels: P4, enhancement, platform: efr32

#3634 [nrf528xx] add radio and random platform fixes
  examples/platforms/nrf52811/radio.c
  examples/platforms/nrf52811/random.c
  examples/platforms/nrf52840/radio.c
Labels: P4, bug, platform: nrf52811, platform: nrf52840

#3457 [tests] enhance Cert_8_1_01_Commissioning
  tests/scripts/thread-cert/Cert_8_1_01_Commissioning.py
  tests/scripts/thread-cert/mesh_cop.py
Labels: P4, continuous-integration, enhancement

#3633 [nrf528xx] update platforms README.md
  examples/platforms/nrf52811/README.md
  examples/platforms/nrf52840/README.md
Labels: docs, platform: nrf52811, platform: nrf52840

#3636 [cc2538] fix RSSI calibration when CC2592 is in use
  examples/Makefile-cc2538
  examples/platforms/cc2538/README.md
  examples/platforms/cc2538/openthread-core-cc2538-config.h
  examples/platforms/cc2538/radio.c
Labels: P4, bug, platform: cc2538

#3637 [time-sync] fix time sync and typo
  examples/Makefile-posix
  examples/common-switches.mk
  src/core/thread/mle_router.cpp
Labels: bug, comp: build, continuous-integration
