Repository openthread/openthread, pull requests merged in 2019-04, with the labels that each got.

#3717 [examples] software implementation of source match table
  examples/platforms/efr32/radio.c
  examples/platforms/utils/Makefile.am
  examples/platforms/utils/soft_source_match_table.c
  examples/platforms/utils/soft_source_match_table.h
Labels: enhancement, platform: efr32

#3723 [dataset] use Read/Save method names instead of Get/Set
  src/core/api/dataset_api.cpp
  src/core/meshcop/dataset_local.cpp
  src/core/meshcop/dataset_local.hpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/thread/mle.cpp
  src/core/utils/channel_manager.cpp
Labels: P4, enhancement

#3725 [nrf528xx] remove unnecessary dependencies from app_error_weak
  third_party/NordicSemiconductor/libraries/app_error/app_error_weak.c
Labels: P3, bug, platform: nrf52811, platform: nrf52840

#3729 [cli] add legacy stubs in cli
  Android.mk
  src/cli/cli.cpp
  src/posix/Makefile.am
Labels: P2, enhancement

#3728 [posix-app] fix alarm issue when time changed
  .travis/before_install.sh
  src/posix/platform/alarm.c
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/platform-posix.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/sim.c
Labels: P1, bug, posix-app

#3677 [diag] use OT_ARRAY_LENGTH to unify code and shrink image size
  examples/platforms/nrf52811/diag.c
  examples/platforms/nrf52840/diag.c
  examples/platforms/utils/code_utils.h
  src/diag/diag_process.cpp
Labels: enhancement, platform: nrf52840

#3738 [posix-app] fix conversion warnings
  .travis.yml
  .travis/check-posix-app-pty
  examples/platforms/posix/radio.c
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/netif.cpp
  src/posix/platform/radio_spinel.cpp
Labels: P2, enhancement, posix-app

#3739 [build] fix build error with announce sender enabled
  .travis/script.sh
  src/core/thread/announce_sender.cpp
Labels: P3, bug

#3737 [coap] remove otCoapMessage from CoapSecure::DefaultHandler()
  examples/platforms/posix/openthread-core-posix-config.h
  src/cli/cli_coap_secure.cpp
  src/cli/cli_coap_secure.hpp
Labels: P4, bug, coap

#3731 [radio-spinel] parse frame rx timestamp
  include/openthread/error.h
  src/ncp/ncp_base_radio.cpp
  src/posix/platform/radio_spinel.cpp
Labels: P4, enhancement, posix-app

#3732 [radio] add supported and preferred channel mask
  Android.mk
  etc/visual-studio/libopenthread.vcxproj
  etc/visual-studio/libopenthread.vcxproj.filters
  etc/visual-studio/libopenthread_k.vcxproj
  etc/visual-studio/libopenthread_k.vcxproj.filters
  include/openthread/link.h
  include/openthread/platform/radio.h
  src/core/Makefile.am
  src/core/api/link_api.cpp
  src/core/mac/mac.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/phy/radio_weak.cpp
  src/core/thread/announce_sender.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/utils/channel_manager.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
Labels: api: platform, enhancement

#3730 [efr32] take advantage of DMA for efr32 USART receive
  examples/platforms/efr32/uart.c
Labels: P4, enhancement, platform: efr32

#3733 [radio] only allow disable in sleep state
  include/openthread/platform/radio.h
  src/core/mac/sub_mac.cpp
  src/posix/platform/radio_spinel.cpp
Labels: P4, api: platform, posix-app

#3736 [api] remove otLinkGetPhyChannel*() Link APIs
  include/openthread/link.h
  src/cli/cli.cpp
  src/core/api/link_api.cpp
  src/diag/diag_process.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: api: user

#3740 [lowpan] suppress unchecked return warning in Lowpan::Compress()
  src/core/thread/lowpan.cpp
Labels: P4, enhancement

#3746 [nlbuild-autotools] update to 1.6.6
  third_party/nlbuild-autotools/repo/.default-version
  third_party/nlbuild-autotools/repo/CHANGES
  third_party/nlbuild-autotools/repo/autoconf/m4/nl_enable_coverage.m4
  third_party/nlbuild-autotools/repo/examples/configure.ac
Labels: P4, continuous-integration, enhancement

#3741 [travis] support clang code coverage
  .travis.yml
  .travis/after_success.sh
  configure.ac
Labels: P4, continuous-integration, enhancement

#3747 [spi-hdlc-adapter] allow log level to be changed
  tools/spi-hdlc-adapter/README.md
  tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Labels: P4, enhancement

#3748 [joiner] remove static requirement for vendor parameters in Start()
  include/openthread/joiner.h
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner.hpp
Labels: P4, enhancement

#3753 [fuzz] advance alarm time to cover timer handlers
  tests/fuzz/ip6_send.cpp
  tests/fuzz/ncp_uart_received.cpp
  tests/fuzz/radio_receive_done.cpp
Labels: P4, continuous-integration, enhancement

#3751 [ip6] clean up return values for `otIp6Send()`
  include/openthread/ip6.h
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
  src/core/net/ip6_mpl.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/network_diagnostic.cpp
Labels: P4, enhancement

#3756 [platform] return error on incorrect otPlatRadioDisable usage
  examples/platforms/nrf52811/radio.c
  examples/platforms/nrf52840/radio.c
  examples/platforms/posix/radio.c
  examples/platforms/posix/sim/radio-sim.c
Labels: P3, enhancement, platform: nrf52811, platform: nrf52840, platform: posix

#3759 [nrf52840] update README.md after SDK release
  examples/platforms/nrf52840/README.md
Labels: docs, platform: nrf52840

#3752 [message] add and use AppendTlv
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/common/tlvs.hpp
  src/core/meshcop/announce_begin_client.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/energy_scan_client.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/leader.cpp
  src/core/meshcop/panid_query_client.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/panid_query_server.cpp
Labels: P4, enhancement

#3757 [nrf528xx] don't return OT_ERROR_FAILED from otPlatRadioTransmit
  examples/platforms/nrf52811/radio.c
  examples/platforms/nrf52840/radio.c
Labels: P4, bug, platform: nrf52811, platform: nrf52840

#3762 [mle] do not apply active dataset from settings after attaching
  src/core/thread/mle.cpp
Labels: P3, bug

#3745 [efr32] improve USART driver error handling
  examples/platforms/efr32/uart.c
Labels: P4, enhancement, platform: efr32

#3761 [mle] enter fast poll mode when dequeue delayed MLE Data Request
  src/core/thread/mle.cpp
Labels: P4, bug

#3760 [radio-spinel] exit if it fails to get radio channelmask from rcp
  src/posix/platform/radio_spinel.cpp
Labels: P2, bug

#3767 [ncp] update MESHCOP_JOINER_COMMISSIONING to allow vendor info to be given
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3772 [nrf52840] update Nordic example CDC ACM driver
  third_party/NordicSemiconductor/libraries/usb/nordic_cdc_acm.cat
  third_party/NordicSemiconductor/libraries/usb/nordic_cdc_acm_example.inf
Labels: P4, enhancement, platform: nrf52840

#3764 [mpl] discard datagrams with multiple MPL Options
  src/core/net/ip6.cpp
Labels: P4, enhancement

#3771 [logging] fix BeaconPayload::ToInfoString() print of network name
  src/core/mac/mac_frame.cpp
Labels: P4, bug

#3774 [ncp] add spinel_meshcop_joiner_state_t enumeration
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3778 [meshcop] clip long strings for vendor name, model, version, data
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/meshcop_tlvs.hpp
Labels: P4, enhancement

#3779 [mle] allow attach and link sync between different Thread versions
  src/core/thread/mle_router.cpp
Labels: P3, bug

#3763 [data-poll-manager] add StopFastPolls() support
  include/openthread/link.h
  src/core/thread/data_poll_manager.cpp
  src/core/thread/data_poll_manager.hpp
  src/core/thread/mle.cpp
Labels: P4, enhancement

#3773 [dataset] allow setting partially complete active dataset
  include/openthread/dataset.h
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_local.cpp
  src/core/meshcop/dataset_local.hpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
Labels: api: user, enhancement

#3781 [network-data] add bounds check when comparing server data
  src/core/thread/network_data_leader_ftd.cpp
Labels: P4, bug

#3749 [posix-app] timeout for rcp radio driver
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
Labels: P3, bug, posix-app

#3780 [data-poll-manager] fix unexpected interval
  src/core/thread/data_poll_manager.cpp
Labels: P2, bug, enhancement

#3776 [efr32] further UART driver refactoring
  examples/platforms/efr32/uart.c
Labels: P4, enhancement, platform: efr32

#3787 [docker] copy source rather than git clone to support CI
  etc/docker/environment/Dockerfile
Labels: P4, continuous-integration, enhancement

#3788 [dtls] convert some of the info level logs to debug level
  src/core/meshcop/dtls.cpp
Labels: P4, enhancement
