Repository openthread/openthread, pull requests merged in 2019-01, with the labels that each got.

#3406 [posix-app] do nothing if select interrupted with no available fds
  src/posix/platform/system.c
Labels: enhancement, posix-app

#3409 [mbedtls] free mbedtls on initialization failure
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
Labels: P3, bug

#3410 [mle] avoid "1U << 32" when calculating attach start delay backoff
  src/core/thread/mle.cpp
Labels: P4, enhancement

#3411 [core] use `1UL` instead of `1U` when working with `uint32_t`
  src/core/mac/channel_mask.hpp
  src/core/mac/sub_mac.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, enhancement

#3415 [ncp-base] add IgnoreReturnValue when error should be ignored
  src/ncp/ncp_base.cpp
Labels: NCP, P4, enhancement

#3421 [android] disable UART echo
  Android.mk
Labels: P3, enhancement, posix-app

#3180 [posix-app] integrate with platform network interface
  .travis/check-posix-app-pty
  configure.ac
  src/posix/Makefile-posix
  src/posix/main.c
  src/posix/platform/Makefile.am
  src/posix/platform/hdlc_interface.hpp
  src/posix/platform/logging.c
  src/posix/platform/netif.cpp
  src/posix/platform/openthread-core-posix-config.h
  src/posix/platform/openthread-system.h
  src/posix/platform/platform-posix.h
  src/posix/platform/system.c
  src/posix/platform/udp.cpp
Labels: P4, enhancement, posix-app

#3408 [mac] remove redundant checks
  src/core/mac/channel_mask.hpp
  src/core/mac/mac.cpp
Labels: P4, enhancement

#3424 [border-agent] check if TLV is valid after reading
  src/core/meshcop/border_agent.cpp
Labels: P4, enhancement

#3425 [mac] post operation task on rx-on-idle mode change
  src/core/mac/mac.cpp
Labels: P4, enhancement

#3426 [posix-app] resolve "implicit conversion changes" warnings
  src/posix/platform/sim.c
Labels: P4, enhancement, posix-app

#3429 [nlbuild-autotools] update to 1.6.5
  third_party/nlbuild-autotools/repo/.default-version
  third_party/nlbuild-autotools/repo/CHANGES
  third_party/nlbuild-autotools/repo/Makefile
  third_party/nlbuild-autotools/repo/README.md
  third_party/nlbuild-autotools/repo/automake/post/rules/coverage.am
  third_party/nlbuild-autotools/repo/examples/Makefile-bootstrap
  third_party/nlbuild-autotools/repo/examples/Makefile-tests.am
  third_party/nlbuild-autotools/repo/examples/Makefile-toplevel.am
  third_party/nlbuild-autotools/repo/examples/repos.conf
  third_party/nlbuild-autotools/repo/make/post/rules/repos.mak
  third_party/nlbuild-autotools/repo/make/pre/macros/git.mak
  third_party/nlbuild-autotools/repo/make/pre/macros/repos.mak
  third_party/nlbuild-autotools/repo/scripts/bootstrap
  third_party/nlbuild-autotools/repo/tools/packages/automake/automake.patches/automake-00.description
  third_party/nlbuild-autotools/repo/tools/packages/automake/automake.patches/automake-00.patch
  third_party/nlbuild-autotools/repo/tools/packages/build
  third_party/nlbuild-autotools/repo/tools/packages/make/make.patches/make-00.patch
  third_party/nlbuild-autotools/repo/tools/packages/make/make.patches/make-00.url
  third_party/nlbuild-autotools/repo/tools/packages/make/make.url
  third_party/nlbuild-autotools/repo/tools/packages/make/make.version
Labels: P4, enhancement

#3430 [test-driver] update README.md format
  third_party/openthread-test-driver/README.google
  third_party/openthread-test-driver/README.md
Labels: P4, docs, enhancement

#3433 [nrf52840] increase max children count
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
Labels: P4, enhancement, platform: nrf52840

#3397 [script] add script to run cert tests
  script/test
  tests/scripts/thread-cert/config.py
Labels: P4, enhancement

#3431 [api] fix typos
  include/openthread/channel_manager.h
  include/openthread/coap.h
  include/openthread/coap_secure.h
  include/openthread/crypto.h
  include/openthread/link_raw.h
  include/openthread/thread.h
  src/cli/cli_coap_secure.cpp
  src/core/api/coap_secure_api.cpp
  src/core/thread/mle.cpp
Labels: P4, api: user, docs, enhancement

#3435 [windows] fix warnings
  examples/platforms/posix/alarm.c
  examples/platforms/posix/platform-posix.h
  examples/platforms/posix/radio.c
  examples/platforms/posix/sim/radio-sim.c
  src/ncp/spinel_decoder.cpp
  src/ncp/spinel_decoder.hpp
  src/posix/platform/radio_spinel.cpp
  tests/unit/test_link_quality.cpp
Labels: P4, enhancement, platform: windows

#3437 [mac] stop timer on pending WaitingForData operation on rx-on-idle change
  src/core/mac/mac.cpp
Labels: P3, bug

#3438 [mac] simplify the check for frame pending in data request ack
  src/core/mac/mac.cpp
Labels: P4, enhancement

#3440 [nrf52840] fix build with COAPS=1 and SNTP_CLIENT=1
  src/core/net/sntp_client.cpp
  src/core/net/sntp_client.hpp
  third_party/NordicSemiconductor/libraries/crypto/nrf52840-mbedtls-config.h
Labels: P4, enhancement, platform: nrf52840

#3444 [dtls] handle MBEDTLS_ERR_SSL_WANT_READ during send
  src/core/meshcop/dtls.cpp
Labels: P4, bug

#3445 [nrf52840] do not include libjlinkrtt in the SDK version of OT libs
  examples/platforms/nrf52840/Makefile.am
Labels: P4, enhancement, platform: nrf52840

#3449 [harness-automation] update device category
  tools/harness-automation/cases/med_9_2_10.py
  tools/harness-automation/cases/med_9_2_18.py
  tools/harness-automation/cases/med_9_2_6.py
Labels: P4, continuous-integration, enhancement

#3452 [docs] fix invalid TODO comment
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, docs, enhancement

#3448 [tests] fix mac key id mode parsing
  tests/scripts/thread-cert/mac802154.py
  tests/scripts/thread-cert/net_crypto.py
Labels: P4, bug, continuous-integration

#3451 [style] fix typos
  examples/platforms/cc2538/diag.c
  examples/platforms/cc2538/radio.c
  examples/platforms/efr32/diag.c
  examples/platforms/gp712/diag.c
  examples/platforms/kw41z/diag.c
  examples/platforms/posix/diag.c
  examples/platforms/posix/uart-posix.c
  examples/platforms/posix/uart-windows.c
  examples/platforms/samr21/diag.c
  src/cli/cli_coap_secure.cpp
  src/core/coap/coap_secure.cpp
  src/core/common/extension.hpp
  src/core/common/tlvs.hpp
  src/core/crypto/ecdsa.hpp
  src/core/mac/mac.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
  src/core/meshcop/leader.hpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/net/dhcp6_client.hpp
  src/core/net/ip6.hpp
  src/core/thread/announce_sender.hpp
  src/core/thread/child_table.hpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle_router_ftd.hpp
  src/core/thread/thread_netif.cpp
  src/core/utils/channel_manager.cpp
  src/core/utils/channel_manager.hpp
  src/core/utils/child_supervision.hpp
  src/ncp/ncp_buffer.cpp
  src/ncp/ncp_spi.hpp
  src/ncp/spinel_encoder.hpp
  src/posix/platform/hdlc_interface.hpp
Labels: P4, enhancement

#3453 [router-table] rename loop variables in UpdateAllocation()
  src/core/thread/router_table.cpp
Labels: P4, enhancement

#3455 [network-data] use enumeration Type for local vs leader
  src/core/thread/network_data.cpp
  src/core/thread/network_data.hpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_local.cpp
  tests/unit/test_network_data.cpp
Labels: P4, enhancement

#3456 [fuzz] add NCP UART input to fuzz tests
  tests/fuzz/Makefile.am
  tests/fuzz/fuzzer_platform.c
  tests/fuzz/ncp_uart_received.cpp
Labels: P4, continuous-integration, enhancement

#3458 [message] add const to read APIs
  include/openthread/message.h
  src/core/api/message_api.cpp
Labels: P4, api: user, enhancement

#3434 [coap] refine CoAP classes
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/coap/coap_secure.cpp
  src/core/coap/coap_secure.hpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/meshcop.hpp
  src/core/net/udp6.hpp
Labels: P4, coap, enhancement

#3446 [spinel] add documentation for spinel properties
  src/ncp/spinel.h
Labels: NCP, P4, docs, enhancement

#3454 [docker] add wpantund and toranj support
  etc/docker/environment/Dockerfile
  etc/docker/environment/docker-entrypoint.sh
Labels: P4, enhancement

#3459 [spinel] add bounds checks when decoding uint
  src/ncp/spinel.c
Labels: NCP, P4, enhancement

#3460 [sntp] fix Keil build with SNTP_CLIENT=1
  include/openthread/platform/toolchain.h
  src/core/net/sntp_client.cpp
  src/core/net/sntp_client.hpp
Labels: P4, comp: build, enhancement

#3462 [coap] return error if CoAP header exceeds message length
  src/core/coap/coap_message.cpp
Labels: P4, coap, enhancement

#3464 [coap] change assert to avoid index out-of-bounds warning
  src/core/coap/coap_message.cpp
Labels: P4, coap, enhancement

#3465 [travis] add arm gcc 8 to build tests
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
Labels: P4, continuous-integration, enhancement

#3466 [android] disable warning no virtual destructor
  Android.mk
Labels: P4, comp: build

#3467 [test] fix on macOS
  script/test
Labels: comp: build, enhancement

#3468 [code-utils] fix wrong pointer size in otALIGN
  src/core/common/code_utils.hpp
Labels: P2, bug

#3469 [coap] add NULL check in Message::Clone()
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
Labels: P4, bug, coap

#3315 [efr32] add support for OQPSK modulation in 915MHz band
  examples/platforms/efr32/Makefile.am
  examples/platforms/efr32/brd4161a/board_config.h
  examples/platforms/efr32/brd4166a/board_config.h
  examples/platforms/efr32/brd4170a/board_config.h
  examples/platforms/efr32/brd4170a/hal-config.h
  examples/platforms/efr32/brd4304a/board_config.h
  examples/platforms/efr32/platform-band.h
  examples/platforms/efr32/radio.c
  examples/platforms/efr32/rail_config.h
  third_party/silabs/LICENSE.txt
  third_party/silabs/README.md
  third_party/silabs/rail_config/rail_config.c
Labels: P4, enhancement, platform: efr32

#3471 [ncp-base] define ResponseType for queued spinel response entries
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
Labels: NCP, P4, enhancement

#3473 [cli] remove cli udp
  src/cli/cli_udp.cpp
  src/cli/cli_udp.hpp
Labels: P4, comp: cli

#3477 [udp] expose UDP receiver API
  include/openthread/udp.h
  src/core/api/udp_api.cpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
Labels: P4, api: user, enhancement

#3470 [cli] cleanup CoAP example
  src/cli/README_COAP.md
  src/cli/cli_coap.cpp
  src/cli/cli_coap.hpp
Labels: P4, coap, comp: cli, enhancement

#3474 [cli] cleanup dataset implementation
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_dataset.cpp
  src/cli/cli_dataset.hpp
Labels: P4, comp: cli, enhancement

#3476 [dhcp] remove dhcp server api
  Android.mk
  etc/visual-studio/libopenthread.vcxproj
  etc/visual-studio/libopenthread.vcxproj.filters
  etc/visual-studio/libopenthread_k.vcxproj
  etc/visual-studio/libopenthread_k.vcxproj.filters
  examples/drivers/windows/otLwf/precomp.h
  examples/drivers/windows/otLwf/thread.c
  include/openthread/Makefile.am
  include/openthread/dhcp6_server.h
  src/cli/cli.cpp
  src/core/Makefile.am
  src/core/api/dhcp6_api.cpp
  src/core/thread/mle.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, api: user, enhancement

#3472 [mle] simplify Start()
  src/core/api/thread_api.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
Labels: P4, enhancement

#3480 [cli] rename cli_udp_example to cli_udp
  Android.mk
  etc/visual-studio/libopenthread-cli.vcxproj
  etc/visual-studio/libopenthread-cli.vcxproj.filters
  src/cli/Makefile.am
  src/cli/cli.hpp
  src/cli/cli_udp.cpp
  src/cli/cli_udp.hpp
Labels: P4, comp: cli, enhancement

#3482 [fuzz] add CLI UART input to fuzz tests
  tests/fuzz/Makefile.am
  tests/fuzz/cli_uart_received.cpp
  tests/fuzz/fuzzer_platform.c
Labels: P4, comp: cli, continuous-integration, enhancement

#3483 [router-table] reuse const method GetRouter() in related non-const version
  src/core/thread/router_table.cpp
  src/core/thread/router_table.hpp
Labels: P4, enhancement

#3485 [slaac] no second address for a single prefix
  src/core/utils/slaac_address.cpp
Labels: P4, enhancement

#3486 [cli] fix GetOwner function for console CLI backend
  Android.mk
  etc/visual-studio/libopenthread-cli-windows.vcxproj
  etc/visual-studio/libopenthread-cli-windows.vcxproj.filters
  etc/visual-studio/libopenthread-cli.vcxproj
  etc/visual-studio/libopenthread-cli.vcxproj.filters
  src/cli/Makefile.am
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_console.cpp
  src/cli/cli_console.hpp
  src/cli/cli_dataset.cpp
  src/cli/cli_dataset.hpp
  src/cli/cli_instance.cpp
  src/cli/cli_server.cpp
  src/cli/cli_server.hpp
  src/cli/cli_uart.cpp
  src/cli/cli_uart.hpp
  src/cli/cli_udp.cpp
Labels: P4, comp: cli, enhancement

#3487 [doc] add missing doc for datatset
  src/cli/README.md
Labels: P4, comp: cli, docs

#3489 [border-agent] reuse dtls restart
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/border_agent.hpp
Labels: P4, enhancement

#3484 [slaac] handle slaac internally
  examples/drivers/windows/otLwf/filter.h
  examples/drivers/windows/otLwf/thread.c
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_instance.cpp
  src/core/api/ip6_api.cpp
  src/core/thread/mle.cpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
Labels: P4, api: user, enhancement

#3481 [mac-frame] change const methods to return pointers to const
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
Labels: P4, enhancement

#3490 [posix-app] expose mainloop APIs
  src/posix/main.c
  src/posix/platform/openthread-system.h
  src/posix/platform/platform-posix.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/system.c
Labels: P4, enhancement, posix-app

#3492 [mle] do not add ip6 addrs in disabled state
  src/core/thread/mle.cpp
Labels: P4, bug

#3493 [coap] return error if CoAP options exceeds message length
  src/core/coap/coap_message.cpp
Labels: P4, bug, coap

#3494 [posix] fix diagnostics for missing diag alarm
  src/posix/platform/alarm.c
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/logging.c
  src/posix/platform/misc.c
  src/posix/platform/netif.cpp
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/random.c
  src/posix/platform/settings.cpp
  src/posix/platform/sim.c
  src/posix/platform/spi-stubs.c
  src/posix/platform/system.c
  src/posix/platform/uart.c
  src/posix/platform/udp.cpp
  tests/scripts/thread-cert/test_diag.py
Labels: P2, bug, posix-app

#3495 [network-data] add length checks to insert operations
  src/core/thread/network_data_local.cpp
Labels: P4, enhancement

#3498 [network-data] add prefix length checks
  src/core/thread/network_data_local.cpp
Labels: P4, enhancement

#3422 [code] add static assert
  examples/platforms/da15000/crypto/aes_alt.h
  src/core/Makefile.am
  src/core/coap/coap_message.hpp
  src/core/common/code_utils.hpp
  src/core/utils/heap.hpp
  src/core/utils/static_assert.hpp
Labels: P4, enhancement

#3499 [cli] add bounds check on channel selection
  src/cli/cli.cpp
Labels: P4, comp: cli, enhancement

#3500 [cli-uart] save space for NULL terminator in rx buffer
  src/cli/cli_uart.cpp
Labels: P4, bug, comp: cli

#3497 [nrf52840] fix build with `DISABLE_BUILTIN_MBEDTLS=1`
  third_party/jlink/Makefile.am
Labels: P4, bug, comp: build, platform: nrf52840

#3502 [cli] move output format to server
  src/cli/cli_console.cpp
  src/cli/cli_console.hpp
  src/cli/cli_server.cpp
  src/cli/cli_server.hpp
  src/cli/cli_uart.cpp
  src/cli/cli_uart.hpp
Labels: P4, comp: cli, enhancement

#3504 [ip6] only allow external mcast addrs when iface is up
  include/openthread/ip6.h
  src/core/net/netif.cpp
  src/core/net/netif.hpp
Labels: P4, bug

#3505 [cli] validate prefix add/remove argument count
  src/cli/cli.cpp
Labels: P4, bug, comp: cli

#3506 [network-data] avoid overflow in Service TLV length computation
  src/core/thread/network_data_local.cpp
Labels: P4, bug

#3461 [mac] update "out of band tx" to check current operation state
  include/openthread/link.h
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
Labels: P4, enhancement

#3501 [cli] refine CLI APIs
  include/openthread/cli.h
  src/cli/cli.cpp
  src/cli/cli_uart.cpp
Labels: P4, api: user, comp: cli, enhancement

#3510 [emsk] set SETTINGS_CONFIG_PAGE_NUM = 2
  examples/platforms/emsk/flash.c
Labels: P4, bug, platform: emsk

#3507 [cli] add ping interval bounds check to avoid Timer::Start() assert
  src/cli/cli.cpp
Labels: P4, bug, comp: cli

#3508 [cli] add length check for "service add"
  src/cli/cli.cpp
Labels: P4, bug, comp: cli

#3513 [thread-netif] change Up()/Down() to void (no return)
  include/openthread/ip6.h
  src/core/api/ip6_api.cpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
Labels: P4, enhancement

#3516 [meshcop] set message offset when sending JOIN_FIN.rsp
  src/core/meshcop/commissioner.cpp
Labels: P3, bug, certification

#3503 [network-data] resolve undefined shift in SetPreference()
  src/core/thread/network_data_local.cpp
  src/core/thread/network_data_tlvs.hpp
Labels: P4, bug

#3518 [cli] add length checks for "coaps set psk"
  src/cli/cli_coap_secure.cpp
Labels: P4, bug, coap, comp: cli

#3521 [router-table] add arg bounds check to Release()
  include/openthread/thread_ftd.h
  src/core/api/thread_ftd_api.cpp
  src/core/thread/router_table.cpp
Labels: P4, bug

#3522 [ncp] resolve undefined shift in BorderRouterConfigToFlagByte
  src/ncp/ncp_base_mtd.cpp
Labels: NCP, P4, enhancement

#3523 [cli] add lower bounds check to channel selection
  src/cli/cli.cpp
Labels: P4, bug, comp: cli

#3524 [thci] update routerselectionjitter before start thread
  tools/harness-thci/OpenThread.py
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P3, bug, certification

#3526 [coap] make CoapBase::Send() private
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/coap/coap_secure.cpp
  src/core/coap/coap_secure.hpp
Labels: P4, coap, enhancement

#3520 [mac] remove mDidTx from otRadioFrame
  include/openthread/link.h
  include/openthread/platform/radio.h
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/mac/mac_frame.hpp
  src/core/mac/sub_mac.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/ncp_base_radio.cpp
Labels: P4, api: user, enhancement

#3517 [build] clean up switches for POSIX platform
  examples/Makefile-posix
  examples/common-switches.mk
  src/posix/Makefile-posix
Labels: P4, comp: build, platform: posix, posix-app

#3528 [docs] update README logo soup
  README.md
  doc/Makefile.am
  doc/images/ot-contrib-at.png
  doc/images/ot-contrib-particle.png
Labels: docs

#3530 [coap] process Option Length = 0xf as a format error
  src/core/coap/coap_message.cpp
Labels: P4, bug, coap

#3531 [cli] fix ping interval bounds check to avoid Timer::Start() assert
  src/cli/cli.cpp
Labels: P4, bug, comp: cli

#3532 [test] fix PRETTY_FILES definition in unit test makefile
  tests/unit/Makefile.am
  tests/unit/test_string.cpp
Labels: P4, enhancement

#3527 [router-table] add new method to iterate over router entries
  src/core/thread/router_table.cpp
  src/core/thread/router_table.hpp
Labels: P4, enhancement

#3534 [router-table] fix allocated router ids bit-vector size
  src/core/thread/router_table.hpp
Labels: P4, enhancement

#3529 [dtls] simplify dtls state machine
  src/core/coap/coap_secure.cpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
Labels: P4, enhancement

#3535 [meshcop] border agent of native commissioner
  include/openthread/dataset.h
  src/core/meshcop/border_agent.hpp
  src/core/meshcop/meshcop.hpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/net/ip6_filter.cpp
  src/core/net/ip6_filter.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
Labels: P4, certification, continuous-integration, enhancement

#3536 [fuzz] disable HDLC FCS check during fuzz tests
  src/ncp/hdlc.cpp
Labels: P4, continuous-integration, enhancement

#3537 [mle] remove redundant mAttachTimer stop
  src/core/thread/mle.cpp
Labels: P4, enhancement

#3539 [mle] change SetStateDetached()/SetStateChild() to be void (no return)
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
Labels: P4, enhancement

#3538 [mle] stop attach timer from SetStateChild()
  src/core/thread/mle.cpp
Labels: P4, bug

#3541 [diag] check buffer size definition
  src/cli/cli_uart.cpp
  src/core/utils/static_assert.hpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_spi.cpp
  src/ncp/ncp_uart.cpp
Labels: NCP, P4, comp: cli
