Repository openthread/openthread, pull requests merged in 2019-10, with the labels that each got.

#4210 [nrf528xx] always enable NRF_MBEDTLS_AES_ALT_INTERRUPT_CONTEXT
  examples/platforms/nrf528xx/nrf52811/openthread-core-nrf52811-config.h
  third_party/NordicSemiconductor/libraries/crypto/aes_alt.c
  third_party/NordicSemiconductor/libraries/crypto/aes_alt.h
  third_party/NordicSemiconductor/libraries/crypto/aes_alt_soft.c
  third_party/NordicSemiconductor/libraries/crypto/aes_alt_soft.h
  third_party/NordicSemiconductor/libraries/crypto/nrf52840-mbedtls-config.h
Labels: P3, bug, platform: nrf52811, platform: nrf52840

#4215 [mac-frame] set kMtu from config param and inline simple getters
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  tests/unit/test_mac_frame.cpp
Labels: P4, enhancement

#4216 [tlvs] use uint32_t for TLV size to avoid overflows
  src/core/common/message.cpp
  src/core/common/tlvs.cpp
  src/core/common/tlvs.hpp
Labels: P4, bug

#4219 [mesh-forwarder] support DHCP traffic forward when DHCP is disabled
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader.hpp
Labels: P2, bug, enhancement

#4212 [nrf52840] add UART and BLE bootloader support
  examples/Makefile-nrf52840
  examples/platforms/nrf528xx/nrf52811/README.md
  examples/platforms/nrf528xx/nrf52840/README.md
  examples/platforms/nrf528xx/nrf52840/nrf52840_bootloader_ble.ld
  examples/platforms/nrf528xx/nrf52840/nrf52840_bootloader_uart.ld
  examples/platforms/nrf528xx/nrf52840/nrf52840_bootloader_usb.ld
Labels: P4, enhancement, platform: nrf52840

#4218 [toranj] add test covering wpantund host route management feature
  tests/toranj/start.sh
  tests/toranj/test-036-wpantund-host-route-management.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#4217 [efr32] add radio.c debug counters for efr32mg12 and efr32mg21
  AUTHORS
  examples/platforms/efr32mg12/brd4161a/board_config.h
  examples/platforms/efr32mg12/brd4166a/board_config.h
  examples/platforms/efr32mg12/brd4170a/board_config.h
  examples/platforms/efr32mg12/brd4304a/board_config.h
  examples/platforms/efr32mg12/platform-band.h
  examples/platforms/efr32mg12/radio.c
  examples/platforms/efr32mg21/brd4180a/board_config.h
  examples/platforms/efr32mg21/platform-band.h
  examples/platforms/efr32mg21/radio.c
Labels: P4, enhancement, platform: efr32

#4224 [toolchain] add definition of UINT16_MAX
  include/openthread/platform/toolchain.h
Labels: P4, bug, comp: build

#4222 [travis] switch to ubuntu bionic
  .travis.yml
Labels: P4, continuous-integration, enhancement

#4146 [mle] fix MleRouter::UpdateRoutes
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router_ftd.hpp
Labels: P4, bug

#4226 [script] use python version specified in test script
  script/test
Labels: P4, enhancement

#4160 [posix] optimize the source match table implementation
  examples/platforms/posix/radio.c
  examples/platforms/utils/soft_source_match_table.c
  examples/platforms/utils/soft_source_match_table.h
Labels: P4, enhancement, platform: posix

#4228 [udp] suppress warning of unused parameter
  src/core/net/udp6.cpp
Labels: P4, enhancement

#4229 [nrf528xx] change casting type to remove SES warning
  examples/platforms/nrf528xx/src/radio.c
Labels: P4, enhancement, platform: nrf52811, platform: nrf52840

#4230 [instance] fix typo in OT_CHANGED_IP6_MULTICAST_*
  include/openthread/instance.h
  src/core/common/notifier.cpp
  src/core/net/netif.cpp
  src/core/thread/mle.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, enhancement

#4232 [posix] always set ACK FP for data requests when SrcMatch is disabled
  examples/platforms/posix/radio.c
Labels: P2, bug, platform: posix

#4156 [examples] provide APIs to manipulate 802.15.4 frames
  examples/platforms/posix/radio.c
  examples/platforms/utils/Makefile.am
  examples/platforms/utils/mac_frame.cpp
  examples/platforms/utils/mac_frame.h
  src/core/mac/mac_frame.hpp
Labels: api: platform, platform: posix

#4227 [coap] remove otCoapMessageSetMessageId()
  include/openthread/coap.h
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/core/api/coap_api.cpp
Labels: P4, api: user, coap, enhancement

#4236 [nrf528xx] correct the link of nRF5 Command Line Tool in README
  examples/platforms/nrf528xx/nrf52811/README.md
  examples/platforms/nrf528xx/nrf52840/README.md
Labels: docs, platform: nrf52811, platform: nrf52840

#4225 [api] add API to get Thread Version
  include/openthread/thread.h
  src/cli/README.md
  src/cli/cli.cpp
  src/core/api/thread_api.cpp
  src/core/openthread-core-config.h
  src/core/thread/mle_constants.hpp
Labels: P4, api: user, enhancement

#4238 [mbedtls] fix wrong ECDSA enabling macro
  third_party/mbedtls/mbedtls-config.h
Labels: P4, bug, comp: build

#4239 [travis] add library size report support
  .travis/check-size
Labels: P4, continuous-integration, enhancement

#4182 [coap] optimize call to GetMatchedResponseCopy
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
Labels: P4, coap, enhancement

#4235 [posix-app] make set an atomic operation
  include/openthread/platform/settings.h
  src/posix/platform/settings.cpp
Labels: P4, enhancement, posix-app

#4244 [tests] fix the wrong port of dtls
  tests/scripts/thread-cert/config.py
Labels: P4, bug, continuous-integration

#4248 [tests] update test_child to use Clear() instead of memset
  tests/unit/test_child.cpp
Labels: P4, continuous-integration, enhancement

#4249 [topology] remove unused (non const) GetExtAddress() method
  src/core/thread/topology.hpp
Labels: P4, enhancement

#4214 [efr32mg12] update the channel range of channel config entry
  third_party/silabs/rail_config/rail_config.c
Labels: P3, bug, platform: efr32

#4246 [radio] handle CCA ED threshold property configuration
  examples/platforms/cc1352/radio.c
  examples/platforms/cc2538/radio.c
  examples/platforms/cc2650/radio.c
  examples/platforms/cc2652/radio.c
  examples/platforms/efr32mg12/radio.c
  examples/platforms/efr32mg21/radio.c
  examples/platforms/gp712/radio.c
  examples/platforms/kw41z/radio.c
  examples/platforms/nrf528xx/src/radio.c
  examples/platforms/posix/radio.c
  examples/platforms/qpg6095/radio.c
  examples/platforms/samr21/radio.c
  include/openthread/platform/radio.h
  src/core/radio/radio.hpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_dispatcher.cpp
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
Labels: NCP, P4, api: platform, enhancement

#4252 [spi-hdlc-adapter] remove unused variables
  tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Labels: P4, enhancement

#4255 [coap] force set message id for CON and NON types
  src/core/coap/coap.cpp
  src/core/meshcop/border_agent.cpp
Labels: P4, bug

#4269 [fuzz] add stub for CCA ED radio APIs
  tests/fuzz/fuzzer_platform.c
Labels: P4, comp: build, continuous-integration

#4265 [mac] set tx frame as empty when tx aborted during frame preparation
  src/core/mac/data_poll_handler.cpp
  src/core/mac/data_poll_sender.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac_frame.hpp
  src/core/thread/indirect_sender.cpp
  src/core/thread/mesh_forwarder.cpp
Labels: P4, bug

#4241 [cli] add hex string payload for `udp send`
  src/cli/README_UDP.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_udp.cpp
  src/cli/cli_udp.hpp
  tests/scripts/thread-cert/node.py
Labels: P3, enhancement

#4272 [nrf528xx] add wildcards to PRETTY_FILES list for nrf528xx sources
  examples/platforms/nrf528xx/Makefile.am
Labels: P4, comp: build, platform: nrf52811, platform: nrf52840

#4143 [heap] export heap API
  include/openthread/heap.h
  src/core/Makefile.am
  src/core/api/heap_api.cpp
  src/core/common/instance.hpp
Labels: P4, api: user, enhancement

#4253 [cli] get preferred and supported channel mask
  src/cli/README.md
  src/cli/cli.cpp
Labels: P4, comp: cli, enhancement

#4276 [mac] adding mac_types.hpp/cpp
  Android.mk
  src/core/Makefile.am
  src/core/common/message.hpp
  src/core/common/settings.hpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  src/core/mac/mac_types.cpp
  src/core/mac/mac_types.hpp
  src/core/meshcop/commissioner.hpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner.hpp
  src/core/meshcop/joiner_router.hpp
  src/core/meshcop/meshcop.cpp
  src/core/meshcop/meshcop.hpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/net/dhcp6_client.hpp
  src/core/net/dhcp6_server.hpp
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  src/core/net/netif.hpp
  src/core/thread/address_resolver.cpp
  src/core/thread/key_manager.hpp
  src/core/thread/lowpan.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router_ftd.hpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/panid_query_server.hpp
  src/core/thread/router_table.hpp
  src/core/thread/src_match_controller.cpp
  src/core/thread/topology.hpp
  src/core/utils/child_supervision.hpp
Labels: P4, enhancement

#4278 [efr32] move __START definition to Makefile-efr32mgxx makefiles
  examples/Makefile-efr32mg12
  examples/Makefile-efr32mg21
  examples/platforms/efr32mg12/Makefile.am
  examples/platforms/efr32mg21/Makefile.am
  third_party/silabs/Makefile.am
Labels: P4, comp: build, enhancement, platform: efr32

#4279 [efr32] add otSysEventSignalPending and NVIC priorities to efr32mg21
  examples/platforms/efr32mg21/Makefile.am
  examples/platforms/efr32mg21/alarm.c
  examples/platforms/efr32mg21/radio.c
  examples/platforms/efr32mg21/system.c
  examples/platforms/efr32mg21/uart.c
Labels: P4, enhancement, platform: efr32

#4257 [toranj] add option to build script to enable tests
  tests/toranj/build.sh
Labels: P4, continuous-integration, enhancement

#4256 [mac] add option to change direct/indirect TX retry number
  include/openthread/link.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/link_api.cpp
  src/core/config/mac.h
  src/core/config/openthread-core-config-check.h
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_ftd.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/ncp_base_radio.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, api: user, comp: cli, enhancement

#4280 [neighbor] add methods to check neighbor state
  src/core/api/thread_api.cpp
  src/core/mac/data_poll_sender.cpp
  src/core/mac/mac.cpp
  src/core/thread/child_table.cpp
  src/core/thread/indirect_sender.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/router_table.cpp
  src/core/thread/topology.hpp
Labels: P4, enhancement

#4274 [notifier] add Update method
  src/core/common/notifier.hpp
  src/core/mac/mac.cpp
  src/core/thread/key_manager.cpp
  src/core/thread/mle.cpp
Labels: P4, enhancement

#4277 [efr32] fix LED gpio port and pin allocation for BRD4166A
  examples/platforms/efr32mg12/brd4166a/hal-config.h
Labels: P4, bug, platform: efr32

#4295 [posix-app] fix implementation of CCA ED threshold config
  src/posix/platform/radio_spinel.cpp
Labels: P3, bug

#4292 [third-party] change end of line character from CRLF do LF
  .travis/check-size
  third_party/mbedtls/repo/programs/pkey/rsa_priv.txt
  third_party/mbedtls/repo/programs/pkey/rsa_pub.txt
  third_party/ti/manifest_driverlib_cc13xx_cc26xx_3_xx_xx.html
  third_party/ti/ti-openthread_1.01.0_manifest.html
Labels: P4, enhancement
