Repository openthread/openthread, pull requests merged in 2019-03, with the labels that each got.

#3638 [mle] fix OOB steering data length
  src/core/thread/mle_router.cpp
Labels: P4, bug

#3639 [thci] match meshlocalprefix accurately to classify the addresses correctly
  tools/harness-thci/OpenThread.py
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P4, bug, certification

#3640 [mle] not echo back ML-EID registered by MTD
  src/core/thread/mle_constants.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data_leader.cpp
  tests/scripts/thread-cert/Cert_5_2_05_AddressQuery.py
  tests/scripts/thread-cert/Cert_5_3_07_DuplicateAddress.py
  tests/scripts/thread-cert/Cert_5_6_01_NetworkDataRegisterBeforeAttachLeader.py
  tests/scripts/thread-cert/Cert_5_6_02_NetworkDataRegisterBeforeAttachRouter.py
  tests/scripts/thread-cert/Cert_5_6_03_NetworkDataRegisterAfterAttachLeader.py
  tests/scripts/thread-cert/Cert_5_6_04_NetworkDataRegisterAfterAttachRouter.py
  tests/scripts/thread-cert/Cert_5_6_05_NetworkDataRegisterAfterAttachRouter.py
  tests/scripts/thread-cert/Cert_5_6_06_NetworkDataExpiration.py
  tests/scripts/thread-cert/Cert_5_6_07_NetworkDataRequestREED.py
  tests/scripts/thread-cert/Cert_5_6_08_ContextManagement.py
  tests/scripts/thread-cert/Cert_5_6_09_NetworkDataForwarding.py
  tests/scripts/thread-cert/Cert_6_1_02_REEDAttach_MED.py
  tests/scripts/thread-cert/Cert_6_3_02_NetworkDataUpdate.py
  tests/scripts/thread-cert/Cert_7_1_01_BorderRouterAsLeader.py
  tests/scripts/thread-cert/Cert_7_1_02_BorderRouterAsRouter.py
  tests/scripts/thread-cert/Cert_7_1_03_BorderRouterAsLeader.py
  tests/scripts/thread-cert/Cert_7_1_04_BorderRouterAsRouter.py
  tests/scripts/thread-cert/Cert_7_1_05_BorderRouterAsRouter.py
  tests/scripts/thread-cert/command.py
Labels: P4, enhancement

#3643 [posix] do not exit on EINTR in UART
  examples/platforms/posix/uart-posix.c
Labels: P4, enhancement, platform: posix

#3645 [build] fix SLAAC switch
  examples/common-switches.mk
Labels: P4, comp: build

#3644 [router-table] simplify router table code
  src/core/thread/router_table.cpp
  src/core/thread/router_table.hpp
Labels: P4, enhancement

#3646 [dhcp6] clean up Prefix Agent state management in DHCPv6 server
  src/core/net/dhcp6_server.cpp
  src/core/net/dhcp6_server.hpp
Labels: P4, enhancement

#3652 [meshcop] fix buffer overflow in Commissioner Session ID compare
  src/core/meshcop/leader.cpp
Labels: P4, bug

#3653 [dtls] fix bug in resetting dtls state on error
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
Labels: P4, bug

#3655 [docs] update repo name
  README.md
Labels: docs

#3378 [phy] add support for OQPSK modulation in 915MHz band
  configure.ac
  etc/visual-studio/libopenthread.vcxproj
  etc/visual-studio/libopenthread.vcxproj.filters
  etc/visual-studio/libopenthread_k.vcxproj
  etc/visual-studio/libopenthread_k.vcxproj.filters
  examples/platforms/cc1352/radio.c
  examples/platforms/cc2650/radio.c
  examples/platforms/cc2652/radio.c
  examples/platforms/posix/radio.c
  include/openthread/dataset.h
  include/openthread/link.h
  include/openthread/platform/radio.h
  src/cli/cli.cpp
  src/core/Makefile.am
  src/core/api/link_api.cpp
  src/core/mac/channel_mask.cpp
  src/core/mac/channel_mask.hpp
  src/core/mac/mac.cpp
  src/core/meshcop/announce_begin_client.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/energy_scan_client.cpp
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/meshcop/panid_query_client.cpp
  src/core/openthread-core-default-config.h
  src/core/phy/phy.hpp
  src/core/thread/announce_begin_server.cpp
  src/core/thread/announce_sender.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mle.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/network_diagnostic_tlvs.hpp
  src/core/thread/panid_query_server.cpp
  src/core/utils/channel_manager.cpp
  src/core/utils/channel_monitor.cpp
  src/core/utils/channel_monitor.hpp
  src/diag/diag_process.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_mtd.cpp
  tests/unit/test_mac_frame.cpp
Labels: P4, enhancement

#3632 [dtls] refine CoAP secure and DTLS
  include/openthread/coap_secure.h
  src/cli/cli_coap_secure.cpp
  src/cli/cli_coap_secure.hpp
  src/core/api/coap_secure_api.cpp
  src/core/coap/coap_secure.cpp
  src/core/coap/coap_secure.hpp
  src/core/common/instance.hpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/border_agent.hpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
Labels: P4, api: user, enhancement

#3658 [nrf52840] do not specify interface protocol in USB CDC
  examples/platforms/nrf52840/usb-cdc-uart.c
Labels: P4, enhancement, platform: nrf52840

#3621 [slaac] enhance and simplify SLAAC support
  include/openthread/ip6.h
  src/core/api/ip6_api.cpp
  src/core/common/instance.hpp
  src/core/common/settings.hpp
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  src/core/thread/mle.cpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
  src/core/utils/slaac_address.cpp
  src/core/utils/slaac_address.hpp
Labels: P4, enhancement

#3657 [diag] add radio sleep / receive mode for RF certification
  src/diag/README.md
  src/diag/diag_process.cpp
  src/diag/diag_process.hpp
Labels: P1, enhancement, platform: nrf52840

#3660 [dtls] simplify logging
  src/core/meshcop/dtls.cpp
Labels: P4, enhancement

#3661 [spinel-decoder] fix comments
  src/ncp/spinel_decoder.hpp
Labels: NCP, P4, docs, enhancement

#3662 [ncp] report 2.4GHz and/or 915MHz support from SPINEL_PROP_CAPS
  src/ncp/ncp_base.cpp
Labels: NCP, P4, enhancement

#3663 [spinel] add spinel definition guideline
  src/ncp/spinel.h
Labels: NCP, P4, docs, enhancement

#3666 [build] fix warning in SLAAC module in Keil
  src/core/utils/slaac_address.cpp
Labels: P4, comp: build, enhancement

#3683 [travis] remove posix-app-ncp test due to frequent failures
  .travis.yml
Labels: P2, continuous-integration, enhancement

#3671 [travis] fix/check EOF newline on pretty/pretty-check
  script/clang-format-check.sh
  script/clang-format.sh
Labels: P4, continuous-integration, enhancement

#3672 [meshcop] make length checks more strict on ChannelMaskTlv parsing
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/meshcop/meshcop_tlvs.hpp
Labels: P4, bug

#3673 [meshcop] avoid shift exponent too large in ChannelTlv processing
  include/openthread/platform/radio.h
  src/core/meshcop/meshcop_tlvs.cpp
Labels: P4, enhancement

#3675 [posix-app] more baudrates on macOS
  src/posix/platform/hdlc_interface.cpp
Labels: P4, enhancement

#3680 [nrf52840] handle NRF_ERROR_BUSY from SD in flash driver
  examples/platforms/nrf52840/flash_sd.c
  examples/platforms/nrf52840/softdevice.h
Labels: P4, enhancement, platform: nrf52840

#3682 [nrf52811] add emulation on nRF52840 to README.md
  examples/platforms/nrf52811/README.md
Labels: docs, platform: nrf52811

#3665 [api] rename ChannelMaskPage0 to ChannelMask
  examples/drivers/windows/otNodeApi/otNodeApi.cpp
  include/openthread/dataset.h
  src/cli/cli_dataset.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_manager.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, api: user, enhancement

#3674 [dtls] handle MBEDTLS_ERR_PEM_ALLOC_FAILED in Dtls::MapError()
  src/core/meshcop/dtls.cpp
Labels: P4, bug

#3511 [posix-app] add readline for CLI
  .travis/script.sh
  configure.ac
  src/posix/Makefile-posix
  src/posix/Makefile.am
  src/posix/console_cli.c
  src/posix/console_cli.h
  src/posix/main.c
  src/posix/platform/openthread-system.h
  src/posix/platform/sim.c
  src/posix/platform/uart.c
Labels: P4, comp: cli, enhancement, posix-app

#3664 [efr32] enable BRD4170A to support 915MHz and 2.4GHz by default
  examples/platforms/efr32/brd4161a/board_config.h
  examples/platforms/efr32/brd4166a/board_config.h
  examples/platforms/efr32/brd4170a/board_config.h
  examples/platforms/efr32/brd4304a/board_config.h
  examples/platforms/efr32/openthread-core-efr32-config.h
  examples/platforms/efr32/radio.c
  examples/platforms/efr32/rail_config.h
Labels: P4, enhancement, platform: efr32

#3687 [link-raw] log frame tx attempt failures
  src/core/mac/link_raw.cpp
  src/core/mac/link_raw.hpp
  src/core/mac/sub_mac_callbacks.cpp
Labels: P4, enhancement

#3689 [posix-app] fix debug flag
  src/posix/Makefile-posix
Labels: P4, comp: build, posix-app

#3692 [ip6] correct annotations
  src/core/net/icmp6.hpp
  src/core/net/ip6.hpp
  src/core/net/ip6_address.hpp
  src/core/net/ip6_headers.hpp
  src/core/net/ip6_mpl.hpp
  src/core/net/ip6_routes.hpp
  src/core/net/udp6.hpp
Labels: P4, enhancement

#3690 [meshcop] process ChannelMaskTlv in message
  src/core/meshcop/meshcop_tlvs.cpp
Labels: P4, enhancement

#3691 [cli] avoid input overflow
  src/cli/cli_uart.cpp
  src/posix/Makefile-posix
  src/posix/platform/openthread-core-posix-config.h
Labels: P4, comp: cli, enhancement

#3693 [meshcop] fix doxygen in ChannelMaskTlv::SetChannelMask()
  src/core/meshcop/meshcop_tlvs.hpp
Labels: docs

#3688 [toranj] add test to cover OT/NCP SLAAC module behavior
  tests/toranj/openthread-core-toranj-config.h
  tests/toranj/start.sh
  tests/toranj/test-026-slaac-address-wpantund.py
  tests/toranj/test-030-slaac-address-ncp.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#3694 [dtls] do not allow Open() or Bind() when DTLS session is started
  src/core/coap/coap_secure.cpp
  src/core/coap/coap_secure.hpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
Labels: P4, bug

#3695 [doc] update documentation of CLI counters command
  src/cli/README.md
Labels: comp: cli, docs

#3589 [tests] add test case Cert_9_2_02
  tests/scripts/thread-cert/Cert_6_1_02_REEDAttach_MED.py
  tests/scripts/thread-cert/Cert_7_1_01_BorderRouterAsLeader.py
  tests/scripts/thread-cert/Cert_7_1_03_BorderRouterAsLeader.py
  tests/scripts/thread-cert/Cert_9_2_02_MGMTCommissionerSet.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/coap.py
  tests/scripts/thread-cert/command.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/mesh_cop.py
  tests/scripts/thread-cert/network_data.py
  tests/scripts/thread-cert/network_layer.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/node_cli.py
  tests/scripts/thread-cert/test_network_layer.py
  tests/scripts/thread-cert/tlvs_parsing.py
Labels: P4, continuous-integration, enhancement

#3696 [style] prefer OT_UNUSED_VARIABLE
  examples/apps/cli/main.c
  examples/apps/ncp/main.c
  examples/platforms/nrf52811/alarm.c
  examples/platforms/nrf52811/diag.c
  examples/platforms/nrf52811/radio.c
  tests/fuzz/fuzzer_platform.c
  tests/unit/test_platform.cpp
Labels: P4, enhancement

#3697 [travis] add travis_retry to before_install
  .travis.yml
Labels: P4, continuous-integration, enhancement

#3698 [udp] return error on source port mismatch in Udp::SendTo()
  src/core/net/udp6.cpp
Labels: P4, enhancement

#3701 [travis] remove unused sources
  .travis/before_install.sh
Labels: api: platform, continuous-integration

#3702 [netdata] fix stable network data version when service updates
  src/core/thread/network_data_leader_ftd.cpp
Labels: P4, bug

#3700 [tests] add an inspector for travis certification tests
  tests/scripts/thread-cert/README.md
  tests/scripts/thread-cert/debug.py
Labels: P4, continuous-integration, enhancement

#3704 [efr32] fix build issues when sub-GHz support is not configured
  examples/platforms/efr32/Makefile.am
  examples/platforms/efr32/openthread-core-efr32-config.h
Labels: bug, comp: build, platform: efr32

#3707 [core] change return type of otMessageRead()
  include/openthread/message.h
  src/core/api/message_api.cpp
Labels: P4, api: user, enhancement

#3708 [udp] add Udp::IsBound() method
  src/core/meshcop/dtls.cpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
Labels: P4, enhancement

#3709 [dtls] return error on multiple calls to `Dtls::Open()`
  src/core/meshcop/dtls.cpp
Labels: P4, enhancement

#3713 [efr32] minor enhancements to radio driver
  examples/platforms/efr32/radio.c
Labels: P4, enhancement, platform: efr32

#3710 [fuzz] advance alarm time to cover timer handlers
  tests/fuzz/cli_uart_received.cpp
  tests/fuzz/fuzzer_platform.c
Labels: P4, continuous-integration, enhancement

#3716 [nrf528xx] add otSysEventSignalPending call in spi-slave driver
  examples/platforms/nrf52811/spi-slave.c
  examples/platforms/nrf52811/uart.c
  examples/platforms/nrf52840/spi-slave.c
  examples/platforms/nrf52840/uart.c
Labels: enhancement, platform: nrf52811, platform: nrf52840

#3720 [docs] fix instances of "the the" in comments
  include/openthread/coap_secure.h
  src/core/coap/coap_secure.hpp
  src/core/meshcop/border_agent.hpp
  src/core/meshcop/dtls.hpp
  src/core/net/sntp_client.hpp
  src/core/openthread-core-default-config.h
  src/ncp/ncp_base_radio.cpp
  src/ncp/ncp_buffer.hpp
Labels: docs

#3659 [ncp] add service spinel bindings
  include/openthread/platform/toolchain.h
  include/openthread/server.h
  src/core/api/server_api.cpp
  src/core/openthread-core-config-check.h
  src/core/openthread-core-default-config.h
  src/core/thread/mle.hpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3718 [style] replace reinterpret_cast with static_cast where possible
  src/core/meshcop/dataset_manager.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_diagnostic.cpp
Labels: P4, enhancement
