Repository openthread/openthread, pull requests merged in 2019-12, with the labels that each got.

#4338 [mle] clean up MleRouter::HandleAdvertisement
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router_ftd.hpp
  src/core/thread/mle_router_mtd.hpp
Labels: P4, cla: yes, enhancement

#4360 [network-data] always support service registration at Leader
  include/openthread/netdata.h
  include/openthread/server.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/netdata_api.cpp
  src/core/api/server_api.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data.hpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_data_local.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.h
Labels: P3, bug, cla: yes, enhancement

#4365 [nrf528xx] remove unnecessary typedef from nrf-config.h
  third_party/NordicSemiconductor/libraries/nrf_security/config/nrf-config.h
Labels: P4, cla: yes, enhancement, platform: nrf52811, platform: nrf52833, platform: nrf52840

#4366 [nrf528xx] fix freertos mutex casting
  third_party/NordicSemiconductor/libraries/nrf_security/nrf_cc310_plat/src/nrf_cc310_platform_mutex_freertos.c
Labels: P2, bug, cla: yes, platform: nrf52811, platform: nrf52833, platform: nrf52840

#4372 [coap] fix response timeout for NON messages
  src/core/coap/coap.cpp
Labels: P3, bug, cla: yes, coap

#4371 [mac] fix typo in data poll sender
  src/core/mac/data_poll_sender.cpp
  src/core/mac/data_poll_sender.hpp
Labels: P4, cla: yes, enhancement

#4336 [posix-app] add log level argument
  src/posix/Makefile-posix
  src/posix/main.c
Labels: P4, enhancement, posix-app

#4352 [posix-app] optimize the interface between radio_spinel and hdlc_interface
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/hdlc_interface.hpp
  src/posix/platform/platform-posix.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
  src/posix/platform/sim.c
Labels: P4, cla: yes, enhancement, posix-app

#4368 [mle] MTD prioritizes ML-EID registration
  src/core/thread/mle.cpp
Labels: P4, cla: yes, enhancement

#4373 [docs] update CLA text
  CONTRIBUTING.md
Labels: cla: yes, docs

#4375 [posix-app] remove dependency on OPENTHREAD_TARGET_DEFINES
  src/posix/Makefile.am
  src/posix/platform/Makefile.am
  src/posix/platform/hdlc_interface.cpp
Labels: P4, cla: yes, comp: build, posix-app

#4378 [examples] add stub for otPlatSettingsDeinit to settings_ram.c
  examples/platforms/utils/settings_ram.c
Labels: P4, bug, cla: yes, comp: build

#4357 [linked-list] adding `LinkedList` class
  src/core/Makefile.am
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/common/linked_list.hpp
  src/core/common/notifier.cpp
  src/core/common/notifier.hpp
  src/core/common/timer.cpp
  src/core/common/timer.hpp
  src/core/net/icmp6.cpp
  src/core/net/icmp6.hpp
  src/core/net/netif.cpp
  src/core/net/netif.hpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
  tests/unit/Makefile.am
  tests/unit/test_linked_list.cpp
Labels: P4, cla: yes, enhancement

#4379 [posix-host] add cmake support
  .travis/script.sh
  CMakeLists.txt
  src/posix/CMakeLists.txt
  src/posix/platform/CMakeLists.txt
Labels: P4, cla: yes, comp: build

#4387 [nrf528xx] change used FEM implementation from simple_gpio to three_pin_gpio
  examples/platforms/nrf528xx/nrf52811/Makefile.am
  examples/platforms/nrf528xx/nrf52833/Makefile.am
  examples/platforms/nrf528xx/nrf52840/Makefile.am
  examples/platforms/nrf528xx/src/fem.c
  examples/platforms/nrf528xx/src/platform-fem.h
  third_party/NordicSemiconductor/Makefile.am
Labels: P4, cla: yes, enhancement, platform: nrf52811, platform: nrf52833, platform: nrf52840

#4383 [thci] fix wrong call to .lstrip('0x')
  tools/harness-thci/OpenThread.py
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P4, bug, cla: yes

#4384 [mac] multiple smaller changes/enhancements
  src/core/mac/mac.cpp
Labels: P4, cla: yes, enhancement

#4392 [nrf52833] fix bootloader configuration
  examples/Makefile-nrf52833
Labels: P4, cla: yes, comp: build, platform: nrf52833

#4231 [harness-automation] support RF-shield test cases
  tools/harness-automation/autothreadharness/harness_case.py
  tools/harness-automation/autothreadharness/settings_sample.py
  tools/harness-automation/cases/leader_9_2_9.py
  tools/harness-automation/cases/med_6_3_2.py
  tools/harness-automation/cases/med_9_2_10.py
  tools/harness-automation/cases/reed_5_6_7.py
  tools/harness-automation/cases/router_9_2_10.py
  tools/harness-automation/cases/router_9_2_9.py
  tools/harness-automation/cases/sed_9_2_10.py
  tools/harness-automation/cases_R140/leader_9_2_9.py
  tools/harness-automation/cases_R140/med_6_3_2.py
  tools/harness-automation/cases_R140/med_9_2_10.py
  tools/harness-automation/cases_R140/reed_5_6_7.py
  tools/harness-automation/cases_R140/router_9_2_10.py
  tools/harness-automation/cases_R140/router_9_2_9.py
  tools/harness-automation/cases_R140/sed_9_2_10.py
Labels: P4, cla: yes, enhancement

#4386 [posix-host] parse all parameters to a structure
  src/posix/main.c
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/hdlc_interface.hpp
  src/posix/platform/openthread-system.h
  src/posix/platform/platform-posix.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
  src/posix/platform/system.c
Labels: P4, cla: yes, enhancement, posix-host

#4394 [diag] add radio state command
  include/openthread/platform/radio.h
  src/core/diags/README.md
  src/core/diags/factory_diags.cpp
  src/core/radio/radio.hpp
  src/core/radio/radio_platform.cpp
Labels: P4, cla: yes, enhancement

#4407 [posix-host] update IsSafeToHandleNow() to avoid re-entrant issue
  src/posix/platform/radio_spinel.hpp
Labels: P1, bug, cla: yes, posix-host

#4399 [dns-client] add const to address pointer
  include/openthread/dns.h
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/net/dns_client.cpp
  src/core/net/dns_client.hpp
Labels: P4, cla: yes, comp: cli, enhancement

#4400 [mle] set appropriate Response TLV length in SendChildUpdateResponse
  src/core/thread/mle_router.cpp
Labels: P4, bug, cla: yes

#4401 [network-diagnostic] avoid reference binding to null pointer
  src/core/thread/network_diagnostic.cpp
  src/core/thread/network_diagnostic.hpp
Labels: P4, cla: yes, enhancement

#4403 [ip6] replace IpProto type with uint8_t
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
  src/core/net/ip6_headers.hpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
  src/core/thread/lowpan.cpp
  src/core/thread/lowpan.hpp
  tests/unit/test_lowpan.hpp
Labels: P4, cla: yes, enhancement

#4404 [commissioner] add network name length check in GeneratePskc()
  src/core/meshcop/commissioner.cpp
Labels: P4, bug, cla: yes

#4408 [posix-host] set logging level early
  src/posix/main.c
Labels: P4, cla: yes, enhancement, posix-host

#4410 [spinel] add missing name for radio caps
  src/ncp/spinel.c
Labels: P4, cla: yes

#4409 [ncp] reduce size by searching property handlers
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: P2, cla: yes, enhancement, posix-host

#4412 [logging] reduce otThreadErrorToString code size
  src/core/common/logging.cpp
Labels: P2, cla: yes, enhancement

#4364 [thci] add configurable device connection type for OpenThread_WpanCtl
  tools/harness-thci/OpenThread_WpanCtl.py
  tools/harness-thci/README.md
  tools/harness-thci/deviceInputFields.xml
Labels: P4, cla: yes, enhancement

#4414 [script] fix linking clang-format-6.0 on Mac OS X
  script/bootstrap
Labels: P4, cla: yes, comp: build, enhancement

#4416 [ncp] conform with c++11 constexpr and static_assert
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
Labels: NCP, P4, cla: yes, enhancement

#4385 [posix-host] add spinel_interface to extend transport layers
  src/posix/platform/Makefile.am
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/hdlc_interface.hpp
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
  src/posix/platform/spinel_interface.hpp
Labels: P4, cla: yes, enhancement, posix-host

#4382 [mac] TxRetry histogram and maximal TxRetry expiry counter added
  .travis/script.sh
  include/openthread/link.h
  src/core/api/link_api.cpp
  src/core/config/mac.h
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/sub_mac.cpp
  src/core/mac/sub_mac.hpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: P4, cla: yes, enhancement

#4417 [link-quality] remove ENABLE_TX_ERROR_RATE_TRACKING feature flag
  include/openthread/thread.h
  include/openthread/thread_ftd.h
  src/core/config/link_quality.h
  src/core/config/openthread-core-config-check.h
  src/core/mac/mac.cpp
  src/core/thread/link_quality.cpp
  src/core/thread/link_quality.hpp
  src/core/thread/mle_router.cpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, cla: yes, enhancement

#4422 [network-diagnostic] remove useless include
  src/core/thread/network_diagnostic_tlvs.hpp
Labels: P4, cla: yes, enhancement

#4421 [mac] add retry flag support for direct messages
  src/core/mac/mac.cpp
  src/core/mac/sub_mac.cpp
Labels: P4, cla: yes, enhancement

#4425 [network-data] support registration on child devices
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
Labels: P4, bug, cla: yes

#4426 [dataset] check if dataset is present in otDatasetIsCommissioned
  src/core/api/dataset_api.cpp
Labels: P3, bug, cla: yes
