Repository openthread/openthread, pull requests merged in 2019-06, with the labels that each got.

#3811 [settings] add option to store settings in volatile storage
  examples/common-switches.mk
  examples/platforms/qpg6095/Makefile.am
  examples/platforms/qpg6095/settings.cpp
  examples/platforms/utils/Makefile.am
  examples/platforms/utils/settings_flash.c
  examples/platforms/utils/settings_ram.c
  include/openthread/platform/settings.h
Labels: P4, enhancement

#3887 [dhcp] fix solicit request issue introduced in #3287
  src/core/net/dhcp6_client.cpp
Labels: P3, bug, certification

#3891 [ncp] update static checking for diag output buffer size
  src/ncp/ncp_base.hpp
  src/ncp/ncp_spi.cpp
  src/ncp/ncp_uart.cpp
Labels: NCP, P4, enhancement

#3895 [android] add random_crypto_api.cpp to Android.mk
  Android.mk
Labels: P4, comp: build, enhancement

#3580 [build] rename ncp_radio to rcp
  .travis/check-posix-app-pty
  .travis/script.sh
  examples/Makefile-nrf52811
  examples/Makefile-nrf52840
  examples/apps/ncp/Makefile.am
  examples/platforms/nrf52811/README.md
  script/test
  src/ncp/Makefile.am
  src/posix/README.md
  tests/toranj/wpan.py
Labels: P4, comp: build, enhancement

#3893 [message] remove the AllMessageQueue in MessagePool
  src/core/common/message.cpp
  src/core/common/message.hpp
  tests/unit/test_priority_queue.cpp
Labels: P4, enhancement

#3894 [random] assert aMax is bigger than aMin
  src/core/common/random.hpp
Labels: P4, enhancement

#3900 [mbedtls] add threading errors translation
  src/core/crypto/mbedtls.cpp
Labels: P4, enhancement

#3897 [dtls] invoke callback after DTLS disconnect timeout
  src/core/meshcop/dtls.cpp
Labels: P4, enhancement

#3902 [ncp] spinel prop to get a new dataset (use when forming new network)
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_ftd.cpp
  src/ncp/spinel.c
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3905 [cli] remove "s_" prefix from static methods
  src/cli/cli.cpp
  src/cli/cli.hpp
Labels: P4, comp: cli, enhancement

#3907 [tests] remove windows-specific test support
  tests/otTestRunner/App.config
  tests/otTestRunner/AssemblyInfo.cs
  tests/otTestRunner/Program.cs
Labels: P4, enhancement, platform: windows

#3889 [spinel] validate decoded/unpacked UTF8 string
  src/ncp/spinel.c
Labels: NCP, P4, enhancement

#3890 [spinel] remove unused definitions
  src/ncp/spinel.h
Labels: NCP, P4, enhancement

#3904 [coap] add checks for OT_ERROR_NO_BUFS
  include/openthread/coap.h
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/core/api/coap_api.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
  src/core/meshcop/announce_begin_client.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/energy_scan_client.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/leader.cpp
  src/core/meshcop/panid_query_client.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/panid_query_server.cpp
Labels: P4, bug

#3909 [mac] rename methods requesting frame transmission
  src/core/api/link_api.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#3910 [dataset] choose a preferred channel when forming new dataset
  src/core/meshcop/dataset_manager_ftd.cpp
Labels: P4, enhancement

#3911 [route-table] remove unused Ip6::Routes
  Android.mk
  src/core/Makefile.am
  src/core/common/instance.hpp
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
  src/core/net/ip6_routes.cpp
  src/core/net/ip6_routes.hpp
Labels: P4, enhancement

#3917 [doc] remove unused definitions
  include/openthread/platform/toolchain.h
Labels: P4, docs, enhancement, platform: windows

#3913 [mesh-forwarder] enhance data poll log message
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, enhancement

#3914 [mac] inline shorter methods / rename frame preparing methods
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
Labels: P4, enhancement

#3920 [auto-start] remove auto-start feature
  include/openthread/thread.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/thread_api.cpp
  src/core/common/instance.cpp
  src/core/common/settings.hpp
  src/core/openthread-core-config-check.h
  src/core/openthread-core-default-config.h
Labels: P4, api: user, enhancement

#3921 [style] apply missing const declarations
  src/core/coap/coap_secure.hpp
  src/core/common/settings.hpp
  src/core/common/tasklet.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_filter.cpp
  src/core/mac/mac_filter.hpp
  src/core/mac/mac_frame.hpp
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/joiner_router.hpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/net/ip6.hpp
  src/core/net/ip6_headers.hpp
  src/core/net/ip6_mpl.hpp
  src/core/net/netif.cpp
  src/core/net/netif.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mle_router_ftd.hpp
  src/core/thread/mle_router_mtd.hpp
  src/core/thread/mle_tlvs.hpp
  src/core/utils/channel_manager.hpp
  src/ncp/ncp_base.hpp
Labels: P4, enhancement

#3817 [thci] bug fixes and clean up the code style
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
  script/pystyle.cfg
  tools/harness-thci/OpenThread.py
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P2, bug, certification, enhancement

#3923 [docs] add SiLabs to list of supporters
  README.md
  doc/images/ot-contrib-silabs.png
Labels: docs

#3915 [mac] move data poll tx into Mac and DataPollManager
  src/core/common/message.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/thread/data_poll_manager.cpp
  src/core/thread/data_poll_manager.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
Labels: P4, enhancement

#3918 [data-poll-manager] remove unneeded code handling NO_BUFS error
  src/core/thread/data_poll_manager.cpp
  src/core/thread/data_poll_manager.hpp
Labels: P4, enhancement

#3919 [tlvs] allow longer length to support forward compatibility
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/leader.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/network_diagnostic_tlvs.hpp
  src/core/thread/thread_tlvs.hpp
Labels: P4, enhancement

#3926 [mle] remove unused MleRouter::RemoveNeighbor method
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router_ftd.hpp
  src/core/thread/mle_router_mtd.hpp
Labels: P4, enhancement

#3927 [examples] add headers to pretty check
  examples/platforms/cc1352/Makefile.am
  examples/platforms/cc1352/cc1352_radio.h
  examples/platforms/cc1352/openthread-core-cc1352-config.h
  examples/platforms/cc2538/Makefile.am
  examples/platforms/cc2538/openthread-core-cc2538-config.h
  examples/platforms/cc2650/Makefile.am
  examples/platforms/cc2650/cc2650_radio.h
  examples/platforms/cc2650/openthread-core-cc2650-config.h
  examples/platforms/cc2652/Makefile.am
  examples/platforms/cc2652/cc2652_radio.h
  examples/platforms/cc2652/openthread-core-cc2652-config.h
  examples/platforms/efr32/Makefile.am
  examples/platforms/efr32/openthread-core-efr32-config.h
  examples/platforms/efr32/rail_config.h
  examples/platforms/emsk/Makefile.am
  examples/platforms/emsk/openthread-core-emsk-config.h
  examples/platforms/gp712/Makefile.am
  examples/platforms/gp712/alarm_qorvo.h
  examples/platforms/gp712/openthread-core-gp712-config.h
  examples/platforms/gp712/platform_qorvo.h
  examples/platforms/gp712/radio_qorvo.h
  examples/platforms/gp712/random_qorvo.h
  examples/platforms/gp712/uart_qorvo.h
  examples/platforms/kw41z/Makefile.am
  examples/platforms/kw41z/openthread-core-kw41z-config.h
  examples/platforms/kw41z/platform-kw41z.h
  examples/platforms/nrf52811/Makefile.am
  examples/platforms/nrf52811/openthread-core-nrf52811-config.h
  examples/platforms/nrf52840/Makefile.am
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
  examples/platforms/posix/Makefile.am
  examples/platforms/qpg6095/Makefile.am
  examples/platforms/qpg6095/alarm_qorvo.h
  examples/platforms/qpg6095/misc_qorvo.h
  examples/platforms/qpg6095/openthread-core-qpg6095-config.h
  examples/platforms/qpg6095/platform_qorvo.h
  examples/platforms/qpg6095/radio_qorvo.h
  examples/platforms/qpg6095/random_qorvo.h
  examples/platforms/qpg6095/settings_qorvo.h
  examples/platforms/qpg6095/uart_qorvo.h
  examples/platforms/samr21/Makefile.am
  examples/platforms/samr21/openthread-core-samr21-config.h
  examples/platforms/utils/Makefile.am
Labels: P4, enhancement

#3929 [tests] change string concatenation format in python scripts
  tests/scripts/thread-cert/node.py
Labels: P4, continuous-integration, enhancement

#3930 [meshcop] add MeshLocalPrefixTlv::GetMeshLocalPrefixLength() method
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/meshcop_tlvs.hpp
Labels: P3, bug

#3931 [docs] update link to GNU Arm Embedded Toolchain
  examples/platforms/cc1352/README.md
  examples/platforms/cc2538/README.md
  examples/platforms/cc2650/README.md
  examples/platforms/cc2652/README.md
  examples/platforms/efr32/README.md
  examples/platforms/kw41z/README.md
  examples/platforms/nrf52811/README.md
  examples/platforms/nrf52840/README.md
  examples/platforms/samr21/README.md
Labels: docs

#3932 [data-poll-sender] rename DataPollManager as DataPollSender
  Android.mk
  src/core/Makefile.am
  src/core/api/link_api.cpp
  src/core/common/instance.hpp
  src/core/mac/data_poll_sender.cpp
  src/core/mac/data_poll_sender.hpp
  src/core/mac/mac.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mle.cpp
  src/core/thread/network_diagnostic.cpp
Labels: P4, enhancement

#3936 [coap] remove payload marker correctly and add payload marker check
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
  src/core/common/message.cpp
Labels: P2, bug, certification

#3935 [network-diagnostic] specify link-local source for link-local destination
  src/core/thread/network_diagnostic.cpp
Labels: P2, certification, enhancement

#3937 [mle] add field-specific length methods to Challenge/Response TLVs
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_tlvs.hpp
Labels: P3, bug

#3940 [docs] Add Samsung to supporters and image cleanup
  README.md
  doc/Makefile.am
  doc/images/ot-contrib-ms.png
  doc/images/ot-contrib-samsung.png
Labels: docs

#3933 [mesh-forwarder] clear children's indirect msg and src match table on stop
  src/core/thread/mesh_forwarder.cpp
Labels: P2, bug

#3941 [mac] simplify how HandleReceivedFrame() passes frame to next layer
  src/core/mac/mac.cpp
Labels: P4, enhancement

#3942 [posix-sim] enhance microsecond alarm implementation
  examples/platforms/posix/Makefile.platform.am
  examples/platforms/posix/alarm.c
Labels: P3, enhancement, platform: posix

#3944 [message] adjust offset when cloning a message subset
  src/core/common/message.cpp
Labels: P3, bug

#3945 [address-resolver] fix TLV length in response messages
  src/core/thread/address_resolver.cpp
Labels: P4, bug

#3949 [commissioner] add error checking to GetLeaderAloc and SendPetition in Start
  src/core/meshcop/commissioner.cpp
Labels: P3, bug

#3950 [posix-app] enhance RCP failure info
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/misc.c
Labels: P4, enhancement

#3939 [mac] change frame length type from uint8_t to uint16_t
  include/openthread/platform/radio.h
  src/core/mac/mac.cpp
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  src/core/thread/lowpan.cpp
  src/core/thread/lowpan.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: api: platform, enhancement
