Repository openthread/openthread, pull requests merged in 2019-05, with the labels that each got.

#3785 [mesh-forwarder] verify data request is ack with fp=1
  doc/spinel-protocol-src/spinel-prop-core.md
  examples/platforms/cc1352/radio.c
  examples/platforms/cc2538/radio.c
  examples/platforms/cc2650/radio.c
  examples/platforms/cc2652/radio.c
  examples/platforms/da15000/radio.c
  examples/platforms/efr32/radio.c
  examples/platforms/emsk/radio.c
  examples/platforms/gp712/radio.c
  examples/platforms/kw41z/radio.c
  examples/platforms/nrf52811/radio.c
  examples/platforms/nrf52840/radio.c
  examples/platforms/posix/radio.c
  examples/platforms/posix/sim/radio-sim.c
  examples/platforms/qpg6095/radio.c
  examples/platforms/samr21/radio.c
  include/openthread/platform/radio.h
  src/core/mac/mac_frame.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/ncp/ncp_base_radio.cpp
  src/ncp/spinel.h
  src/posix/platform/radio_spinel.cpp
Labels: P3, api: platform, enhancement

#3791 [cli] add 'childip' command to cli for getting ip addresses of MTD children
  examples/drivers/windows/otApi/otApi.cpp
  include/openthread/thread_ftd.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
Labels: P4, comp: cli, enhancement

#3789 [timer] fix elapsed overflow
  src/cli/cli.cpp
  src/core/api/thread_api.cpp
  src/core/coap/coap.cpp
  src/core/common/timer.hpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_local.cpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dns_client.cpp
  src/core/net/ip6_mpl.cpp
  src/core/net/sntp_client.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/router_table.cpp
  src/core/thread/time_sync_service.cpp
  src/core/utils/jam_detector.cpp
Labels: P4, enhancement

#3792 [toranj] add thread commissioning test (single joiner)
  tests/toranj/build.sh
  tests/toranj/start.sh
  tests/toranj/test-031-meshcop-joiner-commissioner.py
  tests/toranj/wpan.py
Labels: P4, continuous-integration, enhancement

#3793 [docker] add build status badge
  README.md
Labels: continuous-integration, docs

#3794 [doc] add Cascoda to contributor list
  AUTHORS
  README.md
  doc/images/ot-contrib-cascoda.png
Labels: docs

#3758 [efr32] add support for entering EM2 low-power mode for sleepy devices
  configure.ac
  examples/platforms/efr32/Makefile.am
  examples/platforms/efr32/README.md
  examples/platforms/efr32/alarm.c
  examples/platforms/efr32/platform-efr32.h
  examples/platforms/efr32/radio.c
  examples/platforms/efr32/sleepy-demo/Makefile.am
  examples/platforms/efr32/sleepy-demo/README.md
  examples/platforms/efr32/sleepy-demo/efr32-sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32/sleepy-demo/efr32-sleepy-demo-ftd/main.c
  examples/platforms/efr32/sleepy-demo/efr32-sleepy-demo-mtd/Makefile.am
  examples/platforms/efr32/sleepy-demo/efr32-sleepy-demo-mtd/main.c
  examples/platforms/efr32/system.c
Labels: P4, enhancement, platform: efr32

#3796 [6lowpan] return OT_ERROR_PARSE on MeshHeader::Init() failures
  src/core/thread/lowpan.cpp
  src/core/thread/lowpan.hpp
Labels: P4, enhancement

#3804 [gp712] add include <stdbool.h> to resolve build issues
  examples/platforms/gp712/alarm_qorvo.h
  examples/platforms/gp712/platform_qorvo.h
Labels: P3, bug, platform: gp712

#3799 [cc1352] fixes for integration with Texas Instruments examples
  examples/platforms/cc1352/radio.c
  examples/platforms/cc2650/radio.c
  examples/platforms/cc2652/radio.c
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_local.cpp
Labels: P3, bug, platform: cc1352, platform: cc2650

#3805 [gp712] enforce cross compilation by default
  examples/Makefile-gp712
Labels: comp: build, enhancement, platform: gp712

#3801 [spi-hdlc-adapter] reset NCP/RCP on exit
  tools/spi-hdlc-adapter/spi-hdlc-adapter.c
Labels: P3, bug, enhancement, posix-app

#3800 [posix-app] add option to skip reset RCP
  src/posix/platform/platform-posix.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
  src/posix/platform/system.c
Labels: P3, enhancement, posix-app

#3803 [mle] maintain best parent candidate during router-only search
  src/core/thread/mle.cpp
  src/core/thread/mle_constants.hpp
  src/core/thread/mle_router.cpp
Labels: P4, enhancement

#3809 [posix] use monotonic raw timer
  examples/platforms/posix/alarm.c
  src/posix/platform/alarm.c
Labels: P4, enhancement, posix-app

#3810 [test] fix unclosed file
  tests/scripts/thread-cert/node_cli.py
Labels: P4, continuous-integration

#3812 [notifier] fix the #if check testing LOG_CORE being enabled
  src/core/common/notifier.cpp
Labels: P4, bug

#3814 [spinel] fix outdated comment
  src/ncp/spinel.h
Labels: docs

#3816 [nrf528xx] use Nordic's OUI in factory assigned IEEE EUI-64
  examples/platforms/nrf52811/README.md
  examples/platforms/nrf52811/openthread-core-nrf52811-config.h
  examples/platforms/nrf52811/radio.c
  examples/platforms/nrf52840/README.md
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
  examples/platforms/nrf52840/radio.c
Labels: enhancement, platform: nrf52811, platform: nrf52840

#3819 [ip6] add support for parsing embedded IPv4 address
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  tests/unit/Makefile.am
  tests/unit/test_ip6_address.cpp
Labels: P4, enhancement

#3823 [nrf528xx] fix undefined behavior warning in IAR
  examples/platforms/nrf52811/README.md
  examples/platforms/nrf52811/radio.c
  examples/platforms/nrf52840/README.md
  examples/platforms/nrf52840/radio.c
Labels: enhancement, platform: nrf52811, platform: nrf52840

#3824 [docs] fix see also in doxygen
  include/openthread/channel_manager.h
  include/openthread/instance.h
  include/openthread/ip6.h
  include/openthread/link.h
  include/openthread/platform/debug_uart.h
  include/openthread/thread.h
  include/openthread/thread_ftd.h
Labels: docs, enhancement

#3822 [udp] expose an API to send UDP datagram
  include/openthread/udp.h
  src/core/api/udp_api.cpp
Labels: P3, api: user, enhancement

#3830 [ip6] add additional parse validation to Ip6::Address::FromString
  src/core/net/ip6_address.cpp
  tests/unit/test_ip6_address.cpp
Labels: P4, enhancement

#3831 [nrf52xx] notify if ACK was sent with frame pending bit set
  examples/platforms/nrf52811/radio.c
  examples/platforms/nrf52840/radio.c
Labels: P3, enhancement, platform: nrf52811, platform: nrf52840

#3833 [time-sync] remove reference operator in C API
  include/openthread/network_time.h
  src/cli/cli.cpp
  src/core/api/network_time_api.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, api: user, bug

#3835 [tests] make pretty and update makefile
  tests/unit/Makefile.am
  tests/unit/test_platform.h
Labels: P4, enhancement

#3836 [ncp-buffer] include APIs using otMessage only in FTD/MTD builds
  src/core/Makefile.am
  src/ncp/ncp_buffer.cpp
  src/ncp/ncp_buffer.hpp
  src/ncp/spinel_encoder.hpp
Labels: P4, enhancement

#3837 [ncp] allow PARENT_RESPONSE_INFO property to be filtered by host
  src/ncp/changed_props_set.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_ftd.cpp
Labels: NCP, P4, enhancement

#3840 [entropy] fix included headers in public API
  include/openthread/entropy.h
  include/openthread/random_crypto.h
  include/openthread/random_noncrypto.h
Labels: P4, api: platform, enhancement

#3841 [mbedtls] add missing entropy/ctr_drbg errors to MbedTls::MapError()
  src/core/crypto/mbedtls.cpp
Labels: P4, enhancement

#3842 [nrf528xx] check for otPlatEntropyGet() reentrancy
  examples/platforms/nrf52811/entropy.c
  examples/platforms/nrf52840/entropy.c
Labels: P4, enhancement, platform: nrf52811, platform: nrf52840

#3843 [ip6] add additional parse validation to Ip6::Address::FromString
  src/core/net/ip6_address.cpp
  tests/unit/test_ip6_address.cpp
Labels: P4, enhancement

#3846 [thci] correct conversion of IPv6 prefix
  tools/harness-thci/OpenThread.py
Labels: P3, bug

#3834 [docs] update quick start guides to use dataset method
  examples/apps/cli/README.md
  examples/platforms/efr32/README.md
  examples/platforms/emsk/README.md
  examples/platforms/kw41z/README.md
  examples/platforms/nrf52811/README.md
  examples/platforms/nrf52840/README.md
  examples/platforms/samr21/README.md
Labels: P4, docs, enhancement

#3849 [nrf528xx] add missing include guards
  third_party/NordicSemiconductor/libraries/crypto/nrf52811-mbedtls-config.h
  third_party/NordicSemiconductor/libraries/crypto/nrf52840-mbedtls-config.h
Labels: enhancement, platform: nrf52811, platform: nrf52840

#3821 [android] disable some optional features
  Android.mk
  include/openthread-config-android.h
Labels: P3, comp: build, enhancement, posix-app

#3850 [mle] fix bug in MLE attach behavior
  src/core/thread/mle.cpp
Labels: P2, bug, certification

#3851 [mpl] add extra validation when removing MPL Option
  src/core/net/ip6.cpp
Labels: P4, enhancement

#3854 [api] expose API to obtain RLOC
  include/openthread/thread.h
  src/core/api/thread_api.cpp
Labels: P4, api: user, enhancement

#3855 [cli] clean up IPv6 address printing
  src/cli/README.md
  src/cli/README_COAPS.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_udp.cpp
Labels: P4, comp: cli, enhancement

#3857 [channel-manager] fix interval units
  src/core/utils/channel_manager.cpp
Labels: P4, bug

#3858 [dtls] fix bug of cipher suites check
  src/core/meshcop/dtls.cpp
Labels: P4, bug

#3860 [nrf52840] fix included headers in aes_alt.h
  examples/platforms/nrf52840/openthread-core-nrf52840-config.h
  third_party/NordicSemiconductor/libraries/crypto/aes_alt.h
  third_party/NordicSemiconductor/libraries/crypto/nrf52840-mbedtls-config.h
Labels: P3, bug, platform: nrf52840

#3868 [nlbuild-autotools] update to 1.6.11
  third_party/nlbuild-autotools/repo/.default-version
  third_party/nlbuild-autotools/repo/CHANGES
  third_party/nlbuild-autotools/repo/autoconf/m4/nl_filtered_canonical.m4
  third_party/nlbuild-autotools/repo/automake/post.am
  third_party/nlbuild-autotools/repo/automake/pre.am
  third_party/nlbuild-autotools/repo/automake/pre/macros.am
  third_party/nlbuild-autotools/repo/examples/Makefile-bootstrap
  third_party/nlbuild-autotools/repo/make/host/tools/tools.mak
  third_party/nlbuild-autotools/repo/make/post/rules/bootstrap.mak
  third_party/nlbuild-autotools/repo/make/post/rules/repos.mak
  third_party/nlbuild-autotools/repo/make/pre/macros/verbosity.mak
  third_party/nlbuild-autotools/repo/scripts/bootstrap
  third_party/nlbuild-autotools/repo/tools/packages/m4/m4.url
  third_party/nlbuild-autotools/repo/tools/packages/m4/m4.version
Labels: P4, comp: build, enhancement

#3863 [commissioner] add provisioning URL member variable
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
Labels: P4, enhancement

#3869 [docs] update logo for new branding
  README.md
  doc/Makefile.am
  doc/images/Open-Thread-Logo-200x42.png
  doc/images/openthread_logo.png
  doc/images/ot-contrib-google.png
  doc/images/ot-contrib-nest.png
Labels: docs

#3872 [cc2538] fix radio disabled for entropy get
  examples/platforms/cc2538/entropy.c
Labels: P1, bug, platform: cc2538

#3861 [cc2538] fix entropy.c
  examples/platforms/cc2538/entropy.c
Labels: P1, bug, platform: cc2538

#3870 [mle] skip saving NetworkInfo before device is attached (for first time)
  src/core/thread/mle.cpp
Labels: P4, enhancement

#3873 [cli] fix coap secure typo
  src/cli/cli_coap_secure.cpp
Labels: P4, comp: cli

#3876 [doc] define missing groups
  include/openthread/error.h
Labels: docs

#3871 [mac] keep the second energy scan sample
  src/core/mac/sub_mac.cpp
Labels: P4, bug

#3856 [cli] extend ipaddr command
  examples/drivers/windows/include/otLwfIoctl.h
  examples/drivers/windows/otApi/otApi.cpp
  examples/drivers/windows/otLwf/iocontrol.c
  examples/drivers/windows/otLwf/iocontrol.h
  include/openthread/thread.h
  src/cli/README.md
  src/cli/cli.cpp
Labels: P4, comp: cli, enhancement

#3881 [hdlc] update MultiFrameBuffer to allow saved frames to be re-read
  src/ncp/hdlc.hpp
  src/posix/platform/radio_spinel.cpp
  tests/unit/test_hdlc.cpp
Labels: P4, enhancement

#3882 [cli] count failed ping try
  src/cli/cli.cpp
Labels: P4, comp: cli, enhancement

#3884 [time-sync] reset sequence upon joining a new partition & ensure leader is always authoritative
  src/core/thread/time_sync_service.cpp
Labels: P4, bug

#3886 [instance] update order of member variables
  src/core/common/instance.cpp
  src/core/common/instance.hpp
Labels: P4, enhancement
