Repository openthread/openthread, pull requests merged in 2020-10, with the labels that each got.

#5593 [docs] add source for BeagleBone Black guide
  doc/STYLE_GUIDE.md
  doc/site/en/guides/border-router/beaglebone-black.md
Labels: cla: yes, comp: docs

#5602 [utils] adding 'LookupTable' class and use it in CLI
  Android.mk
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_coap.cpp
  src/cli/cli_coap.hpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_coap_secure.hpp
  src/cli/cli_commissioner.cpp
  src/cli/cli_commissioner.hpp
  src/cli/cli_dataset.cpp
  src/cli/cli_dataset.hpp
  src/cli/cli_joiner.cpp
  src/cli/cli_joiner.hpp
  src/cli/cli_network_data.cpp
  src/cli/cli_network_data.hpp
  src/cli/cli_udp.cpp
  src/cli/cli_udp.hpp
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/api/link_raw_api.cpp
  src/core/utils/lookup_table.cpp
  src/core/utils/lookup_table.hpp
  tests/unit/CMakeLists.txt
  tests/unit/Makefile.am
  tests/unit/test_lookup_table.cpp
Labels: P4, cla: yes, comp: cli, enhancement

#5603 [cli] add new helper 'ParseIp6Prefix()'
  src/cli/cli.cpp
  src/cli/cli.hpp
Labels: P4, cla: yes, comp: cli, enhancement

#5604 [message] add new flavors of Read/Write/Append/Prepend methods
  src/core/api/message_api.cpp
  src/core/backbone_router/bbr_manager.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_secure.cpp
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/common/tlvs.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/joiner_router.hpp
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/net/checksum.cpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dhcp6_server.cpp
  src/core/net/dns_client.cpp
  src/core/net/dns_client.hpp
  src/core/net/dns_headers.hpp
  src/core/net/icmp6.cpp
  src/core/net/ip6.cpp
  src/core/net/ip6_filter.cpp
  src/core/net/ip6_headers.cpp
  src/core/net/ip6_mpl.cpp
  src/core/net/ip6_mpl.hpp
  src/core/net/sntp_client.cpp
  src/core/net/sntp_client.hpp
  src/core/net/udp6.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/discover_scanner.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/indirect_sender.cpp
  src/core/thread/link_metrics.cpp
  src/core/thread/lowpan.cpp
  src/core/thread/lowpan.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mlr_manager.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/network_diagnostic_tlvs.hpp
  src/core/utils/child_supervision.cpp
  tests/unit/test_checksum.cpp
  tests/unit/test_lowpan.cpp
  tests/unit/test_message.cpp
  tests/unit/test_spinel_buffer.cpp
Labels: P4, cla: yes, enhancement

#5605 [ip6] use 'Get<Filter>()' (remove unnecessary namespace)
  src/core/net/ip6.cpp
  src/core/net/udp6.cpp
Labels: P4, cla: yes, enhancement

#5610 [github-actions] fix expect check
  .github/workflows/simulation.yml
Labels: P2, bug, cla: yes, continuous-integration

#5613 [script] fix arm-gcc toolchain install on ubuntu
  script/bootstrap
Labels: cla: yes, comp: build

#5606 [docs] update BeagleBone setup guide
  doc/site/en/guides/border-router/beaglebone-black.md
Labels: cla: yes, comp: docs

#5616 [clang-format] update to clang-format-10
  .clang-format
  .github/workflows/build.yml
  CONTRIBUTING.md
  STYLE_GUIDE.md
  examples/platforms/k32w/src/system.c
  script/bootstrap
  script/clang-format
  src/core/backbone_router/ndproxy_table.hpp
  src/core/common/settings.hpp
  src/core/thread/topology.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  tests/unit/test_spinel_decoder.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5617 [scan-build] update to clang-tools-10
  .github/workflows/build.yml
  script/check-scan-build
Labels: P4, cla: yes, continuous-integration, enhancement

#5615 [cli] replace 'PRIx64' use
  src/cli/cli_joiner.cpp
Labels: P4, cla: yes, comp: cli, enhancement

#5618 [logging] update 'otDump' to use 'ot::String'
  src/core/common/logging.cpp
Labels: P4, cla: yes, enhancement

#5607 [cmd-parser] adding helper 'ParseAs{Type}' functions
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_commissioner.cpp
  src/cli/cli_dataset.cpp
  src/cli/cli_joiner.cpp
  src/cli/cli_network_data.cpp
  src/cli/cli_udp.cpp
  src/core/utils/parse_cmdline.cpp
  src/core/utils/parse_cmdline.hpp
  tests/unit/CMakeLists.txt
  tests/unit/Makefile.am
  tests/unit/test_cmd_line_parser.cpp
Labels: P4, cla: yes, comp: cli, enhancement

#5625 [commissioner] specify src for c/tx
  src/core/meshcop/commissioner.cpp
Labels: P4, cla: yes, enhancement

#5631 [codecov] disable project coverage threshold
  .codecov.yml
Labels: cla: yes, continuous-integration

#5573 [low-power] add cli command `macsend` for certification
  include/openthread/instance.h
  include/openthread/link.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/link_api.cpp
  src/core/common/message.hpp
  src/core/thread/indirect_sender.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  tests/scripts/expect/v1_2-sed_mac_send.exp
  tests/scripts/thread-cert/node.py
Labels: Thread 1.2, certification, cla: yes

#5614 [thread-cert] enhance case 9.2.4 to avoid reverifying coap retransmission packets
  tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5621 [toranj] add new test-case covering joiner-router behavior
  tests/toranj/start.sh
  tests/toranj/test-043-meshcop-joiner-router.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5623 [cmake] avoid recompiling common test sources multiple times
  tests/unit/CMakeLists.txt
Labels: P4, cla: yes, comp: build, continuous-integration, enhancement

#5626 [tests] init joiner with different masterkey before start
  tests/scripts/thread-cert/Cert_8_2_01_JoinerRouter.py
  tests/scripts/thread-cert/Cert_8_2_02_JoinerRouter.py
  tests/scripts/thread-cert/Cert_9_2_11_MasterKey.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5448 [thread-cert] refactor case 5.5.3 using pktverify
  tests/scripts/thread-cert/Cert_5_5_03_SplitMergeChildren.py
  tests/scripts/thread-cert/pktverify/consts.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5459 [thread-cert] refactor case 9.2.7 using pktverify
  tests/scripts/thread-cert/Cert_9_2_07_DelayTimer.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5601 [thread-cert] set node addr64 to EXTENDED_ADDRESS_BASE + nodeid
  tests/scripts/thread-cert/node.py
Labels: P4, cla: yes, enhancement

#5633 [bootstrap] fix link to clang-format-10
  script/bootstrap
Labels: P4, cla: yes

#5634 [expect] refactor common functions
  tests/scripts/expect/_common.exp
  tests/scripts/expect/_multinode.exp
  tests/scripts/expect/cli-big-table.exp
  tests/scripts/expect/cli-channel.exp
  tests/scripts/expect/cli-child-supervision.exp
  tests/scripts/expect/cli-child.exp
  tests/scripts/expect/cli-childip.exp
  tests/scripts/expect/cli-coap.exp
  tests/scripts/expect/cli-coaps.exp
  tests/scripts/expect/cli-coex.exp
  tests/scripts/expect/cli-commissioner.exp
  tests/scripts/expect/cli-counters.exp
  tests/scripts/expect/cli-dataset.exp
  tests/scripts/expect/cli-discerner.exp
  tests/scripts/expect/cli-extaddr.exp
  tests/scripts/expect/cli-ipmaddr.exp
  tests/scripts/expect/cli-log-level.exp
  tests/scripts/expect/cli-mac.exp
  tests/scripts/expect/cli-macfilter.exp
  tests/scripts/expect/cli-misc.exp
  tests/scripts/expect/cli-neighbor.exp
  tests/scripts/expect/cli-netdata.exp
  tests/scripts/expect/cli-ping.exp
  tests/scripts/expect/cli-promiscuous.exp
  tests/scripts/expect/cli-pskc.exp
  tests/scripts/expect/cli-reset.exp
  tests/scripts/expect/cli-router.exp
  tests/scripts/expect/cli-routereligible.exp
  tests/scripts/expect/cli-scan-discover.exp
  tests/scripts/expect/cli-udp.exp
  tests/scripts/expect/cli-unsecure-port.exp
  tests/scripts/expect/posix-diag-rcp.exp
  tests/scripts/expect/posix-rcp.exp
  tests/scripts/expect/posix-scan-tx-to-sleep.exp
  tests/scripts/expect/simulation-networktime.exp
  tests/scripts/expect/tun-dns-client.exp
  tests/scripts/expect/tun-netif.exp
  tests/scripts/expect/tun-netstat.exp
  tests/scripts/expect/tun-sntp.exp
  tests/scripts/expect/tun-udp.exp
  tests/scripts/expect/v1_2-rcp.exp
  tests/scripts/expect/v1_2-sed_mac_send.exp
Labels: P4, cla: yes, continuous-integration, enhancement

#5629 [posix] map address with rtnetlink API on Linux
  include/openthread/instance.h
  include/openthread/ip6.h
  src/core/net/netif.cpp
  src/core/net/netif.hpp
  src/posix/platform/netif.cpp
Labels: P4, cla: yes, enhancement, platform: posix

#5637 [docs] update BBB guide formatting
  doc/site/en/guides/border-router/beaglebone-black.md
Labels: cla: yes, comp: docs

#5636 [cmd-parser] remove dependency of <limits>
  src/core/BUILD.gn
  src/core/Makefile.am
  src/core/common/numeric_limits.hpp
  src/core/utils/parse_cmdline.cpp
Labels: P4, cla: yes, comp: cli

#5638 [indirect-sender] remove existing supervision msg on new msg add
  src/core/thread/indirect_sender.cpp
  src/core/thread/indirect_sender.hpp
Labels: P2, bug, cla: yes

#5624 [debug] prefer user provided assert to system assert
  src/core/common/debug.hpp
  src/posix/platform/misc.cpp
Labels: P4, cla: yes, enhancement

#5640 [cc1352,cc2652] add check before claiming transmit done
  examples/platforms/cc1352/radio.c
  examples/platforms/cc2652/radio.c
Labels: P3, bug, cla: yes, platform: cc1352, platform: cc2652

#5643 [thread-cert] enhance case 5.6.7 for data version increment
  tests/scripts/thread-cert/Cert_5_6_07_NetworkDataRequestREED.py
Labels: P4, bug, cla: yes, continuous-integration

#5641 [docs] update Doxygen menu
  doc/ot_api_doc.h
  include/openthread/instance.h
  include/openthread/link_metrics.h
Labels: cla: yes, comp: docs

#5639 [common] use non-copyable for more instance-unique classes
  src/core/backbone_router/bbr_leader.hpp
  src/core/backbone_router/bbr_local.hpp
  src/core/backbone_router/bbr_manager.hpp
  src/core/backbone_router/multicast_listeners_table.hpp
  src/core/mac/data_poll_handler.hpp
  src/core/mac/data_poll_sender.hpp
  src/core/mac/mac.hpp
  src/core/mac/mac_filter.hpp
  src/core/mac/sub_mac.hpp
  src/core/meshcop/border_agent.hpp
  src/core/meshcop/commissioner.hpp
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/joiner.hpp
  src/core/meshcop/joiner_router.hpp
  src/core/meshcop/meshcop_leader.hpp
  src/core/net/dhcp6_client.hpp
  src/core/net/dhcp6_server.hpp
  src/core/net/dns_client.hpp
  src/core/net/icmp6.hpp
  src/core/net/ip6_filter.hpp
  src/core/net/ip6_mpl.hpp
  src/core/net/sntp_client.hpp
  src/core/net/udp6.hpp
  src/core/thread/address_resolver.hpp
  src/core/thread/child_table.hpp
  src/core/thread/csl_tx_scheduler.hpp
  src/core/thread/discover_scanner.hpp
  src/core/thread/dua_manager.hpp
  src/core/thread/energy_scan_server.hpp
  src/core/thread/indirect_sender.hpp
  src/core/thread/key_manager.hpp
  src/core/thread/link_metrics.hpp
  src/core/thread/lowpan.hpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mle.hpp
  src/core/thread/mlr_manager.hpp
  src/core/thread/neighbor_table.hpp
  src/core/thread/network_data_leader_ftd.hpp
  src/core/thread/network_data_local.hpp
  src/core/thread/network_data_notifier.hpp
  src/core/thread/network_diagnostic.hpp
  src/core/thread/panid_query_server.hpp
  src/core/thread/router_table.hpp
  src/core/thread/src_match_controller.hpp
  src/core/thread/time_sync_service.hpp
  src/core/utils/child_supervision.hpp
  src/core/utils/jam_detector.hpp
  src/core/utils/slaac_address.hpp
Labels: P4, cla: yes, enhancement

#5646 [harness-automation] update readme
  tools/harness-automation/README.rst
Labels: cla: yes, comp: docs

#5645 [coap] allow max URI path length
  src/core/coap/coap.cpp
Labels: P4, cla: yes, enhancement

#5442 [thread-cert] refactor case 9.2.12 and 9.2.13 using pktverify
  tests/scripts/thread-cert/Cert_9_2_12_Announce.py
  tests/scripts/thread-cert/Cert_9_2_13_EnergyScan.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5583 [low-power] add an Enh-ACK frame link layer counter
  src/core/mac/mac.cpp
  src/core/thread/key_manager.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/topology.hpp
Labels: Thread 1.2, cla: yes, enhancement, security

#5652 [thread-cert] turn off OTBR NAT64 in 1.2 Backbone tests
  .github/workflows/simulation-1.2.yml
  script/test
Labels: Thread 1.2, cla: yes, continuous-integration

#5587 [cli] add context for the user commands
  include/openthread/cli.h
  include/openthread/instance.h
  script/check-posix-pty
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/posix/main.c
Labels: P4, cla: yes, comp: cli, enhancement

#5654 [continuous-integration] kill ot-rcp and ot-cli in pty check
  script/check-posix-pty
Labels: P3, bug, cla: yes, continuous-integration

#5656 [otns] emit COAP send/receive events to OTNS
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
  src/core/utils/otns.cpp
  src/core/utils/otns.hpp
Labels: P4, cla: yes, platform: simulation

#5658 [autoconf] remove bashisms from configure.ac
  configure.ac
Labels: bug, cla: yes, comp: build

#5565 [simulation] add configuration MAX_NETWORK_SIZE
  .github/workflows/simulation.yml
  examples/Makefile-simulation
  examples/platforms/simulation/CMakeLists.txt
  examples/platforms/simulation/platform-config.h
  examples/platforms/simulation/platform-simulation.h
  examples/platforms/simulation/radio.c
  examples/platforms/simulation/system.c
  examples/platforms/simulation/virtual_time/platform-sim.c
  src/posix/platform/virtual_time.cpp
  tests/scripts/thread-cert/simulator.py
  tests/scripts/thread-cert/sniffer_transport.py
Labels: P4, cla: yes, platform: posix, platform: simulation

#5655 [dataset-manager] misc enhancements
  src/core/meshcop/dataset_local.hpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/dataset_manager_ftd.cpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5661 [coap] add helper method 'Message::SetTokenFromMessage()'
  src/core/api/coap_api.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
  src/core/meshcop/border_agent.cpp
  src/core/thread/mlr_manager.cpp
Labels: P4, cla: yes, comp: coap, enhancement

#5668 [bootstrap] use sudo when creating arm symlinks
  script/bootstrap
Labels: P4, cla: yes, enhancement

#5669 [cmake-build] ensure cc2538 uses 'CMAKE_BUILD_TYPE=Release'
  script/cmake-build
Labels: P4, cla: yes, comp: build, enhancement

#5663 [border-agent] misc enhancements
  src/core/api/border_agent_api.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/border_agent.hpp
  tests/toranj/openthread-core-toranj-config.h
Labels: P4, cla: yes, comp: meshcop, enhancement

#5673 [notifier] define 'kEventStrings[]' as const pointer
  src/core/common/notifier.cpp
Labels: P4, cla: yes, enhancement

#5674 [logging] update OT logging (use functions)
  script/check-simulation-build-autotools
  src/core/common/logging.cpp
  src/core/common/logging.hpp
  src/core/common/string.hpp
  src/core/config/logging.h
  src/core/config/openthread-core-config-check.h
Labels: P4, cla: yes, enhancement

#5677 [cli] add energy scan channel
  src/cli/README.md
  src/cli/cli.cpp
  tests/scripts/expect/cli-scan-discover.exp
Labels: P4, cla: yes, comp: cli, enhancement

#5682 [nrf528xx] fix typo of return value in otPlatSpiSlavePrepareTransaction
  examples/platforms/nrf528xx/src/transport/spi-slave.c
Labels: P4, bug, cla: yes, platform: nrf52811, platform: nrf52833, platform: nrf52840

#5681 [cc2538] add energy scan
  examples/platforms/cc2538/alarm.c
  examples/platforms/cc2538/cc2538-reg.h
  examples/platforms/cc2538/platform-cc2538.h
  examples/platforms/cc2538/radio.c
Labels: P4, cla: yes, enhancement, platform: cc2538

#5687 [spinel-interface] add config option to change the rx frame buffer size
  src/core/config/platform.h
  src/lib/spinel/spinel_interface.hpp
Labels: P4, cla: yes, enhancement

#5683 [spinel] use OT version rather than MAC config in radio spinel
  src/lib/spinel/radio_spinel_impl.hpp
Labels: Thread 1.2, cla: yes, comp: rcp

#5693 [cmake] add support for external platforms
  CMakeLists.txt
  etc/cmake/functions.cmake
Labels: P3, cla: yes, comp: build, enhancement

#5660 [backbone-router] backbone TMF enhancements
  include/openthread/instance.h
  include/openthread/platform/udp.h
  src/core/backbone_router/backbone_tmf.cpp
  src/core/backbone_router/backbone_tmf.hpp
  src/core/backbone_router/bbr_local.cpp
  src/core/backbone_router/bbr_local.hpp
  src/core/backbone_router/bbr_manager.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
  src/posix/platform/udp.cpp
  tests/scripts/thread-cert/backbone/test_bmlr.py
  tests/scripts/thread-cert/v1_2_test_backbone_router_service.py
  tests/scripts/thread-cert/v1_2_test_domain_unicast_address.py
  tests/scripts/thread-cert/v1_2_test_domain_unicast_address_registration.py
  tests/scripts/thread-cert/v1_2_test_dua_handle_address_error.py
Labels: P2, Thread 1.2, cla: yes, enhancement

#5695 [style] clang-tidy misc enhancements
  .github/workflows/build.yml
  script/bootstrap
  script/clang-tidy
  script/make-pretty
Labels: P4, cla: yes, enhancement

#5691 [posix] ignore unexpected host netif state notification
  src/posix/platform/netif.cpp
Labels: P2, bug, cla: yes

#5697 [efr32] avoid asserts during data requests
  examples/platforms/efr32/src/radio.c
Labels: bug, cla: yes, platform: efr32

#5530 [api] check on prefix length when slaac is enabled
  src/core/api/border_router_api.cpp
  tests/toranj/test-010-on-mesh-prefix-config-gateway.py
Labels: P4, cla: yes, enhancement

#5585 [posix] fix MLE sends ICMPv6 destination unreachable
  src/core/net/ip6.cpp
  src/posix/platform/netif.cpp
  tests/scripts/thread-cert/backbone/test_mle_must_not_send_icmpv6_destination_unreachable.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
Labels: P4, bug, cla: yes, platform: posix

#5700 [efr32] disable OT software CSMA backoff and energy scan
  examples/platforms/efr32/src/openthread-core-efr32-config.h
Labels: bug, cla: yes, platform: efr32

#5699 [efr32] use OT_PLAT_RESET_REASON_OTHER for brown-out/EM4 reset
  examples/platforms/efr32/src/misc.c
Labels: bug, cla: yes, platform: efr32

#5702 [cmdline-parser] avoid casting -INT32_MIN directly to int32_t
  src/core/utils/parse_cmdline.cpp
Labels: P4, bug, cla: yes, comp: cli

#5701 [efr32] remove sTxPowerDbm and use RAIL_GetTxPowerDbm()
  examples/platforms/efr32/src/radio.c
Labels: cla: yes, enhancement, platform: efr32

#5690 [posix] fix udp close
  src/posix/platform/udp.cpp
Labels: bug, cla: yes, platform: posix

#5680 [thread-cert] refactor case 5.1.1 using pktverify
  tests/scripts/thread-cert/Cert_5_1_01_RouterAttach.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5709 [cmake] set default build type to Debug
  CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#5705 [cmake] use init flags in toolchain files
  examples/platforms/cc1352/arm-none-eabi.cmake
  examples/platforms/cc2538/arm-none-eabi.cmake
  examples/platforms/cc2650/arm-none-eabi.cmake
  examples/platforms/cc2652/arm-none-eabi.cmake
  examples/platforms/kw41z/arm-none-eabi.cmake
  examples/platforms/qpg6095/arm-none-eabi.cmake
  examples/platforms/samr21/arm-none-eabi.cmake
  script/cmake-build
Labels: P4, cla: yes, comp: build, enhancement

#5711 [mlr] fix build when OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE is disabled
  src/cli/cli.hpp
  src/core/api/ip6_api.cpp
Labels: cla: yes, comp: cli

#5578 [scripts] add MLR Backbone multicast routing test
  .github/workflows/simulation-1.2.yml
  script/test
  tests/scripts/thread-cert/backbone/test_mlr_multicast_routing.py
  tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_commissioner_timeout.py
  tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_timeout.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/packet.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
  tests/scripts/thread-cert/run_bbr_tests.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P2, Thread 1.2, cla: yes, continuous-integration

#5710 [build] fix warning of clearing non-trivial type
  .github/workflows/build.yml
  script/cmake-build
  src/core/meshcop/commissioner.cpp
  src/core/thread/network_data_leader_ftd.cpp
Labels: P4, cla: yes, comp: build, enhancement

#5545 [low-power] enhance CSL transmission on NRF52840 using `transmit_at`
  examples/platforms/nrf528xx/nrf52840/openthread-core-nrf52840-config.h
  examples/platforms/nrf528xx/src/radio.c
  include/openthread/instance.h
  include/openthread/platform/radio.h
  script/check-size
  src/core/config/mac.h
  src/core/mac/mac.cpp
  src/core/mac/mac_frame.hpp
  src/core/mac/sub_mac.cpp
  src/core/mac/sub_mac.hpp
  src/core/thread/csl_tx_scheduler.cpp
  src/core/thread/csl_tx_scheduler.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  src/ncp/ncp_base_radio.cpp
Labels: P4, Thread 1.2, cla: yes, enhancement, platform: nrf52840

#5706 [cmake] no target_link_options in cmake 3.10
  examples/platforms/cc1352/CMakeLists.txt
  examples/platforms/cc2538/CMakeLists.txt
  examples/platforms/cc2650/CMakeLists.txt
  examples/platforms/cc2652/CMakeLists.txt
  examples/platforms/kw41z/CMakeLists.txt
  examples/platforms/qpg6095/CMakeLists.txt
  examples/platforms/samr21/CMakeLists.txt
  script/check-arm-build-cmake
  script/cmake-build
  third_party/microchip/CMakeLists.txt
  third_party/ti/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#5714 [clang-tidy] modernize-use-bool-literals
  script/make-pretty
  src/cli/cli.cpp
  src/core/thread/mesh_forwarder.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5703 [nrf528xx] fix SPI issue
  examples/platforms/nrf528xx/src/transport/spi-slave.c
  third_party/NordicSemiconductor/nrfx/drivers/include/nrfx_spis.h
  third_party/NordicSemiconductor/nrfx/drivers/src/nrfx_spis.c
  third_party/NordicSemiconductor/nrfx/hal/nrf_spis.h
Labels: P2, bug, cla: yes, platform: nrf52811, platform: nrf52833, platform: nrf52840

#5721 [dataset-manager] simplify 'SendSetRequest()'
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5722 [dataset] add new helper 'SetTlv()' with a template 'ValueType'
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dataset_manager_ftd.cpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5715 [clang-tidy] modernize-use-nullptr
  include/openthread/coap.h
  include/openthread/instance.h
  script/make-pretty
  src/cli/cli.cpp
  src/lib/spinel/spinel_buffer.hpp
  tests/unit/test_platform.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5716 [clang-tidy] readability-simplify-boolean-expr
  script/make-pretty
  src/core/mac/mac.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/ncp_base_radio.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5704 [logging] add optional `otPlatLogLine()` & use it in NCP/CLI
  examples/apps/cli/main.c
  include/openthread/cli.h
  include/openthread/instance.h
  include/openthread/platform/logging.h
  src/cli/cli.cpp
  src/core/common/logging.cpp
  src/ncp/ncp_base.cpp
Labels: P4, cla: yes, enhancement

#5672 [posix] fix cast-align build error on ARM
  src/posix/platform/netif.cpp
  src/posix/platform/udp.cpp
Labels: P4, bug, cla: yes, platform: posix

#5725 [efr32] add MG21/BRD4180B support
  examples/Makefile-efr32mg21
  examples/platforms/efr32/efr32mg13/brd4168a/hal-config.h
  examples/platforms/efr32/efr32mg21/brd4180b/board_config.h
  examples/platforms/efr32/efr32mg21/brd4180b/hal-config.h
  third_party/silabs/Makefile.am
Labels: cla: yes, enhancement, platform: efr32

#5718 [clang-tidy] modernize-use-equals-delete
  script/make-pretty
  src/core/common/non_copyable.hpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5717 [clang-tidy] readability-avoid-const-params-in-decls
  include/openthread/coap.h
  include/openthread/instance.h
  script/make-pretty
  src/core/api/coap_api.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5719 [clang-tidy] modernize-use-equals-default
  script/make-pretty
  src/core/common/locator.hpp
  src/core/common/non_copyable.hpp
  src/core/common/time.hpp
  src/core/thread/link_metrics_tlvs.hpp
  src/core/thread/mle_types.hpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5720 [clang-tidy] google-readability-casting
  script/make-pretty
  src/cli/cli_coap_secure.cpp
  src/core/common/random_manager.cpp
  tests/unit/test_link_quality.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5727 [test] arm build with cmake 3.10
  .github/workflows/build.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#5686 [thread-cert] refactor case 5.1.2 using pktverify
  tests/scripts/thread-cert/Cert_5_1_02_ChildAddressTimeout.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5729 [cli] update cli doc
  src/cli/README.md
Labels: P4, cla: yes, comp: docs

#5731 [site] fix border router guide typo in network
  doc/site/en/guides/border-router/beaglebone-black.md
Labels: cla: yes, comp: docs

#5653 [net-diag] invoke the callback when failed to get the response
  .github/workflows/simulation-1.2.yml
  include/openthread/instance.h
  include/openthread/netdiag.h
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/thread/network_diagnostic.cpp
Labels: bug, cla: yes

#5736 [posix] default hop limit to OPENTHREAD_CONFIG_IP6_HOP_LIMIT_DEFAULT
  src/posix/platform/udp.cpp
Labels: P1, bug, cla: yes, platform: posix

#5735 [type-traits] add 'IsPointer<Type>' and use it in message/dataset
  src/core/BUILD.gn
  src/core/Makefile.am
  src/core/common/message.hpp
  src/core/common/type_traits.hpp
  src/core/meshcop/dataset.hpp
Labels: P4, cla: yes, enhancement

#5635 [continuous-integration] use lcov to generate coverage data
  .codecov.yml
  .github/workflows/posix.yml
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  .github/workflows/toranj.yml
  script/test
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/run_bbr_tests.py
Labels: P4, cla: yes, continuous-integration

#5732 [clang-tidy] misc-unused-using-decls
  script/make-pretty
  src/cli/cli_dataset.cpp
  src/cli/cli_udp.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mle_router.cpp
  tests/unit/test_cmd_line_parser.cpp
  tests/unit/test_lowpan.cpp
Labels: P4, cla: yes, enhancement

#5734 [clang-tidy] google-explicit-constructor
  script/make-pretty
  src/core/backbone_router/multicast_listeners_table.hpp
  src/core/common/message.hpp
  src/core/common/pool.hpp
  src/core/common/settings.hpp
  src/core/common/time_ticker.hpp
  src/core/common/timer.hpp
  src/core/net/netif.cpp
  src/core/net/netif.hpp
  src/core/radio/radio.hpp
  src/core/thread/child_table.hpp
  src/core/thread/link_metrics.cpp
  src/core/thread/link_metrics_tlvs.hpp
  src/core/thread/network_data_notifier.hpp
  src/core/thread/router_table.hpp
  src/core/thread/topology.hpp
  src/core/utils/flash.hpp
  src/core/utils/lookup_table.hpp
  tests/unit/test_lookup_table.cpp
  tests/unit/test_lowpan.hpp
  tests/unit/test_netif.cpp
  tests/unit/test_timer.cpp
Labels: P4, cla: yes, enhancement

#5742 [efr32] radio: increase FIFO size to allow handling of heavy traffic
  examples/platforms/efr32/src/radio.c
Labels: bug, cla: yes, platform: efr32

#5608 [low-power] implement forward tracking series
  include/openthread/instance.h
  include/openthread/link_metrics.h
  script/check-size
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/link_metrics_api.cpp
  src/core/config/mle.h
  src/core/mac/mac.cpp
  src/core/thread/link_metrics.cpp
  src/core/thread/link_metrics.hpp
  src/core/thread/link_metrics_tlvs.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/topology.cpp
  src/core/thread/topology.hpp
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/mle.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/v1_2_LowPower_7_2_01_ForwardTrackingSeries.py
  tests/scripts/thread-cert/v1_2_LowPower_test_forward_tracking_series.py
Labels: P3, Thread 1.2, cla: yes

#5733 [dataset] add 'Info' and 'Components' types
  src/core/api/dataset_api.cpp
  src/core/api/dataset_ftd_api.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dataset_local.cpp
  src/core/meshcop/dataset_local.hpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/joiner.cpp
  src/core/utils/channel_manager.cpp
  src/lib/spinel/radio_spinel_impl.hpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5664 [dua] implement Backbone query and answer
  .github/workflows/simulation-1.2.yml
  include/openthread/instance.h
  include/openthread/thread.h
  src/cli/cli.cpp
  src/core/api/thread_ftd_api.cpp
  src/core/backbone_router/bbr_manager.cpp
  src/core/backbone_router/bbr_manager.hpp
  src/core/backbone_router/ndproxy_table.cpp
  src/core/backbone_router/ndproxy_table.hpp
  src/core/thread/address_resolver.cpp
  src/core/thread/address_resolver.hpp
  src/core/thread/mle_types.hpp
  src/core/thread/thread_tlvs.hpp
  src/core/thread/uri_paths.hpp
  tests/scripts/thread-cert/backbone/bbr_5_11_01.py
  tests/scripts/thread-cert/backbone/test_dua_dad.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
  tests/scripts/thread-cert/pktverify/packet_verifier.py
  tests/scripts/thread-cert/pktverify/utils.py
  tests/scripts/thread-cert/run_bbr_tests.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P2, Thread 1.2, cla: yes, comp: backbone-router, enhancement

#5750 [dua] convert to matching time unit when computation
  src/core/thread/dua_manager.cpp
Labels: P4, Thread 1.2, bug, cla: yes

#5744 [efr32] call mbedtls_hardware_poll directly in otPlatEntropyGet()
  examples/platforms/efr32/src/entropy.c
Labels: cla: yes, enhancement, platform: efr32

#5559 [virtual-time-simulator] optimize ACK radio events
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/simulator.py
  tests/scripts/thread-cert/wpan.py
Labels: P4, cla: yes, enhancement, platform: simulation

#5747 [ip6] allow anycast source
  src/core/net/ip6.cpp
Labels: P4, bug, cla: yes
