Repository openthread/openthread, pull requests merged in 2020-11, with the labels that each got.

#5749 [logging] correct the log level and region settings
  src/core/common/logging.cpp
Labels: P3, bug, cla: yes

#5728 [thread-cert] refactor case 5.1.5 using pktverify
  tests/scripts/thread-cert/Cert_5_1_05_RouterAddressTimeout.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5758 [thci] add ssh connection support on OpenThread_BR.py
  tools/harness-thci/OpenThread.py
  tools/harness-thci/OpenThread_BR.py
Labels: P4, certification, cla: yes

#5595 [dua] implement ND Proxy callbacks
  .github/workflows/simulation-1.2.yml
  include/openthread/backbone_router_ftd.h
  include/openthread/instance.h
  script/test
  src/core/api/backbone_router_ftd_api.cpp
  src/core/backbone_router/bbr_leader.cpp
  src/core/backbone_router/bbr_local.cpp
  src/core/backbone_router/bbr_local.hpp
  src/core/backbone_router/ndproxy_table.cpp
  src/core/backbone_router/ndproxy_table.hpp
  tests/scripts/thread-cert/backbone/bbr_5_11_01.py
  tests/scripts/thread-cert/backbone/test_ndproxy.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/addrs.py
  tests/scripts/thread-cert/run_bbr_tests.py
Labels: Thread 1.2, api: user, cla: yes, enhancement

#5760 [efr32] Use -mfpu=fpv4-sp-d16 for efr32mg1x chips
  examples/Makefile-efr32mg1
  examples/Makefile-efr32mg12
  examples/Makefile-efr32mg13
Labels: P3, bug, cla: yes, platform: efr32

#5754 [script] update 'make-pretty clang-tidy' to output warning/error only
  script/make-pretty
Labels: P4, cla: yes, enhancement

#5764 [low-power] use correct CslFrameRequestAhead for scheduling CSL trasmission
  src/core/thread/csl_tx_scheduler.cpp
  src/core/thread/csl_tx_scheduler.hpp
Labels: P2, Thread 1.2, bug, cla: yes

#5756 [thread-cert] refactor case 5.1.11 using pktverify
  tests/scripts/thread-cert/Cert_5_1_11_REEDAttachLinkQuality.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5765 [thread-cert] refactor case 5.1.12 using pktverify
  tests/scripts/thread-cert/Cert_5_1_12_NewRouterNeighborSync.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5757 [thread-cert] refactor case 5.1.10 using pktverify
  tests/scripts/thread-cert/Cert_5_1_10_RouterAttachLinkQuality.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5730 [thread-cert] refactor case 5.1.6 using pktverify
  tests/scripts/thread-cert/Cert_5_1_06_RemoveRouterId.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5755 [tlvs] new simplified model to process/append TLVs
  src/core/backbone_router/bbr_manager.cpp
  src/core/common/encoding.hpp
  src/core/common/tlvs.cpp
  src/core/common/tlvs.hpp
  src/core/common/type_traits.hpp
  src/core/meshcop/announce_begin_client.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/energy_scan_client.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/meshcop_leader.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/meshcop/panid_query_client.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/announce_begin_server.cpp
  src/core/thread/discover_scanner.cpp
  src/core/thread/dua_manager.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/link_metrics.cpp
  src/core/thread/link_metrics_tlvs.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/mlr_manager.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/network_diagnostic_tlvs.hpp
  src/core/thread/panid_query_server.cpp
  src/core/thread/thread_tlvs.hpp
Labels: P4, cla: yes, enhancement

#5768 [clearable] reuse clearable for some classes
  src/core/mac/mac.cpp
  src/core/thread/link_metrics.cpp
  src/core/thread/link_quality.cpp
  src/core/thread/link_quality.hpp
  tests/unit/test_link_quality.cpp
Labels: P4, cla: yes, enhancement

#5762 [mle] add helper 'ReadFrameCounters()' to read Link/MLE Frame Counters
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, comp: mle, enhancement

#5740 [thread-cert] add more info and tlv checks in case 5.1.7
  tests/scripts/thread-cert/Cert_5_1_07_MaxChildCount.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5766 [thread-cert] refactor case 5.1.13 using pktverify
  tests/scripts/thread-cert/Cert_5_1_13_RouterReset.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5770 [thread-cert] refactor case 5.2.1 using pktverify
  tests/scripts/thread-cert/Cert_5_2_01_REEDAttach.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5769 [linked-list] add an overload for LinkedList::FindMatching for convenience
  src/core/common/linked_list.hpp
  src/core/net/netif.cpp
  src/core/thread/topology.cpp
Labels: P4, cla: yes, enhancement

#5743 [thread-cert] refactor case 5.1.9 using pktverify
  tests/scripts/thread-cert/Cert_5_1_09_REEDAttachConnectivity.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5751 [bootstrap] show warning but not fail when install llvm@9 failed
  script/bootstrap
Labels: cla: yes

#5739 [thread-cert] refactor case 5.1.8 using pktverify
  tests/scripts/thread-cert/Cert_5_1_08_RouterAttachConnectivity.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5723 [thread-cert] refactor case 5.1.4 using pktverify
  tests/scripts/thread-cert/Cert_5_1_04_RouterAddressReallocation.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5586 [scripts] enhance cert_suite to run multiple tests concurrently
  .github/workflows/simulation-1.2.yml
  script/test
  tests/scripts/thread-cert/run_cert_suite.py
Labels: P4, cla: yes, enhancement, platform: simulation

#5771 [clang-tidy] readability-static-accessed-through-instance
  script/make-pretty
  src/core/mac/mac.cpp
  src/core/mac/sub_mac.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5775 [thread-cert] refactor case 5.2.3 using pktverify
  tests/scripts/thread-cert/Cert_5_2_03_LeaderReject2Hops.py
  tests/scripts/thread-cert/pktverify/consts.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5763 [style] fix build with NDEBUG
  examples/platforms/nrf528xx/src/flash.c
  examples/platforms/nrf528xx/src/transport/spi-slave.c
  examples/platforms/nrf528xx/src/transport/usb-cdc-uart.c
  script/check-arm-build-autotools
  script/check-arm-build-cmake
  third_party/NordicSemiconductor/Makefile.am
  third_party/NordicSemiconductor/drivers/radio/mac_features/ack_generator/nrf_802154_ack_data.c
Labels: cla: yes, comp: build, platform: nrf52840

#5782 [dhcp6-client] return error if Identity Association is not found
  src/core/net/dhcp6_client.cpp
Labels: P4, bug, cla: yes

#5781 [clang-tidy] readability-redundant-member-init
  script/make-pretty
  src/core/coap/coap.cpp
  src/core/coap/coap_message.hpp
  src/core/coap/coap_secure.cpp
  src/core/common/instance.cpp
  src/core/common/message.cpp
  src/core/common/notifier.cpp
  src/core/common/timer.hpp
  src/core/mac/mac.cpp
  src/core/net/icmp6.cpp
  src/core/net/ip6.cpp
  src/core/net/netif.cpp
  src/core/net/udp6.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/announce_sender.cpp
  src/core/thread/discover_scanner.cpp
  src/core/thread/link_metrics.cpp
  src/lib/spinel/spinel_encoder.hpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_uart.cpp
Labels: P4, cla: yes, enhancement

#5776 [tests] fix tun-realm-local-multicast.exp
  tests/scripts/expect/tun-realm-local-multicast.exp
Labels: P3, cla: yes, continuous-integration

#5772 [posix] forkpty-arg value as a single argument
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/hdlc_interface.hpp
  src/posix/platform/system.cpp
  tests/scripts/expect/posix-scan-tx-to-sleep.exp
Labels: P4, cla: yes, enhancement, platform: posix

#5788 [posix] add radio URL parameter fem-lnagain
  src/posix/platform/radio.cpp
  src/posix/platform/radio_url.cpp
  tests/scripts/expect/posix-fem-lnagain.exp
Labels: cla: yes, enhancement, platform: posix

#5789 [mle] fix mle log MessageTypeToString
  src/core/thread/mle.cpp
Labels: P4, cla: yes, comp: mle

#5784 [spinel] print error on RCP reset before dying
  src/lib/spinel/radio_spinel_impl.hpp
Labels: P4, cla: yes, comp: rcp, enhancement

#5794 [posix] increase max log size
  src/posix/platform/openthread-core-posix-config.h
Labels: P4, cla: yes, enhancement, platform: posix

#5791 [posix] reduce RCP time sync log
  src/lib/spinel/radio_spinel_impl.hpp
Labels: cla: yes, platform: posix

#5745 [nrf528xx] allow users to implement power setting functions
  examples/platforms/nrf528xx/src/fem.c
  examples/platforms/nrf528xx/src/platform-fem.h
  examples/platforms/nrf528xx/src/radio.c
  examples/platforms/nrf528xx/src/system.c
  third_party/NordicSemiconductor/drivers/radio/fal/nrf_802154_fal.c
Labels: P2, cla: yes, enhancement, platform: nrf52811, platform: nrf52833, platform: nrf52840

#5796 [clang-tidy] readability-inconsistent-declaration-parameter-name
  examples/platforms/simulation/platform-simulation.h
  examples/platforms/simulation/radio.c
  include/openthread/instance.h
  include/openthread/thread.h
  script/make-pretty
  src/cli/cli.hpp
  src/cli/cli_commissioner.hpp
  src/cli/cli_udp.hpp
  src/core/api/thread_ftd_api.cpp
  src/core/coap/coap_message.hpp
  src/core/common/notifier.hpp
  src/core/common/timer.hpp
  src/core/common/tlvs.cpp
  src/core/common/tlvs.hpp
  src/core/mac/sub_mac.hpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
  src/core/meshcop/meshcop.cpp
  src/core/net/dhcp6_client.hpp
  src/core/thread/child_table.hpp
  src/core/thread/discover_scanner.hpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/network_data.hpp
  src/core/thread/network_data_leader_ftd.hpp
  src/core/utils/parse_cmdline.cpp
  tests/fuzz/fuzzer_platform.cpp
  tests/unit/test_platform.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5797 [codecov] enable project coverage threshold
  .codecov.yml
Labels: cla: yes, continuous-integration

#5799 [github-actions] retry coverage uploading on failures
  script/test
Labels: cla: yes, continuous-integration

#5785 [low-power] fix csl simulation
  src/core/mac/sub_mac.cpp
Labels: P3, Thread 1.2, bug, cla: yes, platform: simulation

#5792 [memory] use heap for messages
  .github/workflows/simulation.yml
  etc/cmake/options.cmake
  etc/gn/openthread.gni
  examples/common-switches.mk
  script/check-size
  script/test
  src/core/BUILD.gn
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/config/openthread-core-config-check.h
  src/core/config/openthread-core-default-config.h
  tests/toranj/openthread-core-toranj-config.h
Labels: P4, cla: yes, enhancement

#5804 [build] include project Android.mk in OpenThread Android.mk
  Android.mk
Labels: P2, cla: yes, comp: build, enhancement

#5808 [clang-tidy] readability-else-after-return
  script/make-pretty
  src/core/thread/mle_router.cpp
  tests/unit/test_platform.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5800 [thread-cert] refactor case 5.3.1 using pktverify
  tests/scripts/thread-cert/Cert_5_3_01_LinkLocal.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5814 [thread-cert] refactor case 5.3.5 using pktverify
  tests/scripts/thread-cert/Cert_5_3_05_RoutingLinkQuality.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5811 [thread-cert] refactor case 5.3.4 using pktverify
  tests/scripts/thread-cert/Cert_5_3_04_AddressMapCache.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5809 [thread-cert] refactor case 5.3.3 using pktverify
  tests/scripts/thread-cert/Cert_5_3_03_AddressQuery.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5820 [toranj] use msg pool (do not use heap) in toranj config
  tests/toranj/openthread-core-toranj-config.h
Labels: P4, cla: yes, continuous-integration, enhancement

#5798 [thread-cert] refactor case 5.2.5 using pktverify
  tests/scripts/thread-cert/Cert_5_2_05_AddressQuery.py
  tests/scripts/thread-cert/pktverify/packet_verifier.py
  tests/scripts/thread-cert/pktverify/pcap_reader.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5790 [thread-cert] refactor case 5.2.4 using pktverify
  tests/scripts/thread-cert/Cert_5_2_04_REEDUpgrade.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5777 [thread-cert] refactor case 5.2.6 using pktverify
  tests/scripts/thread-cert/Cert_5_2_06_RouterDowngrade.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5821 [tests] fix tun-realm-local-multicast.exp
  tests/scripts/expect/tun-realm-local-multicast.exp
Labels: P4, cla: yes, continuous-integration

#5818 [efr32] radio: fill in rx info for received ACKs
  examples/platforms/efr32/src/radio.c
Labels: cla: yes, platform: efr32

#5786 [thread-cert] refactor case 5.2.7 using pktverify
  tests/scripts/thread-cert/Cert_5_2_07_REEDSynchronization.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5830 [ncp-base] fix missing error checks in some property handlers
  src/ncp/ncp_base_mtd.cpp
Labels: P4, cla: yes, comp: ncp, enhancement

#5822 [radio-spinel] verify host is connected to an RCP
  src/lib/spinel/radio_spinel_impl.hpp
Labels: P4, cla: yes, enhancement, platform: posix

#5832 [posix] add radio URL parameter cca-threshold
  src/posix/platform/radio.cpp
  src/posix/platform/radio_url.cpp
  tests/scripts/expect/posix-ccathreshold.exp
Labels: cla: yes, enhancement, platform: posix

#5831 [cli] enhance buffer info
  src/core/api/message_api.cpp
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/config/openthread-core-config-check.h
Labels: P4, cla: yes, enhancement

#5828 [cmake] add OT_NCP_VENDOR_HOOK_SOURCE support for RCP
  src/ncp/CMakeLists.txt
  src/ncp/ftd.cmake
  src/ncp/mtd.cmake
  src/ncp/radio.cmake
Labels: P4, cla: yes, comp: build, comp: ncp, enhancement

#5840 [cli] small enhancements and style fixes
  src/cli/cli.cpp
  src/cli/cli.hpp
Labels: P4, cla: yes, comp: cli, enhancement

#5793 [mlr] implement native multicast routing for backbone router
  Android.mk
  script/test
  src/core/common/logging.hpp
  src/core/net/ip6_address.hpp
  src/posix/main.c
  src/posix/platform/CMakeLists.txt
  src/posix/platform/Makefile.am
  src/posix/platform/backbone.cpp
  src/posix/platform/multicast_routing.cpp
  src/posix/platform/multicast_routing.hpp
  src/posix/platform/netif.cpp
  src/posix/platform/openthread-posix-config.h
  src/posix/platform/platform-posix.h
  src/posix/platform/system.cpp
Labels: Thread 1.2, cla: yes, comp: backbone-router, enhancement

#5807 [utils] adding 'DatasetUpdater'
  Android.mk
  etc/cmake/options.cmake
  examples/Makefile-simulation
  examples/common-switches.mk
  include/Makefile.am
  include/openthread/BUILD.gn
  include/openthread/dataset_updater.h
  include/openthread/instance.h
  script/check-scan-build
  script/check-simulation-build-autotools
  script/check-size
  script/cmake-build
  script/make-pretty
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/api/dataset_updater_api.cpp
  src/core/common/instance.cpp
  src/core/common/instance.hpp
  src/core/common/notifier.cpp
  src/core/config/dataset_updater.h
  src/core/mac/mac_types.cpp
  src/core/mac/mac_types.hpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/openthread-core-config.h
  src/core/utils/channel_manager.cpp
  src/core/utils/channel_manager.hpp
  src/core/utils/dataset_updater.cpp
  src/core/utils/dataset_updater.hpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5841 [cli] add helper 'Output()' methods which prepend indentation space
  src/cli/cli.cpp
  src/cli/cli.hpp
Labels: P4, cla: yes, comp: cli, enhancement

#5847 [test] add rcp-ncp node type
  script/test
  tests/scripts/expect/_common.exp
Labels: P4, cla: yes, enhancement

#5833 [low-power] fix CSL scheduler issues to avoid packets stuck in queue for a long time
  include/openthread/instance.h
  include/openthread/thread_ftd.h
  src/cli/README.md
  src/cli/cli.cpp
  src/core/mac/data_poll_handler.hpp
  src/core/thread/csl_tx_scheduler.cpp
  src/core/thread/csl_tx_scheduler.hpp
  src/core/thread/indirect_sender.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/topology.cpp
  tests/scripts/expect/cli-child.exp
Labels: P2, Thread 1.2, bug, cla: yes

#5846 [thread-cert] refactor case 6.2.1 using pktverify
  tests/scripts/thread-cert/Cert_6_2_01_NewPartition.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5854 [android] always enable SLAAC
  Android.mk
Labels: cla: yes, comp: build, enhancement

#5849 [mle] simplify parsing and appending of 'TimeRequestTlv'
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_tlvs.hpp
Labels: P4, cla: yes, comp: mle, enhancement

#5853 [low-power] frame pending bit handling for enh-ack in simulation
  examples/platforms/simulation/radio.c
  examples/platforms/utils/mac_frame.cpp
  examples/platforms/utils/mac_frame.h
  src/core/mac/mac_frame.hpp
Labels: P2, Thread 1.2, bug, cla: yes, platform: simulation

#5857 [cmake] avoid unnecessary rebuilds
  third_party/mbedtls/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#5858 [mle] add missing defs when LONG_ROUTES is enabled
  src/core/thread/mle_router.cpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/mle_types.hpp
Labels: P4, cla: yes, comp: mle, enhancement

#5860 [posix] fix macro typo
  src/posix/platform/system.cpp
Labels: P4, bug, cla: yes, platform: posix

#5864 [spinel] misc style fixes in radio spinel
  src/lib/spinel/radio_spinel.hpp
Labels: P4, cla: yes, comp: docs, enhancement

#5835 [thci] add low power thci
  tools/harness-thci/OpenThread.py
Labels: P4, Thread 1.2, certification, cla: yes, enhancement

#5815 [thread-cert] refactor case 5.3.7 using pktverify
  tests/scripts/thread-cert/Cert_5_3_07_DuplicateAddress.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5824 [thread-cert] refactor case 5.3.10 using pktverify
  tests/scripts/thread-cert/Cert_5_3_10_AddressQuery.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5862 [low-power] enable CCA sampling before CSL transmission
  examples/platforms/nrf528xx/src/radio.c
  src/core/config/mac.h
  src/core/mac/sub_mac.cpp
  src/core/mac/sub_mac.hpp
Labels: P2, Thread 1.2, bug, cla: yes, platform: nrf52811, platform: nrf52833, platform: nrf52840

#5842 [thread-cert] refactor case 6.4.2 using pktverify
  tests/scripts/thread-cert/Cert_6_4_02_RealmLocal.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5844 [thread-cert] refactor case 6.1.2 using pktverify
  tests/scripts/thread-cert/Cert_6_1_02_REEDAttach.py
  tests/scripts/thread-cert/Cert_6_1_02_REEDAttach_MED.py
  tests/scripts/thread-cert/Cert_6_1_02_REEDAttach_SED.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5845 [thread-cert] refactor case 6.1.6 using pktverfiy
  tests/scripts/thread-cert/Cert_6_1_06_REEDAttachLinkQuality.py
  tests/scripts/thread-cert/Cert_6_1_06_REEDAttachLinkQuality_ED.py
  tests/scripts/thread-cert/Cert_6_1_06_REEDAttachLinkQuality_SED.py
  tests/scripts/thread-cert/Makefile.am
Labels: P4, cla: yes, continuous-integration, enhancement

#5873 [docs] OT CLI doc minor fixes
  src/cli/README.md
  src/cli/README_NETDATA.md
Labels: P4, cla: yes, comp: docs

#5875 [tmf] allow turning off TMF proxying for DUA and MLR
  src/core/config/tmf.h
Labels: Thread 1.2, cla: yes

#5874 [ip6] tiny enhancement for HandleOptions
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
Labels: P4, cla: yes, enhancement

#5843 [thread-cert] refactor case 6.4.1 using pktverify
  tests/scripts/thread-cert/Cert_6_4_01_LinkLocal.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5879 [test] fix missing attribute _message_factory
  tests/scripts/thread-cert/simulator.py
Labels: P4, cla: yes, continuous-integration

#5877 [dataset] set key rotation time in security policy on random generation
  src/core/meshcop/dataset.cpp
  src/core/thread/key_manager.cpp
  src/core/thread/key_manager.hpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5865 [docs] updates to run CC1352 and CC2652 as rcp with ot-br-posix
  doc/site/en/guides/border-router/beaglebone-black.md
  examples/platforms/cc1352/radio.c
  examples/platforms/cc2652/radio.c
Labels: cla: yes, comp: docs, platform: cc1352, platform: cc2652

#5838 [thread-cert] refactor case 6.1.1 using pktverify
  tests/scripts/thread-cert/Cert_6_1_01_RouterAttach.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5878 [logging] fix typo in documents
  src/core/common/logging.hpp
Labels: cla: yes, comp: docs

#5876 [dns] misc enhancements
  src/core/api/dns_api.cpp
  src/core/net/dns_client.cpp
  src/core/net/dns_client.hpp
  src/core/net/dns_headers.hpp
Labels: P4, cla: yes, enhancement

#5866 [coap] update OPENTHREAD_CONFIG_COAP_ACK_TIMEOUT error message
  src/core/config/openthread-core-config-check.h
Labels: P4, cla: yes, comp: coap, enhancement

#5871 [github-actions] use ubuntu-20.04 for github actions
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/fuzz.yml
  .github/workflows/posix.yml
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  .github/workflows/size.yml
  .github/workflows/toranj.yml
  .github/workflows/version.yml
  tests/unit/test_link_quality.cpp
Labels: P4, cla: yes, continuous-integration

#5810 [string] add UTF-8 validation
  src/cli/cli_dataset.cpp
  src/core/common/string.cpp
  src/core/common/string.hpp
  src/core/mac/mac.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/meshcop.cpp
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/thread/discover_scanner.cpp
  tests/scripts/expect/cli-dataset.exp
  tests/scripts/expect/cli-networkname.exp
  tests/unit/test_string.cpp
Labels: P4, cla: yes, enhancement

#5889 [docs] fix typo in sntp docs
  include/openthread/instance.h
  include/openthread/sntp.h
Labels: P4, cla: yes, comp: docs, enhancement
