Repository openthread/openthread, pull requests merged in 2020-01, with the labels that each got.

#4437 [mle] fix build error caused by GetParent return type change
  examples/platforms/posix/openthread-core-posix-config.h
  src/core/thread/mle.cpp
Labels: P3, bug, cla: yes

#4436 [platform/utils] RTT: remove non-functional config of Up Buffer's size
  examples/platforms/utils/logging_rtt.c
  examples/platforms/utils/logging_rtt.h
Labels: P4, cla: yes, enhancement

#4438 [tlv] add AppendTo to resolve mutual dependency
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/common/tlvs.cpp
  src/core/common/tlvs.hpp
  src/core/meshcop/announce_begin_client.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/energy_scan_client.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/leader.cpp
  src/core/meshcop/panid_query_client.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/panid_query_server.cpp
Labels: P4, cla: yes, enhancement

#4445 [ip6] fix the fragmentation header check
  src/core/net/ip6.cpp
Labels: P4, bug, cla: yes

#4448 [ncp-base] use handler table for insert/remove and simplify using macros
  src/ncp/ncp_base_dispatcher.cpp
Labels: NCP, P4, cla: yes, enhancement

#4451 [nrf528xx] return the TX power which was actually set in the register
  examples/platforms/nrf528xx/src/radio.c
Labels: P4, cla: yes, enhancement, platform: nrf52811, platform: nrf52833, platform: nrf52840

#4450 [mle] allow setting router eligible attr to false for MTD
  src/core/thread/mle_router.cpp
Labels: cla: yes

#4443 [network-data] fix compile error when building service without border router
  src/core/thread/network_data_local.cpp
Labels: P4, bug, cla: yes, comp: build

#4300 [build] detect undefined macros to avoid misconfigurations
  configure.ac
  examples/common-switches.mk
  examples/platforms/cc1352/radio.c
  examples/platforms/cc2650/alarm.c
  examples/platforms/cc2650/diag.c
  examples/platforms/cc2650/radio.c
  examples/platforms/cc2652/radio.c
  examples/platforms/efr32mg12/Makefile.am
  examples/platforms/efr32mg12/openthread-core-efr32-config.h
  examples/platforms/efr32mg21/Makefile.am
  examples/platforms/efr32mg21/openthread-core-efr32-config.h
  examples/platforms/kw41z/Makefile.am
  examples/platforms/nrf528xx/nrf52811/Makefile.am
  examples/platforms/nrf528xx/nrf52833/Makefile.am
  examples/platforms/nrf528xx/nrf52840/Makefile.am
  examples/platforms/qpg6095/logging.c
  examples/platforms/qpg6095/settings.cpp
  examples/platforms/samr21/Makefile.am
  include/openthread/platform/debug_uart.h
  src/cli/Makefile.am
  src/cli/cli.cpp
  src/cli/cli_coap_secure.hpp
  src/cli/cli_config.h
  src/core/Makefile.am
  src/core/common/encoding.hpp
  src/core/common/random_manager.cpp
  src/core/common/random_manager.hpp
  src/core/config/mac.h
  src/core/config/openthread-core-default-config.h
  src/core/mac/mac_frame.hpp
  src/core/openthread-core-config.h
  src/core/thread/mle.cpp
  src/ncp/Makefile.am
  src/ncp/ncp_config.h
  src/ncp/ncp_uart.hpp
  src/ncp/spinel.c
  third_party/NordicSemiconductor/Makefile.am
  third_party/jlink/Makefile.am
  third_party/silabs/.gitignore
  third_party/silabs/Makefile.am
Labels: P4, bug, cla: yes, comp: build, enhancement

#4427 [mle] link sync enhancement
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, enhancement

#4456 [mesh-forwarder] fix incorrect cast to uint8_t when setting frame length
  src/core/mac/mac_frame.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, bug, cla: yes

#4447 [efr32] update to Silicon Labs SDK v2.7
  examples/Makefile-efr32mg12
  examples/Makefile-efr32mg21
  examples/platforms/efr32mg12/Makefile.am
  examples/platforms/efr32mg12/Makefile.platform.am
  examples/platforms/efr32mg12/README.md
  examples/platforms/efr32mg12/alarm.c
  examples/platforms/efr32mg12/fem-control.c
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/main.c
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/Makefile.am
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/main.c
  examples/platforms/efr32mg12/system.c
  examples/platforms/efr32mg21/Makefile.am
  examples/platforms/efr32mg21/Makefile.platform.am
  examples/platforms/efr32mg21/README.md
  examples/platforms/efr32mg21/alarm.c
  examples/platforms/efr32mg21/fem-control.c
  examples/platforms/efr32mg21/radio.c
  examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/main.c
  examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/Makefile.am
  examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/main.c
  examples/platforms/efr32mg21/system.c
  third_party/silabs/Makefile.am
Labels: P4, cla: yes, enhancement, platform: efr32

#4460 [announce-sender] fix bug in computing announce period
  src/core/thread/announce_sender.cpp
Labels: P4, bug, cla: yes

#4446 [posix-host] add posix parameter to get dataset from NCP and save to file
  .travis.yml
  .travis/before_install.sh
  .travis/check-ncp-rcp-migrate
  .travis/script.sh
  include/openthread/ip6.h
  src/core/common/settings.hpp
  src/ncp/ncp_base_mtd.cpp
  src/posix/main.c
  src/posix/platform/CMakeLists.txt
  src/posix/platform/openthread-system.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
Labels: P2, cla: yes, enhancement

#4233 [harness-sniffer] add OT sniffer support in Thread Test Harness
  tools/harness-sniffer/OT_Sniffer.py
  tools/harness-sniffer/README.md
Labels: P4, cla: yes, enhancement

#4452 [coap] add otCoapOptionIterator and related API functions
  include/openthread/coap.h
  src/core/api/coap_api.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
Labels: P4, api: user, cla: yes, coap, enhancement

#4468 [nlbuild-autotools] update to 1.6.15
  third_party/nlbuild-autotools/repo/.default-version
  third_party/nlbuild-autotools/repo/.travis.yml
  third_party/nlbuild-autotools/repo/CHANGES
  third_party/nlbuild-autotools/repo/MANIFEST
  third_party/nlbuild-autotools/repo/README.md
  third_party/nlbuild-autotools/repo/automake/post/rules/headers.am
  third_party/nlbuild-autotools/repo/tools/packages/autoconf/autoconf.url
  third_party/nlbuild-autotools/repo/tools/packages/automake/automake.url
  third_party/nlbuild-autotools/repo/tools/packages/build
  third_party/nlbuild-autotools/repo/tools/packages/coreutils/coreutils.url
  third_party/nlbuild-autotools/repo/tools/packages/coreutils/coreutils.version
  third_party/nlbuild-autotools/repo/tools/packages/libtool/libtool.url
  third_party/nlbuild-autotools/repo/tools/packages/m4/m4.url
  third_party/nlbuild-autotools/repo/tools/packages/make/make.url
Labels: P4, cla: yes, comp: build, enhancement

#4463 [ncp] remove dead code in SPINEL_PROP_STREAM_NET_INSECURE set handler
  src/ncp/ncp_base_mtd.cpp
Labels: NCP, P4, cla: yes, enhancement

#4465 [mle] remove redundant call to RouterTable::GetRouter
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, enhancement

#4466 [efr32] remove SDKVERSION in makefiles to fix SDK v2.7 build
  examples/Makefile-efr32mg12
  examples/Makefile-efr32mg21
  examples/platforms/efr32mg12/Makefile.am
  examples/platforms/efr32mg12/Makefile.platform.am
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/Makefile.am
  examples/platforms/efr32mg21/Makefile.am
  examples/platforms/efr32mg21/Makefile.platform.am
  examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/Makefile.am
  third_party/silabs/Makefile.am
Labels: P4, bug, cla: yes, comp: build, platform: efr32

#4469 [build] define OPENTHREAD_FTD/MTD/RADIO in posix-app and unit test makefiles
  src/posix/Makefile.am
  src/posix/platform/Makefile.am
  tests/unit/Makefile.am
Labels: cla: yes, comp: build, posix-host

#4432 [mac] correct default OPENTHREAD_CONFIG_MAC_MAX_CSMA_BACKOFFS_DIRECT
  src/core/config/mac.h
Labels: P4, cla: yes, enhancement

#4439 [ncp] add timestamp to log metadata fields
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/spinel.h
Labels: NCP, P4, cla: yes, enhancement

#4474 [script] add ppa without user input
  script/bootstrap
Labels: P4, cla: yes, comp: build, enhancement

#4457 [posix-host] add command mode for ot-ctl
  .travis/check-posix-app-pty
  src/posix/client.c
Labels: P4, cla: yes, enhancement, posix-host

#4475 [ncp] remove dead code in SPINEL_PROP_STREAM_NET set handler
  src/ncp/ncp_base_mtd.cpp
Labels: NCP, P4, cla: yes, enhancement

#4480 [posix-host] explicitly ignore return value on write
  src/posix/client.c
Labels: P4, cla: yes, comp: build, enhancement, posix-host

#4477 [travis] correct error message output
  .travis/check-posix-app-pty
Labels: P4, cla: yes, continuous-integration, enhancement, posix-host

#4489 [codecov] ignore third_party code
  .codecov.yml
Labels: P4, cla: yes, comp: build, enhancement

#4495 [commissioner] remove duplicate `CoapSecure::Stop()` call
  src/core/meshcop/commissioner.cpp
Labels: P4, cla: yes, enhancement

#4487 [meshcop] fix premature free of finalize message
  src/core/meshcop/joiner.cpp
Labels: P4, bug, cla: yes

#4490 [ncp] simplify unimplemented commands
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_mtd.cpp
Labels: NCP, P4, cla: yes, enhancement

#4484 [efr32] Enhancements to radio driver (2/3)
  examples/platforms/efr32mg12/radio.c
Labels: P4, cla: yes, enhancement, platform: efr32

#4473 [mbedtls] split builtin mbedtls management option from mbedtls build option
  examples/common-switches.mk
  examples/platforms/nrf528xx/src/system.c
  src/core/config/openthread-core-default-config.h
  src/core/crypto/mbedtls.cpp
Labels: P4, cla: yes, enhancement

#4502 [cli] emit SIGINT on ctrl-c
  src/cli/cli_uart.cpp
Labels: P4, cla: yes, comp: cli, enhancement, platform: posix

#4498 [build] fix wrong macro name
  examples/common-switches.mk
Labels: P4, bug, cla: yes, comp: build

#4505 [nrf528xx] support pretty out of source directory
  examples/platforms/nrf528xx/Makefile.am
  examples/platforms/nrf528xx/src/platform-softdevice.h
  examples/platforms/nrf528xx/src/softdevice.h
Labels: P4, cla: yes, comp: build, continuous-integration, platform: nrf52811, platform: nrf52833, platform: nrf52840

#4504 [posix-host] add otPlatRadioGetState()
  examples/platforms/posix/radio.c
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/radio_spinel.hpp
Labels: P4, cla: yes, enhancement, posix-host

#4507 [nlbuild-autotools] update to 1.6.16
  third_party/nlbuild-autotools/repo/.default-version
  third_party/nlbuild-autotools/repo/CHANGES
  third_party/nlbuild-autotools/repo/automake/post/rules/pretty.am
Labels: P4, cla: yes, comp: build, enhancement

#4491 [toranj] improve code coverage by using absolute path
  .travis.yml
  .travis/script.sh
  tests/toranj/build.sh
  tests/toranj/start.sh
Labels: P4, cla: yes, comp: build, enhancement

#4503 [mac] simplify scan handlers
  src/core/api/link_api.cpp
  src/core/common/instance.cpp
  src/core/common/instance.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.hpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/energy_scan_server.hpp
  src/core/thread/panid_query_server.cpp
  src/core/thread/panid_query_server.hpp
  src/core/utils/channel_monitor.cpp
  src/core/utils/channel_monitor.hpp
Labels: P4, cla: yes, enhancement

#4506 [efr32] Enhancements to radio driver (3/3)
  examples/platforms/efr32mg12/brd4161a/board_config.h
  examples/platforms/efr32mg12/brd4166a/board_config.h
  examples/platforms/efr32mg12/brd4170a/board_config.h
  examples/platforms/efr32mg12/brd4304a/board_config.h
  examples/platforms/efr32mg12/radio.c
Labels: P4, cla: yes, enhancement, platform: efr32

#4509 [mac-frame] add missing OT_TOOL_PACKED_BEGIN to Beacon class
  src/core/mac/mac_frame.hpp
Labels: P4, bug, cla: yes

#4514 [build] change macOS bootstrapped GCC to official ARM brew tap
  script/bootstrap
Labels: P4, cla: yes, comp: build, enhancement

#4516 [toranj] update test-012-multi-hop-traffic
  tests/toranj/test-012-multi-hop-traffic.py
Labels: P4, cla: yes, continuous-integration, enhancement
