Repository openthread/openthread, pull requests merged in 2020-09, with the labels that each got.

#5369 [thread-cert] refactor case 7.1.2 and 7.1.4 using pktverify
  tests/scripts/thread-cert/Cert_7_1_02_BorderRouterAsRouter.py
  tests/scripts/thread-cert/Cert_7_1_04_BorderRouterAsRouter.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5434 [net] add 'Checksum' class
  Android.mk
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/net/checksum.cpp
  src/core/net/checksum.hpp
  src/core/net/icmp6.cpp
  src/core/net/icmp6.hpp
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
  src/core/net/ip6_address.hpp
  src/core/net/ip6_headers.hpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
  tests/unit/CMakeLists.txt
  tests/unit/Makefile.am
  tests/unit/test_checksum.cpp
Labels: P4, cla: yes, enhancement

#5480 [network-data] remove unused/undefined method decelerations
  src/core/thread/network_data_leader.hpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_local.cpp
  src/core/thread/tmf.hpp
Labels: P4, cla: yes, enhancement

#5472 [github-actions] fix POSIX workflow coverage uploading
  .github/workflows/posix.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#5486 [thread-cert] fix case 6.1.9 random fail
  tests/scripts/thread-cert/Cert_6_1_09_EDSynchronization.py
Labels: P2, bug, cla: yes, continuous-integration

#5482 [coap] misc enhancements
  Android.mk
  include/openthread/coap.h
  include/openthread/instance.h
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/api/coap_api.cpp
  src/core/backbone_router/bbr_manager.cpp
  src/core/backbone_router/multicast_listeners_table.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
  src/core/meshcop/announce_begin_client.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/energy_scan_client.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/meshcop_leader.cpp
  src/core/meshcop/panid_query_client.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/announce_begin_server.cpp
  src/core/thread/dua_manager.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mlr_manager.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/panid_query_server.cpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_uri_paths.hpp
  src/core/thread/uri_paths.cpp
  src/core/thread/uri_paths.hpp
Labels: P4, cla: yes, comp: coap, enhancement

#5485 [style] fix include directives
  src/core/api/channel_manager_api.cpp
  src/core/api/channel_monitor_api.cpp
  src/core/api/child_supervision_api.cpp
  src/core/api/entropy_api.cpp
  src/core/api/network_time_api.cpp
  src/core/api/random_crypto_api.cpp
  src/core/api/random_noncrypto_api.cpp
  src/posix/console_cli.cpp
Labels: P4, cla: yes, enhancement

#5449 [low-power] add CSL implementations on nrf52840
  examples/platforms/nrf528xx/nrf52840/openthread-core-nrf52840-config.h
  examples/platforms/nrf528xx/src/radio.c
  examples/platforms/simulation/radio.c
  include/openthread/platform/radio.h
  src/core/mac/mac.cpp
  src/core/mac/sub_mac.cpp
  src/core/mac/sub_mac.hpp
  src/core/thread/mle.cpp
Labels: P3, Thread 1.2, cla: yes, enhancement, platform: nrf52840

#5487 [style] remove usage of std::numeric_limits
  src/core/backbone_router/bbr_manager.cpp
Labels: cla: yes

#5488 [mle] declare 'Header' as a private nested type of 'Mle'
  src/core/thread/discover_scanner.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, comp: mle, enhancement

#5490 [thread-cert] fix case 5.5.2 random fail
  tests/scripts/thread-cert/Cert_5_5_02_LeaderReboot.py
Labels: P3, bug, cla: yes, continuous-integration

#5422 [dua] add NdProxy table on Backbone Router
  Android.mk
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/backbone_router/bbr_leader.cpp
  src/core/backbone_router/bbr_manager.cpp
  src/core/backbone_router/bbr_manager.hpp
  src/core/backbone_router/ndproxy_table.cpp
  src/core/backbone_router/ndproxy_table.hpp
  src/core/common/instance.hpp
  src/core/config/backbone_router.h
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
  src/core/thread/address_resolver.cpp
  src/core/thread/address_resolver.hpp
  src/core/thread/mle_types.hpp
  tests/unit/CMakeLists.txt
  tests/unit/Makefile.am
  tests/unit/test_ndproxy_table.cpp
Labels: Thread 1.2, cla: yes, enhancement

#5491 [efr32] fix NVM3 initialization error due to alignment issue
  examples/Makefile-efr32mg21
Labels: bug, cla: yes, platform: efr32

#5496 [k32w] use a custom Persistent Data Manager
  examples/Makefile-jn5189
  examples/Makefile-k32w061
  examples/platforms/k32w/jn5189/Makefile.am
  examples/platforms/k32w/jn5189/Makefile.platform.am
  examples/platforms/k32w/jn5189/jn5189-sdk-config.h
  examples/platforms/k32w/jn5189/jn5189.ld
  examples/platforms/k32w/jn5189/openthread-core-jn5189-config.h
  examples/platforms/k32w/k32w061/Makefile.am
  examples/platforms/k32w/k32w061/Makefile.platform.am
  examples/platforms/k32w/k32w061/k32w061-sdk-config.h
  examples/platforms/k32w/k32w061/k32w061.ld
  examples/platforms/k32w/k32w061/openthread-core-k32w061-config.h
  examples/platforms/k32w/src/settings_k32w.c
  examples/platforms/k32w/src/system.c
  third_party/nxp/JN5189DK6/middleware/wireless/framework/Flash/Internal/Flash_Adapter.c
  third_party/nxp/JN5189DK6/middleware/wireless/framework/Flash/Internal/Flash_Adapter.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/FunctionLib/FunctionLib.c
  third_party/nxp/JN5189DK6/middleware/wireless/framework/FunctionLib/FunctionLib.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/Lists/GenericList.c
  third_party/nxp/JN5189DK6/middleware/wireless/framework/Lists/GenericList.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/MemManager/Interface/MemManager.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/MemManager/Source/MemManager.c
  third_party/nxp/JN5189DK6/middleware/wireless/framework/OSAbstraction/Interface/fsl_os_abstraction.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/OSAbstraction/Interface/fsl_os_abstraction_bm.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/OSAbstraction/Interface/fsl_os_abstraction_config.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/OSAbstraction/Interface/fsl_os_abstraction_free_rtos.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/OSAbstraction/Source/fsl_os_abstraction_bm.c
  third_party/nxp/JN5189DK6/middleware/wireless/framework/OSAbstraction/Source/fsl_os_abstraction_free_rtos.c
  third_party/nxp/JN5189DK6/middleware/wireless/framework/PDM/Include/PDM.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/PDM/Library/libPDM.a
  third_party/nxp/JN5189DK6/middleware/wireless/framework/PDM/PDM.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/PDM/pdm_port.c
  third_party/nxp/JN5189DK6/middleware/wireless/framework/Panic/Interface/Panic.h
  third_party/nxp/JN5189DK6/middleware/wireless/framework/Panic/Source/Panic.c
  third_party/nxp/JN5189DK6/middleware/wireless/framework/Reset/Reset.c
  third_party/nxp/K32W061DK6/middleware/wireless/framework/Flash/Internal/Flash_Adapter.c
  third_party/nxp/K32W061DK6/middleware/wireless/framework/Flash/Internal/Flash_Adapter.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/FunctionLib/FunctionLib.c
  third_party/nxp/K32W061DK6/middleware/wireless/framework/FunctionLib/FunctionLib.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/Lists/GenericList.c
  third_party/nxp/K32W061DK6/middleware/wireless/framework/Lists/GenericList.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/MemManager/Interface/MemManager.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/MemManager/Source/MemManager.c
  third_party/nxp/K32W061DK6/middleware/wireless/framework/OSAbstraction/Interface/fsl_os_abstraction.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/OSAbstraction/Interface/fsl_os_abstraction_bm.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/OSAbstraction/Interface/fsl_os_abstraction_config.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/OSAbstraction/Interface/fsl_os_abstraction_free_rtos.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/OSAbstraction/Source/fsl_os_abstraction_bm.c
  third_party/nxp/K32W061DK6/middleware/wireless/framework/OSAbstraction/Source/fsl_os_abstraction_free_rtos.c
  third_party/nxp/K32W061DK6/middleware/wireless/framework/PDM/Include/PDM.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/PDM/Library/libPDM.a
  third_party/nxp/K32W061DK6/middleware/wireless/framework/PDM/PDM.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/PDM/pdm_port.c
  third_party/nxp/K32W061DK6/middleware/wireless/framework/Panic/Interface/Panic.h
  third_party/nxp/K32W061DK6/middleware/wireless/framework/Panic/Source/Panic.c
  third_party/nxp/K32W061DK6/middleware/wireless/framework/Reset/Reset.c
Labels: cla: yes, enhancement, platform: k32w

#5439 [thread-cert] refactor case 9.2.15 and 9.2.16 using pktverify
  tests/scripts/thread-cert/Cert_9_2_15_PendingPartition.py
  tests/scripts/thread-cert/Cert_9_2_16_ActivePendingPartition.py
  tests/scripts/thread-cert/pktverify/consts.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5497 [low-power] remove extra csl tx after buffered message sent by indirect tx
  src/core/thread/csl_tx_scheduler.cpp
Labels: P3, Thread 1.2, bug, cla: yes

#5499 [mac-frame] handle exception case for payload index of mac cmd
  script/test
  src/core/mac/mac_frame.cpp
  tests/unit/test_mac_frame.cpp
Labels: P3, Thread 1.2, bug, cla: yes

#5505 [link-quality] fix fuzzer compile failure
  src/core/thread/link_quality.cpp
Labels: P2, cla: yes, continuous-integration

#5495 [mle] further simplifications of logging in MLE
  src/core/thread/discover_scanner.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, comp: mle, enhancement

#5444 [thread-cert] refactor case 9.2.18 using pktverify
  tests/scripts/thread-cert/Cert_9_2_18_RollBackActiveTimestamp.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/packet_verifier.py
  tests/scripts/thread-cert/pktverify/test_info.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5504 [nrf528xx] check nrf_802154_sleep_if_idle() return status to set correct pending event
  examples/platforms/nrf528xx/src/radio.c
Labels: P1, cla: yes, platform: nrf52811, platform: nrf52833, platform: nrf52840

#5424 [size-report] add size-report for Thread 1.2
  script/check-size
Labels: Thread 1.2, cla: yes, continuous-integration, enhancement

#5429 [thread-cert] refactor case 9.2.14 using pktverify
  tests/scripts/thread-cert/Cert_9_2_14_PanIdQuery.py
  tests/scripts/thread-cert/pktverify/consts.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5479 [github-actions] upload test result artifacts
  .github/workflows/posix.yml
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  script/test
Labels: cla: yes, continuous-integration

#5508 [link-quality] optimize RSS calculation
  src/core/thread/link_quality.cpp
Labels: P4, cla: yes, enhancement

#5371 [thread-cert] refactor case 5.6.6 and 5.6.9 using pktverify
  tests/scripts/thread-cert/Cert_5_6_03_NetworkDataRegisterAfterAttachLeader.py
  tests/scripts/thread-cert/Cert_5_6_04_NetworkDataRegisterAfterAttachRouter.py
  tests/scripts/thread-cert/Cert_5_6_06_NetworkDataExpiration.py
  tests/scripts/thread-cert/Cert_5_6_09_NetworkDataForwarding.py
  tests/scripts/thread-cert/Cert_7_1_02_BorderRouterAsRouter.py
  tests/scripts/thread-cert/Cert_7_1_04_BorderRouterAsRouter.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5514 [reference-device] increase CLI RX buffer size
  src/cli/cli_config.h
Labels: P4, certification, cla: yes

#5513 [thci] avoid globbing in scanJoiner
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P4, certification, cla: yes

#5517 [scripts] fix test_router_reattach
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/test_router_reattach.py
Labels: P4, bug, cla: yes, continuous-integration

#5511 [joiner] add 'Joiner::State' enumeration (c++ style constants)
  src/core/api/joiner_api.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner.hpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5503 [coap] update/simplify CoAP Options generation/processing
  src/core/api/coap_api.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
Labels: P4, cla: yes, comp: coap, enhancement

#5521 [commissioner] add `State` and `JoinerEvent` enums (c++ style constants)
  src/core/api/commissioner_api.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5519 [github-actions] misc enhancements to otns test
  .github/workflows/simulation.yml
Labels: P4, cla: yes, continuous-integration

#5518 [gitignore] ignore more files
  .gitignore
Labels: cla: yes

#5456 [low-power] add RCP support for CSL
  .github/workflows/simulation-1.2.yml
  examples/platforms/nrf528xx/nrf52811/openthread-core-nrf52811-config.h
  examples/platforms/nrf528xx/nrf52833/openthread-core-nrf52833-config.h
  examples/platforms/nrf528xx/nrf52840/openthread-core-nrf52840-config.h
  examples/platforms/simulation/openthread-core-simulation-config.h
  include/openthread/platform/radio.h
  script/test
  src/core/config/mac.h
  src/core/config/openthread-core-config-check.h
  src/core/mac/sub_mac.cpp
  src/core/mac/sub_mac.hpp
  src/core/radio/radio_platform.cpp
  src/core/thread/csl_tx_scheduler.cpp
  src/core/thread/csl_tx_scheduler.hpp
  src/lib/spinel/radio_spinel.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  src/ncp/ncp_base_radio.cpp
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/hdlc_interface.hpp
  src/posix/platform/radio.cpp
  src/posix/platform/spi_interface.hpp
  tests/scripts/expect/v1_2-rcp.exp
  tests/toranj/openthread-core-toranj-config.h
Labels: Thread 1.2, api: platform, cla: yes, comp: rcp, platform: nrf52811, platform: nrf52833, platform: nrf52840, platform: posix, platform: simulation

#5528 [cli] misc enhancements
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_commissioner.cpp
  src/cli/cli_dataset.cpp
  src/cli/cli_joiner.cpp
  src/cli/cli_udp.cpp
  tests/toranj/build.sh
Labels: P4, cla: yes, comp: cli, enhancement

#5452 [thread-cert] refactor case 9.2.10 using pktverify
  tests/scripts/thread-cert/Cert_9_2_10_PendingPartition.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5522 [thread-cert] add low power case 5_3_01
  .github/workflows/simulation-1.2.yml
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
  tests/scripts/thread-cert/v1_2_LowPower_5_3_01_SSEDAttachment.py
Labels: P4, Thread 1.2, certification, cla: yes, continuous-integration

#5533 [continuous-integration] use sudo to kill daemon
  script/check-posix-pty
Labels: P4, bug, cla: yes, continuous-integration

#5534 [continuous-integration] fix expect router link
  tests/scripts/expect/cli-router.exp
Labels: P4, bug, cla: yes, continuous-integration

#5535 [cmake] make UART RAW config visible in daemon mode
  src/posix/CMakeLists.txt
  src/posix/cli.cmake
Labels: cla: yes, comp: build, enhancement, platform: posix

#5501 [low-power] fix csl channel
  include/openthread/link.h
  src/core/api/link_api.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/sub_mac.cpp
  src/core/mac/sub_mac.hpp
  src/core/radio/radio.hpp
  src/core/thread/csl_tx_scheduler.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/mle.py
  tests/scripts/thread-cert/v1_2_test_csl_transmission.py
Labels: Thread 1.2, bug, cla: yes

#5538 [platform] remove unused header file
  include/Makefile.am
  include/openthread/BUILD.gn
  include/openthread/platform/ble.h
Labels: P4, cla: yes, enhancement

#5539 [coap] make CoAP start and stop reentrant
  include/openthread/coap.h
  src/core/backbone_router/backbone_tmf.hpp
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/thread/tmf.hpp
Labels: P4, cla: yes, comp: coap, enhancement

#5529 [efr32] Update for compatibility with GSDK 3.0
  examples/Makefile-efr32mg1
  examples/Makefile-efr32mg12
  examples/Makefile-efr32mg13
  examples/Makefile-efr32mg21
  examples/platforms/efr32mg1/Makefile.am
  examples/platforms/efr32mg1/Makefile.platform.am
  examples/platforms/efr32mg1/README.md
  examples/platforms/efr32mg1/crypto/efr32-mbedtls-config.h
  examples/platforms/efr32mg1/crypto/mbedtls_config.h
  examples/platforms/efr32mg1/crypto/mbedtls_config_autogen.h
  examples/platforms/efr32mg1/radio.c
  examples/platforms/efr32mg1/system.c
  examples/platforms/efr32mg12/Makefile.am
  examples/platforms/efr32mg12/Makefile.platform.am
  examples/platforms/efr32mg12/README.md
  examples/platforms/efr32mg12/crypto/efr32-mbedtls-config.h
  examples/platforms/efr32mg12/crypto/mbedtls_config.h
  examples/platforms/efr32mg12/crypto/mbedtls_config_autogen.h
  examples/platforms/efr32mg12/radio.c
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/Makefile.am
  examples/platforms/efr32mg12/system.c
  examples/platforms/efr32mg13/Makefile.am
  examples/platforms/efr32mg13/Makefile.platform.am
  examples/platforms/efr32mg13/README.md
  examples/platforms/efr32mg13/crypto/efr32-mbedtls-config.h
  examples/platforms/efr32mg13/crypto/mbedtls_config.h
  examples/platforms/efr32mg13/crypto/mbedtls_config_autogen.h
  examples/platforms/efr32mg13/radio.c
  examples/platforms/efr32mg13/sleepy-demo/sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32mg13/sleepy-demo/sleepy-demo-mtd/Makefile.am
  examples/platforms/efr32mg13/system.c
  examples/platforms/efr32mg21/Makefile.am
  examples/platforms/efr32mg21/Makefile.platform.am
  examples/platforms/efr32mg21/README.md
  examples/platforms/efr32mg21/crypto/efr32-mbedtls-config.h
  examples/platforms/efr32mg21/crypto/mbedtls_config.h
  examples/platforms/efr32mg21/crypto/mbedtls_config_autogen.h
  examples/platforms/efr32mg21/radio.c
  examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32mg21/sleepy-demo/sleepy-demo-mtd/Makefile.am
  examples/platforms/efr32mg21/system.c
  third_party/silabs/Makefile.am
Labels: cla: yes, platform: efr32

#5542 [doc] fix broken anchors in CLI Readme
  src/cli/README.md
Labels: cla: yes, comp: docs

#5500 [simulation] fix error handling in simulation flash APIs
  examples/platforms/simulation/flash.c
Labels: P4, bug, cla: yes

#5541 [cmake] list targets one per line in unit test CMakeLists
  tests/unit/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#5549 [cli] change 'binary' arg to '-x' for consistency (#5543)
  src/cli/README_COMMISSIONER.md
  src/cli/README_DATASET.md
  src/cli/cli_commissioner.cpp
  src/cli/cli_dataset.cpp
  tests/scripts/expect/cli-dataset.exp
  tests/scripts/thread-cert/node.py
  tools/harness-thci/OpenThread.py
Labels: P4, cla: yes, comp: cli, enhancement

#5509 [meshcop] add helper function 'LogError()'
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/meshcop.cpp
  src/core/meshcop/meshcop.hpp
  src/core/meshcop/meshcop_leader.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/panid_query_server.cpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5540 [cli] return error from 'Process{Cmd}()' methods, adding 'OT_ERROR_PENDING'
  include/openthread/cli.h
  include/openthread/error.h
  include/openthread/instance.h
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/common/logging.cpp
Labels: P4, cla: yes, comp: cli, enhancement

#5544 [cli] add api version command
  src/cli/README.md
  src/cli/cli.cpp
  tests/scripts/expect/cli-misc.exp
Labels: P3, cla: yes, comp: cli, enhancement

#5548 [posix] fix options dependency
  src/posix/console_cli.cpp
  src/posix/console_cli.h
  src/posix/main.c
Labels: P4, cla: yes, comp: build, enhancement, platform: posix

#5553 [otns] test with a specific OTNS commit
  .github/workflows/simulation.yml
Labels: cla: yes, continuous-integration

#5532 [cli] implement setting/getting cca threshold
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  tests/scripts/expect/cli-misc.exp
Labels: P4, cla: yes, comp: cli, enhancement

#5556 [cli] service and server data as hex-encoded binary values
  src/cli/README.md
  src/cli/cli.cpp
  tests/scripts/thread-cert/test_reed_address_solicit_rejected.py
  tests/scripts/thread-cert/test_service.py
Labels: P4, cla: yes, comp: cli, enhancement

#5550 [mac] only apply neighbor check when key id mode is 1
  src/core/mac/mac.cpp
Labels: P4, cla: yes, enhancement

#5515 [thci] support network name with space for wpanctl
  tools/harness-thci/OpenThread_WpanCtl.py
Labels: P4, certification, cla: yes

#5283 [continuous-integration] add code coverage threshold
  .codecov.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#5466 [ot-ctl] auto reconnect session
  src/posix/client.cpp
  src/posix/main.c
  src/posix/platform/include/openthread/openthread-system.h
  src/posix/platform/misc.cpp
  src/posix/platform/uart.cpp
  tests/scripts/expect/cli-reset.exp
Labels: P3, cla: yes, enhancement, platform: posix

#5552 [cli] fix compile warning
  src/cli/cli_config.h
  src/cli/cli_console.hpp
Labels: P3, cla: yes, comp: cli

#5562 [meshcop] include logging.hpp for helper function 'LogError()'
  src/core/meshcop/meshcop.cpp
Labels: P3, bug, cla: yes, comp: meshcop

#5412 [thread-cert] refactor case 9.2.4 using pktverify
  tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
  tests/scripts/thread-cert/pktverify/packet_verifier.py
  tests/scripts/thread-cert/pktverify/test_info.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5566 [style] fix warnings -Wextra-semi
  src/core/mac/mac_frame.hpp
  src/core/mac/sub_mac.hpp
  src/core/meshcop/meshcop.hpp
  src/core/net/dns_headers.hpp
  src/core/utils/flash.hpp
Labels: P4, cla: yes

#5564 [gn] add missing files to BUILD.gn
  script/check-gn-build
  src/core/BUILD.gn
Labels: cla: yes, comp: build

#5551 [script] fix output when no arguments are specified
  script/test
Labels: cla: yes

#5567 [docs] add style guide for documentation contributions
  CONTRIBUTING.md
  doc/Makefile.am
  doc/STYLE_GUIDE.md
Labels: cla: yes, comp: docs

#5555 [message] add helper macros to free message (on error)
  src/core/backbone_router/bbr_manager.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap_secure.cpp
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/meshcop/announce_begin_client.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/energy_scan_client.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/meshcop_leader.cpp
  src/core/meshcop/panid_query_client.cpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dhcp6_server.cpp
  src/core/net/dns_client.cpp
  src/core/net/icmp6.cpp
  src/core/net/ip6.cpp
  src/core/net/ip6_mpl.cpp
  src/core/net/sntp_client.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/discover_scanner.cpp
  src/core/thread/dua_manager.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mlr_manager.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/panid_query_server.cpp
  src/core/utils/child_supervision.cpp
Labels: P4, cla: yes, enhancement

#5547 [github-actions] run Thread 1.1 cert tests for 1.2 build
  .github/workflows/simulation-1.2.yml
  tests/scripts/thread-cert/Cert_8_1_01_Commissioning.py
  tests/scripts/thread-cert/command.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P4, Thread 1.2, certification, cla: yes, continuous-integration

#5489 [thread-cert] Thread 1.2 CI with OTBR and Backbone link
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  script/test
  tests/scripts/thread-cert/backbone/bbr_5_11_01.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/addrs.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_verifier.py
  tests/scripts/thread-cert/pktverify/utils.py
  tests/scripts/thread-cert/run_bbr_tests.py
  tests/scripts/thread-cert/simulator.py
  tests/scripts/thread-cert/thread_cert.py
Labels: Thread 1.2, certification, cla: yes, continuous-integration

#5537 [reference-device] send fake ADDR_NTF.ntf
  include/openthread/thread.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/thread_ftd_api.cpp
  src/core/thread/address_resolver.hpp
  tests/scripts/thread-cert/node.py
Labels: Thread 1.2, cla: yes, enhancement

#5577 [github-actions] fix thread-wireshark missing
  .github/workflows/simulation-1.2.yml
  tests/scripts/thread-cert/backbone/bbr_5_11_01.py
Labels: P2, cla: yes, continuous-integration

#5575 [codecov] only post coverage check statuses to PRs
  .codecov.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#5481 [low-power] implement link metrics - single probe
  Android.mk
  etc/cmake/options.cmake
  etc/gn/openthread.gni
  examples/common-switches.mk
  include/Makefile.am
  include/openthread/link_metrics.h
  script/test
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/api/link_metrics_api.cpp
  src/core/common/instance.hpp
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/config/mle.h
  src/core/config/openthread-core-config-check.h
  src/core/thread/link_metrics.cpp
  src/core/thread/link_metrics.hpp
  src/core/thread/link_metrics_tlvs.hpp
  src/core/thread/link_quality.cpp
  src/core/thread/link_quality.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router.hpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/mle.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/v1_2_test_single_probe.py
Labels: Thread 1.2, cla: yes, enhancement

#5558 [scripts] fix test_route_table.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/test_route_table.py
Labels: P4, cla: yes, continuous-integration

#5525 [pktverify] verify offline test info
  script/test
  tests/scripts/thread-cert/pktverify/verify.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P4, certification, cla: yes, enhancement

#5516 [dua] handle AddressError
  src/core/thread/address_resolver.cpp
  src/core/thread/dua_manager.cpp
  src/core/thread/dua_manager.hpp
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/thread_cert.py
  tests/scripts/thread-cert/v1_2_test_dua_handle_address_error.py
Labels: Thread 1.2, cla: yes, enhancement

#5580 [scripts] fix test_route_table.py fails by chance
  tests/scripts/thread-cert/test_route_table.py
Labels: P2, bug, cla: yes, continuous-integration

#5523 [dua] handle coap error code for DUA.rsp
  src/cli/README.md
  src/core/backbone_router/bbr_manager.cpp
  src/core/backbone_router/bbr_manager.hpp
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/coap/coap_message.hpp
  src/core/thread/dua_manager.cpp
  src/core/thread/dua_manager.hpp
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/v1_2_test_domain_unicast_address_registration.py
Labels: Thread 1.2, certification, cla: yes, enhancement

#5589 [continuous-integration] fix API change detector
  script/check-api-version
Labels: P4, bug, cla: yes, continuous-integration

#5581 [cli] style fixes and smaller enhancements
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_commissioner.cpp
  src/cli/cli_dataset.cpp
  src/cli/cli_joiner.cpp
  src/cli/cli_network_data.cpp
  src/cli/cli_uart.cpp
  src/cli/cli_udp.cpp
Labels: P4, cla: yes, comp: cli, enhancement

#5592 [linked-list] fix spelling for Indicator typename
  src/core/common/linked_list.hpp
Labels: P4, cla: yes

#5591 [cli] add 'OutputExtAddress()' helper method
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_commissioner.cpp
  src/cli/cli_dataset.cpp
  src/cli/cli_dataset.hpp
  src/cli/cli_joiner.cpp
Labels: P4, cla: yes, comp: cli, enhancement

#5590 [thread-cert] enhance case 9.2.4 for potential packets miss-catching
  tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5597 [thread-cert] enhance case 5.6.6 for potential SED packet out-of-order
  tests/scripts/thread-cert/Cert_5_6_06_NetworkDataExpiration.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5598 [thread-cert] enhance case 9.2.10 for potential MED packets out-of-order
  tests/scripts/thread-cert/Cert_9_2_10_PendingPartition.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5600 [github-actions] use docker/setup-buildx-action@v1
  .github/workflows/docker.yml
Labels: P4, cla: yes, continuous-integration

#5599 [cli] do not pass user-controlled input as format string
  src/cli/cli.cpp
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_udp.cpp
Labels: P3, bug, cla: yes, comp: cli

#5584 [thread-cert] enhance case 9.2.18 for SED packet order
  tests/scripts/thread-cert/Cert_9_2_18_RollBackActiveTimestamp.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5388 [mlr] send BMLR.ntf on Backbone link
  src/core/backbone_router/bbr_manager.cpp
  src/core/backbone_router/bbr_manager.hpp
  src/core/thread/mle_types.hpp
  src/core/thread/uri_paths.cpp
  src/core/thread/uri_paths.hpp
  src/posix/platform/backbone.cpp
  tests/scripts/thread-cert/backbone/test_bmlr.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pcap.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/run_bbr_tests.py
  tests/scripts/thread-cert/thread_cert.py
Labels: Thread 1.2, cla: yes, enhancement

#5596 [nrf_security] use vanilla mbedtls only for AES
  examples/platforms/nrf528xx/nrf52840/Makefile.platform.am
  examples/platforms/nrf528xx/nrf52840/README.md
  third_party/NordicSemiconductor/libraries/nrf_security/config/nrf-config.h
  third_party/NordicSemiconductor/libraries/nrf_security/include/mbedtls/aes_alt.h
  third_party/NordicSemiconductor/libraries/nrf_security/include/mbedtls/cmac_alt.h
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_cc310_backend.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_glue.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_glue_cc310.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_glue_vanilla.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_vanilla_backend.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedtls_base_vanilla.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedtls_tls_vanilla.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedtls_x509_vanilla.a
Labels: P2, Thread 1.2, bug, cla: yes, platform: nrf52840
