Repository openthread/openthread, pull requests merged in 2020-02, with the labels that each got.

#4519 [ip6-address] multiple enhancements
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
Labels: P4, cla: yes, enhancement

#4476 [docs] move Doxygen group structure to the docs directory
  doc/Makefile.am
  doc/ot_api_doc.h
  include/openthread/error.h
Labels: cla: yes, docs

#4518 [posix-host] add hardware flow control capability to hdlc interface
  src/posix/platform/hdlc_interface.cpp
Labels: P4, cla: yes, enhancement, posix-host

#4525 [mle] simplify how parent candidate is cleared
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
Labels: P4, cla: yes, enhancement

#4526 [docs] update list of supporters
  README.md
  doc/Makefile.am
  doc/images/ot-contrib-particle.png
Labels: cla: yes, docs

#4522 [ip6] fix conversion of enum value to uint8_t
  src/core/net/ip6.cpp
Labels: P4, bug, cla: yes

#4500 [cmake] add additional compiler options
  .travis/script.sh
  CMakeLists.txt
  examples/platforms/cc2538/CMakeLists.txt
  examples/platforms/posix/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/core/CMakeLists.txt
  src/ncp/CMakeLists.txt
  src/posix/CMakeLists.txt
  src/posix/platform/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#4528 [android] build CLI and NCP libraries
  Android.mk
  include/openthread-config-android.h
Labels: P3, cla: yes, enhancement

#4527 [settings] encode as packed little endian structs
  src/core/common/settings.cpp
  src/core/common/settings.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, enhancement

#4539 [mle] unify stopping of the advertising timer
  src/core/thread/mle_router.cpp
Labels: cla: yes

#4537 [nrf528xx] fix synchronous GetRssi functionality
  examples/platforms/nrf528xx/src/radio.c
Labels: P4, bug, cla: yes, platform: nrf52811, platform: nrf52833, platform: nrf52840

#4538 [sub-mac] fix incorrect timer configuration for energy scanning
  src/core/mac/sub_mac.cpp
Labels: bug, cla: yes

#4543 [build] add DISABLE_TOOLS flag
  examples/common-switches.mk
Labels: P4, cla: yes, comp: build, enhancement

#4513 [coap] Add helper functions to encode coap block options
  include/openthread/coap.h
  src/core/api/coap_api.cpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
Labels: P4, api: user, cla: yes, coap, enhancement

#4544 [network-data] add check for invalid router IDs
  src/core/thread/network_data_leader_ftd.cpp
Labels: P3, bug, cla: yes

#4545 [docs] correct `dataset activetimestamp` example
  src/cli/README_DATASET.md
Labels: P4, cla: yes, comp: cli, docs

#4548 [spinel] fix when strnlen is not a macro
  src/ncp/spinel.c
Labels: P3, cla: yes, enhancement

#4549 [android] move OPENTHREAD_POSIX_RCP_UART_ENABLE
  Android.mk
Labels: P3, bug, cla: yes, comp: build, posix-host

#4553 [coap] fix comparison with block size validity check
  src/core/coap/coap_message.cpp
Labels: P3, bug, cla: yes, coap

#4551 [build] auto detect big endian
  configure.ac
  src/core/common/encoding.hpp
Labels: P4, cla: yes, comp: build, enhancement

#4547 [posix-host] use c++ for all platform code
  Android.mk
  src/posix/CMakeLists.txt
  src/posix/Makefile.am
  src/posix/client.cpp
  src/posix/console_cli.cpp
  src/posix/console_cli.h
  src/posix/platform/CMakeLists.txt
  src/posix/platform/Makefile.am
  src/posix/platform/alarm.cpp
  src/posix/platform/code_utils.h
  src/posix/platform/entropy.cpp
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/logging.cpp
  src/posix/platform/misc.cpp
  src/posix/platform/netif.cpp
  src/posix/platform/platform-posix.h
  src/posix/platform/radio_spinel.cpp
  src/posix/platform/spi_interface.cpp
  src/posix/platform/system.cpp
  src/posix/platform/uart.cpp
  src/posix/platform/virtual_time.cpp
Labels: P4, cla: yes, enhancement, posix-host

#4562 [network-data] resolve uninitialized output from RlocLookup
  src/core/thread/network_data_leader_ftd.cpp
Labels: P4, bug, cla: yes

#4565 [efr32] remove -Wundef for SDK sources
  third_party/silabs/Makefile.am
Labels: P4, cla: yes, comp: build, enhancement, platform: efr32

#4566 [toranj] fix the check for router entry "is link established"
  tests/toranj/test-012-multi-hop-traffic.py
Labels: P4, bug, cla: yes, continuous-integration

#4572 [mle] invalidate parent if not child
  src/core/thread/mle.cpp
Labels: P4, cla: yes, enhancement

#4574 [posix-host] explicitly ignore return value on write
  src/posix/client.cpp
Labels: P4, cla: yes, comp: build, enhancement, posix-host

#4576 [python] remove unnecessary calls to dict.keys()
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/test_route_table.py
  tools/harness-automation/autothreadharness/runner.py
Labels: P4, cla: yes, continuous-integration, enhancement

#4556 [cli] always output command result
  examples/platforms/cc1352/diag.c
  examples/platforms/cc2538/diag.c
  examples/platforms/cc2650/diag.c
  examples/platforms/cc2652/diag.c
  examples/platforms/efr32mg12/diag.c
  examples/platforms/efr32mg13/diag.c
  examples/platforms/efr32mg21/diag.c
  examples/platforms/gp712/diag.c
  examples/platforms/kw41z/diag.c
  examples/platforms/nrf528xx/src/diag.c
  examples/platforms/posix/diag.c
  examples/platforms/qpg6095/diag.c
  examples/platforms/samr21/diag.c
  include/openthread/diag.h
  include/openthread/platform/diag.h
  src/cli/cli.cpp
  src/core/api/diags_api.cpp
  src/core/diags/factory_diags.cpp
  src/core/diags/factory_diags.hpp
  src/posix/platform/radio_spinel.cpp
  tests/fuzz/fuzzer_platform.c
  tests/scripts/thread-cert/test_diag.py
Labels: P3, cla: yes, enhancement

#4567 [android] build ot-ctl on Android.mk
  .travis.yml
  .travis/check-android-build
  Android.mk
  src/posix/platform/netif.cpp
Labels: P3, cla: yes, comp: build, enhancement

#4573 [posix-host] set network interface name
  .travis/check-posix-app-pty
  src/posix/main.c
  src/posix/platform/netif.cpp
  src/posix/platform/platform-posix.h
  src/posix/platform/system.cpp
Labels: P3, cla: yes, enhancement, posix-host

#4561 [build] do not export openthread/config.h
  include/openthread/Makefile.am
Labels: P4, cla: yes, comp: build, enhancement

#4582 [mle] mark former parent as valid after becoming router
  src/core/thread/mle_router.cpp
Labels: P1, bug, cla: yes

#4579 [test] fix check error, cast non-trivial class pointer to void *
  tests/unit/test_lowpan.hpp
Labels: P4, cla: yes, comp: build, continuous-integration

#4580 [posix-host] ot-cli: handle write() return values
  src/posix/client.cpp
Labels: P4, bug, cla: yes, posix-host

#4585 [efr32] fix 4161a/4166a hal-config.h for upcoming v2.7 SDK patch release
  examples/platforms/efr32mg12/brd4161a/hal-config.h
  examples/platforms/efr32mg12/brd4166a/hal-config.h
Labels: P4, cla: yes, comp: build, platform: efr32

#4588 [build] fix command t not found
  src/ncp/Makefile.am
Labels: P4, cla: yes, comp: build

#4481 [coap] make transmission parameters dynamically configurable
  include/openthread/coap.h
  src/cli/README_COAP.md
  src/cli/cli_coap.cpp
  src/cli/cli_coap.hpp
  src/core/api/coap_api.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/config/coap.h
  src/core/config/openthread-core-config-check.h
Labels: P4, api: user, cla: yes, coap, enhancement

#4584 [coap] validate token length on received messages
  src/core/coap/coap.cpp
  src/core/coap/coap_message.cpp
Labels: P4, bug, cla: yes, coap

#4594 [gp712] fix build error due to conditional include of cfmakeraw
  examples/Makefile-gp712
Labels: P4, bug, cla: yes, comp: build, platform: gp712

#4593 [build] move openthread-system.h under openthread
  Android.mk
  src/posix/CMakeLists.txt
  src/posix/Makefile.am
  src/posix/console_cli.h
  src/posix/main.c
  src/posix/platform/CMakeLists.txt
  src/posix/platform/Makefile.am
  src/posix/platform/include/openthread/openthread-system.h
  src/posix/platform/platform-posix.h
  src/posix/platform/spi_interface.hpp
Labels: P3, cla: yes, comp: build, enhancement, posix-host

#4591 [posix-host] die on RCP timeout
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/include/openthread/openthread-system.h
  src/posix/platform/misc.cpp
  src/posix/platform/radio_spinel.cpp
Labels: P2, cla: yes, enhancement, posix-host

#4325 [mle] add enhanced keep-alive
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
  CMakeLists.txt
  examples/common-switches.mk
  script/test
  src/core/api/thread_api.cpp
  src/core/common/settings.cpp
  src/core/common/settings.hpp
  src/core/config/mac.h
  src/core/mac/data_poll_sender.cpp
  src/core/mac/data_poll_sender.hpp
  src/core/mac/mac.cpp
  src/core/openthread-core-config.h
  src/core/thread/mle.cpp
  src/core/thread/mle_constants.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/topology.hpp
  tests/scripts/thread-cert/message.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/requirements.txt
  tests/scripts/thread-cert/thread_cert.py
  tests/scripts/thread-cert/v1_2_router_5_1_1.py
  tests/scripts/thread-cert/v1_2_test_enhanced_keep_alive.py
Labels: P4, Thread 1.2, cla: yes, enhancement

#4568 [posix-host] enable platform udp/netif by default in daemon mode
  src/posix/platform/openthread-core-posix-config.h
Labels: P4, cla: yes, comp: build, enhancement, posix-host

#4595 [cli] adjust arg length checking to 'coap parameters'
  src/cli/cli_coap.cpp
Labels: P4, bug, cla: yes, coap, comp: cli

#4554 [coap] smaller enhancements
  src/core/api/coap_api.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/coap/coap_secure.cpp
  src/core/coap/coap_secure.hpp
Labels: P4, cla: yes, enhancement

#4596 [posix-host] fix warnings caused by SPI arguments
  src/posix/main.c
  src/posix/platform/radio_spinel.cpp
Labels: P3, cla: yes, enhancement, posix-host

#4601 [mac] fix macro comment typo
  src/core/mac/mac_frame.cpp
Labels: P4, cla: yes

#4605 [posix-host] include inttypes.h in spi_interface.cpp
  src/posix/platform/spi_interface.cpp
Labels: P3, cla: yes, comp: build, posix-host

#4606 [network-diagnostic] declare ExtMacAddressTlv as packed
  src/core/thread/network_diagnostic_tlvs.hpp
Labels: P4, cla: yes, enhancement

#4555 [build] rename example platform POSIX to simulation
  .travis.yml
  .travis/before_install.sh
  .travis/check-ncp-rcp-migrate
  .travis/check-posix-app-pty
  .travis/script.sh
  Makefile.am
  configure.ac
  etc/docker/Makefile
  etc/docker/codelab_otsim/Dockerfile
  etc/docker/ot_sim/Dockerfile
  etc/docker/ot_sim/README.md
  etc/docker/ot_sim/start_sim
  examples/Makefile-simulation
  examples/apps/cli/README.md
  examples/apps/cli/main.c
  examples/apps/ncp/main.c
  examples/platforms/Makefile.am
  examples/platforms/Makefile.platform.am
  examples/platforms/simulation/CMakeLists.txt
  examples/platforms/simulation/Makefile.am
  examples/platforms/simulation/Makefile.platform.am
  examples/platforms/simulation/README.md
  examples/platforms/simulation/alarm.c
  examples/platforms/simulation/diag.c
  examples/platforms/simulation/entropy.c
  examples/platforms/simulation/flash.c
  examples/platforms/simulation/logging.c
  examples/platforms/simulation/misc.c
  examples/platforms/simulation/openthread-core-simulation-config.h
  examples/platforms/simulation/platform-config.h
  examples/platforms/simulation/platform-simulation.h
  examples/platforms/simulation/radio.c
  examples/platforms/simulation/spi-stubs.c
  examples/platforms/simulation/system.c
  examples/platforms/simulation/uart.c
  examples/platforms/simulation/virtual_time/alarm-sim.c
  examples/platforms/simulation/virtual_time/platform-sim.c
  include/openthread/platform/debug_uart.h
  script/bootstrap
  script/test
  src/cli/README.md
  src/cli/README_COAP.md
  src/cli/README_COAPS.md
  src/cli/README_COMMISSIONING.md
  src/posix/README.md
  tests/toranj/build.sh
  tests/unit/Makefile.am
  third_party/ti/ti-openthread_1.01.0_manifest.html
Labels: P4, cla: yes, enhancement, platform: posix

#4607 [posix] fix handling SPI interrupts
  src/posix/platform/spi_interface.cpp
Labels: P3, bug, cla: yes, posix-host

#4564 [dtls] fix allocation and deallocation of ssl cookies
  src/core/meshcop/dtls.cpp
Labels: P4, bug, cla: yes

#4396 [coap] add support for RFC7641
  examples/Makefile-simulation
  examples/common-switches.mk
  include/openthread/coap.h
  src/cli/README_COAP.md
  src/cli/cli_coap.cpp
  src/cli/cli_coap.hpp
  src/core/api/coap_api.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
  src/core/config/coap.h
  src/posix/Makefile-posix
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/test_coap_observe.py
Labels: P4, cla: yes, coap, enhancement

#4603 [travis] move package check into lint stage
  .travis.yml
Labels: P4, cla: yes, comp: build, enhancement

#4586 [efr32] Radio: don't abort current operation on switching to idle
  examples/platforms/efr32mg12/Makefile.am
  examples/platforms/efr32mg12/Makefile.platform.am
  examples/platforms/efr32mg12/alarm.c
  examples/platforms/efr32mg12/brd4161a/board_config.h
  examples/platforms/efr32mg12/brd4166a/board_config.h
  examples/platforms/efr32mg12/brd4304a/board_config.h
  examples/platforms/efr32mg12/crypto/efr32-mbedtls-config.h
  examples/platforms/efr32mg12/diag.c
  examples/platforms/efr32mg12/entropy.c
  examples/platforms/efr32mg12/fem-control.c
  examples/platforms/efr32mg12/flash.c
  examples/platforms/efr32mg12/misc.c
  examples/platforms/efr32mg12/openthread-core-efr32-config-check.h
  examples/platforms/efr32mg12/openthread-core-efr32-config.h
  examples/platforms/efr32mg12/platform-band.h
  examples/platforms/efr32mg12/platform-efr32.h
  examples/platforms/efr32mg12/radio.c
  examples/platforms/efr32mg12/sleepy-demo/Makefile.am
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-ftd/main.c
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/Makefile.am
  examples/platforms/efr32mg12/sleepy-demo/sleepy-demo-mtd/main.c
  examples/platforms/efr32mg12/startup-gcc.c
  examples/platforms/efr32mg12/system.c
  examples/platforms/efr32mg12/uart.c
  examples/platforms/efr32mg13/brd4168a/board_config.h
  examples/platforms/efr32mg13/openthread-core-efr32-config.h
  examples/platforms/efr32mg13/radio.c
Labels: P2, bug, cla: yes, platform: efr32

#4610 [mle] improve readability of RouteTlv
  src/core/thread/mle_tlvs.hpp
  src/core/thread/network_diagnostic_tlvs.hpp
Labels: P4, cla: yes, enhancement

#4613 [typos] fix typos
  include/openthread/diag.h
  include/openthread/link.h
  include/openthread/netdata.h
  include/openthread/platform/diag.h
  src/core/common/locator.hpp
  src/core/diags/factory_diags.hpp
  src/core/mac/data_poll_handler.hpp
  src/core/meshcop/dataset_manager.hpp
  src/core/thread/lowpan.hpp
  src/core/thread/time_sync_service.cpp
  src/lib/spinel/spinel.c
  src/lib/spinel/spinel.h
  src/ncp/ncp_spi.cpp
  src/posix/platform/radio_spinel.cpp
  tests/scripts/thread-cert/Cert_5_2_04_REEDUpgrade.py
  tests/scripts/thread-cert/Cert_9_2_02_MGMTCommissionerSet.py
  tests/toranj/test-004-scan.py
  tests/toranj/test-016-neighbor-table.py
  tests/toranj/test-024-partition-merge.py
  tests/toranj/test-032-child-attach-with-multiple-ip-addresses.py
  tests/toranj/test-034-poor-link-parent-child-attach.py
  tests/toranj/test-600-channel-manager-properties.py
  tests/toranj/test-602-channel-manager-channel-select.py
  tests/unit/test_hdlc.cpp
  tests/unit/test_spinel_buffer.cpp
  tests/unit/test_spinel_decoder.cpp
Labels: P4, cla: yes, enhancement

#4604 [build] enhancements for OpenThread border router
  CMakeLists.txt
  etc/cmake/options.cmake
  src/cli/CMakeLists.txt
  src/core/CMakeLists.txt
  src/core/api/link_raw_api.cpp
  src/core/common/instance.cpp
  src/core/mac/link_raw.cpp
  src/core/mac/mac_frame.cpp
  src/core/mac/sub_mac_callbacks.cpp
  src/ncp/CMakeLists.txt
  src/posix/platform/CMakeLists.txt
  third_party/mbedtls/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement
