Repository openthread/openthread, pull requests merged in 2020-04, with the labels that each got.

#4772 [github-actions] add `apt update` to each build
  .github/workflows/build.yml
  .github/workflows/simulation.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#4771 [network-data] fix FindTlv() to return NULL when TLV sequence is malformed
  src/core/thread/network_data.cpp
Labels: P4, bug, cla: yes

#4774 [gp712] align with the new otPlatFlash API
  examples/platforms/gp712/flash.c
  examples/platforms/gp712/openthread-core-gp712-config.h
Labels: P4, cla: yes, enhancement, platform: gp712

#4777 [toranj] update test-602-channel-select to add extra wait
  tests/toranj/test-602-channel-manager-channel-select.py
Labels: P4, cla: yes, enhancement

#4765 [mac] remove disable CSMA-CA on the last transmit
  src/core/config/mac.h
  src/core/config/openthread-core-config-check.h
  src/core/mac/sub_mac.cpp
Labels: P4, cla: yes

#4600 [toranj] add new test-case for cache table snoop
  tests/toranj/openthread-core-toranj-config.h
  tests/toranj/start.sh
  tests/toranj/test-039-address-cache-table-snoop.py
  tests/toranj/wpan.py
Labels: P4, cla: yes, continuous-integration, enhancement

#4521 [efr32] add nvm3 support
  examples/Makefile-efr32mg13
  examples/platforms/efr32mg12/Makefile.am
  examples/platforms/efr32mg12/Makefile.platform.am
  examples/platforms/efr32mg12/efr32mg12.ld
  examples/platforms/efr32mg12/flash.c
  examples/platforms/efr32mg12/openthread-core-efr32-config.h
  examples/platforms/efr32mg13/Makefile.am
  examples/platforms/efr32mg13/Makefile.platform.am
  examples/platforms/efr32mg13/efr32mg13.ld
  examples/platforms/efr32mg13/flash.c
  examples/platforms/efr32mg13/openthread-core-efr32-config.h
  examples/platforms/efr32mg21/Makefile.am
  examples/platforms/efr32mg21/Makefile.platform.am
  examples/platforms/efr32mg21/efr32mg21.ld
  examples/platforms/efr32mg21/flash.c
  examples/platforms/efr32mg21/openthread-core-efr32-config.h
  third_party/silabs/Makefile.am
Labels: P4, cla: yes, enhancement, platform: efr32

#4776 [mesh-forwarder] include address resolving queue in message eviction
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, cla: yes, enhancement

#4779 [network-data] periodically check for stale child ids
  src/core/thread/mle_router.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
Labels: P2, bug, cla: yes

#4756 [core] use the common `RouterIdSet` class
  src/core/thread/mle_router.cpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/mle_types.hpp
  src/core/thread/network_diagnostic_tlvs.hpp
  src/core/thread/router_table.cpp
  src/core/thread/router_table.hpp
  src/core/thread/thread_tlvs.hpp
Labels: P4, cla: yes, enhancement

#4766 [meshcop] generate PSKc from passphrase
  include/openthread/commissioner.h
  include/openthread/dataset.h
  src/cli/README.md
  src/cli/README_DATASET.md
  src/cli/cli.cpp
  src/cli/cli_dataset.cpp
  src/core/api/commissioner_api.cpp
  src/core/api/dataset_api.cpp
  src/core/crypto/pbkdf2_cmac.cpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
  src/core/meshcop/meshcop.cpp
  src/core/meshcop/meshcop.hpp
  src/ncp/ncp_base_ftd.cpp
  tests/unit/test_pskc.cpp
Labels: P4, api: user, cla: yes, comp: meshcop, enhancement

#4781 [network-data] add IncrementVersionAndStableVersion()
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
Labels: P4, cla: yes, enhancement

#4773 [nrf528xx] update nrf security
  third_party/NordicSemiconductor/libraries/nrf_security/config/nrf-config.h
  third_party/NordicSemiconductor/libraries/nrf_security/include/mbedtls/chacha20_alt.h
  third_party/NordicSemiconductor/libraries/nrf_security/include/mbedtls/chachapoly_alt.h
  third_party/NordicSemiconductor/libraries/nrf_security/include/mbedtls/poly1305_alt.h
  third_party/NordicSemiconductor/libraries/nrf_security/include/mbedtls/sha1_alt.h
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_cc310_backend.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_glue.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_glue_cc310.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_glue_vanilla.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedcrypto_vanilla_backend.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedtls_base_vanilla.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedtls_tls_vanilla.a
  third_party/NordicSemiconductor/libraries/nrf_security/lib/libmbedtls_x509_vanilla.a
Labels: P4, cla: yes, enhancement, platform: nrf52833, platform: nrf52840

#4786 [mesh-forwarder] fix bug in evicting from address resolver queue
  src/core/common/message.hpp
  src/core/thread/mesh_forwarder.cpp
Labels: P1, bug, cla: yes

#4780 [network-data] simplify code, user helper methods
  src/core/thread/network_data.cpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
Labels: P4, cla: yes, enhancement

#4789 [address-resolver] ensure prev pointer stays valid on entry removal
  src/core/thread/address_resolver.cpp
  src/core/thread/address_resolver.hpp
Labels: P1, bug, cla: yes

#4790 [nrf528xx] add defines needed for compilation with IAR in nrf_security
  third_party/NordicSemiconductor/libraries/nrf_security/config/nrf-config.h
  third_party/NordicSemiconductor/libraries/nrf_security/include/mbedtls/ecp.h
Labels: P4, cla: yes, comp: build, platform: nrf52811, platform: nrf52833, platform: nrf52840

#4787 [coap] avoid div-by-0 error in validating coap params
  src/core/coap/coap.cpp
Labels: P4, bug, cla: yes, comp: coap

#4791 [toranj] update test-039 to stagger initial address queries
  tests/toranj/openthread-core-toranj-config.h
  tests/toranj/test-039-address-cache-table-snoop.py
Labels: P4, cla: yes, continuous-integration, enhancement

#4792 [github-actions] include fuzz checks
  .github/workflows/fuzz.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#4783 [network-data] implement network data notifier
  Android.mk
  BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/api/border_router_api.cpp
  src/core/api/server_api.cpp
  src/core/backbone_router/local.cpp
  src/core/common/instance.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data.hpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_data_local.hpp
  src/core/thread/network_data_notifier.cpp
  src/core/thread/network_data_notifier.hpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
Labels: P4, cla: yes, enhancement

#4798 [network-data] use GetLocator() when registering network data
  src/core/thread/network_data_leader_ftd.cpp
Labels: P4, cla: yes, enhancement

#4797 [android] export CFLAGS and include directories
  Android.mk
Labels: P4, cla: yes, comp: build, enhancement

#4794 [mle] add DeviceRole type, and IsChild, IsRouter, etc method
  src/core/api/link_api.cpp
  src/core/api/network_time_api.cpp
  src/core/api/thread_api.cpp
  src/core/api/thread_ftd_api.cpp
  src/core/backbone_router/local.cpp
  src/core/common/instance.cpp
  src/core/common/settings.cpp
  src/core/mac/data_poll_handler.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/meshcop_leader.cpp
  src/core/thread/announce_sender.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_types.hpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_diagnostic.cpp
  src/core/thread/router_table.cpp
  src/core/thread/time_sync_service.cpp
  src/core/utils/channel_manager.cpp
  src/core/utils/child_supervision.cpp
  src/core/utils/jam_detector.cpp
Labels: P4, cla: yes, comp: mle, enhancement

#4648 [harness-automation] fix case selection issue when using Chrome 80
  tools/harness-automation/autothreadharness/harness_case.py
Labels: P4, bug, cla: yes

#4805 [network-data-notifier] fix flag for child removed notification
  src/core/thread/network_data_notifier.cpp
Labels: P3, bug, cla: yes

#4803 [mbedtls] leverage cmake provided by mbedtls
  examples/platforms/cc1352/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/core/CMakeLists.txt
  src/ncp/CMakeLists.txt
  third_party/mbedtls/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#4802 [network-data] adopt const for methods, parameters, and local vars
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/meshcop.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data.hpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader.hpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_data_local.hpp
  src/core/thread/network_data_tlvs.hpp
Labels: P4, cla: yes, enhancement

#4806 [network-data] simplify ServiceTlv
  src/core/backbone_router/leader.cpp
  src/core/backbone_router/local.cpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_data_tlvs.hpp
Labels: P4, cla: yes, enhancement

#4782 [ip6] disable security for link-local packets from unsecure ports
  Android.mk
  src/core/config/ip6.h
  src/core/net/ip6.cpp
  src/core/net/ip6_filter.cpp
  src/core/net/ip6_filter.hpp
Labels: P4, cla: yes, enhancement

#4793 [bbr] support domain prefix addition and removal
  include/openthread/backbone_router_ftd.h
  include/openthread/netdata.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/backbone_router_ftd_api.cpp
  src/core/api/border_router_api.cpp
  src/core/backbone_router/local.cpp
  src/core/backbone_router/local.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data.cpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_data_local.hpp
  src/core/thread/network_data_tlvs.hpp
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/v1_2_test_backbone_router_service.py
Labels: P3, Thread 1.2, cla: yes

#4809 [logging] dynamic level enhancements
  .github/workflows/simulation.yml
  etc/cmake/options.cmake
  include/openthread/logging.h
  script/test
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/logging_api.cpp
  src/core/common/instance.hpp
  tests/scripts/expect/log-level.exp
Labels: P4, api: user, cla: yes, comp: cli, enhancement

#4811 [address-resolver] use RLOC dest when send `a/ae` to child
  src/core/thread/address_resolver.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
Labels: P3, bug, cla: yes

#4820 [notifier] add string for flags newly introduced
  src/core/common/notifier.cpp
Labels: P4, Thread 1.2, cla: yes, enhancement

#4822 [ip6] fix remove unsecure port behavior
  src/core/net/ip6.cpp
Labels: P3, bug, cla: yes

#4815 [domain] add domain name
  include/openthread/thread.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/thread_api.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.hpp
  src/core/mac/mac_types.cpp
  src/core/mac/mac_types.hpp
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  tests/unit/test_mac_frame.cpp
Labels: P4, Thread 1.2, cla: yes

#4831 [qpg6095] fix license header typo in settings.cpp
  examples/platforms/qpg6095/settings.cpp
Labels: P4, cla: yes, platform: qpg6095

#4821 [meshcop] avoid unnecessary `RemoveUnsecurePort`
  src/core/meshcop/joiner_router.cpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#4795 [bbr] (Un)Subscribe AllDomainBBRs multicast address
  src/core/backbone_router/leader.cpp
  src/core/backbone_router/leader.hpp
  src/core/backbone_router/local.cpp
  src/core/backbone_router/local.hpp
  src/core/net/ip6_address.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/v1_2_test_backbone_router_service.py
Labels: P3, Thread 1.2, cla: yes

#4819 [logging] add bbr region
  etc/cmake/options.cmake
  examples/common-switches.mk
  include/openthread/platform/logging.h
  src/core/backbone_router/leader.cpp
  src/core/backbone_router/leader.hpp
  src/core/backbone_router/local.cpp
  src/core/backbone_router/local.hpp
  src/core/common/logging.hpp
  src/core/config/logging.h
  src/lib/spinel/spinel.h
  src/ncp/ncp_base.cpp
Labels: P3, Thread 1.2, cla: yes

#4830 [network-data] define and use a common Iterate method for all entry types
  src/core/thread/network_data.cpp
  src/core/thread/network_data.hpp
Labels: P4, cla: yes, enhancement

#4832 [ip6-address] methods to set address to common multicast addresses
  src/core/net/dhcp6_client.cpp
  src/core/net/ip6.cpp
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  src/core/net/netif.hpp
  src/core/thread/address_resolver.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, enhancement

#4775 [cmake] disable -pedantic-errors together with -Werror
  CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#4839 [ip6] add check before adding or removing the unsecure port
  include/openthread/ip6.h
  src/core/net/ip6_filter.cpp
  src/core/net/ip6_filter.hpp
Labels: P4, cla: yes, enhancement

#4838 [key-manager] add helper method
  src/core/mac/mac.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/thread/key_manager.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, enhancement

#4841 [ip6-address] helper methods to set Link-Local and RLOC/ALOC addresses
  src/core/coap/coap.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dhcp6_server.hpp
  src/core/net/icmp6.cpp
  src/core/net/ip6.cpp
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  src/core/thread/lowpan.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data_leader_ftd.cpp
Labels: P4, cla: yes, enhancement

#4840 [random] use crypto RNG in places where non-trival random is required
  src/core/coap/coap_message.cpp
  src/core/mac/mac_types.cpp
  src/core/mac/mac_types.hpp
  src/core/net/dhcp6_client.cpp
  src/core/thread/mle.cpp
  src/core/utils/slaac_address.cpp
Labels: P4, cla: yes, enhancement

#4846 [samr21] fix build when logging is enabled
  examples/platforms/samr21/logging.c
Labels: P3, bug, cla: yes, comp: build, platform: samr21

#4826 [mac-frame] enhance utility functions
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  tests/unit/test_mac_frame.cpp
Labels: P3, cla: yes, enhancement

#4843 [network-data] validate Prefix and Service TLVs have sub-TLVs
  src/core/thread/network_data_leader_ftd.cpp
Labels: P4, cla: yes, enhancement

#4844 [dataset] multiple enhancements (add Type, rename to GetTlv/SetTlv, etc.)
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dataset_local.cpp
  src/core/meshcop/dataset_local.hpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/joiner_router.cpp
  src/posix/platform/radio_spinel.cpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#4848 [logging] fix compile error for BBR region
  src/core/common/logging.hpp
Labels: P3, Thread 1.2, bug, cla: yes

#4851 [github-actions] use matrix for gcc builds
  .github/workflows/build.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#4853 [tests] add cli pskc command test
  tests/scripts/expect/pskc.exp
Labels: P4, cla: yes, continuous-integration

#4829 [continuous-integration] move android check to GitHub Actions
  .github/workflows/build.yml
  .travis/before_install.sh
  .travis/check-android-build
  .travis/script.sh
  .travis/test_multicast_join.py
  CONTRIBUTING.md
  README.md
  script/check-android-build
  script/check-posix-pty
  tests/scripts/misc/test_multicast_join.py
  tests/toranj/README.md
Labels: P4, cla: yes, continuous-integration, enhancement

#4834 [mle] REED to handle rejected ADDR_SOL.rsp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router.hpp
  src/core/thread/network_data_local.cpp
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/test_reed_address_solicit_rejected.py
Labels: P3, cla: yes, comp: mle, enhancement

#4857 [docs] update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: P4, cla: yes, comp: docs

#4852 [docker] add docker file for android check
  etc/docker/android-trusty/Dockerfile
Labels: P4, cla: yes, continuous-integration, enhancement

#4855 [network-data] fix length overflow in ServiceTlv::IsValid()
  src/core/thread/network_data_tlvs.hpp
Labels: P4, bug, cla: yes

#4804 [posix] open netif fds with O_NONBLOCK in a compatible way
  src/posix/platform/misc.cpp
  src/posix/platform/netif.cpp
  src/posix/platform/platform-posix.h
  src/posix/platform/uart.cpp
  src/posix/platform/udp.cpp
  src/posix/platform/virtual_time.cpp
Labels: cla: yes, enhancement, platform: posix

#4842 [cmake] enable running simulation unit tests using cmake
  CMakeLists.txt
  script/test
  tests/CMakeLists.txt
  tests/unit/CMakeLists.txt
Labels: P4, cla: yes, comp: build, continuous-integration

#4864 [nrf52811] use the default heap size to save RAM
  examples/platforms/nrf528xx/nrf52811/openthread-core-nrf52811-config.h
Labels: P3, cla: yes, enhancement, platform: nrf52811

#4856 [dataset] add GetTlv<Type>(), and SetTlv() for simple TLVs
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dataset_local.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager_ftd.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/thread/network_data_leader.cpp
Labels: P4, cla: yes, enhancement

#4867 [joiner] fix code coverage typo
  src/core/meshcop/joiner.cpp
Labels: P4, cla: yes

#4866 [size-report] support local check
  .github/workflows/size.yml
  script/bootstrap
  script/check-size
Labels: P4, cla: yes, continuous-integration, enhancement

#4865 [platform] fix errno undefined on some libc
  src/lib/platform/exit_code.c
Labels: P4, cla: yes, comp: build

#4871 [posix] use enumerations for RCP bus
  Android.mk
  src/posix/Makefile-posix
  src/posix/main.c
  src/posix/platform/CMakeLists.txt
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/hdlc_interface.hpp
  src/posix/platform/openthread-posix-config.h
  src/posix/platform/radio.cpp
  src/posix/platform/spi_interface.cpp
  src/posix/platform/spi_interface.hpp
  tests/toranj/openthread-core-toranj-config-posix.h
Labels: P4, cla: yes, enhancement, platform: posix

#4617 [cc1352,cc26xx] fix unaligned access of ext address in radio.c
  examples/platforms/cc1352/radio.c
  examples/platforms/cc2650/radio.c
  examples/platforms/cc2652/radio.c
  examples/platforms/utils/encoding.h
Labels: P3, bug, cla: yes, platform: cc1352, platform: cc2652

#4868 [cli] add `factoryreset` for Joiner in README_COMMISSIONING.md
  src/cli/README_COMMISSIONING.md
Labels: cla: yes, comp: cli, comp: docs, comp: meshcop

#4849 [efr32] update NVM3 to use default instance
  examples/platforms/efr32mg12/efr32mg12.ld
  examples/platforms/efr32mg12/flash.c
  examples/platforms/efr32mg13/efr32mg13.ld
  examples/platforms/efr32mg13/flash.c
  examples/platforms/efr32mg21/efr32mg21.ld
  examples/platforms/efr32mg21/flash.c
  third_party/silabs/Makefile.am
Labels: P3, cla: yes, enhancement, platform: efr32

#4880 [pretty] fix yapf version to 0.29.0
  .github/workflows/build.yml
  CONTRIBUTING.md
  STYLE_GUIDE.md
  script/bootstrap
Labels: P1, cla: yes, continuous-integration

#4882 [cli] fix infinite loop on networkdiagnostic
  src/core/thread/network_diagnostic.cpp
Labels: P4, bug, cla: yes, comp: cli

#4837 [mle] 1.2 MED registers MA (scope > 3) to its parent via AR TLV
  src/core/thread/mle.cpp
  src/core/thread/topology.hpp
  tests/scripts/thread-cert/command.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/v1_2_test_multicast_registration.py
Labels: P3, Thread 1.2, cla: yes

#4876 [cmake] enhancements for supporting cmake in ot-br-posix
  .github/workflows/build.yml
  CMakeLists.txt
  etc/cmake/options.cmake
  script/test
Labels: P4, cla: yes, comp: build, enhancement

#4089 [thread-cert] use the same mesh local prefix as Thread harness
  tests/scripts/thread-cert/Cert_5_2_04_REEDUpgrade.py
  tests/scripts/thread-cert/Cert_5_3_11_AddressQueryTimeoutIntervals.py
  tests/scripts/thread-cert/Cert_6_4_02_RealmLocal.py
  tests/scripts/thread-cert/Cert_9_2_13_EnergyScan.py
  tests/scripts/thread-cert/Cert_9_2_14_PanIdQuery.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
Labels: P4, certification, cla: yes, continuous-integration, enhancement

#4888 [dataset] misc enhancements
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dataset_local.cpp
  src/core/meshcop/dataset_manager.cpp
Labels: P4, cla: yes, enhancement

#4889 [mac] fix warning in mac_types.hpp
  src/core/mac/mac_types.hpp
Labels: P4, cla: yes, comp: build

#4890 [diag] initialize tx power and channel on start
  src/core/diags/factory_diags.cpp
Labels: P4, cla: yes, enhancement

#4891 [test] allow extra options
  script/test
Labels: P4, cla: yes, comp: build, enhancement

#4892 [cmake] detect big endian
  CMakeLists.txt
  etc/cmake/options.cmake
  examples/platforms/cc1352/CMakeLists.txt
  examples/platforms/cc1352/arm-none-eabi.cmake
  examples/platforms/cc2538/CMakeLists.txt
  examples/platforms/cc2538/arm-none-eabi.cmake
  examples/platforms/cc2650/CMakeLists.txt
  examples/platforms/cc2650/arm-none-eabi.cmake
  examples/platforms/cc2652/CMakeLists.txt
  examples/platforms/cc2652/arm-none-eabi.cmake
  examples/platforms/kw41z/CMakeLists.txt
  examples/platforms/kw41z/arm-none-eabi.cmake
  examples/platforms/qpg6095/CMakeLists.txt
  examples/platforms/qpg6095/arm-none-eabi.cmake
  examples/platforms/samr21/CMakeLists.txt
  examples/platforms/samr21/arm-none-eabi.cmake
Labels: P4, cla: yes, comp: build, enhancement

#4901 [style] remove const from uint16_t function/method params
  examples/platforms/cc1352/radio.c
  examples/platforms/cc2538/radio.c
  examples/platforms/cc2650/radio.c
  examples/platforms/cc2652/radio.c
  examples/platforms/gp712/radio.c
  examples/platforms/gp712/radio_qorvo.h
  examples/platforms/jn5189/radio.c
  examples/platforms/kw41z/radio.c
  examples/platforms/nrf528xx/src/radio.c
  examples/platforms/qpg6095/radio.c
  examples/platforms/qpg6095/radio_qorvo.h
  examples/platforms/samr21/radio.c
  src/core/api/link_raw_api.cpp
  src/lib/spinel/radio_spinel.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  tests/fuzz/fuzzer_platform.cpp
  tests/unit/test_platform.cpp
Labels: P4, cla: yes, enhancement

#4887 [mac-frame] helper methods to calculate size of headers/MIC
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
Labels: P4, cla: yes, enhancement

#4898 [address-resolver] fix ADDR_NTF.ans to use Child's Mesh Local IID
  src/core/thread/address_resolver.cpp
  src/core/thread/topology.hpp
Labels: P3, bug, cla: yes

#4893 [bbr] move bbr relative addresses to BackboneRouter::Local
  src/core/backbone_router/leader.cpp
  src/core/backbone_router/local.cpp
  src/core/backbone_router/local.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
Labels: P3, Thread 1.2, cla: yes, enhancement

#4850 [tests] add Thread 1.2 all features build test
  script/check-simulation-build-autotools
Labels: P4, Thread 1.2, cla: yes, continuous-integration, enhancement

#4812 [cmake] enable user specified mbedtls target
  CMakeLists.txt
  etc/cmake/options.cmake
  examples/platforms/cc1352/CMakeLists.txt
  examples/platforms/cc2650/CMakeLists.txt
  examples/platforms/cc2652/CMakeLists.txt
  examples/platforms/qpg6095/CMakeLists.txt
  examples/platforms/samr21/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/core/CMakeLists.txt
  src/ncp/CMakeLists.txt
  tests/unit/CMakeLists.txt
  third_party/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#4663 [tests] add 5_7_01 network diagnostic test cases
  tests/scripts/thread-cert/Cert_5_7_01_CoapDiagCommands_A.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/network_diag.py
  tests/scripts/thread-cert/node.py
Labels: P4, cla: yes, continuous-integration, enhancement

#4885 [build] fix warnings for ti-cgt
  src/cli/cli_coap.cpp
  src/core/api/thread_ftd_api.cpp
  src/core/coap/coap.cpp
  src/core/config/openthread-core-config-check.h
  src/core/mac/data_poll_handler.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac_frame.cpp
  src/core/mac/sub_mac.cpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/joiner.cpp
  src/core/thread/indirect_sender.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_data_notifier.cpp
  src/core/thread/network_diagnostic.cpp
  src/lib/spinel/spinel.c
  src/lib/spinel/spinel_buffer.cpp
  src/ncp/ncp_base.cpp
Labels: P4, cla: yes, enhancement

#4664 [posix] refactoring of netif code, mostly to accommodate BSDs
  src/posix/platform/netif.cpp
Labels: P4, cla: yes, enhancement, platform: posix

#4906 [continuous-integration] add macos posix build check
  .github/workflows/build.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#4908 [docs] update Doxygen menu for OTNS and BBR
  doc/ot_api_doc.h
Labels: cla: yes, comp: docs

#4899 [commissioner] fix duplicate commissioner start
  src/core/meshcop/commissioner.cpp
Labels: P4, bug, cla: yes

#4903 [mac] disable SubMac on instance finalization
  src/core/common/instance.cpp
  src/core/mac/mac.cpp
Labels: P3, bug, cla: yes

#4905 [mac] verify that Security Level is correct in rx frame
  src/core/mac/mac.cpp
Labels: P4, cla: yes, enhancement

#4907 [dataset-manager] adding DatasetTlv (a generic Dataset TLV to read from msg)
  src/core/meshcop/dataset_manager.hpp
  src/core/meshcop/dataset_manager_ftd.cpp
Labels: P4, cla: yes, enhancement

#4911 [continuous-integration] recover verbose check
  .github/workflows/simulation.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#4875 [cmake] move cc1352 & cc2652 libs to third-party cmake file
  examples/platforms/cc1352/CMakeLists.txt
  examples/platforms/cc2652/CMakeLists.txt
  third_party/CMakeLists.txt
  third_party/ti/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement, platform: cc1352, platform: cc2652

#4902 [commissioner] remove duplicate MGMT_COMMISSISONER_SET.req
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, enhancement

#4916 [test] fix script/test on macOS
  script/test
Labels: P3, bug, cla: yes, comp: build

#4917 [toranj] fix typos
  tests/toranj/test-001-get-set.py
  tests/toranj/test-031-meshcop-joiner-commissioner.py
Labels: P4, cla: yes, continuous-integration, enhancement

#4914 [cmake] add log output option
  CMakeLists.txt
  examples/apps/cli/CMakeLists.txt
  examples/apps/ncp/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#4915 [instance] fix multiple instance compilation
  .github/workflows/simulation.yml
  etc/cmake/options.cmake
  examples/common-switches.mk
  src/core/common/instance.cpp
  src/core/common/instance.hpp
Labels: P3, bug, cla: yes
