Repository openthread/openthread, pull requests merged in 2020-12, with the labels that each got.

#5885 [low-power] remove obsolete CSL functions
  src/core/mac/sub_mac.cpp
  src/core/mac/sub_mac.hpp
Labels: Thread 1.2, cla: yes, enhancement

#5890 [radio-spinel] simplify 'Request()'
  src/lib/spinel/radio_spinel.hpp
  src/lib/spinel/radio_spinel_impl.hpp
Labels: P4, cla: yes, enhancement, platform: posix

#5872 [mle] let the command `partitionid` return the current partition id
  include/openthread/instance.h
  include/openthread/thread_ftd.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/thread_ftd_api.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_ftd.cpp
  tests/scripts/expect/cli-partitionid.exp
  tests/scripts/thread-cert/Cert_5_5_03_SplitMergeChildren.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/thread_cert.py
  tests/toranj/openthread-core-toranj-config.h
  tools/harness-thci/OpenThread.py
Labels: P3, bug, cla: yes, comp: mle

#5893 [dua] delay DUA registration to avoid transmission failure
  src/core/thread/dua_manager.cpp
  src/core/thread/dua_manager.hpp
Labels: P4, Thread 1.2, cla: yes, enhancement

#5861 [github-actions] upload core dump, so libs and binaries for crashed programs
  .github/workflows/simulation-1.2.yml
  CONTRIBUTING.md
  script/test
Labels: P4, cla: yes, continuous-integration, enhancement

#5813 [thread-cert] refactor case 5.3.6 using pktverify
  tests/scripts/thread-cert/Cert_5_3_06_RouterIdMask.py
  tests/scripts/thread-cert/Cert_5_3_06b_RouterIdMask.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/pktverify/layer_fields.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5894 [backbone-router] fix otBackboneRouterMulticastListenerGetNext missing
  include/openthread/backbone_router_ftd.h
  include/openthread/instance.h
  src/core/api/backbone_router_ftd_api.cpp
  src/core/backbone_router/multicast_listeners_table.cpp
  src/core/backbone_router/multicast_listeners_table.hpp
Labels: P4, cla: yes, comp: backbone-router

#5884 [border-router] move configuration check from api to inner class
  src/core/api/border_router_api.cpp
  src/core/thread/network_data_local.cpp
Labels: P4, cla: yes, enhancement

#5850 [thread-cert] add case 6.1.4 REEDAttachConnectivity using pktverify
  tests/scripts/thread-cert/Cert_6_1_04_REEDAttachConnectivity.py
  tests/scripts/thread-cert/Makefile.am
Labels: P4, cla: yes, continuous-integration, enhancement

#5855 [thread-cert] refactor case 7.1.1 using pktverify
  tests/scripts/thread-cert/Cert_7_1_01_BorderRouterAsLeader.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5823 [thread-cert] refactor case 5.3.9 using pktverify
  tests/scripts/thread-cert/Cert_5_3_09_AddressQuery.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5827 [thread-cert] refactor case 5.5.1 using pktverify
  tests/scripts/thread-cert/Cert_5_5_01_LeaderReboot.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5834 [thread-cert] refactor case 5.7.1 using pktverify
  tests/scripts/thread-cert/Cert_5_7_01_CoapDiagCommands.py
  tests/scripts/thread-cert/Cert_5_7_01_CoapDiagCommands_A.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_verifier.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5905 [efr32] remove -nostartfiles to use Newlib _start
  examples/Makefile-efr32mg1
  examples/Makefile-efr32mg12
  examples/Makefile-efr32mg13
  examples/Makefile-efr32mg21
  third_party/silabs/Makefile.am
Labels: cla: yes, comp: build, platform: efr32

#5892 [thread-cert] fix 5.3.3 random fail by small chance
  tests/scripts/thread-cert/Cert_5_3_03_AddressQuery.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
Labels: P4, bug, certification, cla: yes, continuous-integration

#5902 [udp6] initialize Socket variables in its constructor
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
Labels: P3, bug, cla: yes

#5888 [style] simplify build paths
  .github/workflows/posix.yml
  .github/workflows/simulation.yml
  examples/Makefile-simulation
  script/check-ncp-rcp-migrate
  script/check-posix-pty
  script/test
  src/posix/Makefile-posix
  src/posix/README.md
Labels: P4, cla: yes, comp: build, enhancement

#5908 [diag] check state before entering diagnostic mode
  src/core/diags/factory_diags.cpp
  tests/scripts/expect/cli-misc.exp
Labels: P4, cla: yes, enhancement

#5895 [android] remove settings storage path from config file
  include/openthread-config-android.h
Labels: P3, cla: yes, comp: build, enhancement

#5906 [dataset] implement ChannelMaskTlv::IsValid()
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/meshcop/meshcop_tlvs.hpp
Labels: P4, cla: yes, enhancement

#5778 [github-actions] remove coverage artifacts after uploading
  .github/workflows/posix.yml
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  .github/workflows/toranj.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#5907 [cc1352,cc26xx] add C++ constructor calls
  third_party/ti/README.md
  third_party/ti/devices/cc13x2_cc26x2/startup_files/startup_gcc.c
  third_party/ti/devices/cc26x0/linker_files/cc26x0f128.lds
  third_party/ti/devices/cc26x0/startup_files/startup_gcc.c
Labels: P3, bug, cla: yes, platform: cc1352, platform: cc2652

#5899 [github-actions] add dependent PR support
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  .github/workflows/toranj.yml
  script/git-tool
  script/test
Labels: P4, cla: yes, continuous-integration, enhancement

#5867 [radio] send max power table to radio
  examples/platforms/simulation/radio.c
  include/openthread/instance.h
  include/openthread/platform/radio.h
  src/core/radio/max_power_table.hpp
  src/core/radio/radio_platform.cpp
  src/lib/spinel/radio_spinel.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  src/lib/spinel/spinel.c
  src/lib/spinel/spinel.h
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_dispatcher.cpp
  src/posix/platform/radio.cpp
  tests/scripts/expect/posix-max-power-table.exp
Labels: P3, api: platform, cla: yes, comp: rcp, enhancement

#5891 [backbone-router] add build options for Backbone Router features
  etc/cmake/options.cmake
  script/check-simulation-build-cmake
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/backbone_router_ftd_api.cpp
  src/core/api/thread_ftd_api.cpp
  src/core/backbone_router/bbr_leader.cpp
  src/core/backbone_router/bbr_manager.cpp
  src/core/backbone_router/bbr_manager.hpp
  src/core/backbone_router/multicast_listeners_table.cpp
  src/core/backbone_router/multicast_listeners_table.hpp
  src/core/backbone_router/ndproxy_table.cpp
  src/core/backbone_router/ndproxy_table.hpp
  src/core/common/instance.hpp
  src/core/config/backbone_router.h
  src/core/net/ip6.cpp
  src/core/thread/address_resolver.cpp
  tests/unit/test_multicast_listeners_table.cpp
  tests/unit/test_ndproxy_table.cpp
Labels: cla: yes, comp: backbone-router, comp: build, enhancement

#5916 [github-actions] update binaries path in upload action
  .github/workflows/simulation-1.2.yml
Labels: P3, cla: yes, comp: build, continuous-integration

#5921 [mac] stop timer before starting non-idle operation
  src/core/mac/mac.cpp
Labels: P1, Thread 1.2, bug, certification, cla: yes

#5912 [thread-cert] fix case 5.3.6 issue #5909
  tests/scripts/thread-cert/Cert_5_3_06_RouterIdMask.py
Labels: P4, bug, cla: yes, continuous-integration

#5923 [build] remove FTD/MTD/RADIO from core config file
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/ip6_api.cpp
  src/core/backbone_router/bbr_leader.cpp
  src/core/common/instance.hpp
  src/core/common/notifier.cpp
  src/core/common/time_ticker.cpp
  src/core/config/mac.h
  src/core/config/openthread-core-config-check.h
  src/core/config/tmf.h
  src/core/mac/data_poll_handler.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/sub_mac.cpp
  src/core/mac/sub_mac.hpp
  src/core/thread/csl_tx_scheduler.cpp
  src/core/thread/csl_tx_scheduler.hpp
  src/core/thread/dua_manager.cpp
  src/core/thread/dua_manager.hpp
  src/core/thread/indirect_sender.cpp
  src/core/thread/indirect_sender.hpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_tlvs.hpp
  src/core/thread/mlr_manager.cpp
  src/core/thread/mlr_manager.hpp
  src/core/thread/mlr_types.hpp
  src/core/thread/neighbor_table.cpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
  src/core/thread/topology.cpp
  src/core/thread/topology.hpp
Labels: P4, Thread 1.2, cla: yes, comp: build, enhancement

#5859 [thread-cert] refactor case 7.1.3 using pktverify
  tests/scripts/thread-cert/Cert_7_1_03_BorderRouterAsLeader.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5920 [test] separate code coverage data files
  .github/workflows/posix.yml
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  script/gcda-tool
  script/test
  tests/scripts/expect/_common.exp
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/node.py
Labels: P4, cla: yes, continuous-integration

#5917 [efr32] add missing bytes to sleepy-demo masterkey
  examples/platforms/efr32/sleepy-demo/sleepy-demo-ftd/main.c
  examples/platforms/efr32/sleepy-demo/sleepy-demo-mtd/main.c
Labels: cla: yes, platform: efr32

#5868 [thread-cert] add case 7.1.6 BorderRouterAsLeader using pktverify
  tests/scripts/thread-cert/Cert_7_1_06_BorderRouterAsLeader.py
  tests/scripts/thread-cert/Makefile.am
Labels: P4, cla: yes, continuous-integration, enhancement

#5882 [thread-cert] refactor case 7.1.5 using pktverfiy
  tests/scripts/thread-cert/Cert_7_1_05_BorderRouterAsRouter.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5869 [thread-cert] add case 7.1.8 BorderRouterAsFED using pktverify
  tests/scripts/thread-cert/Cert_7_1_08_BorderRouterAsFED.py
  tests/scripts/thread-cert/Makefile.am
Labels: P4, cla: yes, continuous-integration, enhancement

#5925 [dua] delay registration for DUA newly added
  src/core/backbone_router/bbr_manager.cpp
  src/core/thread/dua_manager.cpp
  src/core/thread/dua_manager.hpp
Labels: P2, Thread 1.2, cla: yes

#5922 [dns] add helper methods to append/parse DNS names
  Android.mk
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/common/string.cpp
  src/core/common/string.hpp
  src/core/net/dns_client.cpp
  src/core/net/dns_client.hpp
  src/core/net/dns_headers.cpp
  src/core/net/dns_headers.hpp
  tests/toranj/openthread-core-toranj-config.h
  tests/unit/CMakeLists.txt
  tests/unit/Makefile.am
  tests/unit/test_dns.cpp
  tests/unit/test_string.cpp
Labels: P4, cla: yes, comp: dns, enhancement

#5883 [thread-cert] refactor case 8.1.1 using pktverify
  tests/scripts/thread-cert/Cert_8_1_01_Commissioning.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_verifier.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5910 [tmf] TMF not to use platform udp
  script/check-posix-pty
  src/core/net/ip6.cpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
Labels: bug, cla: yes, platform: posix, security

#5852 [scripts] test multicast routing across Thread and Backbone
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
  tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_across_thread_pans.py
  tests/scripts/thread-cert/mcast6.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/bytes.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
Labels: Thread 1.2, cla: yes, comp: backbone-router, continuous-integration, enhancement

#5886 [thread-cert] refactor case 6.5.2 using pktverify
  tests/scripts/thread-cert/Cert_6_5_02_ChildResetReattach.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5933 [github-actions] upload core dumps for expects tests
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  script/test
Labels: P4, cla: yes, continuous-integration, enhancement

#5932 [efr32] radio: fix otPlatRadioGetTransmitPower
  examples/platforms/efr32/src/radio.c
Labels: bug, cla: yes, platform: efr32

#5929 [meshcop-tlvs] fix ChannelMaskBaseTlv::IsValid()
  src/core/meshcop/meshcop_tlvs.cpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5780 [low-power] implement enhanced-ack based probing
  examples/platforms/nrf528xx/src/radio.c
  examples/platforms/simulation/radio.c
  examples/platforms/utils/CMakeLists.txt
  examples/platforms/utils/Makefile.am
  examples/platforms/utils/link_metrics.cpp
  examples/platforms/utils/link_metrics.h
  examples/platforms/utils/mac_frame.cpp
  examples/platforms/utils/mac_frame.h
  include/openthread/instance.h
  include/openthread/link_metrics.h
  include/openthread/platform/radio.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/link_metrics_api.cpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.cpp
  src/core/mac/mac_frame.hpp
  src/core/radio/radio.hpp
  src/core/thread/link_metrics.cpp
  src/core/thread/link_metrics.hpp
  src/core/thread/link_metrics_tlvs.hpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/topology.hpp
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
  tests/scripts/thread-cert/v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks.py
  tests/unit/test_platform.cpp
Labels: P3, Thread 1.2, api: platform, api: user, cla: yes, enhancement, platform: simulation

#5936 [devsite] migrate Porting guide to GitHub
  doc/site/en/guides/porting/_toc.yaml
  doc/site/en/guides/porting/certification-and-readme.md
  doc/site/en/guides/porting/implement-advanced-features.md
  doc/site/en/guides/porting/implement-platform-abstraction-layer-apis.md
  doc/site/en/guides/porting/index.md
  doc/site/en/guides/porting/set-up-the-build-environment.md
  doc/site/en/guides/porting/validate-the-port.md
Labels: cla: yes, comp: docs

#5904 [thread-cert] add case 8.3.1 CommissionerPetition using pktverify
  tests/scripts/thread-cert/Cert_5_6_06_NetworkDataExpiration.py
  tests/scripts/thread-cert/Cert_5_6_09_NetworkDataForwarding.py
  tests/scripts/thread-cert/Cert_8_3_01_CommissionerPetition.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5935 [posix] add error logs in trel platform implementation under posix
  src/posix/platform/trel_udp6.cpp
Labels: P4, cla: yes, comp: trel, enhancement, platform: posix

#5937 [tests] fix comparison in test_cmd_line_parser
  tests/unit/test_cmd_line_parser.cpp
Labels: P4, bug, cla: yes, continuous-integration

#5943 [mac-links] fix setting Ext Address on TREL link
  src/core/mac/mac_links.hpp
Labels: P2, bug, cla: yes, platform: posix

#5939 [low-power] small improvements in CSL code
  examples/platforms/nrf528xx/src/radio.c
  src/core/mac/sub_mac.hpp
  src/core/thread/csl_tx_scheduler.cpp
  src/core/thread/csl_tx_scheduler.hpp
Labels: P4, Thread 1.2, cla: yes, enhancement

#5947 [meshcop-tlv] fix ChannelMaskTlv::GetChannelMask()
  src/core/meshcop/meshcop_tlvs.cpp
Labels: P4, bug, cla: yes, comp: meshcop

#5945 [test] add 'otPlatEntropyGet()' using TRNG for unit test
  tests/unit/test_platform.cpp
Labels: P4, cla: yes, enhancement

#5946 [crypto] add 'Sha256::Hash' type
  include/openthread/crypto.h
  include/openthread/instance.h
  src/core/api/crypto_api.cpp
  src/core/crypto/hkdf_sha256.cpp
  src/core/crypto/hkdf_sha256.hpp
  src/core/crypto/hmac_sha256.cpp
  src/core/crypto/hmac_sha256.hpp
  src/core/crypto/sha256.cpp
  src/core/crypto/sha256.hpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/meshcop.cpp
  src/core/thread/key_manager.hpp
  src/core/utils/slaac_address.cpp
  tests/unit/test_hmac_sha256.cpp
Labels: P4, api: user, cla: yes, enhancement

#5948 [meshcop-tlv] fix typo with ChannelMasEntry (Note missing 'k')
  src/core/meshcop/meshcop_tlvs.cpp
Labels: bug, cla: yes, comp: meshcop

#5938 [thread-cert] add case 5.7.3 CoapDiagCommands using pktverify
  tests/scripts/thread-cert/Cert_5_7_03_CoapDiagCommands.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/utils.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5952 [thread-cert] add case 9.2.1 MGMTCommissionerGet using pktverify
  tests/scripts/thread-cert/Cert_9_2_01_MGMTCommissionerGet.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5949 [thread-cert] add case 9.2.3 ActiveDatasetGet using pktverify
  tests/scripts/thread-cert/Cert_9_2_03_ActiveDatasetGet.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5931 [thread-cert] refactor case 9.2.11 using pktveriy
  tests/scripts/thread-cert/Cert_9_2_11_MasterKey.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5953 [cli] fix typo in commissioner/joiner docs
  src/cli/cli_commissioner.hpp
  src/cli/cli_joiner.hpp
Labels: cla: yes, comp: cli, comp: docs

#5955 [backbone-router] fix build option compile issues
  src/posix/platform/backbone.cpp
  src/posix/platform/multicast_routing.cpp
  src/posix/platform/multicast_routing.hpp
Labels: Thread 1.2, cla: yes, comp: backbone-router, platform: posix

#5940 [thread-cert] add case 5.7.2 CoapDiagCommands using pktverify
  tests/scripts/thread-cert/Cert_5_7_02_CoapDiagCommands.py
  tests/scripts/thread-cert/Makefile.am
Labels: P4, cla: yes, continuous-integration, enhancement

#5951 [thread-cert] add case 9.2.19 PendingDatasetGet using pktverify
  tests/scripts/thread-cert/Cert_9_2_19_PendingDatasetGet.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5839 [posix] fix build warnings/errors on macOS
  src/posix/platform/udp.cpp
Labels: P4, bug, cla: yes, platform: posix

#5898 [thread-cert] add case 8.1.6 using pktverify
  tests/scripts/thread-cert/Cert_8_1_06_Commissioning.py
  tests/scripts/thread-cert/command.py
  tests/scripts/thread-cert/mesh_cop.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/simulator.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5957 [multi-radio] copy all TX buffers before encryption
  src/core/mac/mac.cpp
Labels: P3, bug, cla: yes, comp: trel

#5956 [link-raw] disable/enable MAC layer when link-raw is enabled/disabled
  src/core/mac/link_raw.cpp
Labels: P4, bug, cla: yes

#5960 [nrf528xx] fix sleep_to_tx transition problem
  third_party/NordicSemiconductor/drivers/radio/rsch/nrf_802154_rsch.c
Labels: P2, bug, cla: yes, platform: nrf52840

#5924 [thread-cert] add case 8.2.5 JoinerRouter using pktverify
  tests/scripts/thread-cert/Cert_8_2_05_JoinerRouter.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5959 [thread-cert] add case 9.2.5 ActiveDataset using pktverify
  tests/scripts/thread-cert/Cert_9_2_05_ActiveDataset.py
  tests/scripts/thread-cert/Makefile.am
Labels: P4, cla: yes, continuous-integration, enhancement

#5965 [spinel] fix errors in RCP recovery
  src/lib/spinel/radio_spinel_impl.hpp
  tests/scripts/expect/posix-rcp-restoration.exp
Labels: bug, cla: yes, comp: rcp

#5964 [border-agent] remove UDP receiver on commissioner disconnect
  src/core/meshcop/border_agent.cpp
Labels: P4, cla: yes, enhancement, platform: posix

#5966 [dataset] do not allow Extended TLVs in Operational Dataset
  src/core/meshcop/dataset.cpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5962 [thread-cert] refactor case 9.2.9 using pktverify
  tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
  tests/scripts/thread-cert/Cert_9_2_05_ActiveDataset.py
  tests/scripts/thread-cert/Cert_9_2_07_DelayTimer.py
  tests/scripts/thread-cert/Cert_9_2_08_PersistentDatasets.py
  tests/scripts/thread-cert/Cert_9_2_09_PendingPartition.py
  tests/scripts/thread-cert/Cert_9_2_17_Orphan.py
  tests/scripts/thread-cert/Cert_9_2_18_RollBackActiveTimestamp.py
  tests/scripts/thread-cert/Cert_9_2_19_PendingDatasetGet.py
  tests/scripts/thread-cert/backbone/test_dua_dad.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/test_layer_fields.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5968 [github-actions] enable full logs in expect tests
  .github/workflows/simulation.yml
Labels: cla: yes, continuous-integration, enhancement

#5954 [crypto] add ECDSA (P-256 curve) key-gen, signing, and verification
  Android.mk
  src/core/crypto/ecdsa.cpp
  src/core/crypto/ecdsa.hpp
  src/core/crypto/mbedtls.cpp
  src/core/crypto/sha256.hpp
  tests/toranj/openthread-core-toranj-config.h
  tests/unit/CMakeLists.txt
  tests/unit/Makefile.am
  tests/unit/test_ecdsa.cpp
  third_party/mbedtls/Makefile.am
  third_party/mbedtls/mbedtls-config.h
Labels: P4, cla: yes, enhancement

#5967 [thread-cert] add case 5.8.4 SecurityPolicyTLV using pktverify
  tests/scripts/thread-cert/Cert_5_8_04_SecurityPolicyTLV.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/packet_filter.py
  tests/scripts/thread-cert/pktverify/utils.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5978 [diags] fix broken anchor in Diags Readme
  src/core/diags/README.md
Labels: cla: yes, comp: cli, comp: docs

#5972 [thread-cert] add case 9.2.6 DatasetDissemination using pktverify
  tests/scripts/thread-cert/Cert_9_2_06_DatasetDissemination.py
  tests/scripts/thread-cert/Makefile.am
Labels: P4, cla: yes, continuous-integration, enhancement

#5976 [thread-cert] fix case 5.1.12 intermittent failure
  tests/scripts/thread-cert/Cert_5_1_12_NewRouterNeighborSync.py
Labels: bug, cla: yes, continuous-integration

#5974 [thread-cert] fix case 7.1.6 intermittent failure
  tests/scripts/thread-cert/Cert_7_1_06_BorderRouterAsLeader.py
Labels: bug, cla: yes, continuous-integration

#5975 [thread-cert] fix case 8.3.1 intermittent failure
  tests/scripts/thread-cert/Cert_8_3_01_CommissionerPetition.py
Labels: bug, cla: yes, continuous-integration

#5881 [thread-cert] add case 7.1.7 using pktverify
  tests/scripts/thread-cert/Cert_7_1_07_BorderRouterAsLeader.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/pktverify/layer_fields.py
  tests/scripts/thread-cert/pktverify/utils.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5987 [thread-cert] relax time difference to less than 1.1 for case 5.1.13 to fix issue #5979
  tests/scripts/thread-cert/Cert_5_1_13_RouterReset.py
  tests/scripts/thread-cert/pktverify/consts.py
Labels: bug, cla: yes, continuous-integration

#5958 [harness-automation] fix the result parsed uncorrectly using Chrome 80
  tools/harness-automation/autothreadharness/harness_case.py
Labels: cla: yes, enhancement

#5961 [nrf528xx] add max power table support
  examples/platforms/nrf528xx/src/platform-nrf5.h
  examples/platforms/nrf528xx/src/radio.c
  include/openthread/instance.h
  include/openthread/platform/radio.h
Labels: cla: yes, enhancement, platform: nrf52840

#5981 [dns-client] randomize ID of outgoing query
  src/core/net/dns_client.cpp
  src/core/net/dns_client.hpp
Labels: cla: yes, comp: dns, enhancement

#5989 [ecdsa] fix ECDSA public key size for DNSKEY
  src/core/crypto/ecdsa.cpp
  src/core/crypto/ecdsa.hpp
  tests/unit/test_ecdsa.cpp
Labels: P4, cla: yes, enhancement

#5988 [heap] expand internal heap size for ECDSA
  src/core/config/openthread-core-default-config.h
Labels: P4, cla: yes, comp: build, enhancement

#5484 [doc] add description of common switches
  examples/README.md
Labels: P4, cla: yes, comp: docs, enhancement

#5996 [expect] fix CLI router tests
  tests/scripts/expect/cli-router.exp
Labels: P4, bug, cla: yes, continuous-integration

#6000 [tests] add "return" for dummy test platform API
  tests/unit/test_platform.cpp
Labels: cla: yes, continuous-integration

#5999 [radio] send radio command to the region
  examples/platforms/nrf528xx/src/platform-nrf5.h
  examples/platforms/nrf528xx/src/radio.c
  examples/platforms/simulation/radio.c
  include/openthread/instance.h
  include/openthread/platform/radio.h
  script/check-posix-pty
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/radio/radio_platform.cpp
  src/lib/spinel/radio_spinel.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  src/lib/spinel/spinel.h
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_dispatcher.cpp
  src/posix/platform/radio.cpp
  src/posix/platform/radio_url.cpp
  tests/scripts/expect/cli-region.exp
Labels: api: platform, cla: yes

#5997 [cli] router table command to output `Link`
  src/cli/README.md
  src/cli/cli.cpp
  tests/scripts/thread-cert/node.py
Labels: cla: yes, comp: cli, comp: otci, enhancement

#5911 [ip6] add filter for packets from host
  script/check-posix-pty
  src/core/net/ip6.cpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
Labels: P3, cla: yes, enhancement

#6002 [crypto] add new flavors of 'Update()' for SHA-256 and HMAC computation
  src/core/common/message.hpp
  src/core/crypto/hkdf_sha256.cpp
  src/core/crypto/hmac_sha256.cpp
  src/core/crypto/hmac_sha256.hpp
  src/core/crypto/sha256.cpp
  src/core/crypto/sha256.hpp
  src/core/meshcop/meshcop.cpp
  src/core/thread/key_manager.cpp
  src/core/utils/slaac_address.cpp
  tests/unit/test_ecdsa.cpp
  tests/unit/test_hmac_sha256.cpp
Labels: P4, cla: yes, enhancement

#5856 [border-router] initial implementation of prefix/route management
  .github/workflows/simulation-1.2.yml
  Android.mk
  etc/cmake/options.cmake
  etc/gn/openthread.gni
  examples/common-switches.mk
  include/Makefile.am
  include/openthread/BUILD.gn
  include/openthread/border_router.h
  include/openthread/icmp6.h
  include/openthread/instance.h
  include/openthread/platform/infra_if.h
  include/openthread/platform/logging.h
  script/test
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/api/border_router_api.cpp
  src/core/border_router/infra_if_platform.cpp
  src/core/border_router/router_advertisement.cpp
  src/core/border_router/router_advertisement.hpp
  src/core/border_router/routing_manager.cpp
  src/core/border_router/routing_manager.hpp
  src/core/common/instance.cpp
  src/core/common/instance.hpp
  src/core/common/logging.hpp
  src/core/common/notifier.cpp
  src/core/common/settings.cpp
  src/core/common/settings.hpp
  src/core/config/border_router.h
  src/core/config/logging.h
  src/core/config/openthread-core-config-check.h
  src/core/net/icmp6.hpp
  src/core/net/ip6_address.hpp
  src/lib/spinel/spinel.h
  src/ncp/ncp_base.cpp
  src/posix/platform/CMakeLists.txt
  src/posix/platform/Makefile.am
  src/posix/platform/infra_if.cpp
  src/posix/platform/platform-posix.h
  src/posix/platform/system.cpp
  tests/scripts/thread-cert/border_routing/test_multi_border_routers.py
  tests/scripts/thread-cert/border_routing/test_multi_thread_networks.py
  tests/scripts/thread-cert/border_routing/test_single_border_router.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/unit/test_platform.cpp
Labels: cla: yes, enhancement

#5973 [thread-cert] fix case 7.1.5 intermittent failure
  tests/scripts/thread-cert/Cert_7_1_05_BorderRouterAsRouter.py
Labels: bug, cla: yes, continuous-integration

#6009 [cli] fix typo in joiner readme doc
  src/cli/README_JOINER.md
Labels: cla: yes, comp: cli, comp: docs

#6007 [ip6] use ALOC source address
  src/core/net/ip6.cpp
  src/core/net/udp6.cpp
  tests/scripts/thread-cert/Cert_8_3_01_CommissionerPetition.py
  tests/scripts/thread-cert/Cert_9_2_01_MGMTCommissionerGet.py
  tests/scripts/thread-cert/Cert_9_2_02_MGMTCommissionerSet.py
  tests/scripts/thread-cert/Cert_9_2_03_ActiveDatasetGet.py
  tests/scripts/thread-cert/Cert_9_2_19_PendingDatasetGet.py
Labels: bug, cla: yes

#6012 [android] add missing 'ecdsa.cpp' src file in android makefile
  Android.mk
Labels: P4, cla: yes, comp: build, enhancement

#6004 [efr32] conditional definition for MBEDTLS_SSL_MAX_CONTENT_LEN
  examples/platforms/efr32/src/mbedtls_config.h
Labels: cla: yes, comp: build, platform: efr32

#6022 [low-power] fix test case Low Power 5_3_01
  tests/scripts/thread-cert/v1_2_LowPower_5_3_01_SSEDAttachment.py
Labels: P4, certification, cla: yes, continuous-integration

#6023 [nrf52811] use RTC1 instead of RTC0
  examples/platforms/nrf528xx/nrf52811/platform-config.h
Labels: P2, bug, cla: yes, platform: nrf52811

#5998 [key-manager] remove default master key
  script/check-posix-pty
  src/core/thread/key_manager.cpp
  src/core/thread/key_manager.hpp
  tests/scripts/expect/_common.exp
  tests/scripts/expect/_multinode.exp
  tests/scripts/expect/cli-big-table.exp
  tests/scripts/expect/cli-multicast-loop.exp
  tests/scripts/expect/posix-rcp-restoration.exp
  tests/scripts/expect/tun-realm-local-multicast.exp
  tests/scripts/expect/tun-udp.exp
  tests/scripts/expect/v1_2-rcp.exp
  tests/scripts/thread-cert/thread_cert.py
  tests/toranj/test-002-form.py
Labels: P4, cla: yes, enhancement

#5779 [otci] add OpenThread Controller Interface library
  .github/workflows/otci.yml
  tests/scripts/thread-cert/simulator.py
  tools/otci/LICENSE
  tools/otci/README.md
  tools/otci/otci/__init__.py
  tools/otci/otci/command_handlers.py
  tools/otci/otci/connectors.py
  tools/otci/otci/constants.py
  tools/otci/otci/errors.py
  tools/otci/otci/otci.py
  tools/otci/otci/types.py
  tools/otci/otci/utils.py
  tools/otci/setup.py
  tools/otci/tests/test_otci.py
Labels: cla: yes, comp: otci, enhancement
