Repository openthread/openthread, pull requests merged in 2020-06, with the labels that each got.

#5027 [posix] clean up for radio url
  script/check-ncp-rcp-migrate
  script/check-posix-pty
  src/posix/README.md
  src/posix/main.c
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/include/openthread/openthread-system.h
  src/posix/platform/radio_url.cpp
  src/posix/platform/radio_url.hpp
  src/posix/platform/system.cpp
  tests/scripts/expect/posix-diag-rcp.exp
  tests/scripts/expect/posix-max-power-table.exp
  tests/scripts/thread-cert/node.py
  tests/toranj/wpan.py
Labels: P3, cla: yes, enhancement, platform: posix

#5024 [ip6] forward any packet with on-mesh destination
  src/core/net/ip6.cpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
Labels: P3, bug, cla: yes

#5032 [continuous-integration] use apt-get instead of apt
  .github/workflows/build.yml
  .github/workflows/simulation.yml
  .github/workflows/toranj.yml
  etc/docker/arm32v7_ubuntu_wpantund/Dockerfile
  etc/docker/x86_ubuntu_wpantund/Dockerfile
  script/bootstrap
Labels: P4, cla: yes, enhancement

#5033 [simulation] use ACK frame generation utils
  examples/platforms/simulation/radio.c
Labels: P4, cla: yes, enhancement, platform: simulation

#4999 [low-power] encapsulate method to update header IE
  src/core/common/message.cpp
  src/core/common/message.hpp
  src/core/mac/mac.cpp
  src/core/mac/mac.hpp
  src/core/mac/mac_frame.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P3, cla: yes, enhancement

#5030 [test] cover micro timer in unittest
  tests/unit/test_platform.cpp
  tests/unit/test_platform.h
  tests/unit/test_timer.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5034 [continuous-integration] add version number check
  .github/workflows/version.yml
  script/check-api-version
Labels: P4, cla: yes, continuous-integration, enhancement

#5036 [mle] restore operational datasets when becoming leader
  src/core/thread/mle_router.cpp
Labels: P4, bug, cla: yes

#5009 [bootstrap] remove PPA on Ubuntu 20.04 and later
  script/bootstrap
Labels: P4, cla: yes, enhancement

#5037 [test] add expect tests for `child`
  tests/scripts/expect/cli-2-nodes.exp
  tests/scripts/expect/cli-ping.exp
Labels: P4, cla: yes, continuous-integration, enhancement

#5038 [tests] skip running expected fail tests
  tests/scripts/thread-cert/Cert_5_3_10_AddressQuery.py
  tests/scripts/thread-cert/Cert_5_7_01_CoapDiagCommands_A.py
  tests/scripts/thread-cert/Cert_8_1_01_Commissioning.py
  tests/scripts/thread-cert/Cert_8_1_02_Commissioning.py
  tests/scripts/thread-cert/Cert_8_2_01_JoinerRouter.py
  tests/scripts/thread-cert/Cert_8_2_02_JoinerRouter.py
  tests/scripts/thread-cert/Cert_9_2_02_MGMTCommissionerSet.py
  tests/scripts/thread-cert/Cert_9_2_04_ActiveDataset.py
  tests/scripts/thread-cert/Cert_9_2_07_DelayTimer.py
  tests/scripts/thread-cert/Cert_9_2_08_PersistentDatasets.py
  tests/scripts/thread-cert/Cert_9_2_09_PendingPartition.py
  tests/scripts/thread-cert/Cert_9_2_10_PendingPartition.py
  tests/scripts/thread-cert/Cert_9_2_11_MasterKey.py
  tests/scripts/thread-cert/Cert_9_2_12_Announce.py
  tests/scripts/thread-cert/Cert_9_2_13_EnergyScan.py
  tests/scripts/thread-cert/Cert_9_2_14_PanIdQuery.py
  tests/scripts/thread-cert/Cert_9_2_15_PendingPartition.py
  tests/scripts/thread-cert/Cert_9_2_16_ActivePendingPartition.py
  tests/scripts/thread-cert/Cert_9_2_17_Orphan.py
  tests/scripts/thread-cert/Cert_9_2_18_RollBackActiveTimestamp.py
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/test_coap_observe.py
  tests/scripts/thread-cert/test_coaps.py
  tests/scripts/thread-cert/test_diag.py
  tests/scripts/thread-cert/test_ipv6_fragmentation.py
  tests/scripts/thread-cert/test_ipv6_source_selection.py
  tests/scripts/thread-cert/test_reed_address_solicit_rejected.py
  tests/scripts/thread-cert/test_service.py
  tests/scripts/thread-cert/thread_cert.py
Labels: P4, cla: yes, continuous-integration, enhancement

#5039 [simulation] send enh-ack for 802.15.4-2015 frames
  examples/platforms/simulation/radio.c
  examples/platforms/utils/mac_frame.cpp
  src/core/mac/mac_frame.cpp
Labels: P4, Thread 1.2, cla: yes, enhancement, platform: simulation

#5044 [udp6] add method documentation for GetUdpSockets()
  src/core/net/udp6.hpp
Labels: cla: yes, comp: docs

#4976 [mac] move auxiliary frame counter from Mac to SubMac
  examples/platforms/simulation/radio.c
  include/openthread/instance.h
  include/openthread/link_raw.h
  include/openthread/platform/radio.h
  src/core/api/link_raw_api.cpp
  src/core/mac/link_raw.cpp
  src/core/mac/link_raw.hpp
  src/core/mac/mac.cpp
  src/core/mac/sub_mac.cpp
  src/core/mac/sub_mac.hpp
  src/core/mac/sub_mac_callbacks.cpp
  src/core/radio/radio.hpp
  src/core/radio/radio_platform.cpp
  src/core/thread/key_manager.cpp
  src/core/thread/key_manager.hpp
  src/lib/spinel/radio_spinel.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  src/lib/spinel/spinel.h
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_radio.cpp
  src/posix/platform/radio.cpp
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/test_reset.py
Labels: P3, Thread 1.2, api: platform, api: user, cla: yes

#5043 [test] add expect tests for pcap receiving
  src/cli/cli.cpp
  tests/scripts/expect/cli-2-nodes.exp
Labels: P4, cla: yes, continuous-integration, enhancement

#5045 [posix] fix uart-baudrate argument of radio url
  src/posix/platform/hdlc_interface.cpp
Labels: P3, bug, cla: yes, platform: posix

#5040 [meshcop] adding SteeringData class
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/meshcop.cpp
  src/core/meshcop/meshcop.hpp
  src/core/meshcop/meshcop_tlvs.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle.hpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router.hpp
  tests/unit/CMakeLists.txt
  tests/unit/Makefile.am
  tests/unit/test_steering_data.cpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5046 [radio-url] GetValue once and add missing doc
  src/posix/platform/hdlc_interface.cpp
  src/posix/platform/radio_url.cpp
  src/posix/platform/spi_interface.cpp
Labels: P4, cla: yes, enhancement, platform: posix

#5048 [posix] use os defined macros
  configure.ac
  examples/platforms/gp712/uart-posix.c
  examples/platforms/simulation/uart.c
  src/core/common/debug.hpp
Labels: P4, cla: yes, comp: build, enhancement, platform: posix, platform: simulation

#5049 [tests] add dns client tests
  .github/workflows/simulation.yml
  script/test
  tests/scripts/expect/tun-dns-client.exp
Labels: P4, cla: yes, continuous-integration, enhancement

#5050 [timer] use function reference (instead of pointer) as timer handler
  src/cli/cli.cpp
  src/core/coap/coap.cpp
  src/core/common/timer.hpp
  src/core/common/trickle_timer.cpp
  src/core/mac/data_poll_sender.cpp
  src/core/mac/mac.cpp
  src/core/mac/sub_mac.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dtls.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner_router.cpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dns_client.cpp
  src/core/net/ip6.cpp
  src/core/net/ip6_mpl.cpp
  src/core/net/sntp_client.cpp
  src/core/thread/address_resolver.cpp
  src/core/thread/announce_begin_server.cpp
  src/core/thread/announce_sender.cpp
  src/core/thread/energy_scan_server.cpp
  src/core/thread/key_manager.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_notifier.cpp
  src/core/thread/panid_query_server.cpp
  src/core/utils/channel_manager.cpp
  src/core/utils/channel_monitor.cpp
  src/core/utils/child_supervision.cpp
  src/core/utils/jam_detector.cpp
Labels: P4, cla: yes, enhancement

#5051 [cli] add output for RCP version string
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
Labels: P4, cla: yes, comp: cli, enhancement

#5054 [test] add expect tests for router, scan, and more
  tests/scripts/expect/cli-2-nodes.exp
  tests/scripts/expect/cli-misc.exp
Labels: P4, cla: yes, continuous-integration, enhancement

#5056 [test] modularize expect scripts
  tests/scripts/expect/_common.exp
  tests/scripts/expect/_multinode.exp
  tests/scripts/expect/cli-2-nodes.exp
Labels: P4, cla: yes, continuous-integration, enhancement

#5059 [mle] simplify appending of MLE Discovery TLV in Mle::Discover()
  src/core/thread/mle.cpp
Labels: P4, cla: yes, enhancement

#5062 [posix] fix build daemon mode
  src/posix/Makefile-posix
Labels: P4, bug, cla: yes, comp: build

#4975 [harness-automation] add a parser tool for TopologyConfig file
  tools/harness-automation/parse_topofile.py
Labels: P4, cla: yes, enhancement

#5058 [cmake] use the correct define for external heap
  etc/cmake/options.cmake
Labels: P3, bug, cla: yes, comp: build

#5063 [test] split out 1.2 and posix from simulation
  .github/workflows/posix.yml
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
Labels: P4, cla: yes, continuous-integration, enhancement

#4900 [dua] support to specify iid for domain unicast address
  include/openthread/instance.h
  include/openthread/ip6.h
  include/openthread/thread.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/thread_api.cpp
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  src/core/thread/dua_manager.cpp
  src/core/thread/dua_manager.hpp
  tests/scripts/thread-cert/command.py
  tests/scripts/thread-cert/config.py
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/v1_2_test_domain_unicast_address.py
Labels: P3, Thread 1.2, api: user, cla: yes

#5065 [meshcop] move Joiner::IsPskdValid() to MeshCoP::IsPskdValid()
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/joiner.hpp
  src/core/meshcop/meshcop.cpp
  src/core/meshcop/meshcop.hpp
Labels: P3, bug, cla: yes, comp: meshcop

#5068 [posix] fix spinel radio state transition
  src/lib/spinel/radio_spinel_impl.hpp
Labels: P3, bug, cla: yes, platform: posix

#5069 [fuzz] limit PBKDF2 iterations to avoid OSS-Fuzz timeout
  src/core/crypto/pbkdf2_cmac.cpp
Labels: P4, cla: yes, continuous-integration, enhancement

#5055 [meshcop] support get/set operational dataset via raw TLVs
  include/openthread/dataset.h
  include/openthread/instance.h
  src/cli/README_DATASET.md
  src/cli/cli_dataset.cpp
  src/cli/cli_dataset.hpp
  src/core/api/dataset_api.cpp
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dataset_local.cpp
  src/core/meshcop/dataset_local.hpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
Labels: P4, api: user, cla: yes, comp: cli, comp: meshcop, enhancement

#5070 [posix] fix otPlatAlarmMicroGetNow to use scaled time
  src/posix/platform/alarm.cpp
Labels: P4, bug, cla: yes, platform: posix

#4904 [dua] save dad counter into non volatile memory
  src/core/common/settings.cpp
  src/core/common/settings.hpp
  src/core/thread/dua_manager.cpp
  src/core/thread/dua_manager.hpp
  src/core/thread/mle.cpp
Labels: P3, Thread 1.2, cla: yes

#5071 [cmake] add posix in platform list
  CMakeLists.txt
  etc/cmake/functions.cmake
Labels: P4, cla: yes, comp: build, enhancement

#5079 [cmake] use ot-config to umbrella private includes
  CMakeLists.txt
  examples/apps/cli/CMakeLists.txt
  examples/apps/ncp/CMakeLists.txt
  examples/platforms/cc1352/CMakeLists.txt
  examples/platforms/cc2538/CMakeLists.txt
  examples/platforms/cc2650/CMakeLists.txt
  examples/platforms/cc2652/CMakeLists.txt
  examples/platforms/kw41z/CMakeLists.txt
  examples/platforms/qpg6095/CMakeLists.txt
  examples/platforms/samr21/CMakeLists.txt
  examples/platforms/simulation/CMakeLists.txt
  examples/platforms/utils/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/core/CMakeLists.txt
  src/lib/hdlc/CMakeLists.txt
  src/lib/platform/CMakeLists.txt
  src/lib/spinel/CMakeLists.txt
  src/ncp/CMakeLists.txt
  src/posix/CMakeLists.txt
  src/posix/platform/CMakeLists.txt
  third_party/mbedtls/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#5082 [mle-tlvs] remove unused type/constant definitions
  src/core/thread/mle_tlvs.hpp
Labels: P4, cla: yes, enhancement

#5083 [network-data] in Validate() only check dups against prior prefixes
  src/core/thread/network_data_leader_ftd.cpp
Labels: P4, cla: yes, enhancement

#5087 [posix] fix ot-ctl CLI output missing
  src/posix/client.cpp
Labels: P3, bug, cla: yes, platform: posix

#5074 [efr32] update EFR32 mbedTLS configuration to use more hardware acceleration
  examples/platforms/efr32mg12/crypto/efr32-mbedtls-config.h
  examples/platforms/efr32mg13/crypto/efr32-mbedtls-config.h
  examples/platforms/efr32mg21/crypto/efr32-mbedtls-config.h
  third_party/silabs/Makefile.am
Labels: P3, cla: yes, enhancement, platform: efr32

#5067 [script] install shellcheck in bootstrap
  script/bootstrap
Labels: P4, cla: yes, enhancement

#5091 [efr32] turn off specific warnings for certain mbed TLS configurations
  examples/Makefile-efr32mg21
Labels: P3, cla: yes, comp: build, platform: efr32

#5100 [bootstrap] add missing newlib on Ubuntu >= 20.04
  script/bootstrap
Labels: P4, cla: yes, comp: build, enhancement

#5088 [docs] add English source for the Thread Primer
  doc/site/en/guides/thread-primer/index.md
  doc/site/en/guides/thread-primer/ipv6-addressing.md
  doc/site/en/guides/thread-primer/network-discovery.md
  doc/site/en/guides/thread-primer/node-roles-and-types.md
  doc/site/en/guides/thread-primer/router-selection.md
  script/make-pretty
Labels: cla: yes, comp: docs

#5094 [tests] use longer timeouts for simulation tests
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/simulator.py
Labels: P3, cla: yes, continuous-integration

#5101 [posix] fix build errors on macOS
  src/posix/client.cpp
Labels: P4, cla: yes, comp: build, enhancement, platform: posix

#5019 [ip6-address] add a type flag to addresses
  include/openthread/instance.h
  include/openthread/ip6.h
  src/cli/cli.cpp
  src/core/backbone_router/local.cpp
  src/core/meshcop/border_agent.cpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dhcp6_server.hpp
  src/core/net/netif.cpp
  src/core/thread/dua_manager.cpp
  src/core/thread/mle.cpp
  src/core/utils/slaac_address.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, api: user, cla: yes, enhancement

#5095 [settings] fix DUA logging
  script/check-simulation-build-autotools
  src/core/common/settings.cpp
Labels: P4, Thread 1.2, bug, cla: yes

#5105 [encoding] add uint64_t read/write methods for big/little endian encodings
  src/core/common/encoding.hpp
Labels: P4, cla: yes, enhancement

#5103 [github-actions] fix version workflow's name
  .github/workflows/version.yml
Labels: cla: yes, continuous-integration

#5077 [style] advance C++ language standard to C++11
  .clang-format
  Android.mk
  STYLE_GUIDE.md
  configure.ac
  tests/fuzz/fuzzer_platform.cpp
Labels: P4, cla: yes, comp: build, enhancement

#5084 [cmake] generate a mbedtls-config.h without private headers
  third_party/mbedtls/CMakeLists.txt
  third_party/mbedtls/mbedtls-config.h
Labels: P4, cla: yes, comp: build, enhancement

#5089 [posix] get time offset between host and rcp
  examples/platforms/nrf528xx/src/alarm.c
  include/openthread/instance.h
  include/openthread/link_raw.h
  include/openthread/platform/radio.h
  src/core/api/link_raw_api.cpp
  src/core/radio/radio_platform.cpp
  src/lib/spinel/radio_spinel.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  src/lib/spinel/spinel.h
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_radio.cpp
  src/posix/platform/radio.cpp
Labels: Thread 1.2, api: platform, cla: yes

#5093 [tests] ignore otError in spinel tests
  .github/workflows/simulation.yml
  tests/unit/test_spinel_buffer.cpp
  tests/unit/test_spinel_decoder.cpp
Labels: P4, cla: yes

#5108 [link-raw] set receive done callback when enabled
  examples/platforms/simulation/radio.c
  examples/platforms/simulation/system.c
  include/openthread/instance.h
  include/openthread/link_raw.h
  src/core/api/link_raw_api.cpp
  src/core/mac/link_raw.cpp
  src/core/mac/link_raw.hpp
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_radio.cpp
  tests/scripts/expect/posix-scan-tx-to-sleep.exp
Labels: bug, cla: yes, comp: rcp, continuous-integration

#5111 [size-report] retry multiple times
  script/check-size
Labels: P4, cla: yes, continuous-integration, enhancement

#5110 [commissioner] prefer entry with Joiner ID match over one accepting any
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/commissioner.hpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5117 [cmake] fix error messages on macOS
  third_party/mbedtls/CMakeLists.txt
Labels: P4, bug, cla: yes, comp: build

#5120 [otns] allow build without JOINER=1
  src/core/utils/otns.cpp
Labels: bug, cla: yes, comp: build

#5119 [posix] only update timeout with a lower value
  src/posix/platform/alarm.cpp
Labels: P3, bug, cla: yes, platform: posix

#5126 [simulation] remove linux specific prctl
  examples/platforms/simulation/uart.c
Labels: P4, cla: yes, enhancement, platform: simulation

#5124 [logging] add OPENTHREAD_CONFIG_LOG_MESHCOP
  etc/cmake/options.cmake
  examples/common-switches.mk
  src/core/common/logging.hpp
  src/core/config/logging.h
  src/core/meshcop/commissioner.cpp
Labels: P4, cla: yes, enhancement

#5104 [logging] remove NCP_SPINEL output
  CMakeLists.txt
  examples/apps/ncp/main.c
  examples/platforms/cc1352/logging.c
  examples/platforms/cc2538/logging.c
  examples/platforms/cc2650/logging.c
  examples/platforms/cc2652/logging.c
  examples/platforms/efr32mg12/logging.c
  examples/platforms/efr32mg12/system.c
  examples/platforms/efr32mg13/logging.c
  examples/platforms/efr32mg13/system.c
  examples/platforms/efr32mg21/logging.c
  examples/platforms/efr32mg21/system.c
  examples/platforms/gp712/logging.c
  examples/platforms/k32w/src/logging.c
  examples/platforms/kw41z/logging.c
  examples/platforms/nrf528xx/src/logging.c
  examples/platforms/nrf528xx/src/system.c
  examples/platforms/samr21/logging.c
  examples/platforms/samr21/system.c
  examples/platforms/simulation/logging.c
  examples/platforms/utils/logging_rtt.c
  src/core/config/logging.h
  src/core/config/openthread-core-config-check.h
  src/ncp/ncp_base.cpp
  tests/toranj/openthread-core-toranj-config.h
Labels: P4, cla: yes, comp: ncp, enhancement

#5122 [posix] use real time signal for microsecond timer
  Android.mk
  examples/platforms/simulation/alarm.c
  script/test
  src/posix/Makefile.am
  src/posix/main.c
  src/posix/platform/CMakeLists.txt
  src/posix/platform/alarm.cpp
  src/posix/platform/include/openthread/openthread-system.h
  src/posix/platform/platform-posix.h
  src/posix/platform/system.cpp
  tests/scripts/thread-cert/node.py
Labels: P4, cla: yes, continuous-integration, enhancement, platform: posix

#5123 [test] add expect tests for channel, coex, and discover
  tests/scripts/expect/cli-channel.exp
  tests/scripts/expect/cli-coex.exp
  tests/scripts/expect/cli-scan-discover.exp
Labels: P4, cla: yes, continuous-integration, enhancement

#5127 [core] use C++11 static_assert
  src/cli/cli_uart.cpp
  src/core/Makefile.am
  src/core/coap/coap_message.hpp
  src/core/common/code_utils.hpp
  src/core/mac/channel_mask.hpp
  src/core/mac/data_poll_handler.hpp
  src/core/meshcop/meshcop.cpp
  src/core/radio/radio.hpp
  src/core/thread/indirect_sender.hpp
  src/core/thread/topology.hpp
  src/core/utils/heap.hpp
  src/core/utils/slaac_address.cpp
  src/core/utils/static_assert.hpp
  src/ncp/changed_props_set.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/ncp_spi.cpp
  src/ncp/ncp_uart.cpp
  tests/unit/test_toolchain.cpp
Labels: P4, cla: yes, enhancement

#5128 [android] enable commissioner
  Android.mk
Labels: P3, cla: yes, comp: build, enhancement

#5132 [style] remove c++11 check and OT_NCP_CONST
  src/ncp/ncp_base_dispatcher.cpp
Labels: P4, cla: yes, comp: ncp, enhancement

#5129 [ncp] ensure JOINER_STATE is not limited to FTD only
  src/ncp/ncp_base_dispatcher.cpp
Labels: P4, bug, cla: yes, comp: ncp

#5135 [efr32] remove extra parenthesis causing compilation problems
  examples/platforms/efr32mg12/system.c
  examples/platforms/efr32mg13/system.c
  examples/platforms/efr32mg21/system.c
Labels: P3, bug, cla: yes, comp: build, platform: efr32

#5136 [tasklet] use function reference (instead of pointer) for handler
  src/core/coap/coap_secure.cpp
  src/core/common/notifier.cpp
  src/core/common/tasklet.hpp
  src/core/mac/mac.cpp
  src/core/net/ip6.cpp
  src/core/thread/mesh_forwarder.cpp
  src/ncp/ncp_base.cpp
Labels: P4, cla: yes, enhancement

#5118 [simulation] support transmit security at simulation radio
  examples/platforms/simulation/radio.c
  examples/platforms/utils/mac_frame.cpp
  examples/platforms/utils/mac_frame.h
  src/core/mac/mac_frame.cpp
Labels: Thread 1.2, cla: yes, platform: simulation, security

#5141 [spinel] fix use of OT header file in spinel.c
  src/lib/spinel/spinel.c
Labels: P4, bug, cla: yes

#5115 [docker] build ot-daemon/ot-ctl in codelab_otsim
  etc/docker/codelab_otsim/Dockerfile
Labels: cla: yes, comp: docs

#5139 [posix] ensure backward compatible with older RCP image
  src/lib/spinel/radio_spinel_impl.hpp
Labels: bug, cla: yes, platform: posix

#5145 [test] add expect tests for dataset and networktime
  .github/workflows/simulation.yml
  tests/scripts/expect/cli-dataset.exp
  tests/scripts/expect/cli-misc.exp
Labels: P4, cla: yes, continuous-integration, enhancement

#5147 [dtls] remove unused method decelerations
  src/core/meshcop/dtls.hpp
Labels: P4, cla: yes, comp: meshcop, enhancement

#5148 [net-data-tlvs] update documentation and index parameter name style
  src/core/thread/network_data_tlvs.hpp
Labels: P4, cla: yes, enhancement

#5150 [utils] remove wrap_string.h
  examples/platforms/k32w/src/settings_k32w.c
  src/core/utils/wrap_string.h
Labels: P4, cla: yes, enhancement

#5156 [mle] suppress parent response when >= 32 active routers
  src/core/thread/mle_router.cpp
Labels: P4, cla: yes, enhancement

#5151 [mac-filter] misc enhancements
  include/openthread/instance.h
  include/openthread/link.h
  src/cli/cli.cpp
  src/core/api/link_api.cpp
  src/core/mac/mac_filter.cpp
  src/core/mac/mac_filter.hpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, api: user, cla: yes, enhancement

#5158 [test] fix multiple extra options
  script/test
Labels: P4, bug, cla: yes

#5164 [linked-list] fix Find() when list is empty
  src/core/common/linked_list.hpp
  tests/unit/test_linked_list.cpp
Labels: P4, bug, cla: yes

#5161 [bootstrap] update bootstrap user messages
  script/bootstrap
Labels: cla: yes, comp: docs

#5160 [devsite] add clarifications to multicast addressing primer
  doc/site/en/guides/thread-primer/ipv6-addressing.md
  doc/site/en/guides/thread-primer/node-roles-and-types.md
Labels: cla: yes, comp: docs

#5143 [posix] wait for writable before next try
  src/posix/platform/hdlc_interface.cpp
Labels: P4, cla: yes, enhancement, platform: posix

#5157 [github-actions] fix expects fail by chance
  tests/scripts/expect/_common.exp
  tests/scripts/expect/cli-channel.exp
  tests/scripts/expect/cli-child.exp
  tests/scripts/expect/cli-childip.exp
  tests/scripts/expect/cli-coex.exp
  tests/scripts/expect/cli-counters.exp
  tests/scripts/expect/cli-dataset.exp
  tests/scripts/expect/cli-extaddr.exp
  tests/scripts/expect/cli-ipmaddr.exp
  tests/scripts/expect/cli-log-level.exp
  tests/scripts/expect/cli-mac.exp
  tests/scripts/expect/cli-macfilter.exp
  tests/scripts/expect/cli-misc.exp
  tests/scripts/expect/cli-neighbor.exp
  tests/scripts/expect/cli-ping.exp
  tests/scripts/expect/cli-promiscuous.exp
  tests/scripts/expect/cli-pskc.exp
  tests/scripts/expect/cli-router.exp
  tests/scripts/expect/cli-routereligible.exp
  tests/scripts/expect/cli-scan-discover.exp
  tests/scripts/expect/posix-diag-rcp.exp
  tests/scripts/expect/posix-max-power-table.exp
  tests/scripts/expect/posix-rcp.exp
  tests/scripts/expect/posix-scan-tx-to-sleep.exp
  tests/scripts/expect/tun-dns-client.exp
  tests/scripts/expect/tun-netif.exp
  tests/scripts/expect/tun-sntp.exp
Labels: P3, bug, cla: yes, continuous-integration

#5155 [otns] add default implementation for otPlatOtnsStatus
  src/core/common/logging.hpp
  src/core/utils/otns.cpp
Labels: cla: yes, enhancement
