Repository openthread/openthread, pull requests merged in 2021-01, with the labels that each got.

#6035 [scripts] optionally install pretty format for Raspbian in bootstrap
  script/bootstrap
Labels: P4, cla: yes, enhancement

#6027 [coap] fix order of operations in TxParameters::IsValid()
  src/core/coap/coap.cpp
Labels: P4, cla: yes, comp: coap, enhancement

#6026 [link-raw] do not disable link raw during transmit/scan operation
  src/core/mac/link_raw.cpp
  src/core/mac/sub_mac.hpp
Labels: P4, cla: yes, comp: ncp, enhancement

#6037 [posix] increase message buffer pool to 256
  src/posix/platform/openthread-core-posix-config.h
Labels: P4, cla: yes, enhancement, platform: posix

#6006 [simulation] increase simulator UDP buffer size
  tests/scripts/thread-cert/simulator.py
  tests/scripts/thread-cert/sniffer_transport.py
Labels: P4, cla: yes, platform: simulation

#6019 [gn] add all mbedtls .c source files to sources
  third_party/mbedtls/BUILD.gn
Labels: cla: yes, comp: build, enhancement

#6040 [build] remove unneeded-internal-declaration warning on Fuchsia
  src/lib/spinel/radio_spinel_impl.hpp
Labels: cla: yes, comp: build, enhancement

#6020 [nrf528xx] enable unused-parameter warning for platform code
  examples/platforms/nrf528xx/nrf52811/Makefile.am
  examples/platforms/nrf528xx/nrf52833/Makefile.am
  examples/platforms/nrf528xx/nrf52840/Makefile.am
  examples/platforms/nrf528xx/src/radio.c
  examples/platforms/nrf528xx/src/transport/transport.c
Labels: P4, cla: yes, comp: build, enhancement, platform: nrf52811, platform: nrf52833, platform: nrf52840

#6021 [nrf52840] implement enh-ack probing
  examples/platforms/nrf528xx/src/radio.c
  examples/platforms/utils/Makefile.am
  examples/platforms/utils/link_metrics.cpp
  examples/platforms/utils/link_metrics.h
  examples/platforms/utils/mac_frame.cpp
  examples/platforms/utils/mac_frame.h
  src/core/thread/link_metrics.cpp
  third_party/NordicSemiconductor/drivers/radio/nrf_802154.c
  third_party/NordicSemiconductor/drivers/radio/nrf_802154.h
  third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c
Labels: P3, Thread 1.2, cla: yes, enhancement, platform: nrf52840

#6046 [radio-spinel] add option to skip RCP compatibility check during init
  src/lib/spinel/radio_spinel.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  src/posix/platform/radio.cpp
  src/posix/platform/radio_url.cpp
Labels: P4, cla: yes, enhancement, platform: posix

#6045 [test] enhance parsing addresses
  src/posix/platform/ip6_utils.hpp
  src/posix/platform/netif.cpp
  src/posix/platform/udp.cpp
  tests/scripts/expect/_common.exp
  tests/scripts/expect/_multinode.exp
  tests/scripts/expect/cli-anycast.exp
  tests/scripts/expect/cli-big-table.exp
  tests/scripts/expect/cli-channel.exp
  tests/scripts/expect/cli-child-supervision.exp
  tests/scripts/expect/cli-child.exp
  tests/scripts/expect/cli-childip.exp
  tests/scripts/expect/cli-coap.exp
  tests/scripts/expect/cli-coaps.exp
  tests/scripts/expect/cli-coex.exp
  tests/scripts/expect/cli-commissioner.exp
  tests/scripts/expect/cli-counters.exp
  tests/scripts/expect/cli-dataset.exp
  tests/scripts/expect/cli-discerner.exp
  tests/scripts/expect/cli-extaddr.exp
  tests/scripts/expect/cli-ipmaddr.exp
  tests/scripts/expect/cli-log-level.exp
  tests/scripts/expect/cli-mac.exp
  tests/scripts/expect/cli-macfilter.exp
  tests/scripts/expect/cli-misc.exp
  tests/scripts/expect/cli-multicast-loop.exp
  tests/scripts/expect/cli-neighbor.exp
  tests/scripts/expect/cli-netdata.exp
  tests/scripts/expect/cli-networkname.exp
  tests/scripts/expect/cli-partitionid.exp
  tests/scripts/expect/cli-ping.exp
  tests/scripts/expect/cli-promiscuous.exp
  tests/scripts/expect/cli-pskc.exp
  tests/scripts/expect/cli-region.exp
  tests/scripts/expect/cli-reset.exp
  tests/scripts/expect/cli-router.exp
  tests/scripts/expect/cli-routereligible.exp
  tests/scripts/expect/cli-scan-discover.exp
  tests/scripts/expect/cli-udp.exp
  tests/scripts/expect/cli-unsecure-port.exp
  tests/scripts/expect/posix-ccathreshold.exp
  tests/scripts/expect/posix-diag-rcp.exp
  tests/scripts/expect/posix-fem-lnagain.exp
  tests/scripts/expect/posix-max-power-table.exp
  tests/scripts/expect/posix-rcp-restoration.exp
  tests/scripts/expect/posix-rcp.exp
  tests/scripts/expect/posix-scan-tx-to-sleep.exp
  tests/scripts/expect/simulation-networktime.exp
  tests/scripts/expect/tun-dns-client.exp
  tests/scripts/expect/tun-netif.exp
  tests/scripts/expect/tun-netstat.exp
  tests/scripts/expect/tun-realm-local-multicast.exp
  tests/scripts/expect/tun-sntp.exp
  tests/scripts/expect/tun-udp.exp
  tests/scripts/expect/v1_2-rcp-restoration.exp
  tests/scripts/expect/v1_2-rcp.exp
  tests/scripts/expect/v1_2-sed_mac_send.exp
Labels: P4, cla: yes, continuous-integration

#6050 [efr32] fix for trng entropy API
  examples/platforms/efr32/src/entropy.c
Labels: bug, cla: yes, platform: efr32

#6051 [ecdsa] relax/fix the assert check on MPI encoded size
  src/core/crypto/ecdsa.cpp
Labels: P4, bug, cla: yes

#6025 [utils] implement a item-pointer iterator template for many iterators
  src/core/BUILD.gn
  src/core/Makefile.am
  src/core/backbone_router/ndproxy_table.cpp
  src/core/backbone_router/ndproxy_table.hpp
  src/core/common/iterator_utils.hpp
  src/core/net/netif.hpp
  src/core/thread/child_table.cpp
  src/core/thread/child_table.hpp
  src/core/thread/router_table.cpp
  src/core/thread/router_table.hpp
Labels: P4, cla: yes, enhancement

#6052 [network-data] check serverTlv data length before parsing
  src/core/thread/network_data_leader.cpp
Labels: P4, cla: yes, comp: backbone-router, enhancement

#6054 [posix] set external heap callbacks
  src/posix/platform/system.cpp
Labels: cla: yes, enhancement, platform: posix

#6055 [neighbor-table] fix typo (macAddresss -> macAddress)
  src/core/thread/neighbor_table.cpp
Labels: P4, cla: yes, enhancement

#6056 [build] add missing infra_if.cpp file in Android.mk
  Android.mk
Labels: cla: yes, comp: build

#6059 [dns-headers] fix typos, rename some methods
  src/core/net/dns_headers.cpp
  src/core/net/dns_headers.hpp
Labels: P4, cla: yes, comp: dns, enhancement

#6061 [dns-client] use 'Header::SetRandomMessageId()' to set query message ID
  src/core/net/dns_client.cpp
Labels: P4, cla: yes, comp: dns, enhancement

#6066 [bootstrap] fix pretty format install
  script/bootstrap
Labels: P4, bug, cla: yes, enhancement

#6065 [doc] amend DUA and MLR fast poll comments
  src/core/thread/dua_manager.cpp
  src/core/thread/mlr_manager.cpp
Labels: P4, Thread 1.2, cla: yes

#6049 [github-actions] upload core dump only when crash happens
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  script/test
Labels: P4, cla: yes, continuous-integration, enhancement

#6071 [random-manager] fail if unable to seed the CTR DRBG
  src/core/common/random_manager.cpp
Labels: cla: yes, enhancement, security

#6069 [logging] add logging region DNS
  etc/cmake/options.cmake
  examples/common-switches.mk
  include/openthread/instance.h
  include/openthread/platform/logging.h
  src/core/BUILD.gn
  src/core/common/logging.hpp
  src/core/config/logging.h
  src/core/net/dns_client.cpp
  src/lib/spinel/spinel.h
  src/ncp/ncp_base.cpp
Labels: cla: yes, comp: dns

#6072 [tests] fix expecting command output
  tests/scripts/thread-cert/node.py
Labels: bug, cla: yes, continuous-integration

#6068 [message] new helper methods to compare bytes in a message
  src/core/common/message.cpp
  src/core/common/message.hpp
  tests/unit/test_message.cpp
Labels: P4, cla: yes, enhancement

#6073 [tests] use dedicated _expect_done method for success commands
  tests/scripts/thread-cert/node.py
Labels: cla: yes, continuous-integration, enhancement

#6075 [dns-client] remove QuestionAaaa class
  src/core/net/dns_client.cpp
  src/core/net/dns_headers.hpp
Labels: cla: yes, comp: dns, enhancement

#6077 [docs] create Operational Dataset group
  doc/ot_api_doc.h
  include/openthread/dataset.h
  include/openthread/dataset_ftd.h
  include/openthread/dataset_updater.h
  include/openthread/instance.h
Labels: cla: yes, comp: docs

#6081 [bootstrap] fix gcc-arm-none-eabi install
  script/bootstrap
Labels: cla: yes

#6086 [mesh-forwarder] remove unused UpdateIndirectMessages() declaration
  src/core/thread/mesh_forwarder.hpp
Labels: P4, cla: yes, enhancement

#6044 [posix] tune core config for posix
  src/posix/platform/openthread-core-posix-config.h
Labels: P4, cla: yes, enhancement, platform: posix

#6083 [otns] fix compile issue when log region CORE is enabled
  src/core/utils/otns.cpp
Labels: P4, cla: yes, comp: build

#6082 [script] script/test cert with multiple arguments
  script/test
Labels: P4, cla: yes, enhancement

#6094 [bootstrap] overwrite existing links
  script/bootstrap
Labels: cla: yes

#6008 [border-router] add external route for on-link prefix and external OMR prefixes
  .github/workflows/simulation-1.2.yml
  include/openthread/border_router.h
  include/openthread/instance.h
  include/openthread/platform/infra_if.h
  src/cli/README.md
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/api/border_router_api.cpp
  src/core/border_router/router_advertisement.cpp
  src/core/border_router/router_advertisement.hpp
  src/core/border_router/routing_manager.cpp
  src/core/border_router/routing_manager.hpp
  src/core/thread/network_data.hpp
  src/posix/platform/infra_if.cpp
  tests/scripts/thread-cert/border_routing/test_multi_border_routers.py
  tests/scripts/thread-cert/border_routing/test_multi_thread_networks.py
  tests/scripts/thread-cert/border_routing/test_single_border_router.py
  tests/scripts/thread-cert/node.py
Labels: cla: yes, enhancement

#6085 [scripts] add option to not build bbr when building 1.2
  .github/workflows/simulation-1.2.yml
  script/test
Labels: P4, cla: yes, comp: build, enhancement

#6090 [posix] logging enhancements to infra if
  src/posix/platform/infra_if.cpp
Labels: cla: yes, enhancement, platform: posix

#6089 [posix] bind infra IF socket to specific interface
  src/posix/platform/infra_if.cpp
Labels: cla: yes, enhancement, platform: posix

#6096 [script] fix warning string for mdv
  script/bootstrap
Labels: P4, cla: yes, comp: build, comp: docs, enhancement

#6102 [thread-cert] ignore CLI log lines
  tests/scripts/thread-cert/node.py
Labels: P4, cla: yes, enhancement

#6104 [android] add library `libcutils` for compiling ot-cli and ot-ncp
  Android.mk
Labels: P2, bug, cla: yes, comp: build

#6092 [build] only build unit tests when FTD is enabled
  tests/CMakeLists.txt
Labels: P4, cla: yes, comp: build, enhancement

#6099 [k32w] Project CHIP fixes
  examples/platforms/k32w/src/radio.c
  examples/platforms/k32w/src/system.c
Labels: cla: yes, platform: k32w

#6079 [ncp-base] fix set hander for 'SPINEL_PROP_MAC_DENYLIST'
  src/ncp/ncp_base_mtd.cpp
Labels: P4, bug, cla: yes, comp: ncp

#6107 [mle] ensure reserved bit in Mode TLV is set
  src/core/thread/mle_types.hpp
Labels: P2, bug, cla: yes, comp: mle

#6105 [otci] get router link information
  tools/otci/otci/otci.py
  tools/otci/otci/types.py
  tools/otci/tests/test_otci.py
Labels: cla: yes, comp: otci, enhancement

#6101 [dns-name] require message offset to point to DNS header
  src/core/net/dns_client.cpp
  src/core/net/dns_headers.cpp
  src/core/net/dns_headers.hpp
  src/core/net/srp_server.cpp
  src/core/net/srp_server.hpp
  tests/unit/test_dns.cpp
Labels: P4, cla: yes, comp: dns, enhancement

#6088 [dns] fix dns failed to append names of length 255
  src/core/net/dns_headers.cpp
  src/core/net/dns_headers.hpp
  tests/unit/test_dns.cpp
Labels: P4, bug, cla: yes, comp: dns

#6078 [dns-header] new methods to compare label/name from message
  src/core/net/dns_headers.cpp
  src/core/net/dns_headers.hpp
  tests/unit/test_dns.cpp
Labels: P4, cla: yes, comp: dns, enhancement

#6112 [scripts] allow virtual time simulator to `go` less than 1 second
  tests/scripts/thread-cert/simulator.py
Labels: P4, cla: yes, enhancement

#6097 [dns-header] helper methods to parse/find/read record(s) in a message
  src/core/net/dns_headers.cpp
  src/core/net/dns_headers.hpp
  tests/unit/test_dns.cpp
Labels: P4, cla: yes, comp: dns, enhancement

#6084 [logging] refine FULL_LOGS option
  etc/cmake/options.cmake
  examples/common-switches.mk
  script/test
  src/core/BUILD.gn
  src/core/config/logging.h
Labels: P4, cla: yes

#4247 [coap] add CoAP(s) block-wise transfer support to CoAP(s) client and server
  etc/cmake/options.cmake
  examples/Makefile-simulation
  examples/common-switches.mk
  include/openthread/coap.h
  include/openthread/coap_secure.h
  include/openthread/instance.h
  script/cmake-build
  script/make-pretty
  src/cli/README_COAP.md
  src/cli/README_COAPS.md
  src/cli/cli_coap.cpp
  src/cli/cli_coap.hpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_coap_secure.hpp
  src/core/api/coap_api.cpp
  src/core/api/coap_secure_api.cpp
  src/core/coap/coap.cpp
  src/core/coap/coap.hpp
  src/core/coap/coap_message.cpp
  src/core/coap/coap_message.hpp
  src/core/coap/coap_secure.cpp
  src/core/coap/coap_secure.hpp
  src/core/config/coap.h
  tests/scripts/thread-cert/Makefile.am
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/test_coap_block.py
Labels: cla: yes, comp: coap, enhancement

#6111 [udp] fix UDP not accessible via RLOC/ALOC with PLAT_UDP
  src/core/net/ip6.cpp
  tests/scripts/thread-cert/border_routing/test_plat_udp_accessiblity.py
Labels: bug, cla: yes, platform: posix

#6062 [ncp] add support for SRP client in NCP and spinel
  src/lib/spinel/spinel.c
  src/lib/spinel/spinel.h
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
  src/ncp/ncp_config.h
Labels: P4, cla: yes, comp: ncp, enhancement

#6118 [child-table] enhance address iterator method
  src/core/thread/topology.cpp
Labels: P4, cla: yes, enhancement

#6117 [dns-name] allow 'Dns::Name' to be given as string or from message
  src/core/net/dns_headers.cpp
  src/core/net/dns_headers.hpp
  tests/unit/test_dns.cpp
Labels: P4, cla: yes, comp: dns, enhancement

#6113 [srp] get parsed TXT entry from SRP server
  include/openthread/dns.h
  include/openthread/instance.h
  include/openthread/srp_client.h
  include/openthread/srp_server.h
  src/cli/cli_srp_client.cpp
  src/cli/cli_srp_client.hpp
  src/cli/cli_srp_server.cpp
  src/cli/cli_srp_server.hpp
  src/core/api/srp_server_api.cpp
  src/core/net/dns_headers.cpp
  src/core/net/dns_headers.hpp
  src/core/net/srp_client.cpp
  src/core/net/srp_client.hpp
  src/core/net/srp_server.cpp
  src/core/net/srp_server.hpp
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/test_srp_register_single_service.py
Labels: cla: yes, comp: dns, enhancement

#6114 [dns] match DNS name with specific domain
  src/core/net/dns_headers.cpp
  src/core/net/dns_headers.hpp
  src/core/net/srp_server.cpp
  src/core/net/srp_server.hpp
  tests/unit/test_dns.cpp
Labels: cla: yes, comp: dns, enhancement

#6128 [posix] set up heap before creating OT instance
  src/posix/platform/system.cpp
Labels: P2, bug, cla: yes

#6129 [network-data] remove unused enum constants
  src/core/thread/network_data.hpp
Labels: P4, cla: yes, enhancement

#6060 [otci] get prefixes/routes/services in thread network data
  tools/otci/otci/otci.py
  tools/otci/tests/test_otci.py
Labels: cla: yes, comp: otci, enhancement
