Repository openthread/openthread, pull requests merged in 2021-03, with the labels that each got.

#6210 [thread-cert] remove border_routing directory
  tests/scripts/thread-cert/border_router/test_dnssd_server.py
Labels: P4, certification, cla: yes, comp: dns

#6219 [harness-thci] remove `pylint` issues from THCI file and small fix
  tools/harness-thci/OpenThread.py
Labels: bug, certification, cla: yes, enhancement

#6214 [mesh-forwarder] add helper 'RemoveMessageIfNoPendingTx()'
  src/core/thread/indirect_sender.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mesh_forwarder.hpp
  src/core/thread/mesh_forwarder_ftd.cpp
Labels: P4, cla: yes, enhancement

#6220 [srp] rename Advertising to ServiceUpdate
  src/core/api/srp_server_api.cpp
  src/core/net/srp_server.cpp
  src/core/net/srp_server.hpp
Labels: cla: yes, comp: dns, enhancement

#6223 [mac] only append header termination IE2 when data payload is present
  src/core/thread/mesh_forwarder.cpp
Labels: cla: yes, comp: mac

#6204 [tests] add test to verify DHCP6 client works after reset
  tests/scripts/thread-cert/border_router/test_plat_udp_accessiblity.py
  tests/scripts/thread-cert/node.py
Labels: bug, cla: yes, platform: posix

#6217 [config] perform OT config checks in the related module
  src/core/backbone_router/bbr_local.hpp
  src/core/border_router/routing_manager.hpp
  src/core/common/logging.hpp
  src/core/common/message.cpp
  src/core/config/openthread-core-config-check.h
  src/core/mac/sub_mac.hpp
  src/core/net/dhcp6_client.hpp
  src/core/net/dhcp6_server.hpp
  src/core/net/udp6.hpp
  src/core/thread/dua_manager.hpp
  src/core/thread/link_metrics.hpp
  src/core/thread/mlr_manager.hpp
Labels: P4, cla: yes, enhancement

#6221 [message] use opaque 'otMessage' and add 'otMessageBuffer'
  include/openthread/instance.h
  include/openthread/message.h
  include/openthread/platform/messagepool.h
  src/core/common/message.hpp
Labels: P4, api: user, cla: yes, enhancement

#6230 [tests] add OTBR_DUA_ROUTING=ON to OTBR build
  script/test
Labels: P0, bug, cla: yes, continuous-integration

#6216 [border-router] test host leaves and rejoins
  tests/scripts/thread-cert/border_router/test_single_border_router.py
Labels: P4, cla: yes, continuous-integration, enhancement

#6234 [git] pull dependency pull requests
  .github/workflows/size.yml
  script/check-size
  script/git-tool
Labels: cla: yes, continuous-integration, enhancement

#6235 [build] add missing files for Android.mk
  Android.bp
  Android.mk
Labels: cla: yes, comp: build

#6236 [mac] fix default Thread Domain name per v1.2.1-draft4 spec
  src/core/mac/mac.cpp
Labels: Thread 1.2, cla: yes

#6200 [spinel] add interface identifier of the Thread Domain Unicast Address
  src/lib/spinel/spinel.h
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_ftd.cpp
Labels: Thread 1.2, cla: yes, comp: ncp, enhancement

#6239 [trel] add 'OT_TREL' CMake option & 'TREL' autoconf switch
  etc/cmake/options.cmake
  examples/README.md
  examples/common-switches.mk
Labels: P4, cla: yes, comp: build, comp: trel, enhancement

#6245 [spinel] fix missing prototype warning
  src/lib/spinel/spinel.c
Labels: P4, bug, cla: yes, comp: ncp

#6242 [cli] remove aBufLength and error message
  include/openthread/cli.h
  include/openthread/instance.h
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_config.h
  src/cli/cli_console.cpp
  src/cli/cli_uart.cpp
  src/posix/console_cli.cpp
Labels: cla: yes, comp: cli, enhancement

#6240 [tests] allow extra chars in prefix list 'wpanctl' output in toranj
  tests/toranj/wpan.py
Labels: cla: yes, comp: ncp, continuous-integration, enhancement

#6249 [git] reflect branch rename from 'master' to 'main'
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/makefile-check.yml
  .github/workflows/otci.yml
  .github/workflows/posix.yml
  .github/workflows/simulation-1.2.yml
  .github/workflows/simulation.yml
  .github/workflows/size.yml
  .github/workflows/toranj.yml
  .github/workflows/version.yml
  CONTRIBUTING.md
  README.md
  doc/site/en/guides/porting/certification-and-readme.md
  doc/site/en/guides/porting/implement-advanced-features.md
  doc/site/en/guides/porting/implement-platform-abstraction-layer-apis.md
  doc/site/en/guides/porting/index.md
  doc/site/en/guides/porting/set-up-the-build-environment.md
  examples/platforms/efr32/efr32mg1/README.md
  examples/platforms/efr32/efr32mg12/README.md
  examples/platforms/efr32/efr32mg13/README.md
  examples/platforms/efr32/efr32mg21/README.md
  examples/platforms/kw41z/README.md
  examples/platforms/samr21/README.md
Labels: P1, cla: yes, comp: docs, continuous-integration, enhancement

#6252 [spinel] fix unused variables
  src/lib/spinel/radio_spinel_impl.hpp
Labels: cla: yes, comp: rcp

#6246 [tests] test updating SRP host address
  tests/scripts/thread-cert/border_router/test_advertising_proxy.py
  tests/scripts/thread-cert/test_srp_register_single_service.py
Labels: P4, cla: yes, continuous-integration

#6253 [git-tool] fix non-fast-forward pull
  script/git-tool
Labels: cla: yes, continuous-integration, enhancement

#6261 [dtls] fix ECDSA configuration for newer mbed TLS versions
  src/core/meshcop/dtls.cpp
  src/core/meshcop/dtls.hpp
Labels: cla: yes, enhancement, security

#6262 [dataset-updater] set `mDataset` to `nullptr` in `Cancel()`
  src/core/meshcop/dataset_updater.cpp
Labels: P4, bug, cla: yes, comp: meshcop

#6268 [posix] fix socket issues
  src/core/net/dhcp6_client.cpp
  src/posix/platform/infra_if.cpp
  src/posix/platform/multicast_routing.cpp
  tests/scripts/thread-cert/border_router/test_plat_udp_accessiblity.py
Labels: P1, bug, cla: yes

#6263 [mac] increase macMaxFrameRetries to 15
  src/core/config/mac.h
Labels: P4, cla: yes, comp: mac, enhancement

#6265 [cli] update 'README_UDP.md'
  src/cli/README_UDP.md
Labels: P4, cla: yes, comp: cli, comp: docs, enhancement

#6266 [android] remove Android.bp
  Android.bp
  etc/android/openthread-config-android-version.h.in
  script/config-android-version-gen.sh
  script/update-makefiles.py
Labels: P3, cla: yes, comp: build, enhancement

#6215 [tests] update OTBR CI test script
  .github/workflows/simulation-1.2.yml
  script/test
Labels: cla: yes, continuous-integration

#6276 [tests] fix advertising proxy tests
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/requirements.txt
Labels: P1, bug, cla: yes

#6270 [logging] refine BBR log level
  src/core/backbone_router/backbone_tmf.cpp
  src/core/backbone_router/bbr_manager.cpp
  src/core/common/logging.hpp
Labels: P4, cla: yes, comp: backbone-router, enhancement

#6259 [posix] detect POSIX in source
  Android.mk
  etc/gn/openthread.gni
  examples/platforms/simulation/CMakeLists.txt
  include/openthread/instance.h
  src/cli/BUILD.gn
  src/cli/Makefile.am
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_config.h
  src/cli/cli_uart.cpp
  src/posix/platform/CMakeLists.txt
Labels: cla: yes, comp: build, comp: cli, enhancement, platform: posix

#6282 [dua] fix assert failure
  src/core/thread/dua_manager.cpp
Labels: P1, Thread 1.2, bug, cla: yes

#6279 [tests] add radio metadata in sniffer log using TAP TLVs
  tests/scripts/thread-cert/pcap.py
Labels: cla: yes, continuous-integration, enhancement

#6248 [srp-server] notify advertising proxy of host/service expiration
  src/core/net/srp_server.cpp
  src/core/net/srp_server.hpp
  tests/scripts/thread-cert/border_router/test_advertising_proxy.py
  tests/scripts/thread-cert/node.py
Labels: cla: yes, comp: dns, enhancement

#6277 [radio-spinel] perform "RestoreDatasetFromNcp()" with single OT instance config
  src/lib/spinel/radio_spinel_impl.hpp
Labels: P4, cla: yes, comp: rcp, enhancement

#6247 [border-router] add random delay before changing routing policies
  src/core/border_router/routing_manager.cpp
  src/core/border_router/routing_manager.hpp
  tests/scripts/thread-cert/border_router/test_plat_udp_accessiblity.py
Labels: cla: yes, enhancement

#6280 [border-router] send at least one router solicitation
  src/core/border_router/routing_manager.cpp
Labels: cla: yes, enhancement

#6287 [nrf528xx] improve CSL phase calculation
  examples/platforms/nrf528xx/src/radio.c
Labels: Thread 1.2, cla: yes, enhancement

#6288 [ncp] remove unused code
  src/ncp/ncp_base.cpp
Labels: cla: yes, comp: ncp

#6293 [indirect-sender] skip over an empty frame in 'HandleSentFrameToChild()'
  src/core/thread/indirect_sender.cpp
Labels: P4, bug, cla: yes, comp: mac

#6275 [simulation] do not update CSL IE in retransmission
  examples/platforms/simulation/radio.c
  tests/scripts/thread-cert/pktverify/consts.py
  tests/scripts/thread-cert/v1_2_test_csl_transmission.py
Labels: bug, cla: yes, platform: simulation

#6289 [cmake] do not set CMAKE_BUILD_TYPE if OT is not a top-level project
  CMakeLists.txt
Labels: cla: yes, comp: build, enhancement

#6301 [efr32] fix compilation errors in radio.c with Thread 1.2, fix RCP bug in PAL
  examples/platforms/efr32/src/radio.c
Labels: Thread 1.2, cla: yes, comp: build, platform: efr32

#6309 [tests] add allowlist after reset to restore same network topology
  tests/scripts/thread-cert/test_reset.py
Labels: bug, cla: yes, continuous-integration

#6231 [spinel] add multicast listener registration
  src/lib/spinel/spinel.c
  src/lib/spinel/spinel.h
  src/ncp/ncp_base.cpp
  src/ncp/ncp_base.hpp
  src/ncp/ncp_base_dispatcher.cpp
  src/ncp/ncp_base_mtd.cpp
Labels: Thread 1.2, cla: yes, comp: ncp, enhancement

#6307 [codecov] disable project coverage threshold
  .codecov.yml
Labels: P4, bug, cla: yes, continuous-integration

#6305 [test] print size diff symbol by symbol
  script/check-size
Labels: P4, cla: yes, continuous-integration

#6284 [utils] add 'Utils::PingSender'
  Android.mk
  etc/cmake/options.cmake
  etc/gn/openthread.gni
  examples/Makefile-simulation
  examples/README.md
  examples/common-switches.mk
  include/Makefile.am
  include/openthread/BUILD.gn
  include/openthread/instance.h
  include/openthread/ping_sender.h
  script/check-arm-build-autotools
  script/check-scan-build
  script/check-simulation-build-autotools
  script/check-size
  script/cmake-build
  script/make-pretty
  script/test
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/api/ping_sender_api.cpp
  src/core/common/instance.cpp
  src/core/common/instance.hpp
  src/core/config/ping_sender.h
  src/core/openthread-core-config.h
  src/core/utils/ping_sender.cpp
  src/core/utils/ping_sender.hpp
  src/posix/Makefile-posix
  tests/fuzz/oss-fuzz-build
Labels: P4, cla: yes, comp: cli, enhancement

#6315 [thread-tlvs] rename to follow style
  src/cli/cli.cpp
  src/core/backbone_router/bbr_manager.cpp
  src/core/thread/mlr_manager.cpp
  src/core/thread/mlr_manager.hpp
  src/core/thread/thread_tlvs.hpp
  src/ncp/ncp_base_mtd.cpp
Labels: P4, cla: yes, enhancement

#6318 [udp] bind to Thread interface by default
  src/core/coap/coap.cpp
  src/core/meshcop/dtls.cpp
  src/core/net/dnssd_server.cpp
  src/core/net/srp_server.cpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
Labels: cla: yes, enhancement

#6306 [timer] simplify 'TrickleTimer'
  src/core/common/trickle_timer.cpp
  src/core/common/trickle_timer.hpp
  src/core/net/dhcp6_client.cpp
  src/core/net/dhcp6_client.hpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router.hpp
Labels: P4, cla: yes, enhancement

#6325 [test] package with Thread version
  script/test
Labels: cla: yes, continuous-integration, enhancement

#6324 [config] fix typo in OPENTHREAD_CONFIG_NCP_UART_ENABLE error message
  src/core/config/openthread-core-config-check.h
Labels: P4, cla: yes, enhancement

#6323 [notifier] remove extra space in log message
  src/core/common/notifier.cpp
Labels: cla: yes

#6326 [daemon] log command line
  src/posix/platform/daemon.cpp
Labels: cla: yes, enhancement, platform: posix

#6336 [border-router] more strict state check before evaluating routing policy
  src/core/border_router/routing_manager.cpp
Labels: cla: yes, comp: border router, enhancement

#6322 [srp-server] bind SRP Server to Thread netif
  src/core/config/srp_server.h
  src/core/net/srp_server.cpp
  src/core/net/srp_server.hpp
  tests/scripts/thread-cert/node.py
  tests/scripts/thread-cert/test_srp_auto_start_mode.py
Labels: cla: yes, comp: dns, enhancement

#6332 [udp] bind to an interface when sending/connecting
  src/core/api/udp_api.cpp
  src/core/net/udp6.cpp
  src/core/net/udp6.hpp
Labels: cla: yes, platform: posix

#6328 [efr32] switch NAME_WLE to NAME_WE to be CMake 3.10 compatible
  third_party/silabs/cmake/imported_libs.cmake
Labels: cla: yes, comp: build, platform: efr32

#6329 [efr32] bug fixes, UART API changes
  examples/platforms/efr32/sleepy-demo/sleepy-demo-ftd/CMakeLists.txt
  examples/platforms/efr32/sleepy-demo/sleepy-demo-ftd/Makefile.am
  examples/platforms/efr32/sleepy-demo/sleepy-demo-ftd/main.c
  examples/platforms/efr32/sleepy-demo/sleepy-demo-mtd/CMakeLists.txt
  examples/platforms/efr32/sleepy-demo/sleepy-demo-mtd/Makefile.am
  examples/platforms/efr32/sleepy-demo/sleepy-demo-mtd/main.c
  examples/platforms/efr32/src/radio.c
Labels: cla: yes, comp: build, platform: efr32

#6335 [dns-types] declare 'Ecdsa256KeyRecord' as 'Equatable'
  src/core/net/dns_types.hpp
Labels: P4, cla: yes, comp: dns, enhancement

#6330 [ping-sender] adding missing doxygen tags
  doc/ot_api_doc.h
  include/openthread/instance.h
  include/openthread/ping_sender.h
Labels: api: user, cla: yes, comp: docs

#6340 [equatable] 'Unequatable' class adding overload of operator `!=`
  src/core/common/equatable.hpp
  src/core/common/settings.hpp
  src/core/common/time.hpp
  src/core/mac/channel_mask.hpp
  src/core/meshcop/meshcop.hpp
  src/core/net/ip6_address.hpp
  src/core/net/socket.hpp
  src/core/thread/network_data.hpp
  src/core/thread/topology.hpp
Labels: P4, cla: yes, enhancement

#6333 [ot-ctl] send a line at once
  src/posix/client.cpp
Labels: cla: yes, platform: posix

#6327 [border-router] enhance on-link prefix check
  src/core/border_router/router_advertisement.hpp
  src/core/border_router/routing_manager.cpp
  src/core/border_router/routing_manager.hpp
Labels: cla: yes, comp: border router, enhancement

#6354 [github-action] remove use of mplatform/mquery in docker build
  .github/workflows/docker.yml
Labels: bug, cla: yes, continuous-integration

#6351 [docs] remove plat-uart
  doc/ot_api_doc.h
Labels: cla: yes, comp: docs

#6331 [string] update doxygen api closing comment
  src/core/common/string.hpp
Labels: P4, cla: yes, comp: docs, enhancement

#6345 [link-metrics] address header file loop with 'topology.h'
  src/core/thread/link_metrics.cpp
  src/core/thread/link_metrics.hpp
  src/core/thread/link_metrics_tlvs.hpp
  src/core/thread/topology.hpp
Labels: P4, cla: yes, enhancement

#6334 [net] add `Ip4::Address` class
  Android.mk
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/net/ip4_address.cpp
  src/core/net/ip4_address.hpp
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  tests/unit/CMakeLists.txt
  tests/unit/Makefile.am
  tests/unit/test_ip_address.cpp
Labels: P4, cla: yes, enhancement

#6357 [dns-client] simplify `SendQuery()` and add comment
  src/core/net/dns_client.cpp
  src/core/net/dns_client.hpp
Labels: P4, cla: yes, comp: dns, enhancement

#6346 [ip6-address] simplify `FromString()`
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  tests/unit/test_ip_address.cpp
Labels: P4, cla: yes, enhancement

#6353 [ip6-address] add `SetFromTranslatedIp4Address()` for NAT64
  src/core/net/ip6_address.cpp
  src/core/net/ip6_address.hpp
  tests/unit/test_ip_address.cpp
Labels: P4, cla: yes, enhancement

#6341 [ping-sender] show ping reply statistics
  include/openthread/instance.h
  include/openthread/ping_sender.h
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/core/config/ping_sender.h
  src/core/net/icmp6.hpp
  src/core/utils/ping_sender.cpp
  src/core/utils/ping_sender.hpp
  tests/scripts/thread-cert/node.py
  tools/otci/tests/test_otci.py
Labels: api: user, cla: yes, comp: cli, enhancement

#6364 [message] add method to append bytes read from another/same message
  src/core/common/message.cpp
  src/core/common/message.hpp
  tests/unit/test_message.cpp
Labels: P4, cla: yes, enhancement

#6378 [ot-ctl] fix ot-ctl hang
  src/posix/client.cpp
Labels: P1, bug, cla: yes, platform: posix

#6365 [dns] adding `Name::AppendTo()` to copy DNS name from one message to another
  src/core/net/dns_types.cpp
  src/core/net/dns_types.hpp
  tests/unit/test_dns.cpp
Labels: api: platform, cla: yes, comp: dns, enhancement

#6369 [samr21] move to openthread/ot-samr21
  configure.ac
  examples/Makefile-samr21
  examples/platforms/Makefile.am
  examples/platforms/Makefile.platform.am
  examples/platforms/samr21/CMakeLists.txt
  examples/platforms/samr21/Makefile.am
  examples/platforms/samr21/Makefile.platform.am
  examples/platforms/samr21/README.md
  examples/platforms/samr21/alarm.c
  examples/platforms/samr21/arm-none-eabi.cmake
  examples/platforms/samr21/crypto/aes_alt.c
  examples/platforms/samr21/crypto/aes_alt.h
  examples/platforms/samr21/crypto/samr21-mbedtls-config.h
  examples/platforms/samr21/cxx_helpers.c
  examples/platforms/samr21/diag.c
  examples/platforms/samr21/entropy.c
  examples/platforms/samr21/flash.c
  examples/platforms/samr21/logging.c
  examples/platforms/samr21/misc.c
  examples/platforms/samr21/openthread-core-samr21-config-check.h
  examples/platforms/samr21/openthread-core-samr21-config.h
  examples/platforms/samr21/platform-samr21.h
  examples/platforms/samr21/radio.c
  examples/platforms/samr21/system.c
  examples/platforms/samr21/uart.c
  examples/platforms/samr21/user_row.h
  script/check-arm-build-autotools
  script/check-arm-build-cmake
  script/cmake-build
  third_party/CMakeLists.txt
  third_party/microchip/CMakeLists.txt
  third_party/microchip/README.md
  third_party/microchip/include/asf.h
  third_party/microchip/include/compiler.h
  third_party/microchip/include/conf_board.h
  third_party/microchip/include/conf_clocks.h
  third_party/microchip/include/conf_extint.h
  third_party/microchip/include/conf_spi.h
  third_party/microchip/include/conf_trx_access.h
  third_party/microchip/include/samr21x18a.ld
  third_party/microchip/include/status_codes.h
  third_party/microchip/include/user_board.h
Labels: cla: yes, platform: samr21
