Repository openthread/openthread, pull requests merged in 2022-11, with the labels that each got.

#8316 [diag] add gpio diag command support
  examples/platforms/simulation/radio.c
  include/openthread/diag.h
  include/openthread/instance.h
  include/openthread/platform/diag.h
  src/core/api/diags_api.cpp
  src/core/diags/README.md
  src/core/diags/factory_diags.cpp
  src/core/diags/factory_diags.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  src/ncp/ncp_base.cpp
  src/posix/platform/radio.cpp
  tests/fuzz/fuzzer_platform.cpp
  tests/scripts/expect/cli-diags.exp
  tests/scripts/expect/posix-diag-rcp.exp
Labels: enhancement, P3, comp: diags

#8343 [cli] update CLI `Output` class
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_coap.cpp
  src/cli/cli_coap.hpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_coap_secure.hpp
  src/cli/cli_commissioner.hpp
  src/cli/cli_dataset.hpp
  src/cli/cli_history.hpp
  src/cli/cli_joiner.hpp
  src/cli/cli_network_data.hpp
  src/cli/cli_output.cpp
  src/cli/cli_output.hpp
  src/cli/cli_srp_client.cpp
  src/cli/cli_srp_client.hpp
  src/cli/cli_srp_server.hpp
  src/cli/cli_tcp.cpp
  src/cli/cli_tcp.hpp
  src/cli/cli_udp.cpp
  src/cli/cli_udp.hpp
Labels: enhancement, P4, comp: cli

#8339 [log] add compile-time check for `printf` style arg check to log functions
  src/core/backbone_router/bbr_leader.cpp
  src/core/backbone_router/bbr_local.cpp
  src/core/backbone_router/bbr_manager.cpp
  src/core/backbone_router/multicast_listeners_table.cpp
  src/core/backbone_router/ndproxy_table.cpp
  src/core/border_router/routing_manager.cpp
  src/core/common/log.hpp
  src/core/common/notifier.cpp
  src/core/common/settings.cpp
  src/core/mac/mac.cpp
  src/core/mac/sub_mac.cpp
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dtls.cpp
  src/core/net/srp_client.cpp
  src/core/net/srp_server.cpp
  src/core/net/tcp6.cpp
  src/core/net/tcp6_ext.cpp
  src/core/thread/announce_sender.cpp
  src/core/thread/link_metrics.cpp
  src/core/thread/mesh_forwarder.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mlr_manager.cpp
  src/core/thread/network_data_publisher.cpp
  src/core/thread/time_sync_service.cpp
  src/core/utils/channel_manager.cpp
  src/core/utils/channel_monitor.cpp
Labels: enhancement, P4, comp: logging

#8353 [netif] fix bug in print statement with no corresponding argument
  src/posix/platform/netif.cpp
Labels: bug, platform: posix

#8350 [net-diag] reuse similar MLE TLV definitions
  src/core/thread/network_diagnostic.cpp
  src/core/thread/network_diagnostic_tlvs.hpp
Labels: enhancement, P4, comp: netdiag

#8356 [log] add arg format check to `otLog{Level}Plat()` functions
  examples/platforms/utils/soft_source_match_table.c
  include/openthread/instance.h
  include/openthread/logging.h
  src/posix/platform/daemon.cpp
  src/posix/platform/netif.cpp
Labels: enhancement, P4, api: user, comp: logging

#8273 [crypto] add ECDSA API
  Android.mk
  include/openthread/crypto.h
  include/openthread/instance.h
  include/openthread/platform/crypto.h
  src/core/BUILD.gn
  src/core/CMakeLists.txt
  src/core/Makefile.am
  src/core/crypto/crypto_platform.cpp
  src/core/crypto/ecdsa.cpp
  src/core/crypto/ecdsa.hpp
  src/core/crypto/ecdsa_tinycrypt.cpp
Labels: enhancement, security, P4, api: platform

#8280 [telemetry] border routing packet counters
  include/openthread/instance.h
  include/openthread/ip6.h
  src/core/api/ip6_api.cpp
  src/core/config/ip6.h
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
Labels: comp: border router

#8357 [net-diag] add a common `SendDiagnosticCommand()` method
  src/core/thread/network_diagnostic.cpp
  src/core/thread/network_diagnostic.hpp
Labels: enhancement, P4, comp: netdiag

#8364 [tlv] `ReadTlvValue()` to handle regular or extended TLVs
  src/core/common/tlvs.cpp
  src/core/common/tlvs.hpp
Labels: enhancement, P4

#8361 [clang-tidy] add `modernize-loop-convert`
  script/make-pretty
  src/core/mac/mac.cpp
  src/core/net/ip4_types.cpp
  src/ncp/ncp_base_ftd.cpp
Labels: P4, continuous-integration

#8365 [clang-tidy] add `readability-redundant-control-flow`
  script/make-pretty
  src/core/thread/dua_manager.cpp
  src/core/thread/link_metrics.cpp
  src/core/thread/network_diagnostic.cpp
Labels: P4, continuous-integration

#8354 [cli] add `OutputUint64()` for 64-bit integer value in decimal format
  src/cli/cli.cpp
  src/cli/cli_commissioner.cpp
  src/cli/cli_dataset.cpp
  src/cli/cli_joiner.cpp
  src/cli/cli_output.cpp
  src/cli/cli_output.hpp
Labels: enhancement, P4, comp: cli

#8368 [net-diag] simplify processing of TLVs, allow extended TLV
  src/core/thread/network_diagnostic.cpp
  src/core/thread/network_diagnostic.hpp
  src/core/thread/network_diagnostic_tlvs.hpp
Labels: enhancement, P4, comp: netdiag

#8369 [cli] add compile-time `printf` style arg check in CLI
  src/cli/cli.cpp
  src/cli/cli.hpp
  src/cli/cli_coap.cpp
  src/cli/cli_coap_secure.cpp
  src/cli/cli_commissioner.cpp
  src/cli/cli_dataset.cpp
  src/cli/cli_network_data.cpp
  src/cli/cli_output.cpp
  src/cli/cli_output.hpp
  src/cli/cli_srp_server.cpp
  src/cli/cli_tcp.cpp
Labels: enhancement, P4, comp: cli

#8373 [posix] use __GLIBC__ instead of __linux__ in backtrace
  src/posix/platform/backtrace.cpp
Labels: bug, P3, platform: posix

#8377 [cli] fix `printf` style output
  src/cli/cli.cpp
Labels: comp: cli

#8374 [netdata] simplify `RouteLookup()` methods
  src/core/net/ip6.cpp
  src/core/thread/mesh_forwarder_ftd.cpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader.hpp
  src/core/thread/thread_netif.cpp
  src/core/thread/thread_netif.hpp
Labels: enhancement, P4, comp: netdata

#8380 [tests] fix comparison width warning
  tests/unit/test_network_data.cpp
Labels: continuous-integration

#8375 [netdata] add helper method to compare two BR entries
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader.hpp
Labels: enhancement, P4, comp: netdata

#8376 [netdata] update `Notifier` to prepare and send SVR_DATA.ntf msg
  src/core/thread/network_data.cpp
  src/core/thread/network_data.hpp
  src/core/thread/network_data_leader_ftd.cpp
  src/core/thread/network_data_leader_ftd.hpp
  src/core/thread/network_data_local.cpp
  src/core/thread/network_data_local.hpp
  src/core/thread/network_data_notifier.cpp
  src/core/thread/network_data_notifier.hpp
Labels: enhancement, P4, comp: netdata

#8372 [cli] add commands for Border Routing counters
  include/openthread/instance.h
  include/openthread/ip6.h
  src/cli/README.md
  src/cli/cli.cpp
  src/core/api/ip6_api.cpp
  src/core/net/ip6.hpp
Labels: comp: cli, comp: border router

#8342 [spinel] log radio spinel frame
  src/lib/spinel/radio_spinel.hpp
  src/lib/spinel/radio_spinel_impl.hpp
  src/lib/spinel/spinel.c
  src/lib/spinel/spinel.h
Labels: P3, comp: rcp

#8389 [build] add build option `OT_BORDER_ROUTING_COUNTERS`
  etc/cmake/options.cmake
Labels: comp: build

#8341 [tests] add tests for Border Routing Counters
  tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_across_thread_pans.py
  tests/scripts/thread-cert/border_router/test_multi_thread_networks.py
  tests/scripts/thread-cert/call_dbus_method.py
  tests/scripts/thread-cert/node.py
Labels: continuous-integration

#8391 [diag] add gpio mode commands
  examples/platforms/simulation/diag.c
  examples/platforms/simulation/radio.c
  include/openthread/instance.h
  include/openthread/platform/diag.h
  src/core/diags/README.md
  src/core/diags/factory_diags.cpp
  src/posix/platform/radio.cpp
  tests/scripts/expect/cli-diags.exp
Labels: enhancement, P3, comp: diags

#8397 [github-actions] fix macos build checks
  .github/workflows/build.yml
Labels: continuous-integration

#8401 [spinel] fix `printf` style output
  src/lib/spinel/radio_spinel_impl.hpp
Labels: comp: rcp

#8394 [cli] update `OutputSpaces()` to use literal format string
  src/cli/cli_output.cpp
Labels: enhancement, P4, comp: cli

#8399 [bootstrap] remove brew from apt package installations
  script/bootstrap
Labels: P4

#8404 [meshcop] simplify `StateTlv`
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/meshcop_tlvs.hpp
Labels: enhancement, P4, comp: meshcop

#8405 [docker] update ubuntu to 22.04
  etc/docker/environment/Dockerfile
Labels: P4

#8411 [commissioner] fix provisioning URL comparison
  src/core/meshcop/commissioner.cpp
Labels: bug, P4, comp: meshcop

#8415 [doc] add doc for coex command
  src/cli/README.md
Labels: comp: docs, comp: cli

#8413 [mle] use `Tlv::FindTlvValueOffset()` instead of `FindTlvOffset()`
  src/core/meshcop/dataset.cpp
  src/core/meshcop/dataset.hpp
  src/core/meshcop/dataset_manager.cpp
  src/core/meshcop/dataset_manager.hpp
  src/core/thread/discover_scanner.cpp
  src/core/thread/mle.cpp
  src/core/thread/mle_router.cpp
  src/core/thread/mle_router.hpp
  src/core/thread/network_data_leader.cpp
  src/core/thread/network_data_leader.hpp
  tests/unit/test_lowpan.cpp
Labels: enhancement, P4, comp: netdata

#8417 [tlv] helper methods to read/find/append TLVs with UTF8 string value
  src/core/backbone_router/bbr_manager.cpp
  src/core/common/tlvs.cpp
  src/core/common/tlvs.hpp
  src/core/meshcop/commissioner.cpp
  src/core/meshcop/joiner.cpp
  src/core/meshcop/meshcop_tlvs.hpp
  src/core/thread/thread_tlvs.hpp
Labels: enhancement, P4

#7937 [spinel] update the updating/adding RCP spinel property guideline
  include/openthread/instance.h
  include/openthread/platform/radio.h
  src/lib/spinel/radio_spinel_impl.hpp
  src/lib/spinel/spinel.h
  src/posix/platform/radio.cpp
Labels: enhancement, P3, comp: rcp

#8418 [github-actions] add Dependabot configuration for GitHub Actions updates
  .github/dependabot.yml
Labels: enhancement, P4, continuous-integration

#8416 [telemetry] implement RA/RS counters
  include/openthread/instance.h
  include/openthread/ip6.h
  src/cli/README.md
  src/cli/cli.cpp
  src/core/border_router/routing_manager.cpp
  src/core/net/ip6.cpp
  src/core/net/ip6.hpp
Labels: enhancement, P4, api: user, comp: border router

#8421 [tlv] add private helper methods to parse and find TLVs in a message
  src/core/common/tlvs.cpp
  src/core/common/tlvs.hpp
  tests/unit/CMakeLists.txt
  tests/unit/Makefile.am
  tests/unit/test_tlv.cpp
Labels: enhancement, P4

#8427 [meshcop] update processing of UDP Encapsulation TLV
  src/core/meshcop/border_agent.cpp
  src/core/meshcop/meshcop_tlvs.hpp
Labels: enhancement, P4, comp: meshcop

#8433 [router-table] fix router next hop change on `Release(aRouterId)`
  src/core/thread/router_table.cpp
Labels: bug, P4, comp: mle

#8431 [test] `test_routing_manager` to check duplicate PIO/RIO prefixes
  tests/unit/test_routing_manager.cpp
Labels: enhancement, P4, comp: cli, comp: border router

#8392 [nat64] use DBus API for NAT64 tests
  tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py
  tests/scripts/thread-cert/border_router/nat64/test_single_border_router.py
  tests/scripts/thread-cert/call_dbus_method.py
  tests/scripts/thread-cert/node.py
Labels: enhancement, P4, continuous-integration

#8436 [routing-manager] ensure local prefix is changed on xpanid change
  src/core/border_router/routing_manager.cpp
  tests/unit/test_routing_manager.cpp
Labels: bug, enhancement, P4, comp: border router

#8435 [api] include Thread version in neighbor info
  include/openthread/instance.h
  include/openthread/thread.h
  src/cli/cli.cpp
  src/core/thread/topology.cpp
  tests/scripts/expect/cli-neighbor.exp
Labels: enhancement, P4, api: user

#8453 [build] fix `LOCAL_EXPORT_CFLAGS`
  Android.mk
Labels: comp: build

#8446 [logging] fix format strings
  src/cli/cli.cpp
  src/lib/spinel/radio_spinel_impl.hpp
Labels: comp: cli, comp: rcp

#8455 [indirect-sender] reset CSL Tx attempts in `DataPollHandler`
  src/core/mac/data_poll_handler.cpp
Labels: bug, Thread 1.2, comp: low-power

#8456 [github-actions] exclude dependabot branches
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/fuzz.yml
  .github/workflows/makefile-check.yml
  .github/workflows/otbr.yml
  .github/workflows/otci.yml
  .github/workflows/otns.yml
  .github/workflows/posix.yml
  .github/workflows/simulation-1.1.yml
  .github/workflows/simulation-1.2.yml
  .github/workflows/size.yml
  .github/workflows/toranj.yml
  .github/workflows/version.yml
Labels: enhancement, P4, continuous-integration

#8457 [dependabot] update commit message prefix
  .github/dependabot.yml
Labels: enhancement, P4, continuous-integration

#8454 [netdata] increase `kInfoStringSize`
  src/core/thread/network_data_publisher.hpp
Labels: enhancement, P4
